### ISSUE TITLE
1.5.2 Client Crash

### ISSUE THREAD

**Issue by swan201** [ProtocolSupport/ProtocolSupport#100]
i use 361 commit ProtocolSupport.

1.5.2 Client Crash to Bad packet 96 and 175

**Comment by Shevchik** [comment]
How exactly does this happen?

**Comment by swan201** [comment]
is summerserver.ptcs.kr just go in then crash

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by swan201** [comment]
@Shevchik Thx!!
