### ISSUE TITLE
Board is not Showing Correctly When using 

### ISSUE THREAD

**Issue by Xuwznln** [ProtocolSupport/ProtocolSupport#1000]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps version`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

If you fail to check the above, your issue will be closed. Otherwise we're glad to help :-)

Hello, I am using the latest build version of ProtocolSupport on paperspigot1.13.2. But the board is not showing correctly when using client 1.12. Just like this:
![1](https://user-images.githubusercontent.com/18435084/50382066-c3895680-06d1-11e9-95f4-e93b61db2994.png)
![2](https://user-images.githubusercontent.com/18435084/50382079-f3d0f500-06d1-11e9-986d-16f5460a98e3.png)

Please fix that, much Thanks!

**Comment by Shevchik** [comment]
You need to make sure that text fits in the limits (including the color codes). I will try to make string clamp color aware, so at least you won't have random numbers floating around, but generally you will have to work it out of the scoreboard plugin side.

**Comment by Shevchik** [comment]
Should be a bit better now. However remember that you are still limited by 16 symbols.

**Comment by DankPrison** [comment]
> Should be a bit better now. However remember that you are still limited by 16 symbols.

why is it limited to 16 symbols, the old 1.12.2 version of protocol support doesn't have this issue? Why is it an issue now? 16 including color codes is very short... hard to make any decent scoreboard with that please fix asap.

**Comment by zeronerve** [comment]
I recently switched from the lastest protocolsupport build for 1.13.2 to the latest build for 1.14.4. Scoreboard lines were working well in 1.8.9 on my 1.13.2 server, but after the change to 1.14.4, the lines are cutoff. Is there a solution for this?
