### ISSUE TITLE
Sleeping makes blocks vanish

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#1001]
https://youtu.be/G24usHrpS9M

Blocks seem to reappear if you right click them. 
I tested this in 1.13.3, 1.12.2, and 1.8.9. The footage here is in 1.13.2

**Comment by Shevchik** [comment]
Works fine here. Need a map with exact position.

**Comment by MasterDash5** [comment]
Took me a bit to download the world. Here it is.

https://www.dropbox.com/s/ybi41jb1kx01hjd/world.zip?dl=0

The coords of the video are X:-4568399 Y:85 Z:-22054232

**Comment by Maximvdw** [comment]
Might also be advised to post a list of plugins. I've seen similar issues on server using "anti lag" plugins that forcefully block packets (sleeping = black screen = no need to update visual things)
