### ISSUE TITLE
Players are invisible.

### ISSUE THREAD

**Issue by TheIntelloBox** [ProtocolSupport/ProtocolSupport#1003]
Hello,

I'm using the latest dev build on Paper Spigot 1.13.2 and my players are invisible.
My friend is in 1.12.2 and I'm in 1.13.2 and we can't see us.

Moreover, we can't see the mobs in MobArena.

Can you help me ?

Thanks ! :D

**Comment by TheWranger** [comment]
Are you running the latest version from jenkins (as of now), there was an issue related to invisible entities a little bit ago.

**Comment by TheIntelloBox** [comment]
Yeah

**Comment by TheIntelloBox** [comment]
UP

**Comment by Shevchik** [comment]
Works fine there. Make sure you are using latest paper + latest ps dev build.

**Comment by TheIntelloBox** [comment]
No it doesn't work

**Comment by Shevchik** [comment]
It surely does.
https://imgur.com/a/GpNstC0

**Comment by TheIntelloBox** [comment]
Wanna come on my server to test ? ^^

**Comment by TheIntelloBox** [comment]
So ?

**Comment by Shevchik** [comment]
Paste an ip address there.

**Comment by TheIntelloBox** [comment]
speedcraft.omgcraft.fr:12646

**Comment by TheIntelloBox** [comment]
Here is the build info: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2018.12.27 at 18:54:33 MSK, buildhost: build.true-games.org, buildnumber: 329)

**Comment by MatrixTunnel** [comment]
Mind pasting your spigot.yml and sending it here? (use pastebin or something similar)

**Comment by TheIntelloBox** [comment]
https://pastebin.com/Kq1BYe2x

**Comment by MatrixTunnel** [comment]
Ah, you changed the entity tracking range. I personally had issues with invisible players when I changed the default value. You might want to try reverting it and see if that fixes the problem

@shevchik do you know what could be causing this with PS?

**Comment by TheIntelloBox** [comment]
@MatrixTunnel What is your value of entity tracking range ? :D

**Comment by MatrixTunnel** [comment]
Default is `48` for players

**Comment by TheIntelloBox** [comment]
Nothing changes, still invisible.

**Comment by MatrixTunnel** [comment]
Are they completely invisible until you respawn or just all the time?

**Comment by TheIntelloBox** [comment]
Completely invisible. Even Mobs.

**Comment by TheIntelloBox** [comment]
I really need your help, I can't open my server because of this bug...

**Comment by 7kasper** [comment]
Hey I've never seen this happen. Try generating a fresh server with no config files and just ProtocolSupport and paper and see if it still happens.

**Comment by TheIntelloBox** [comment]
Maybe you know plugins that are not compatible with ProtocolSupport ?

**Comment by TheIntelloBox** [comment]
@MatrixTunnel @Shevchik I tested with only ProtocolSupport installed. Here is the result: https://youtu.be/ctkPeXWi5jk

**Comment by Shevchik** [comment]
This was caused by world view distance set to 1. We don't support paper view-distance API right now, and most likely won't any time soon.
