### ISSUE TITLE
1.12.2 (and eventually lower version) disonnect from 1.13.2 (No transformer found for state PLAY and packet id 49)

### ISSUE THREAD

**Issue by i9hdkill** [ProtocolSupport/ProtocolSupport#1009]
Spigot Build:
[16:31:18 INFO]: This server is running CraftBukkit version git-Spigot-8ede039-d0a9130 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[16:31:18 INFO]: Checking version, please wait...
[16:31:18 INFO]: You are running the latest version

PS Buildinfo
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.01.01 at 17:02:45 MSK, buildhost: build.true-games.org, buildnumber: 336
PS Debug:
https://pastebin.com/MctKYGzW

We are using QualityArmor to replace existing Crackshot Weapons.
But unfortunately, when shooting, 1.12.2 and eventuall lower clients are getting a disconnect.

**Comment by i9hdkill** [comment]
Thank you. Isn't it possible to somehow translate the face player packet to a teleport package in 1.12 and lower?

**Comment by Shevchik** [comment]
Will require getting player position from server (which can be out of sync, because of async access). Also calculations need to be written, and i'm no that good at math.

**Comment by Shevchik** [comment]
Shouldn't kick players anymore.

**Comment by i9hdkill** [comment]
Thanks! But seems like the build didn't trigger
