### ISSUE TITLE
Error when connecting using 1.7.10

### ISSUE THREAD

**Issue by LuminousViper** [ProtocolSupport/ProtocolSupport#101]
I am currently using protocol support followed all the fixes and are using correct server versions (spigot, mc, craftbukkit) I can connect to the server in 1.8.8 but when i try to connect on 1.7.10 i get this: 
Exception Connecting:CorruptedFrameException : Empty Packet! @ net.md_5.bungee.protocol.Varint21FrameDecoder:34

Console Output: [19:41:52] [Server thread/INFO]: LuminousViper[/**************] logged in with entity id 381 at ([Hub]-69.04192412308858, 72.0, 123.45104020242626)
[19:41:52] [Server thread/INFO]: LuminousViper lost connection: Internal Exception: java.io.IOException: Broken pipe
[19:41:52] [Server thread/INFO]: LuminousViper left the game.

**Comment by LuminousViper** [comment]
Thank you

**Comment by Shevchik** [comment]
Not a protocol support issue, it's bungee kicking players.
