### ISSUE TITLE
Block torch, disappears when the server restarts.

### ISSUE THREAD

**Issue by Guest1131** [ProtocolSupport/ProtocolSupport#1012]
I noticed that there is a problem, after I place the block torch,with client version 1.12.2 it appears, but after I leave the server and return, or restart the server, the block torch, there is no more, disappears.

Using server 1.13.2

Please resolve.

**Comment by Guest1131** [comment]
?

**Comment by Shevchik** [comment]
Can't reproduce, places just fine. Make sure you don't have any other plugins first.

**Comment by MasterDash5** [comment]
Actually the torches are technically still there. Older clients just can't see them

1.13.2: http://prntscr.com/mcoqeu
1.8.9: http://prntscr.com/mcoqlr

Furthermore, I haven't seen this happen to wall torches, just ground ones

**Comment by Guest1131** [comment]
This problem really does exist.

I just tried it even without any plugins installed, but only with the ProtocolSupport plugin, and the problem is there.

With client 1.12.2, the color of the grass is brighter, and the flashlights, you can't see.

If I enter with client 1.13.2 instead, everything is perfectly visible.

- Server: version git-Spigot-f56e2e7-ed274c5 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

- ProtocolSupport: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.01.27 at 04:34:36 MSK, buildhost: build.true-games.org, buildnumber: 345)

Client: 1.12.2

To play back do so: 

1) Sign in with client 1.12.2

2) Use server 1.13.2

3) Place the object the torch, on a wooden block or not.

4) Exit the server and return, you will see that the flashlight is gone.

Please resolve

**Comment by Guest1131** [comment]
If I use ViaBackRewards instead of ProtocolSupport there is no longer this problem.

**Comment by Shevchik** [comment]
Indeed, only normal standing torch has this problem, wall torches work fine. Need to fix the preflattening mapping i guess.

**Comment by Shevchik** [comment]
Fixed

**Comment by Guest1131** [comment]
I just installed the last build, it works perfectly now, thanks :)
