### ISSUE TITLE
MCPENew Branch Compiling Issue

### ISSUE THREAD

**Issue by bman921** [ProtocolSupport/ProtocolSupport#1013]
Hello! I was trying to compile the latest commit of the mcpe-new branch and I got this error.
`> Task :updateShadeLibraries 
Skipping download of library raknetserver-8.jar because it already exists
Skipping download of library udpserver-2.jar because it already exists

> Task :updateSpigot 
Skipping building of library spigot-1.13.2-3.jar because it already exists

> Task :compileJava 
/home/brandon/Desktop/ProtocolSupport/src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/EntityLook.java:30: error: method create in class SetPosition cannot be applied to given types;
                        return RecyclableSingletonList.create(SetPosition.create(entity, 0, 0, 0, pitch, yaw, SetPosition.ANIMATION_MODE_PITCH));
                                                                         ^
  required: NetworkEntity,double,double,double,float,float,float,int
  found: NetworkEntity,int,int,int,int,int,int
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
`

**Comment by colinrgodsey** [comment]
There is no public support for MCPE right now. If you are a developer (especially with a server you can test on), please let us know in the discord and we can get you set up.
