### ISSUE TITLE
GUI Title issues

### ISSUE THREAD

**Issue by LavRad** [ProtocolSupport/ProtocolSupport#1015]
When using a version lower than 1.13 (1.12.2 for example) the player loses formatting (colour codes/bold) in the title of GUIs. 
1.12.2: http://prntscr.com/mb671c
1.13.2: http://prntscr.com/mb679z
Other effects are present too such as the cutting of long holograms and random cutting of scoreboard lines.
1.13.2: http://prntscr.com/mb6eoa
1.12.2: http://prntscr.com/mb6exq

To ensure this issue is present I've:
Used the latest PaperSpigot and Spigot on two servers running the latest ProtocolSupport (and ProtocolLib)
The only plugin the server uses for backwards compatibility is ProtocolSupport.
ProtocolSupport Build Info: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.01.09 at 21:17:14 MSK, buildhost: build.true-games.org, buildnumber: 340)
Server is running on 1.13.2

If you need any more information let me know, and if relevant let me know how to obtain that information since I'm new to issue reporting.

Thanks

**Comment by Artuto** [comment]
Its a known bug that Scoreboards are cut off in 1.13.2

**Comment by LavRad** [comment]
They’re cut off in versions under 1.13.2, and it’s not on the main page. I asked Shevchik about it on discord and they didn’t seem to know about the issue I’m having. Now I realise the similarities to https://github.com/ProtocolSupport/ProtocolSupport/issues/1000
I’ll review the 16 symbol limit to see if it’s possible.

**Comment by Shevchik** [comment]
Create a separate issues for each of those issues. Scoreboards are cut off due to 16 symbols prefix/suffix limit in previous versions.

**Comment by Shevchik** [comment]
Actually same for entity names, they are limited to 64 symbols in previous versions.

**Comment by LavRad** [comment]
Do I still need to make another issue post?
Ignore my Scoreboard and Hologram issue, I'll make my holograms shorter and fix scoreboard thank you.

**Comment by Shevchik** [comment]
No.

**Comment by Shevchik** [comment]
Inventory open packet wasn't changed between 1.13.2 and 1.12.2, however indeed, no formatting works.
I guess something changed with handling name itself.

**Comment by LavRad** [comment]
Can anything be done about it?

**Comment by Shevchik** [comment]
No idea yet, will find whats changed first, and then i will be able to tell if i can fix that or not.

**Comment by Shevchik** [comment]
Should be fixed now.
Old versions used json components, however extracted unformatted text from them. Legacy colors still work tho.

**Comment by LavRad** [comment]
Where can I get a .jar of the fix? Thanks

**Comment by LavRad** [comment]
Fixed! Thank you for your help :)
