### ISSUE TITLE
Grass not correctly displayed

### ISSUE THREAD

**Issue by Guest1131** [ProtocolSupport/ProtocolSupport#1017]
There is a problem with ProtocolSupport.

version protocolsupport :  protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.01.27 at 04:34:36 MSK, buildhost: build.true-games.org, buildnumber: 345)

version server:  git-Spigot-f56e2e7-a65b73a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

version server 

Grass is not displayed correctly, and lighter, grass should normally be displayed dark green, the classic Minecraft green.

screen: 

![immagine](https://user-images.githubusercontent.com/43791580/51925973-7430f700-23f0-11e9-9360-f17d540ae1ec.png)

**Comment by Shevchik** [comment]
We already have a separate issue that tracks torches. As for grass, use a client denug screen, and see if biomes match.
