### ISSUE TITLE
Text cut - ScoreBoard

### ISSUE THREAD

**Issue by Guest1131** [ProtocolSupport/ProtocolSupport#1019]
Hi, I have a problem with ProtocolSupport, the lyrics in the scoreboard, I use FeatherBoard for the scoreboard.

It doesn't display correctly, the text doesn't show everything, only meta.

- Server: CraftBukkit version git-Spigot-f56e2e7-ed274c5 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

- ProtocolSupport: 
 
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.01.27 at 04:34:36 MSK, buildhost: build.true-games.org, buildnumber: 345)

Client: 1.12.2 or lower.

**Comment by Shevchik** [comment]
See already closed issues. You reached the scoreboard suffix/prefix length limit.

**Comment by Guest1131** [comment]
With client 1.13.2, you can see wider:

![immagine](https://user-images.githubusercontent.com/43791580/51986860-7901b380-24a1-11e9-8686-cfcf2cc609ff.png)

**Comment by Maximvdw** [comment]
The issue has been circumvented in the latest (4.18.0) version of featherboard

**Comment by Guest1131** [comment]
What do you mean, "circumvented"?

**Comment by Maximvdw** [comment]
The latest featherboard uses packets that are sent to players. 1.13 players get different scoreboard packets than other players.

Why I say 'circumvented' is because this issue still remains a compatibility issue that should have some fix implemented by protocolsupport.

The ideal scenario would be that protocolsupport sees that a plugin attempts to send a too long prefix. When no suffix is being sent, it should split the prefix and transfer the colors. That way it keeps compatibility.

**Comment by zeronerve** [comment]
@Shevchik @Maximvdw  I recently built a scoreboard class that worked perfectly in 1.13.2 for 1.8.9 clients, but it stopped worked (cutoff lines) once I moved to 1.14.4. My understanding is that I'm very close to having this working and I'm resisting setting up a new plugin with additional dependencies. Is there a specific difference in the way ProtocolSupport for 1.14.4 (lastest builds) handles prefix/suffix lengths for 1.8.9 clients, and if so, can you help me understand the issue?

**Comment by Shevchik** [comment]
1.14.4 additionally eats 2-4 color chars from prefix if last prefix color doesn't match team color.

**Comment by zeronerve** [comment]
Thanks! Are you aware of a workaround?

**Comment by zeronerve** [comment]
@Maximvdw  This issue still exists for 1.8.9 clients connected to a 1.14.4 server.

**Comment by Shevchik** [comment]
Your scoreboard plugin will have to split prefix to suffix based on this.
You can also try making a plugin that intercepts scoreboards packets and splits prefix.
