### ISSUE TITLE
[1.4.7] Layered snow problem

### ISSUE THREAD

**Issue by Shevchik** [ProtocolSupport/ProtocolSupport#102]
1.4.7 client renders multi layered snow blocks just fine, but always walks through them (it thinks that their height is 0).

Solutions:
1)Inject snow block that has zero height
Problems: Server may react wrong for players with new protocols where snow block has actual height
2)Replace layered blocks with full ones
Problems: Player will float in air for others

**Comment by Tom-III** [comment]
Make the server ignore the height and let them walk through them (same thing must be done for carpets)

**Comment by Tom-III** [comment]
was it fixed?

**Comment by Shevchik** [comment]
Yes it was.
