### ISSUE TITLE
Server Lags when a player enters

### ISSUE THREAD

**Issue by Alexre** [ProtocolSupport/ProtocolSupport#1023]
* ProtocolSupport version (/ps buildinfo) protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2017.10.22 at 13:01:43 MSK, buildhost: build.true-games.org, buildnumber: 176)
* Server version Paper version git-Paper-1596 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

When someone joins the server it throws this error and the server freezes for a second:

Code here: https://paste.ubuntu.com/p/XxgtRSHdDr/

**Comment by Alexre** [comment]
I have to mention that this starts happening some hours after the server is started, when I restart it the error doesn't happen until x time

**Comment by Shevchik** [comment]
1. We only support latest dev build, which is for 1.13.2
2. That's not the protocolsupport who throws this exception
