### ISSUE TITLE
Pipeline exception

### ISSUE THREAD

**Issue by Razvy311** [ProtocolSupport/ProtocolSupport#1025]
Hello. I got a little problem with the plugin. In installed it recently and I get constant errors in my console.

Error: https://pastebin.com/bPVGqhgT

Spigot Version: 1.13.2 - 0 Version behind
ProtocolSupport: 355 Build

**Comment by Shevchik** [comment]
Link is wrong

**Comment by Shevchik** [comment]
Caused by: java.io.IOException: Can't serialize unregistered packet

Remove all other plugins and try again.

**Comment by Razvy311** [comment]
I don't get any errors with all plugins removed.

I've also tried to upload the plugin on another server and I get this error
https://pastebin.com/aSArjVk1 .
