### ISSUE TITLE
Banner Color Re-Mapping Incorrect

### ISSUE THREAD

**Issue by InfinityAspire** [ProtocolSupport/ProtocolSupport#1027]
* ProtocolSupport Build 363
* PaperSpigot 1.13.2 - Build 525

The colors on banners are wrong on versions older than 1.13, although patterns are preserved.
The color I witnessed was that on 1.13 the banner was purple and white which is correct, whereas on all older clients it was green and white. Other colors may be affected.

**Comment by Shevchik** [comment]
I need images and command used to obtain such banners, since i'm not familiar with them.

**Comment by MasterDash5** [comment]
Banner layer colors seem to be remapped incorrectly.

1.13.2: https://imgur.com/a/icoIUlC
1.12.2: https://imgur.com/a/YRMypWL

**Comment by Shevchik** [comment]
So base color's are fine, only pattern are wrong?

**Comment by MasterDash5** [comment]
correcto

**Comment by Shevchik** [comment]
Should be fixed now.
