### ISSUE TITLE
Error when opening server.

### ISSUE THREAD

**Issue by denizdeni** [ProtocolSupport/ProtocolSupport#1028]
Server Version : 1.13.2

LOG :  [latest.log](https://github.com/ProtocolSupport/ProtocolSupport/files/2884263/latest.log)

Help please!

**Comment by WesleyVanNeck** [comment]
Use latest dev build

**Comment by denizdeni** [comment]
i used papermc, and it's gived error too.

log : [latest.log](https://github.com/ProtocolSupport/ProtocolSupport/files/2890135/latest.log)

**Comment by denizdeni** [comment]
okay nvm. i fixed it.
