### ISSUE TITLE
Players can pick up items from chest

### ISSUE THREAD

**Issue by AsVaidas** [ProtocolSupport/ProtocolSupport#1029]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo)
* Server version

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

* protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.02.18 at 09:55:10 MSK, buildhost: build.true-games.org, buildnumber: 364)
* get-Paper-525 (MC: 1.13.2)

When you open an inventory with mycommand (or other custom build plugin), event.setCancalled(true) doesn't work and players can pick up items from those inventories. /ps debug doesn't show anything

**Comment by Shevchik** [comment]
Client doesn't actually take items out tho, it's just a desync. Will fix it when i get well.

**Comment by AsVaidas** [comment]
But I was able to place those blocks that I picked up

**Comment by Shevchik** [comment]
Nobody sees them except you (unless you were in creative mode while placing).

**Comment by Shevchik** [comment]
Fixed
