### ISSUE TITLE
[1.7-1.8] Random kick players

### ISSUE THREAD

**Issue by DardBrinza** [ProtocolSupport/ProtocolSupport#103]
Everything is working fine , then throws out most of the server with messages to the console . There is always random and at different times. I use the latest Protocol Support, spigot , Authme. Log:
http://pastebin.com/RNMf3qgp

2) How to cut / remove protocols for 1.5.2-1.6.4 and leave only 1.7.2 and higher clients VersionControl not offer , is not working.

**Comment by MrPowerGamerBR** [comment]
1. Enable Debug Mode for ProtocolSupport (/ps debug) and then report the error when this happens again.

2. Use a plugin to kick older protocols (or make your own)

**Comment by Shevchik** [comment]
Read installation instructions, you missed 1 step.

**Comment by DardBrinza** [comment]
Oh, I did not notice this point O_o knew only late-bind: false. Thank you for help , I advise you to allocate mandatory conditions :)

**Comment by Shevchik** [comment]
Any configurable changes are out of score of this project.

**Comment by DardBrinza** [comment]
The problem repeated itself :

late-bind: false
use-native-transport=false

http://pastebin.com/AvJDDSr7

**Comment by Shevchik** [comment]
dtltraders crashed your server, has nothing to do with protocolsupport
