### ISSUE TITLE
Items can be taken from the gui menu.

### ISSUE THREAD

**Issue by OverBrave** [ProtocolSupport/ProtocolSupport#1030]
Items can be taken from the gui menu.
Chestcommands-shopguiplus-tuske.
It can be taken from all of them.

![image](https://user-images.githubusercontent.com/47111280/53171048-b4038c80-35f2-11e9-880d-9c87e3953f3c.png)

![image](https://user-images.githubusercontent.com/47111280/53170647-b1546780-35f1-11e9-85d0-8ae4ff31c746.png)

Paper version : Paper-525

![image](https://user-images.githubusercontent.com/47111280/53170971-7f8fd080-35f2-11e9-9708-f9a4a1831765.png)

1.13.2 Server version

**Comment by Shevchik** [comment]
Already tracked in #1029
