### ISSUE TITLE
Skulls do not load correctly

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#1031]
https://cubeimage.de/images/2019/02/23/6v10B.png
This only happens when the skulls exist before the chunk is sent to the player. When they are updated in a chunk the player sees it will correctly be updated.

This server is running Paper version git-Paper-527 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.02.22 at 13:47:56 MSK, buildhost: build.true-games.org, buildnumber: 365)

**Comment by MasterDash5** [comment]
This appears to happen in 1.12.2 and lower.
Also gonna quickly say this happens with flower pots as well.

1.13.2: https://imgur.com/a/enrUg9o
1.12.2: https://imgur.com/a/BFIl6k1

**Comment by Mikie** [comment]
Can confirm, this is an issue. Hopefully this can be fixed soon.

**Comment by Shevchik** [comment]
Works fine for me.
/minecraft:give @p player_head{SkullOwner:md_5}
Placed on ground, relogged, can see it just fine.

**Comment by mibby** [comment]
@Shevchik I can also confirm that heads do not have their texture.

Paper dev 597 (Spigot 1.13.2)
ProtocolSupport dev 370
Travertine dev 91 (Waterfall/BungeeCord)

1.13 client - I can see the placed head which has a skull texture of an arrow.
1.12.2 client - I do not see the texture and only see a skeleton head instead.

The skulls are spawned in with the plugin HeadDatabase, which should just be a playerhead with a base64 skin ID attached.

**Comment by Shevchik** [comment]
Dump that plugin head nbt there, maybe it will show something.
Because normal heads work fine.

**Comment by Brokkonaut** [comment]
I did some testing and it only happens to heads placed at a wall. If they are placed at the ground they work normal.

Its broken for all heads on the wall, also for heads created with `/minecraft:give @p player_head{SkullOwner:md_5}`

or from the heads database (example):

`/give @p minecraft:player_head{display:{Name:"{\"text\":\"Topaz Ore\"}"},SkullOwner:{Id:"253fdcb4-0ec8-40b8-9699-56c3c7f8bd9d",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTdlMmY0OTQyNDNhY2FkM2Y0ODQ0YmM1YWUyZDVmZDUzZTY5MjczMzA0YzlkYmY1YmQxMzA5NDlmYTEzMjk4ZiJ9fX0="}]}}} 1`

**Comment by Shevchik** [comment]
Fixed. Tho actually it wasn't skull related. Any tileentity that required block data and that never sent tile update after initial chunk data send only worked when placing on y % 16 == 0, due to internal mistake in blockdatacache index by coord calculation.

**Comment by Brokkonaut** [comment]
thanks, i can confirm it is fixed now
