### ISSUE TITLE
UPDATE 1.13.2

### ISSUE THREAD

**Issue by successed** [ProtocolSupport/ProtocolSupport#1033]
PLEASE UPDATE 1.13.2

**Comment by WesleyVanNeck** [comment]
no

download latest dev build geez be friendly to the devs man

**Comment by successed** [comment]
Where can I download?

**Comment by SiebeDW** [comment]
you can find it on the jenkins (build passing thing at top of readme)

**Comment by successed** [comment]
> you can find it on the jenkins (build passing thing at top of readme)

Yes i now used my server deweloper version and i need tab complete disable, How to fix this ?

**Comment by SiebeDW** [comment]
I dont think that protocolsupport can disable tab completion
