### ISSUE TITLE
Warning spam in the console

### ISSUE THREAD

**Issue by LactoseTheIntolerant** [ProtocolSupport/ProtocolSupport#1035]
This is what I get in the console after the first person that joins the server after the server has been restarted...

[WARNING] java.lang.IllegalArgumentException: Unable to find findStatistic in net.minecraft.server.v1_13_R2.StatisticList
[WARNING] at com.comphenix.protocol.reflect.FuzzyReflection.getMethodByParameters(FuzzyReflection.java:280)
[WARNING] at com.comphenix.protocol.wrappers.WrappedStatistic.<clinit>(WrappedStatistic.java:24)
[WARNING] at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method)
[WARNING] at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:843)
[WARNING] at com.comphenix.protocol.wrappers.BukkitConverters.getWrappedStatisticConverter(BukkitConverters.java:693)
[WARNING] at com.comphenix.protocol.wrappers.BukkitConverters.getConvertersForGeneric(BukkitConverters.java:1012)
[WARNING] at com.comphenix.protocol.wrappers.BukkitConverters.getUnwrappers(BukkitConverters.java:1031)
[WARNING] at com.comphenix.protocol.injector.PacketConstructor.<init>(PacketConstructor.java:62)
[WARNING] at com.comphenix.protocol.injector.PacketConstructor.<clinit>(PacketConstructor.java:45)
[WARNING] at com.comphenix.protocol.injector.BukkitUnwrapper.unwrapItem(BukkitUnwrapper.java:100)
[WARNING] at com.comphenix.protocol.utility.MinecraftFields.getNetworkManager(MinecraftFields.java:29)
[WARNING] at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:84)
[WARNING] at com.comphenix.protocol.injector.netty.ProtocolInjector$4.updatePlayer(ProtocolInjector.java:368)
[WARNING] at com.comphenix.protocol.injector.PacketFilterManager.onPlayerLogin(PacketFilterManager.java:1003)
[WARNING] at com.comphenix.protocol.injector.PacketFilterManager.access$500(PacketFilterManager.java:77)
[WARNING] at com.comphenix.protocol.injector.PacketFilterManager$4.onPlayerLogin(PacketFilterManager.java:976)
[WARNING] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[WARNING] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[WARNING] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[WARNING] at java.lang.reflect.Method.invoke(Method.java:498)
[WARNING] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305)
[WARNING] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[WARNING] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[WARNING] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[WARNING] at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:113)
[WARNING] at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.loginTick(AbstractLoginListenerPlay.java:85)
[WARNING] at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.tick(SpigotLoginListenerPlay.java:81)
[WARNING] at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230)
[WARNING] at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119)
[WARNING] at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994)
[WARNING] at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[WARNING] at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[WARNING] at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[WARNING] at java.lang.Thread.run(Thread.java:813)

**Comment by WesleyVanNeck** [comment]
not a  ProtocolSupport issue

**Comment by krusic22** [comment]
Not ProtocolSupports fault. 
ProtocolLib and the plugin using it it's to blame.

**Comment by LactoseTheIntolerant** [comment]
Alright, sorry for wasting your time, also thank you for the fast response!
