### ISSUE TITLE
FlyingBlock does not render on MC 1.13

### ISSUE THREAD

**Issue by kangarko** [ProtocolSupport/ProtocolSupport#1038]
I have a plugin CoreArena that spawns a flying block with velocity to produce procedural damage on explosion.

With ProtocolSupport, no flying blocks are shot. When the plugin is removed, everything works correctly.

With ProtocolSupport:
![a](https://i.imgur.com/3k1HPyY.gif) (https://i.imgur.com/3k1HPyY.gif)

Without ProtocolSupport:
![b](https://i.imgur.com/C5R2oCk.gif) (https://i.imgur.com/C5R2oCk.gif)

You have my build info and everything in #1037

**Comment by Shevchik** [comment]
Does it affect any other version?
Also does gravel and sand work?

**Comment by kangarko** [comment]
Oddly enough it started to work! Not really sure what was going on :)
