### ISSUE TITLE
Using Custom Enchants with ProtocolSupport adds visual-only 'Protection' on versions below 1.13

### ISSUE THREAD

**Issue by SimplyBallistic** [ProtocolSupport/ProtocolSupport#1039]
Spigot version: 1.13.2
ProtocolSupport Version:  protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.03.08 at 02:45:24 MSK, buildhost: build.true-games.org, buildnumber: 366)

Using Client version 1.12.2:
<img width="149" alt="1.12.2" src="https://user-images.githubusercontent.com/25571542/54473031-95299c00-4826-11e9-9abd-1f3a5f78e192.PNG">
Using Client version 1.13.2:
<img width="128" alt="2" src="https://user-images.githubusercontent.com/25571542/54473038-aa9ec600-4826-11e9-9b36-85495d1252a3.PNG">

Hey there!

I seemed to be having issues with ProtocolSupport when attempting to use it with custom enchants I've developed. As you can see, in versions below 1.13, we get an unusual Protection label within the lore despite the item not actually containing the enchant. However, in 1.13.2, the item displays just fine. Have any idea why this may be occurring? 
This is an example of how we add the enchants into the item:
```java
ItemMeta meta=item.getItemMeta();

        meta.removeEnchant(this);
        if(meta instanceof EnchantmentStorageMeta){
            ((EnchantmentStorageMeta) meta).addStoredEnchant(this, level, true);
        }else meta.addEnchant(this,level,true);
        item.setItemMeta(meta);
```
keep in mind the Bleed II text is a custom lore and isn't given automatically by MC. The client just thinks its a good idea to add protection along with it. 

Thanks!

**Comment by Shevchik** [comment]
The happens because you have an unknown ehcantment in the enchant tag.
When to legacy ids unknown enchants translate as 0, which in return is seen as protection ehcnatment.
Make sure you clear the enchant tag from enchants that aren't really ones before item is sent.
