### ISSUE TITLE
PE: Multiple versions of PE possible?

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#104]
Is it possible to support multiple versions of PE? On the MCPE branch of course

**Comment by MrPowerGamerBR** [comment]
Yes, it is possible, but Shevchik said that wouldn't do this because it would be a waste of time (Because MCPE auto updates itself in most of the devices)

He said this when I was adding some remappers for MCPE, maybe his opinion has changed since he said that.

**Comment by Tom-III** [comment]
In android it does not auto update and a lot of players play 0.11 because of no hunger

**Comment by Shevchik** [comment]
It is. I'm running it inside android emulator and autoupdates just fine.

**Comment by MrPowerGamerBR** [comment]
Android and iOS (since iOS 7) auto updates applications (except when the user disables auto update for a specific app)
