### ISSUE TITLE
 Players can not ride 2 people on the boat.

### ISSUE THREAD

**Issue by OverBrave** [ProtocolSupport/ProtocolSupport#1040]
Players can not ride 2 people on the boat.

![image](https://user-images.githubusercontent.com/47111280/54492253-f52b4b80-48d5-11e9-9922-b2a78214f2e4.png)

![image](https://user-images.githubusercontent.com/47111280/54492259-06745800-48d6-11e9-938e-b69b41948af9.png)

**Comment by Brokkonaut** [comment]
This works as intended if you allow clients with versions < 1.9 to connect. If you want to disable support for those old clients you can use https://www.spigotmc.org/resources/protocolsupportstuff.44527/
