### ISSUE TITLE
Empty holograms have visible name

### ISSUE THREAD

**Issue by Patbox** [ProtocolSupport/ProtocolSupport#1046]
Empty holograms is named "Armorstand" (text depends on language).
1.13.2: ![image](https://user-images.githubusercontent.com/39821509/54870651-cca9c280-4da9-11e9-82d1-73e800aae86d.png)
1.12.2: 
![image](https://user-images.githubusercontent.com/39821509/54870654-e9de9100-4da9-11e9-988c-dcd1937bae5a.png)

Server: Paper version git-Paper-571 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

ProtocolSupport: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.03.19 at 00:23:44 MSK, buildhost: build.true-games.org, buildnumber: 367)

PSaddons: LegacyChest

Hologram plugin: Holographic Displays

**Comment by Shevchik** [comment]
Empty name is threated by old versions as if it didn't have a custom name set at all. So it uses the default one.

**Comment by Patbox** [comment]
On the server with version 1.12.2 I did not have this problem (I'm now update to 1.13) :/
