### ISSUE TITLE
Plugin incompatibility // certain packets not being remapped?

### ISSUE THREAD

**Issue by mibby** [ProtocolSupport/ProtocolSupport#1047]
Paper dev 597 (Spigot 1.13.2)
Travertine dev 91 (Waterfall/BungeeCord)
ProtocolSupport dev 370

Noticed some plugin incompatibility with ProtocolSupport. Assuming because certain packets aren't being registered or remapped properly?

---

1) BungeeTabListPlus (dev 796)
https://github.com/CodeCrafter47/BungeeTabListPlus
https://www.spigotmc.org/resources/bungeetablistplus.313/

On 1.13, I am correctly colored and sorted above all others. I also see the world placeholder for the world I am currently in.
![link](https://i.imgur.com/Vd6qYDC.png)

On 1.12, it does not color me and I am sorted last in the list. I also do not see the world placeholder for the world I am currently in.
![link2](https://i.imgur.com/S0TsRx1.png)

Edit: Apparently other players who are on 1.13 while I'm on 1.12 see me as white too! :(

---

2) Better View Distance (compiled as of commit https://github.com/Kugge/BestViewDistance/commit/8e335e8d61ba77dd4e1c83dfda28e23ac98771f9 with some fixes)
https://github.com/Kugge/BestViewDistance
https://www.spigotmc.org/resources/best-view-distance.61963/
Config - https://paste.ubuntu.com/p/StcnYd9tdm/

On 1.13, BVD correctly detects the server TPS at 20 & my in-game ping, updating my view distance to the configured maximum of 16 chunks.
![link3](https://i.imgur.com/QH3TkTV.png)

On 1.12, BVD correctly detects the server TPS at 20, but I'm not sure it detects my ping or the requested chunk update is not interpreted properly. My view distance does not get updated and stays at the configured minimum of 4 chunks. Higher chunk view distance is not sent to the client.
![link4](https://i.imgur.com/xES6um4.png)

---

There are no errors whatsoever in either the proxy or server console.

**Comment by Shevchik** [comment]
BungeeTablist operates bungee side, so there is nothing we change there. So you will have to ask plugin author, not us.
We don't support paper view distance api, so any view distance changing plugins will not work.

**Comment by mibby** [comment]
BungeeTablist has a bukkit communication bridge to send data to the Bungee plugin, so it's possible ProtocolSupport may be breaking something in the plugin messages sent?

--

RE: View distance changing - I figured how it sends view distance would be version independent and wouldn't matter. Just would provide and set players with a larger view distance rendering as supported by vanilla packet sending? In any case, this issue isn't too big of a deal, the tab list is more important to me. :(

**Comment by Shevchik** [comment]
Also view distance is version independant, however changing view distance is not a packet. View distance is changed in the server itself, and we overwrite that part of the server (entity tracker to be exact) with out own changes, that do not support dynamic view distance.

**Comment by Shevchik** [comment]
I allowed 1.13 formatted channel name for < 1.13 versions. So it should be working now.
