### ISSUE TITLE
Plugin channels are broken

### ISSUE THREAD

**Issue by Artuto** [ProtocolSupport/ProtocolSupport#1050]
Not sure if this falls into PS or PSB domain but here it goes:

We're using a plugin that uses channels to teleport players between servers.

We noticed that when there's only 1.13 players the conmands work as intended.
However, when someone using 1.12.2 or older is playing the commands stop working suddenly.

**Comment by mibby** [comment]
@Shevchik Possibly related to https://github.com/ProtocolSupport/ProtocolSupport/issues/1047 with BungeeTabList plugin channels not working on 1.12 and older, but working fine on 1.13?

**Comment by Shevchik** [comment]
All < 1.13 plugin channel will have l: appended and all other invalid symbols removed.
Your plugin will have to be adapted to use transformed channel name.

**Comment by Artuto** [comment]
The plugin is 1.13 format (otherwise it wont register in Spigot).

For example `llcore:warps` does NOT work in 1.12 and older

**Comment by Shevchik** [comment]
Yeah, 1.13 doens't work as i said. It will be transformed to l:llcorewarps.
Use protocollib to debug which channel name is actually used.
