### ISSUE TITLE
Plugin favors decor over function.

### ISSUE THREAD

**Issue by EOT3000** [ProtocolSupport/ProtocolSupport#1062]
If I join 1.12 server with something old (lets say 1.5), then the plugin favors blocks that look the same over ones with same durability. Simply put, you can mine concrete for the speed of wool in 1.5!

**Comment by EOT3000** [comment]
Server version and ps version don't matter

**Comment by Shevchik** [comment]
You actually can't since the server will disallow breaking such block right now (it will reapper), and will break shorty after server really finishes breaking it.

Also wool breaks slower that concrete when using just hands.

**Comment by EOT3000** [comment]
really? because a player said that
