### ISSUE TITLE
Hit damage

### ISSUE THREAD

**Issue by iViniiAw** [ProtocolSupport/ProtocolSupport#1066]
If you fast click, even in 1.8, the damage taken is the 1.9> cooldown damage ( 1/2 a heart I think )

**Comment by Shevchik** [comment]
Works as intended.

**Comment by Emilia1012** [comment]
use https://www.spigotmc.org/resources/oldcombatmechanics-disable-1-9-hit-cooldown.19510/

**Comment by Emilia1012** [comment]
that should fix it :P

**Comment by iViniiAw** [comment]
Okay, thought devs forgot this feature lol
Great choice. This plugin is lit!
