### ISSUE TITLE
An Internal error occured

### ISSUE THREAD

**Issue by Blackfire62** [ProtocolSupport/ProtocolSupport#107]
This happens everytime a non 1.8 player joins.
Using latest jenkins version

 [16:41:56 INFO]: UUID of player guy is d18225f9-811c-3585-bc17-aee125a06810
> [16:41:56 INFO]: guy[/78.99.145.2:36208] logged in with entity id 167 at ([lobby]20.355286886456113, 72.0, -31.574786789686392)
> [16:41:56 INFO]: guy lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

**Comment by Shevchik** [comment]
Enable debug and show the output

**Comment by swan201** [comment]
I think This issue look like same https://github.com/ProtocolSupport/ProtocolSupport/issues/108 this issue. https://github.com/ProtocolSupport/ProtocolSupport/commit/3eb7a17af736b8c80153c4ebb5fe59caf6b22333 This Commit broken non 1.8 Client connect maybe
