### ISSUE TITLE
Wolf Collar Colour Incorrectly Mapped

### ISSUE THREAD

**Issue by InfinityAspire** [ProtocolSupport/ProtocolSupport#1072]
Just a small issue with Wolf collar colours, they're not mapped correctly between versions.
Versions I've tested are 1.12.2 <-> 1.13.x

* ProtocolSupport version: Build 377
* Server version: Paper 1.13.2 Build 612

**Comment by magicus** [comment]
As a note, I fixed wolf collars for PE some time ago. Might be that the same remap is needed for older PC clients.
