### ISSUE TITLE
kick issue with protocol support, travertine, viaversion on 1.14

### ISSUE THREAD

**Issue by PhanaticD** [ProtocolSupport/ProtocolSupport#1079]
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.04.09 at 18:42:11 MSK, buildhost: build.true-games.org, buildnumber: 377)

ViaVersion 2.0.1

Paper version git-Paper-624 (MC: 1.13.2)

This server is running Travertine version git:Travertine-Bootstrap:1.14-SNAPSHOT:06d4cc9:95 by md_5

players are getting kicked on 1.14 with this https://hastebin.com/raw/isunococex 
found that its from protocolsupport using a heap dump: https://gyazo.com/60b21158ff00758cd2667b71a97ed186

the only plugins that I use that modify scoreboard that I am aware of are FeatherBoard, and NameTagEdit

**Comment by Shevchik** [comment]
Server sent a duplicated scoreboard team. Has nothing to do with protocolsupport.

**Comment by Shevchik** [comment]
Server sent a duplicated scoreboard team. Has nothing to do with protocolsupport.
