### ISSUE TITLE
[Request] Please, update versions for 1.14 to jenkins

### ISSUE THREAD

**Issue by MorkaZ** [ProtocolSupport/ProtocolSupport#1085]
Please, can you build this resource and upload it to jenkins? Some people are waiting for it (including me). 
I was trying to build this project using gradle file but I have some JDK problems that I am unnable to fix and building proces is always failing after some minutes. :/

**Comment by Shevchik** [comment]
The 1.14 branch is WIP, and many things don't work yet. Wait until it is merged to master.

**Comment by MorkaZ** [comment]
Ok, thanks for response :)
