### ISSUE TITLE
Players are getting kicked when they hit/kill entity

### ISSUE THREAD

**Issue by MorkaZ** [ProtocolSupport/ProtocolSupport#1086]
Players are getting kicked when they hit/kill entity.
I have did some tests after many reports about being kicked and I have reproduced it.
Sometimes, when player hits entity (for example pig) he gets kicked with this message:
![kick](https://user-images.githubusercontent.com/4214815/57262890-7ef1cc80-706e-11e9-812a-1a0fae54ce73.png)
There is no error in console exemp kick with message above.
I have executed /protocolsupport debug, reproduced this bug again and got this error in console:
https://pastebin.com/tKqEBQYM
I have also noticed that it only happens when player is not flying, is in survival mode and he is hitting by clicking on mob (shooting projectile at mob do not kick).

Can you please fix it? With this bug one of my servers is unplayable with protocolsupport (players almost cant hit mobs). 

I am using:
- Java 1.8 on debian9. 
- 2 weeks ago builded spigot 1.13.2
- Latest protocolsupport from your jenkins
- Raw (without plugins) Bungeecord (tested on 1.13 and 1.14 versions)

**Comment by MorkaZ** [comment]
https://github.com/BentoBoxWorld/BSkyBlock/issues/117

**Comment by Shevchik** [comment]
You have a plugin that sends invalid data. The entity animation packet has no animation type 1.

**Comment by MorkaZ** [comment]
As in ticket reported above, I have noticed it happens only on Bskyblock's worlds. Maybe Bskyblock generates this error?
Can you please add simple replace method that will change this data "1" to valid value? Thanks

**Comment by MorkaZ** [comment]
Can you please create simple replace method that will change animation type value in packet to correct number to avoid problems like this one?

**Comment by Shevchik** [comment]
No.

**Comment by MorkaZ** [comment]
Found cause. Thank you a lot for helping.
It is anticheat premium plugin called "Reflex".

**Comment by Shevchik** [comment]
This value had a meaning of performing hurt animation in many versions of minecraft. Yet is was replaced by entity status in further versions.
