### ISSUE TITLE
In game name tab complete

### ISSUE THREAD

**Issue by Xosmuits** [ProtocolSupport/ProtocolSupport#1089]
I love the plugin, it is so well done! But I have a problem, a big one, when using a version besides 1.13.2 you can't use tab for player names, it always completes commands, even without slash. Is there anything to fix this? Just to notice, it completes names after a command is written.

http://prntscr.com/norddz

**Comment by Shevchik** [comment]
Tab complete is handled by server, not by protocolsupport.

**Comment by Xosmuits** [comment]
What can I do then?
