### ISSUE TITLE
Disconnected Error.

### ISSUE THREAD

**Issue by drizzerx** [ProtocolSupport/ProtocolSupport#109]
Strange Issue. Some times you can join the server and everything works perfect. But other times you cant even get into the server if ProtocolSupport is installed. This is what happens:

Logging in...
Disconnected

Even if I try changing versions (1.7.X-1.8.X) I am still unable to join. 

If I remove the protocolsupport plugin everything works fine. Tried removing it from my server lobbies and users having this problem could join again. 

A lot of users have complained about this, and the strange thing is that without doing anything the error fixes itself but different players start having this issue. I have tried to search for errors in the log files but there is no error stacktrace.

I don't know if its something related to the spigot version or the bungee version of protocolsupport (I have both of them installed) 
I am using the latest spigot and bungee version
Also the latest protocolsupport version for spigot and bungee

**Comment by Shevchik** [comment]
Are you sure that you disabled native transport and you don't have any plugins that do something heavy in main/network thread?

**Comment by drizzerx** [comment]
![27dbeb17da8dfbc6697a203b69db124c1d6d58114e88506e62 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/10679538/12004816/2b65c140-ab3f-11e5-81c0-90bfe679aab7.jpg)
![27dbeb17da8dfbc6697a203b69db124c1d6d58114e88506e62 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/10679538/12004817/2b677abc-ab3f-11e5-92c0-0b06a863b997.jpg)
Yes, I am pretty sure. 
Bungee Plugins:
![asdasd](https://cloud.githubusercontent.com/assets/10679538/12004818/50506866-ab3f-11e5-975a-410a302ed47b.PNG)

Lobby Plugins:
![saf](https://cloud.githubusercontent.com/assets/10679538/12004820/711ba344-ab3f-11e5-9ddb-c57d4f2739dd.PNG)

**Comment by sgdc3** [comment]
Hello! ;)
Are you using latest protocollib version?
Skinrestorer should be installed bungee-side only!
Your authme version is outdated, try latest dev build.

**Comment by Shevchik** [comment]
Do you able to connect to server directly when this happens?

**Comment by drizzerx** [comment]
Yes. I think this video should explain everything:
https://youtu.be/GFJeEG60mlU
He was using mc version 1.8.7 with Optifine. I tried joining with the same exact version and I had no problem :/. I updated Authme & Protocollib and deleted SkinRestorer from the servers like sgdc said.

**Comment by drizzerx** [comment]
Also one thing I noticed is that he connects to the bungee, but does not even try to connect to the server. He does not even get forwarded to the lobbies.

**Comment by Shevchik** [comment]
Than it is a problem on protocolsupportbungee side.
