### ISSUE TITLE
Enchantments for wrong tools

### ISSUE THREAD

**Issue by Artuto** [ProtocolSupport/ProtocolSupport#1090]
A player in MC 1.8 reported that while enchanting they got this enchantment for a pickaxe:

![unknown (1)](https://user-images.githubusercontent.com/9273973/57953814-c8d08300-78b6-11e9-896c-898e3935a99f.png)

I tried to reproduce this on MC 1.13.2 however I couldnt, so I'm guessing it is a PS bug.

I'm using latest `mcpenew` with `master` merged on it

**Comment by Shevchik** [comment]
Did some changes around that part. Maybe that fixed the issue (since i couldn't reproduce it).
