### ISSUE TITLE
1.14.1: Signs disappear when logging out

### ISSUE THREAD

**Issue by alvarlagerlof** [ProtocolSupport/ProtocolSupport#1093]
ProtocolSupport version: Latest (built from gradle)
Server version: Paper 1.14.1 build #22

**Comment by jordanwilliams1** [comment]
@alvarlagerlof How did you get it to load on 1.14? I'm trying but it wont :(

**Comment by Speentie8081** [comment]
@jordanwilliams1 https://ci.skorrloregaming.com/job/ProtocolSupport-1.14/
