### ISSUE TITLE
Feature: Allow PS to be installed to a maven repository

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#1104]
I think it would be useful if ProtocolSupport could be installed to a local maven repository, this can simplify developing dependent projects.

It is just a small change to the build.gradle, just add
`apply plugin: 'maven'` (https://docs.gradle.org/current/userguide/maven_plugin.html)

This allows to use `./gradlew install`

**Comment by Artuto** [comment]
You can also use jitpack.io
