### ISSUE TITLE
Repeated randomly kick players from the server.

### ISSUE THREAD

**Issue by DardBrinza** [ProtocolSupport/ProtocolSupport#111]
Again, the players kicked from the server.It occurs similar: the server every 20 minutes for about 3 seconds stops and returns for further work. But sometimes the server stops at 10 seconds and kicks all players server. Latest build PS and spigot.

My settings:
use-native-transport=false
late-bind: false

Error:
http://pastebin.com/B3sFbA1p

**Comment by Shevchik** [comment]
Your server crashed due to really poor UserCache performance. Delete usercache.json and change spigot settings to limit max usercache value to 0.
