### ISSUE TITLE
Incorrect banner pattern color on items & shields

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#1110]
Same incorrect colors as #1027 
Tested using 1.12.2 and 1.13.2

Banner: http://prnt.sc/o2cd0m
Shield: http://prnt.sc/o2cddk

**Comment by Nikita11790** [comment]
incase no-one knows the banner should be white, not black and the shield should be orange not red

**Comment by Shevchik** [comment]
Fixed
