### ISSUE TITLE
ProtocolSupport blocks holograms from working in newer versions

### ISSUE THREAD

**Issue by Wynandus** [ProtocolSupport/ProtocolSupport#1112]
The plugin blocks holograms from showing in newer versions of minecraft, in 1.14.2 you can't see the holograms from both the plugin holograms and holographicdisplays. Please fix this

Buildinfo: http://prntscr.com/o2kz10
Server version: paperspigot 1.14.2-RO.1-SNAPSHOT

**Comment by Shevchik** [comment]
1. You are using not yet supported version.
2. Your build is old.
3. The required metadata remaps were implemented a day ago, so this is already fixed.
