### ISSUE TITLE
Fireworks Cause the Older Clients Quit the Game

### ISSUE THREAD

**Issue by Xuwznln** [ProtocolSupport/ProtocolSupport#1116]
* ProtocolSupport version (/ps buildinfo) 379(the latest one)
* Server version 1.14.2 paper

when a player lunch a firework , other players quit with the log like this: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: No type id exists for object class protocolsupport.protocol.types.networkentity.metadata.objects.NetworkEntityMetadataObjectOptionalVarInt for protocol version MINECRAFT_1_13
Please fix that, Thanks!

**Comment by Shevchik** [comment]
Should be fixed

**Comment by Xuwznln** [comment]
tested 1.12.2 1.13 , its fixed, thanks!
