### ISSUE TITLE
Timings Lag from task AbstractLoginListenerPlay$1(interval 1)

### ISSUE THREAD

**Issue by Wealthyturtle** [ProtocolSupport/ProtocolSupport#1119]
* ProtocolSupport version (/ps buildinfo): ProtocolSupport Build 381
* Server version: Spigot 1.14.3

Currently, when using /timings paste and leaving the server on for some time, it can be seen that AbstractLoginListenerPlay$1(interval 1) is causing significant lag in the Pct Tick column.

When only 1 player is on the server, the Pct Tick was around 100% (https://timings.spigotmc.org/?url=potetoyepe). This value seems to scale linearly with the number of players who log into the server. 

On my main server, this value seems to range from around 400% to 800% at certain occasions (https://timings.spigotmc.org/?url=oxolayavod).

Any idea?

**Comment by Shevchik** [comment]
This task actually just calls the mojang login code. So it has to be something inside the server itself.

**Comment by Wealthyturtle** [comment]
If it's any help, I turned on /ps debug and this got thrown out
```
[Wed, 26. Jun 2019 08:39:04 GMT INFO] [ProtocolSupport] /127.0.0.1:50650 connected with protocol version MINECRAFT_1_7_5
[Wed, 26. Jun 2019 08:39:05 GMT INFO] [ProtocolSupport] /127.0.0.1:50766 connected with protocol version MINECRAFT_1_7_5
[Wed, 26. Jun 2019 08:39:06 GMT INFO] [ProtocolSupport] /127.0.0.1:50894 connected with protocol version MINECRAFT_1_7_5
[Wed, 26. Jun 2019 08:39:07 GMT INFO] [ProtocolSupport] /127.0.0.1:51010 connected with protocol version MINECRAFT_1_7_5
[Wed, 26. Jun 2019 08:39:08 GMT INFO] [ProtocolSupport] /127.0.0.1:51126 connected with protocol version MINECRAFT_1_7_5``` almost every second

**Comment by Shevchik** [comment]
This task mostly calls mojang and original bukkit code, so the reason for it being slow it essentially original mojang code being slow.
