### ISSUE TITLE
Retry. No error, only kick all players

### ISSUE THREAD

**Issue by DardBrinza** [ProtocolSupport/ProtocolSupport#112]
Latest spigot + protocol support. User-cache: 0

https://gist.github.com/DardBrinza/79b1cfc79bad939e21a4

**Comment by Shevchik** [comment]
Well, your server is overloaded with some shit. Use timings to profile it, and stop reporting it here, your issues has nothing to do with protocolsupport.
Also i'm not helping you anymore, you have a type of server that i personally dislike.
