### ISSUE TITLE
ladders

### ISSUE THREAD

**Issue by MrScopes** [ProtocolSupport/ProtocolSupport#1121]
ladders don't work on 1.8 and lower

**Comment by ArtelGG** [comment]
I believe the same issue is happening for carpets as well.

**Comment by Gerrygames** [comment]
I fixed this issue in my plugin:
https://github.com/Gerrygames/ViaRewind-Legacy-Support/commit/ba4d64cb56c0e5619d5457106b12cd62d461adf7#diff-115be94630bee5116785c0aa09c87f9f
Feel free to use the code :)

**Comment by Shevchik** [comment]
Fixed
