### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MithrandirCraft** [ProtocolSupport/ProtocolSupport#1122]
Found this error on crash, thought it might be relevant allthough I'm not using the latest version of PS (probably since I'm still on 1.13.2)
https://pastebin.com/aqHBN0eJ

Spigot 1.13.2
PS 4.29-dev

I am now updating to the latest dev build, as indicated, still wanted to let this be known. The only plugins I see in the error are PS and Chairs?

**Comment by Shevchik** [comment]
Not a protocolsupport problem.
