### ISSUE TITLE
Sometimes 1.12 clients are getting kicked "180 can't be represented as byte (out of range)"

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#1123]
Exception:
https://pastebin.com/raw/T7RPb9YP

ProtocolSupport: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.07.02 at 02:56:14 MSK, buildhost: build.true-games.org, buildnumber: 385, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:d4126d64c1a8cf11e54b209ed1dc162ab7b5d5d8)
Server: Paper version git-Paper-0d079188 (MC: 1.14.3)

**Comment by Shevchik** [comment]
Fixed
