### ISSUE TITLE
Bug 1.14.3 Server (panda animations)

### ISSUE THREAD

**Issue by JoelDeadMach** [ProtocolSupport/ProtocolSupport#1124]
**Description:** 
Soo there is a issue with protocolsupport if your server is 1.14.3, panda's are turning to just black panda's instead of different colors (while you are also in 1.14.3 client)
the animations of the panda's are also not working when protocolsupport is enabled.

**Debug output:** 
https://pastebin.com/x30vb5bt ( I am logged in on 1.14.3 client)

**ProtocolSupport version (/ps buildinfo):**
https://i.imgur.com/7IfJxsd.png
https://github.com/ProtocolSupport/ProtocolSupport:origin/master:9ae6b918465f1f0bfb70be8a7b9c80b15750e880)

**Server version:**
https://i.imgur.com/2RVE4NW.png

**Comment by JoelDeadMach** [comment]
The only plugin is ps

**Comment by JoelDeadMach** [comment]
The only thing they do is walking around and standing, nothing else:
![image](https://user-images.githubusercontent.com/22543334/60755016-0ebde380-9fea-11e9-9275-3a9706578a5b.png) (and they are only black, when i remove ps they have like different colors brown and such.

It should do like this: 
![image](https://user-images.githubusercontent.com/22543334/60755029-66f4e580-9fea-11e9-8e30-c12b71702e20.png)

**Comment by Shevchik** [comment]
Fixed.
