### ISSUE TITLE
Stripped logs not visually appearing in clients older than 1.13

### ISSUE THREAD

**Issue by axemwa** [ProtocolSupport/ProtocolSupport#1128]
When joining a 1.13.2 server from a 1.12.2 client ITEM_FRAMES that are on the ground appear vertical when they are supposed to be flat on the ground can this be fixed?

Paper #639 - https://papermc.io/ci/job/Paper-1.13/639/
ProtocolSupport #393 - https://build.true-games.org/job/ProtocolSupport/393/

**Comment by Speentie8081** [comment]
No

**Comment by axemwa** [comment]
oh well thanx for letting me know anyway and for the quick response ;)

**Comment by axemwa** [comment]
@Speentie8081 
What about stripped logs? Is there a way to make them appear for the player when using a client older than 1.13 strips a log? I tested with client in 1.12.2 on my 1.13.2 server and even though it allows me to strip the logs in older client versions it does not allow me to see the stripped log itself visually, it still appears to be a normal log even though iot's not. Is this something that can be fixed?

**Comment by Shevchik** [comment]
Stirped logs were added in 1.13.2. Stop asking and do a basic research yourself.

**Comment by axemwa** [comment]
Well I won't know if I don't ask will I, this is quicker than basic research atm as I wouldn't know where to first look so it's not like I'm not trying

I just thought it was weird that the new "WOOD" textures are working in 1.12.2 clients when joining the 1.13.2 server but stripped textures aren't that's all so I thought I'd mention it instead of starting a new issue, no need to get upset and/or make assumptions.

If you prefer me to ask questions somewhere else then please guide me to where I need to go. I don't mean to upset anybody, I'm just sort of new to all this and this is just where I've been told to ask questions and make reports for other devs so I just assumed you would be the same.
