### ISSUE TITLE
ProtocolSupport prevents MaintenanceMode's MOTD from appearing

### ISSUE THREAD

**Issue by axemwa** [ProtocolSupport/ProtocolSupport#1130]
Clients can't see [MaintenanceMode](https://www.spigotmc.org/resources/maintenancemode-bungee-and-spigot-support-1-8-1-14.40699/)'s server ping description/custom motd etc. with PS installed, even if the client is on the same version as the server. Can you plz fix/add support?

Last report by KennyTV
![image](https://user-images.githubusercontent.com/37608633/61575761-f7fdad80-ab0e-11e9-87ea-b86ad4b48064.png)

Original report by Alter-Ego 
![image](https://user-images.githubusercontent.com/37608633/61575789-51fe7300-ab0f-11e9-8e74-9bfe180f0009.png)

**Comment by Shevchik** [comment]
This needs paperserverlistping implementation

**Comment by Shevchik** [comment]
Should be fixed now.
