### ISSUE TITLE
Players with 1.8 are getting disconnected when they try to join the 1.13.2 server.

### ISSUE THREAD

**Issue by axemwa** [ProtocolSupport/ProtocolSupport#1131]
Getting disconnected when trying to join the 1.13.2 server with a 1.8 client
I got this client error
![image](https://user-images.githubusercontent.com/37608633/61591278-04affd80-ac04-11e9-8ae3-c627d24e0ac5.png)
and these WARNS and ERRORS in console. 

https://hastebin.com/axapepohum.md

I have a feeling that it's a plugin conflict cause it allows me to join on a fresh/new 1.13.2 server with 1.8 client, just not my current server. If you could help me find out what it is it would mean a lot :)

* ProtocolSupport version 
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.04.09 at 18:42:11 MSK, buildhost: build.true-games.org, buildnumber: 377)
* Server version
Paper-639 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by axemwa** [comment]
Similar to this issue I think
https://github.com/ProtocolSupport/ProtocolSupport/issues/812

**Comment by Shevchik** [comment]
Not a protocolsupport problem. The problem is either in protcollib itself, or some plugin that uses it.

**Comment by axemwa** [comment]
Disabling ProtocolLib seems to fix it but then again disabling ProtocolSupportLegacySupport seems to fix it too and by fix it I mean allows the 1.8 client to join the 1.13.2 server

**Comment by axemwa** [comment]
Hmm removing ProtocolSupportLegacySupport seems to have fixed the 1.8 client issue I was having, strange and on another server removing WorldChangeScreenRemover.jar fixed it
