### ISSUE TITLE
Kicked by Killing squid

### ISSUE THREAD

**Issue by VirgilFabre** [ProtocolSupport/ProtocolSupport#1133]
My player got kicked 2 times (1 At first, then second as a test)
He had 1.12.2 on the lastest 1.14.4 server with lastest version

Here's what appeared
[https://i.snag.gy/wFUrB5.jpg](url)

**Comment by Shevchik** [comment]
Should be fixed

**Comment by VirgilFabre** [comment]
We tested it again
IM HAPPY WE DIDN'T TEST IT ON THE SERVER lmao
it crashed the whole server, server froze

https://i.snag.gy/6qKonQ.jpg
