### ISSUE TITLE
Incorrect smooth stone/sandstone remap

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#1136]
Smooth stone/sandstone is remapped as stone/sandstone for older versions.

1.13.2: http://prnt.sc/oikiea
1.8.9: http://prnt.sc/oikila

**Comment by Speentie8081** [comment]
Working as intended *

**Comment by krusic22** [comment]
Older versions do support that block, so I see no reason to not remap to it.

**Comment by ArtelGG** [comment]
Double slabs that look exactly like that block do exist in older versions.

**Comment by Shevchik** [comment]
Fixed.
