### ISSUE TITLE
Lost connection to server

### ISSUE THREAD

**Issue by j0ach1mmall3** [ProtocolSupport/ProtocolSupport#114]
Whenever a custom enchantment from my plugin displays for a 1.7.10 user on a 1.8.9 server, the 1.7.10 user gets kicked with the message "[Proxy] Lost connection to server."
Running ProtocolSupport 4.2.1
(My plugin: UltimateCosmetics, I display a "Glow" effect when a player has selected a cosmetic")
The ID of this enchantment happens to be 255, and in the log it mentions an ArrayIndexOutOfBoundException, so I'm guessing that's some kind of incompatibility here.
Log: http://pastebin.com/bULUnd2z

**Comment by Shevchik** [comment]
Your enchantment is outside of the side of default enchantment array size

**Comment by j0ach1mmall3** [comment]
So you will fix this issue, or do I have to edit my plugin?

**Comment by Shevchik** [comment]
Already fixed
