### ISSUE TITLE
PE Clients crash on respawn

### ISSUE THREAD

**Issue by DisabledMallis** [ProtocolSupport/ProtocolSupport#1147]
To start, here is my build info:
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.07.27 at 19:05:00 EDT, buildhost: unknown, buildnumber: unknown, buildgit: unknown)
doesnt seem to provide the info for some reason but i just compiled the mcpenew branch myself, so maybe thats why? Still clueless about that.

Server version:
Paper version git-Paper-134 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

And here is what ps debug is showing:
https://paste.ubuntu.com/p/T3y5V6Zh53/

If i missed anything or whatever just tell me

**Comment by Shevchik** [comment]
We don't support PE branch, it's clearly written in the readme.
