### ISSUE TITLE
SERVER CRASH BY KILLING SQUID (Urgent)

### ISSUE THREAD

**Issue by VirgilFabre** [ProtocolSupport/ProtocolSupport#1150]
9 Days ago I posted
_My player got kicked 2 times (1 At first, then second as a test)
He had 1.12.2 on the lastest 1.14.4 server with lastest version
Here's what appeared
https://i.snag.gy/wFUrB5.jpg_

We tested it again
IM HAPPY WE DIDN'T TEST IT ON THE SERVER
**it crashed the whole server, server froze**

https://i.snag.gy/6qKonQ.jpg

**Comment by Shevchik** [comment]
The freeze doesn't contain Server Thread stacktrace dump.

**Comment by VirgilFabre** [comment]
It is a protocol support problem.
I only have this plugin on.... it's a test server where anyone can be op, we re having fun for days
And live I just said lets test the squid again, and crash.

**Comment by VirgilFabre** [comment]
Don't worry I know what I'm talking about....

**Comment by Shevchik** [comment]
Your server timed out of chunk loading, has nothing to do with protocolsupport.

**Comment by VirgilFabre** [comment]
Somehow its the stick that's way too op that we used to kill it that's op....
False alarm.


Well, now I feel like a dick lmao ayy

**Comment by Speentie8081** [comment]
This has to be the most hilarious thread I have ever read on here
