### ISSUE TITLE
Potted wither rose & lily of the valley

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#1151]
The remappings for potted wither rose and lily of the valley dont actually appear inside pots. I tested with cornflower as well, doesn't happen with it.

1.14.4: http://prnt.sc/omrkmb
1.8.9: http://prnt.sc/omrkr2

**Comment by Shevchik** [comment]
< 1.13 are remapped to just flower pots, no idea how you even see them (with the exception of client initial place).
I changed the remap however, just so 1.13 clients can see potted remap.

I will not readd the blockdata -> legacy tile remapper, so for < 1.13 potted flowers will display just as flowers (soon).
