### ISSUE TITLE
Black base banner color on place

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#1152]
When placing a banner, the base color will be black. If you leave and re-enter the chunks (or relog), the base color will display correctly again.

1.8.9: http://prnt.sc/onr3z9
1.14.4: http://prnt.sc/onr5he

The issue was pretty hard for me to explain, so I used gifs just in case.

**Comment by Shevchik** [comment]
Has something to do tile updates on block place, because beds have almost the same issue.

**Comment by MasterDash5** [comment]
Skulls seem to have a pretty similar issue too.

**Comment by Shevchik** [comment]
Fixed
