### ISSUE TITLE
Polar Bears are 1.10

### ISSUE THREAD

**Issue by pkt77** [ProtocolSupport/ProtocolSupport#1153]
The entity remapper sets polar bears to spiders on 1.10. They were added on that version as you can see on the wiki: https://minecraft.gamepedia.com/Polar_Bear

(Pandas need to be updated with this change too)

I also think they should be remapped to a sheep instead, unless there's a reason they're spiders?

**Comment by Shevchik** [comment]
Fixed.

Polar bears can be hostile. It will look strange if sheep will start suddenly attacking player.
