### ISSUE TITLE
1.8 players on 1.14 server get clipped into walls by setVelocity

### ISSUE THREAD

**Issue by theonlygusti** [ProtocolSupport/ProtocolSupport#1154]
ProtocolSupport version: v4.29-dev
Server version: git-Paper-156 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Bug is reproducible on other server versions.

1.8 clients get stuck in walls by velocity packets: https://youtu.be/axH3wtEAajg

1.14 clients do not.

**Comment by Shevchik** [comment]
Couldn't reproduce.
Need this map for testing.

**Comment by theonlygusti** [comment]
@Shevchik what I did was make a plugin that always sets the player's velocity to the player's direction, `player.setVelocity` etc.

Maybe it's not possible using vanilla creative fly in 1.8, but with `setVelocity` from plugins it happens all the time.

It works most consistently on corners, doesn't just need this map.

Here's the crappy plugin I made, turn on by toggling flight

[kits-0.0.0.jar.zip](https://github.com/ProtocolSupport/ProtocolSupport/files/3464933/kits-0.0.0.jar.zip)

**Comment by Shevchik** [comment]
Well, that's exactly what you do wrong. Applying velocity will desync player (because the server has old velocity, while player already calculated itself new one), and will cause position change reject. And since clients below 1.9 don't handle teleport reject well, this happens.

**Comment by theonlygusti** [comment]
@Shevchik it doesn't happen on a 1.8 server with a 1.8 client

**Comment by Shevchik** [comment]
It's doesn't matter. 1.14.4 server validates movement stricter than 1.8.
