### ISSUE TITLE
Explosions desync blocks

### ISSUE THREAD

**Issue by Gerrygames** [ProtocolSupport/ProtocolSupport#1155]
ProtocolSupport version:
``protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.08.03 at 23:47:09 MSK, buildhost: build.true-games.org, buildnumber: 410, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:353364f9295b5c094503b193d925134cf1bb82a5)``
Server version:
``git-Spigot-e5b1b5d-e5e8eec (MC: 1.14.4)``

If I create an explosion with a radius higher than normal blocks disappear on 1.13.2 (and probably lower) that are actually still present on the server.
Test plugin code:
http://paste.cytooxien.de/cijisajano.java
Video:
https://youtu.be/LmE1BXuglds

I tested this like 10 times and this only happened to the 1.13.2 client, not the 1.14.4 client. So I am pretty certain this is an issue with ProtocolSupport. Seems like it doesn't happen all the time, but if a few TNT blocks explode it's pretty much guaranteed. I did not test with any other 1.14.x client because the protocol changes are minimal.

This might be related:
https://github.com/ViaVersion/ViaVersion/issues/1365

**Comment by Shevchik** [comment]
I forgot to propagate block changes to chunk cache for explosions. Will fix it soon.

**Comment by Shevchik** [comment]
I also detected a difference between explosion calculations between new and old versions:

This is a part of code that calculates block origin point for explosion in 1.14.4:
        int var2 = MathHelper.floor((double)this.a);
        int var3 = MathHelper.floor((double)this.b);
        int var4 = MathHelper.floor((double)this.c);

This is the same part of code for 1.12.2:
      int j = (int)this.posX;
      int k = (int)this.posY;
      int l = (int)this.posZ;

Which means that origin point differs by 1 for negative locatons.
Does the issue only reproduces for negative coordinates for you?

**Comment by Gerrygames** [comment]
Oh this could actually be it. I will test it at differently signed coordinates.

**Comment by Gerrygames** [comment]
Yeah pretty certain it only happens for negative coordinates.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by Gerrygames** [comment]
Pretty sure it's fixed. Can't reproduce it anymore and the cause you mentioned makes sense.
