### ISSUE TITLE
Minecraft BE can't enter the server!

### ISSUE THREAD

**Issue by RONGYAO749** [ProtocolSupport/ProtocolSupport#1158]
As the title shows, after using this plugin, my MinecraftBE can't enter the server, but the Java version can still enter.

ProtocolSupport version: The latest development version (I don't know the version, but I can confirm that I downloaded the latest version)

Server version: 1.14+ (PaperSpigot)

**Comment by krusic22** [comment]
ProtocolSupport PE is currently not supported.
