### ISSUE TITLE
Empty protocolsupport list

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#116]
01.01 14:47:59 [Server] INFO [1.4.7]: 
01.01 14:47:59 [Server] INFO [1.5.1]: 
01.01 14:47:59 [Server] INFO [1.5.2]: 
01.01 14:47:59 [Server] INFO [1.6.1]: 
01.01 14:47:59 [Server] INFO [1.6.2]: 
01.01 14:47:59 [Server] INFO [1.6.4]: 
01.01 14:47:59 [Server] INFO [1.7.5]: 
01.01 14:47:59 [Server] INFO [1.7.10]: 
01.01 14:47:59 [Server] INFO [1.8]:
Running latest spigot 1.8.8 and latest protocolsupport dev build. (Also tried compiling from source, same problem)

Also getting this spammed a bit in the console, I don't know if its related:
01.01 14:47:29 [Server] WARN Tried to add entity null that already exists with UUID 48429485-5f97-2a80-a0d9-5a3eba085fd4

EDIT: After plenty of testing I have seen that this happens only to server with bungeecord behind it!

**Comment by Shevchik** [comment]
I probably know the reason
