### ISSUE TITLE
Shulker Box 1.14.4 IndexOutOfBoundsException

### ISSUE THREAD

**Issue by IndiCuddie** [ProtocolSupport/ProtocolSupport#1160]
Running a server on Paper 1.14.4 and when i place down a Shulker Box and a 1.14.4 client opens it the inventory is 27 slots and when i join on a 1.9 client the inventory is 36 slots which means there in-turn is an IndexOutOfBoundsException, [Server] INFO java.lang.IndexOutOfBoundsException: Index: 71, Size: 63

**Comment by Shevchik** [comment]
Fixed
