### ISSUE TITLE
Player NPCs sometimes disappear on older versions

### ISSUE THREAD

**Issue by MrIvanPlays** [ProtocolSupport/ProtocolSupport#1161]
* ProtocolSupport version https://gyazo.com/8878836461a7cda995acbb810a2b0ccf
* Server version https://gyazo.com/fc04a5217ffd96493b2259902dcf3880

Sometimes a player disappears (he didn't left the server as we see him in the tab and also see him chatting). This happens randomly on older versions, I'm sure that this happens on 1.8 as I expected this on the specified version, not sure for 1.9 - 1.13 .

**Comment by MrIvanPlays** [comment]
Here's a video representing the problem

![Video](https://i.imgur.com/OlIoLYj.mp4)

**Comment by Shevchik** [comment]
Test without other plugins first.

**Comment by MrIvanPlays** [comment]
It looks like without plugins there's no problem. Ill find the problem plugin. Thanks for the help
