### ISSUE TITLE
Placing a chest results in ender chest

### ISSUE THREAD

**Issue by MrIvanPlays** [ProtocolSupport/ProtocolSupport#1162]
* ProtocolSupport version https://gyazo.com/8878836461a7cda995acbb810a2b0ccf
* Server version https://gyazo.com/fc04a5217ffd96493b2259902dcf3880

When I place a chest on 1.8, this chest results in ender chest. When I place it on 1.14 tho, the players on 1.8 see it as a ender chest. Pretty sure something's bugged with item ids, which were removed in 1.13.

**Comment by krusic22** [comment]
Non issue. Use ProtocolSupportLegacyChests is you want the chests to look "correctly".

**Comment by MrIvanPlays** [comment]
Ok thanks
