### ISSUE TITLE
Server thread dump

### ISSUE THREAD

**Issue by Heliosard** [ProtocolSupport/ProtocolSupport#1164]
Hello,
Since the installation of ProtocolSupport on one of our hubs servers, after a few hours of launch, we encounter a thread dump.

Here is the error: https://gist.github.com/Heliosard/aaf07fa16be75471a65e8b7c2248d0db

**ProtocolSupport version:** protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.08.27 at 14:24:53 MSK, buildhost: build.true-games.org, buildnumber: 437, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:3a80c661fe665611a15d8cf39e91160e6775d2f2)

**Server version:** git-Paper-176 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Do you need more information? Any additional tests?

Thank you in advance for your help.

**Comment by Shevchik** [comment]
This method literally calls mojang join game code, so not a protocolsupport problem.
