### ISSUE TITLE
[1.14.4] Hunger bar goes to 0 when strong Saturation potion effect (more than 127 level) is applied, and it stays at 0 forever

### ISSUE THREAD

**Issue by KabanFriends** [ProtocolSupport/ProtocolSupport#1166]
**The reproduction steps may be wrong due to the randomness of the bug. Please read the EDIT section I wrote while reproducing.**

Build Info:
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.08.27 at 14:24:53 MSK, buildhost: build.true-games.org, buildnumber: 437, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:3a80c661fe665611a15d8cf39e91160e6775d2f2)

Server Software: Spigot 1.14.4
CraftBukkit version git-Spigot-798ea6a-368f4e9 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Tested with only ProtocolSupport plugin

Debug log: None

How to reproduce:
1. Join 1.14.4 server which has ProtocolSupport installed
2. Run `/effect give <username> minecraft:saturation 1000000 255 true`
3. See the hunger bar
[Optional steps]
4. Run `/effect clear <username>`
5. Get food and eat it

Expected result: Hunger bar stays at max value (Without ProtocolSupport, this is the actual result)
Actual result: Hunger bar goes to 0, eating food won't give any hunger bar value (even after you remove Saturation effect from you)

**EDIT:** _This problem didn't happen when I tested it again (the problem where the hunger bar goes to 0), but still it sends me the weird error message when I run saturation command. Seems like the hunger bar problem happens very randomly, but the command still gave me an incorrect result._

*Tested in 2 servers (mine and my friend's), the same problem happened on both servers.

This is my guess, but maybe ProtocolSupport is changing how Saturation works. In Vanilla or any servers without ProtocolSupport, Saturation 255 gives you full hunger bar. But with ProtocolSupport, I think Saturation 255 gives you minus value for hunger bar, resulting in the hunger bar to get glitched

This bug caused a problem in my command minigame. All players have to run away from the enemy but they can't run because of saturation glitch. I can just change my command to make it doesn't happen, but this would be annoying for people who haven't noticed this bug.

**Comment by Shevchik** [comment]
The actual protocol level potion amplifier is a byte value (and nbt storage is too). So protocolsupport converts the effect level to byte value to fix another issue related to levitation and slow falling.
So essentially you just used unsupported amplifier.
