### ISSUE TITLE
Block(s) disappears in escape menu below version 1.13

### ISSUE THREAD

**Issue by MarkElf** [ProtocolSupport/ProtocolSupport#1169]
* ProtocolSupport version (/ps buildinfo)
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.08.27 at 14:24:53 MSK, buildhost: build.true-games.org, buildnumber: 437, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:3a80c661fe665611a15d8cf39e91160e6775d2f2)
* Server version
1.14.4, b186 of paperspigot - the latest currently.

Regular stone slabs seem to have this issue.
(Using a 1.8 & 1.12 client) With escape menu: https://prnt.sc/p3492o
(Using a 1.8 & 1.12 client) Regularly: http://prntscr.com/p34bfg
(Using 1.14.4 client) Regluar/escape: http://prntscr.com/p34kyi

If I missed any requirements to submit an issue. please let me know.

**Comment by Shevchik** [comment]
Try with vanilla client first.

**Comment by MarkElf** [comment]
They don't disappear with a vanilla client. I probably should have tried that first before wasting your time, sorry.

The blocks do exist though they visually disappear.
