### ISSUE TITLE
Crash Item Frame

### ISSUE THREAD

**Issue by franxyk** [ProtocolSupport/ProtocolSupport#1173]
As many know from 1.13 the item frame can be rotated or placed horizontally, when it is placed that way and you enter with versions 1.7 on a server 1.14 the client crashes with this error:
Description: Rendering entity in world
Details:
Entity Type: ItemFrame (st)
Entity ID: 530089
Entity Name: entity.ItemFrame.name

**Comment by Shevchik** [comment]
Should probably remap that to default item frame rotation, so at least it doesn't crash.

**Comment by franxyk** [comment]
Will you correct that in future versions?

**Comment by Shevchik** [comment]
Fixed
