### ISSUE TITLE
Brown mooshroom issue

### ISSUE THREAD

**Issue by djytw** [ProtocolSupport/ProtocolSupport#1174]
Red mooshrooms won't turn brown when struck by lightning.
Futhermore, if spawn a brown one without PS, then install PS and restart server, the brown one will turn red.

ps buildinfo: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.08.27 at 14:24:53 MSK, buildhost: build.true-games.org, buildnumber: 437, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:3a80c661fe665611a15d8cf39e91160e6775d2f2)

paper 1.14.4 build#208 (2019-10-03)

no other plugins

**Comment by Shevchik** [comment]
Block mapping error i guess

**Comment by djytw** [comment]
yes, only display as a red one. NBT tag is still type:brown

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/0bf043fe915ff344ebc0fb4320552a039ba89c01
