### ISSUE TITLE
Stone slab in < 1.14 looks like cobblestone slab

### ISSUE THREAD

**Issue by kamil445** [ProtocolSupport/ProtocolSupport#1176]
This ![asd](https://gamepedia.cursecdn.com/minecraft_gamepedia/thumb/f/f5/Smooth_Stone_Slab.png/32px-Smooth_Stone_Slab.png?version=716bdb31cf960a2984682561f35664fa) on 1.13, 1.12 itd client and 1.14 server looks like ![asd](https://gamepedia.cursecdn.com/minecraft_gamepedia/thumb/3/31/Cobblestone_Slab.png/32px-Cobblestone_Slab.png?version=45c7f9a428ef8f315673046a361c13d1), should be ![asd](https://gamepedia.cursecdn.com/minecraft_gamepedia/thumb/f/f5/Smooth_Stone_Slab.png/32px-Smooth_Stone_Slab.png?version=716bdb31cf960a2984682561f35664fa)

When i place this ![asd](https://gamepedia.cursecdn.com/minecraft_gamepedia/thumb/f/f5/Smooth_Stone_Slab.png/32px-Smooth_Stone_Slab.png?version=716bdb31cf960a2984682561f35664fa) using 1.13 client on 1.14 server, then i switch to 1.14 client and i see this ![asd](https://gamepedia.cursecdn.com/minecraft_gamepedia/thumb/archive/0/0e/20190124204445%21Stone_Slab.png/120px-Stone_Slab.png?version=2e0dbbe8b2fb27b96be50b30d233dd05)(can't find smaller image sorry) should be ![asd](https://gamepedia.cursecdn.com/minecraft_gamepedia/thumb/f/f5/Smooth_Stone_Slab.png/32px-Smooth_Stone_Slab.png?version=716bdb31cf960a2984682561f35664fa)

**Comment by zeronerve** [comment]
I'm also having this same issue in 1.15.1
