### ISSUE TITLE
Jukebox broken

### ISSUE THREAD

**Issue by allbombson** [ProtocolSupport/ProtocolSupport#1177]
Tested with 1.6.1 on a 1.14.4 server. jukeboxes dont play music.

**Comment by allbombson** [comment]
I believe this is due to the fact that sounds got changed after 1.10 so anything under 1.10 is likely broken.

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/bebe90584beb86aaf8a546991d5c5dfc968ace4b
