### ISSUE TITLE
Issue with entity and name tag visibility

### ISSUE THREAD

**Issue by RoblokazPlays** [ProtocolSupport/ProtocolSupport#1178]
Hi, so I have a server with minigames and some game modes such as Factions, Survival, and Creative.
This is probably a plugin incompatibility as I recreated it on my test server with only the protocol support plugin.
My server version is PaperSpigot 1.14.4, and my ProtocolSupport build info is this:
![image](https://user-images.githubusercontent.com/56515875/67057563-a0bfa700-f116-11e9-80d2-79a52d3efbe7.png)
So the issue is that entities apart from players are completely invisible, and you cannot see nametags, which makes it hard for people with holograms.

And for Factions, Skyblock, BedWars, SkyWars, and a whole lot of other games, not being able to see mobes is a problem. Imagine being attacked by an invisible spider and not even be able to hit it! A sad ending to a player's life, shall it be?

Please fix this problem. I'll send a screenshot of all the plugins that I am using right now. Maybe you could figure out which one is causing the problem? Thanks.
![image](https://user-images.githubusercontent.com/56515875/67058127-1593e080-f119-11e9-96da-cd2c4b56f08a.png)
![image](https://user-images.githubusercontent.com/56515875/67058136-1f1d4880-f119-11e9-9e6b-d9f9696a4844.png)

**Comment by RoblokazPlays** [comment]
hello

**Comment by Shevchik** [comment]
If this is a plugin incompatibility then you can try removing half f the plugins until you find which one was incompatible.

**Comment by VanillaChan6571** [comment]
This is ProtocolSupport Issue with Entities API not displaying correctly and using ProtocolSupportLegacySupport would of worked but is not updated. You would have to downgrade your server or wait for the plugin to get updated. :/
