### ISSUE TITLE
EntityLLama some kind of bugs

### ISSUE THREAD

**Issue by Ste3et** [ProtocolSupport/ProtocolSupport#1179]
* ProtocolSupport: version #442 
* Server version: paperSpigot 1.14.1 build 221

Description:
It is unable to spawn Llama with custom color (Brown,Creamy,White,...)
It's not possible to give him a decor item, if you tame the llama and place the decor on his slot your client crashs and you got these minecraft crashlog: https://hastebin.com/usoyitasan.cs

Best regrads,
Ste3et_C0st

**Comment by Shevchik** [comment]
Fixed
