### ISSUE TITLE
Maximum length for LivingEntity Metadata in 1.8.9

### ISSUE THREAD

**Issue by zeronerve** [ProtocolSupport/ProtocolSupport#1180]
Is it possible to increase the maximum length of nametags to enable longer lines (for instance in Holographic Displays) for 1.8.9 clients? Lines are being cut off at 64 characters in 1.8.9 clients, but not in 1.13.2. This would greatly help with things like leaderboards that display a good bit of information.

https://github.com/ProtocolSupport/ProtocolSupport/blob/master/src/protocolsupport/protocol/typeremapper/entity/metadata/types/base/LivingEntityMetadataRemapper.java#L17

I'm using build 377 on Paper 1.13.2 (latest).

**Comment by Shevchik** [comment]
No idea, that needs testing.

**Comment by Shevchik** [comment]
Looks like >= 1.7 versions don't have a limit, so i removed it.

**Comment by zeronerve** [comment]
Thanks so much!!

**Comment by zeronerve** [comment]
It works perfectly.
