### ISSUE TITLE
Jumping on to iron bars in 1.8.9 on 1.14.4 server

### ISSUE THREAD

**Issue by zeronerve** [ProtocolSupport/ProtocolSupport#1182]
Hi. for players with 1.8.9 clients, it's not possible to jump onto an iron bar when the player is touching (or near) the edge of the iron bar. 

This is in a 1.8.9 client...
https://youtu.be/dmKo0fvrIFM

This is in 1.14.4 client...
https://youtu.be/5h6jZvXwEkk

I'm using your latest dev build 4.28 on Paper 1.14.4 (lastest build)

**Comment by Shevchik** [comment]
Probably bounding boxes are different between versions. Will probably check it later.

**Comment by zeronerve** [comment]
Thanks!

**Comment by zeronerve** [comment]
any look at this yet?

**Comment by zeronerve** [comment]
We have a couple of minigame maps that are compromised because of this. Could take a look? I appreciate your work!

**Comment by Shevchik** [comment]
Bounding box actually changed between 1.8.9 -> 1.9. Will investigate more when i have time.

**Comment by zeronerve** [comment]
Thank you. This is still a problem for our players, as we have a few maps with exposed iron bars in prominent paths.

**Comment by Shevchik** [comment]
This is finally fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/85895ee18217071c30a4343ae82627a19fc83e27

**Comment by zeronerve** [comment]
Thank you!
