### ISSUE TITLE
Scoreboard character cut off at 16 mark.

### ISSUE THREAD

**Issue by Niall7459** [ProtocolSupport/ProtocolSupport#1183]
One character is cutout when joining on lower versions than 1.13.2.

Video:
https://i.gyazo.com/0fb4292aed91000aec7c1ac45382bf19.mp4

Version:
![version](https://i.gyazo.com/thumb/1200/c2cc68a737a5b9796223f085f2e8fe00-png.jpg)

Server version:
![version](https://i.gyazo.com/88cc03593bc2c4ab9987a77dbc02d834.png)

**Comment by Artuto** [comment]
#1019

**Comment by Niall7459** [comment]
It looks like theres no planned fix. I'll see what I can do to support this, but don't really see why plugins themselves should have to deal with this.
Would you be accepting PR's for this?

**Comment by Shevchik** [comment]
Because moving the part of the prefix to suffix is not a thing that everyone want 100% (some people do use suffixes and prefixes separately), which means that such thing can't be in the core itself. You cal always PR such thing to ProtocolSupportLegacySupport tho.

**Comment by Artuto** [comment]
Perhaps, it could be turned on by using a system property? Not the most intuitive but it would work
