### ISSUE TITLE
Players getting kicked

### ISSUE THREAD

**Issue by x9nico** [ProtocolSupport/ProtocolSupport#1187]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo): Latest dev build for 1.14.4
* Server version 1.14.4 (Latest build)

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

Hello, I'm using ProtocolSupport on Latest PaperSpigot 1.14.4 build with latest 1.14.4 version of PS.
and my players are getting this error: Internal Exception: java.lang.IllegalArgumentException: You must pass a 'Packet' object!

**Comment by x9nico** [comment]
It does that when a Player < to 1.9 are doing a right click.

**Comment by Shevchik** [comment]
That's not a protocolsupport error.

**Comment by x9nico** [comment]
Ok, thanks you.

**Comment by Rayzr522** [comment]
The bug is coming from our plugin, OldCombatMechanics, from this line: https://github.com/kernitus/BukkitOldCombatMechanics/blob/master/src/main/java/kernitus/plugin/OldCombatMechanics/utilities/packet/Packet.java#L108

However, this error would only throw if a packet that is received does not inherit from the `Packet` NMS class. Does ProtocolSupport wrap packets in a higher class? Or does it inject custom packets of some kind? Any idea why it would do this?

**Comment by Shevchik** [comment]
We don't. But you can always just print the instance you received so you find what it actually is.
