### ISSUE TITLE
[question] Alternative for 1.7.10 servers

### ISSUE THREAD

**Issue by k1r0s** [ProtocolSupport/ProtocolSupport#1189]
So far, my friends and I we want to play thaumcraft 4 (1.7.10) on a server. Actually thermos works very well. and on top of that we run bukkit plugins and forge mods.

https://github.com/CyberdyneCC/Thermos 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.58 (MC: 1.7.10)

It uses spigot to some extend but im not sure how much.

some plugins are compatible whereas some not.

I've compiled https://github.com/Shevchik/SkinsRestorer/ for my server by using the following dependencies:

```
├── craftbukkit-1.7.10-R0.1.jar
├── ProtocolLib.jar https://github.com/dmulloy2/ProtocolLib/releases/tag/3.7.0
└── ProtocolSupport.jar (latest)
```
https://share.getcloudapp.com/xQu0494q

The issue comes at dropping ProtocolSupport.jar on plugins folder. It does not work indeed.

My quesion is if someone can help me in order to check what is missing from Thermos in order to make this work.

Thanks in advance

**Comment by Shevchik** [comment]
The protocolsupport plugin description states the server version it supports.

**Comment by k1r0s** [comment]
note: i've tested compiled skinsrestorer and works fine. users are able to see each other skins. Though own skin appears to be default one :\

but thats fine
