### ISSUE TITLE
connection not closed for legacy ping

### ISSUE THREAD

**Issue by Sneakometer** [ProtocolSupport/ProtocolSupport#1190]
As the title says, a connection that is used for a legacy server list ping (https://wiki.vg/Protocol#Legacy_Server_List_Ping) in both 1.6 and 1.4 to 1.5 / pre 1.4 style is not gracefully closed by the server after the data was sent. This results in the client not knowing when to stop reading data.

Example:
Using this little pre 1.4 ping java programm:
```
Socket socket = new Socket("127.0.0.1", 25565);
OutputStream out =socket.getOutputStream();
InputStream in = socket.getInputStream();
		
// legacy server list ping
out.write(0xFE);
		
int b;
while((b = in.read()) != -1) {
    System.out.println(b);
}
		
System.out.println("end");
socket.close();

```
For a server without ProtocolSupport installed, the end of the programm is reached fine:
```
255
0
54
0
71
...
0
48
0
48
end
```

But for a server that is using ProtocolSupport, the end is never reached:
```
255
0
54
0
71
...
0
167
0
49
0
48
```
The programm is stuck here until the server eventually timeouts the connection.

ProtocSupport build: 377 (2019.04.09)
Server: 1.13.2

**Comment by Shevchik** [comment]
The client does know when to finish reading the data tho (when packets were successfully decoded).

Also you are using unsupported build. I may look into tho, but then you will have to backport the fix.
