### ISSUE TITLE
Error message [1.14.4]

### ISSUE THREAD

**Issue by MarkElf** [ProtocolSupport/ProtocolSupport#1191]
* ProtocolSupport version (/ps buildinfo)
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.11.29 at 12:59:16 MSK, buildhost: build.true-games.org, buildnumber: 456, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:03cd0161f6277eb41ce8311741fb2564df88ce41)

* Server version
paperspigot b230 - 1.14.4

Error: https://pastebin.com/wsNGfsCs

**Comment by PhanaticD** [comment]
same issue: https://pastebin.com/raw/tRVc0Vuw

**Comment by Shevchik** [comment]
Both of those blockdata ids don't exist. Try without other plugins first.

**Comment by MarkElf** [comment]
I don't think I was running any conflicting plugins that would have unique block ids; I got the error above on an SMP server. Only one related plugin and I'm not entirely sure how I got the error, logs show one person joining and 3 leaving including myself while on 1.12.2 (Others were for sure on 1.14.4). Plugins:
AutoSaveWorld, ClearLag, Essentials, Lift, MarriageMaster, ProtocolSupport, ProtocolSupportLegacyChest, SimpleSit, TreeFellerPlus, WorldEdit, WorldGuard

**Comment by Shevchik** [comment]
Then it has to be something in the map maybe. Upload a section of map where it happens.

**Comment by MarkElf** [comment]
If it's a non-traditional block, then it might be a worldedited in end_portal block. To clarify, the portal that would send you to the end when walking into it, not the end portal frame. I use those for lighting. The only other thing that comes to mind is stonebrick walls which we started to use recently.

**Comment by Shevchik** [comment]
Since the map wasn't provided, i'm unable to debug this.
Reopen with attached map if that still happens on whatever will be latest by then.
