### ISSUE TITLE
ServerListPingEvent

### ISSUE THREAD

**Issue by FrukTik** [ProtocolSupport/ProtocolSupport#1192]
ServerListPingEvent не работает в 462 версии.
В меню серверов при включенном query показывает 0 игроков, но игроки есть на сервере. Также не мониторят игроков мониторинги серверов. При удалении  ProtocolSupport игроки снова видны и в меню, и в мониторингах, вы это исправите, или есть настройка?

**Comment by yannicklamprecht** [comment]
English translation:

> ServerListPingEvent does not work in 462 versions. The server menu shows 0 players when the query is enabled, but the players are on the server. Also does not monitor the players monitoring the servers. When you remove ProtocolSupport, the players are visible again both in the menu and in the monitoring, will you fix it, or is there a configuration?

**Comment by Shevchik** [comment]
Currently displayed online player count uses player sample size, which is actually limited to max sample sizes. Should pass actual player count separately to fix that.

**Comment by FrukTik** [comment]
What 0.0 Repeat again please and in Russian.

**Comment by yannicklamprecht** [comment]
> В настоящее время отображаемый онлайн-плеер использует размер выборки плеера, который на самом деле ограничен максимальными размерами выборки. Чтобы это исправить, необходимо отдельно пропустить фактический подсчет игроков.

**Comment by FrukTik** [comment]
> Currently displayed online player count uses player sample size, which is actually limited to max sample sizes. Should pass actual player count separately to fix that.

Can you fix it?

**Comment by Shevchik** [comment]
Should be fixed now
