### ISSUE TITLE
1.15 bee particle

### ISSUE THREAD

**Issue by Kuass** [ProtocolSupport/ProtocolSupport#1194]
* protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.12.18 at 19:09:35 MSK, buildhost: build.true-games.org, buildnumber: 463
* git-Paper-27 (MC: 1.15.1)

If particle `falling_honey` and `falling_nectar` occurs, a NullPointerException is thrown.

**Comment by Shevchik** [comment]
Fixed

**Comment by Kuass** [comment]
> 결정된

thank you !
