### ISSUE TITLE
I am unable to find a working version for 1.13.2.

### ISSUE THREAD

**Issue by OskarZyg** [ProtocolSupport/ProtocolSupport#1196]
I am unable to find a working version for 1.13.2. There is either a labelling or code issue as I get the error: `Unsupported API version 1.14`.
Thank You!

**Comment by Shevchik** [comment]
We don't support outdated versions. The spigot link did point to a correct version, so no idea what is wrong.

**Comment by OskarZyg** [comment]
Ok, run it on a server if it is correct.

**Comment by OskarZyg** [comment]
![image](https://user-images.githubusercontent.com/56176746/71475228-4195a700-27d7-11ea-8dd4-864490aba0d2.png)

**Comment by yannicklamprecht** [comment]
You aren't reading. https://build.true-games.org/job/ProtocolSupport/377/artifact/target/ProtocolSupport.jar

I checked this one. It has the api-version 1.13 in it. So it should work.
