### ISSUE TITLE
1.15 boat

### ISSUE THREAD

**Issue by Kuass** [ProtocolSupport/ProtocolSupport#1197]
* protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.12.18 at 19:09:35 MSK, buildhost: build.true-games.org, buildnumber: 465
* git-Paper-31 (MC: 1.15.1)

The boat is now a single seater.
Put the plugin, You cannot ride in the back seat of the boat.

**Comment by TNTUP** [comment]
I can confirm this aswell, is this fixed in the latest release of ProtocolSupport? The server is still on 1.15.1,  soon to update to 1.15.2 when all plugins (mainly dynmap, asyncworldedit, protocollib, libsdisguises...)

Reading issues related to this issue and I'm using BlockVersion to block all 1.7.x and 1.8.x, only allowing 1.9-1.15.2. The plugin ProtocolSupportStuff isn't updated for 1.13.x and 1.15.x so is there anything I can do?

**Comment by Shevchik** [comment]
BlockVersion uses old api version block methods, you need a plugin that actually supports disabling versions using new api.

**Comment by TNTUP** [comment]
Ahh :( There's no such known plugin that can do that actually :/ Thanks anyways ^^

**Comment by yumjunstar** [comment]
@TNTUP Hey Boat can't afford 2 player , 1 mob and 1 player , 2 mobs until now dev -481  How can I fix this bug Should I make a new tickets about this issue?

**Comment by TNTUP** [comment]
> @TNTUP Hey Boat can't afford 2 player , 1 mob and 1 player , 2 mobs until now dev -481 How can I fix this bug Should I make a new tickets about this issue?

Use ProtocolSupportStuff and block 1.8.x versions and restart the server

**Comment by yumjunstar** [comment]
> > @TNTUP Hey Boat can't afford 2 player , 1 mob and 1 player , 2 mobs until now dev -481 How can I fix this bug Should I make a new tickets about this issue?
> 
> Use ProtocolSupportStuff and block 1.8.x versions and restart the server

That plugin is outdated My server version is 1.15.2 paper -143

**Comment by TNTUP** [comment]
> > > @TNTUP Hey Boat can't afford 2 player , 1 mob and 1 player , 2 mobs until now dev -481 How can I fix this bug Should I make a new tickets about this issue?
> > 
> > 
> > Use ProtocolSupportStuff and block 1.8.x versions and restart the server
> 
> That plugin is outdated My server version is 1.15.2 paper -143 Even when I join with version 1.15.2, 2 people still can't ride a boat

The plugin works fine on my 1.15.2 server, no issues by disabling 1.8.x protocols. Give it a try :)
