### ISSUE TITLE
Scoreboards breaking

### ISSUE THREAD

**Issue by ChaseSantos** [ProtocolSupport/ProtocolSupport#1198]
Server version: 1.15.1
PS build number: 466

![image](https://user-images.githubusercontent.com/33441571/71636429-6df55d00-2bf5-11ea-90c0-aeb8cefae0f4.png)
![image](https://user-images.githubusercontent.com/33441571/71636431-82395a00-2bf5-11ea-8f7f-d64b697efa94.png)

**Comment by ChaseSantos** [comment]
*Second screenshot was taken on 1.12, the working one was taken on the native version 1.15.1

**Comment by yannicklamprecht** [comment]
If I remember right 1.12.x did have a limitation on scoreboard width.

**Comment by toxamin** [comment]
you must set the color of the team, to the last color of the prefix
