### ISSUE TITLE
Support for AutoIn?

### ISSUE THREAD

**Issue by Kurimatzu** [ProtocolSupport/ProtocolSupport#120]
Hello,

I'm using Autoin plugin on my server ( it is very good) but when I enter the 1.7.2 ~ 1.7.10 I get this error:

![capturar](https://cloud.githubusercontent.com/assets/9270074/12215834/d0d4a874-b6b3-11e5-95e9-1c966282af45.PNG)

It is possible to put up a stand for this plugin?

Thank you,
_Kurimatzu_

**Comment by Shevchik** [comment]
No. I'm not supporting not open source plugins anyway.

**Comment by sgdc3** [comment]
@Kurimatzu Check out FastLogin. It's a simpler and less hacky auto login system that should work fine with protocol support ;)
