### ISSUE TITLE
Picked items don't disappear on versions older 1.14

### ISSUE THREAD

**Issue by car1ot** [ProtocolSupport/ProtocolSupport#1200]
Picked items don't disappear on versions older 1.14

My plugins list: ProtocolSupport

I deleted all plugins, but problem didn't disappear.

**Comment by Shevchik** [comment]
Wasn't able to reproduce (dropped item on the floor and picked it up). Additional replication steps needed.

**Comment by car1ot** [comment]
Yes. Here is additional: Item only can't be picked up, when player die, holding this item in HAND.

**Comment by PixelPerfect** [comment]
Bumping this as have ran into this today

**Comment by KarlPro123** [comment]
Confirming (older than 1.14 clients)

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/74627d427d0cb4f88e2b33084eaf8f775ec2bd94
