### ISSUE TITLE
 Theft animation 1.15.1

### ISSUE THREAD

**Issue by FrukTik** [ProtocolSupport/ProtocolSupport#1201]
I will use the latest version of the plugin and kernel. Without the ProtocolSupport, pandas eat bamboo and lie on their backs, but there is no animation with the plugin. Can you fix it?
![2020-01-06_11 33 46](https://user-images.githubusercontent.com/20886295/71806373-af648d00-3079-11ea-9e83-4e97b79112c3.png)

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by FrukTik** [comment]
Cool
