### ISSUE TITLE
Unknown mob entity network type id 1,708

### ISSUE THREAD

**Issue by TNTUP** [ProtocolSupport/ProtocolSupport#1203]
PS BUILDINFO
[0 02:29:06 INFO]: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.01.04 at 13:35:33 MSK, buildhost: build.true-games.org, buildnumber: 467, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:a82f2b462774aee5e15680f7c1a4692e6a559517)

SERVER VERSION
[0 02:30:28 INFO]: This server is running Paper version git-Paper-33 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

On 1.14.4/1.15.1 server this rare bug can occur sometimes and its annoying as it forces me to reboot the server when no one are able to connect. I'm suspecting a plugin which creates a custom mob entity so the only ones I can think of is ProCosmetics and EchoPet. I've removed ProCosmetics but the issue persists so I've pinpointed to EchoPet. I've both submitted an issue on their issue tracker and I hope I can finally fix this issue. https://github.com/Arnuh/EchoPet/issues/64

Logs are on pastebin https://pastebin.com/eRmdWs4u

**Comment by Shevchik** [comment]
Yeah, entity type id 1864 is not a valid entity type id. So it should be a bug in echopet (or maybe some other plugin, that somehow interferes).

**Comment by TNTUP** [comment]
I've reported it to EchoPet devs aswell as it occurs on the 1.14.4 and 1.15.1 servers. Reported to the ProCosmestic dev aswell, but since it occured without the plugin I closed the issue report(deleted post on its spigotmc page)

**Comment by TNTUP** [comment]
Looks like its a bug with EchoPet, closing the issue for now. Should I open up another issue about sound issue? Creepers/TNT explosion doesn't fire up on clients below 1.15.1 (tested 1.14.4, 1.13.2, 1.12.2 etc)
