### ISSUE TITLE
TabCompleteEvent high server usage

### ISSUE THREAD

**Issue by PWWP** [ProtocolSupport/ProtocolSupport#1205]
Am reporting a performance issue with "ProtocolSupportStuff :: Event: n.p.p.l.a.PaperAsyncTabCompleteHandler"
It is probably not normal that TabCompleteEvent gives 20% server load?

Link to timings: https://timings.aikar.co/?id=8b99e0794ad24a08b70b4f9a33d00731

* ProtocolSupport version (/ps buildinfo)
![obraz](https://user-images.githubusercontent.com/6884361/72667722-47ba2480-3a1f-11ea-9a1a-d88049d4c772.png)

* Server version
![obraz](https://user-images.githubusercontent.com/6884361/72667730-56a0d700-3a1f-11ea-89bc-baaf25bca0a3.png)

**Comment by Shevchik** [comment]
Wrong repo
