### ISSUE TITLE
Tab Complete is broken for commands with double slash for <= 1.12.2 clients

### ISSUE THREAD

**Issue by Leymooo** [ProtocolSupport/ProtocolSupport#1206]
What is expected:
![image](https://user-images.githubusercontent.com/8667294/72742347-32c1ca80-3bb2-11ea-8fd0-35a49f83dd17.png ) (1.12.2 server + client 1.12.2)
What is really going on:
![image](https://user-images.githubusercontent.com/8667294/72742397-4c631200-3bb2-11ea-9843-94c716177f19.png)(1.15.1 server + ps + client 1.12.2)

short video: https://youtu.be/p3f0KFQO1a4

build info:  ` protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.01.04 at 13:35:33 MSK, buildhost: build.true-games.org, buildnumber: 467, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:a82f2b462774aee5e15680f7c1a4692e6a559517)`

server version:  `[18:18:18] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-037559e-661bebc (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[18:18:18] [Server thread/INFO]: Checking version, please wait...
[18:18:19] [Thread-14/INFO]: You are running the latest version`

plugins: ` Plugins (2): WorldEdit, ProtocolSupport`

**Comment by Shevchik** [comment]
Server can't tab complete tab commands starting with /, it returns the list of command like if / wasn't there.

**Comment by Leymooo** [comment]
Server can do this
```
CraftPlayer player = (CraftPlayer) event.getPlayer();
        EntityPlayer entityPlayer = player.getHandle();

        PacketPlayInTabComplete packetPlayInTabComplete = new PacketPlayInTabComplete();

        PacketDataSerializer packetDataSerializer = new PacketDataSerializer(Unpooled.buffer());
        packetDataSerializer.d(1);
        packetDataSerializer.a("//ex", 32500);
        try {
            packetPlayInTabComplete.a(packetDataSerializer);
        } catch (IOException e) {
            e.printStackTrace();
        }

        StringReader stringreader = new StringReader(packetPlayInTabComplete.c());

        if (stringreader.canRead() && stringreader.peek() == '/') {
            stringreader.skip();
        }


        ParseResults<CommandListenerWrapper> parseresults = MinecraftServer.getServer().getCommandDispatcher().a().parse(stringreader,
                entityPlayer.getCommandListener());


        MinecraftServer.getServer().getCommandDispatcher().a().getCompletionSuggestions(parseresults).thenAccept((suggestions) -> {
            System.out.println(suggestions.getRange());
            System.out.println(suggestions.getList());
        });
```
and output is 
```
[20:52:29] [Server thread/INFO]: StringRange{start=1, end=4}
[20:52:29] [Server thread/INFO]: [Suggestion{range=StringRange{start=1, end=4}, text='/expand', tooltip='null'}, Suggestion{range=StringRange{start=1, end=4}, text='/ext', tooltip='null'}, Suggestion{range=StringRange{start=1, end=4}, text='/extinguish', tooltip='null'}]
```
maybe something wrong in protocol translations?

**Comment by Shevchik** [comment]
You are passing the command with two / to the parser. But the initial / has to be stripped at protocol layer in order to make single / commands work.

**Comment by Leymooo** [comment]
Idk how good is this method, but looks like it works correctly

![image](https://user-images.githubusercontent.com/8667294/72838321-beae2200-3c98-11ea-9781-8dac03bf09e6.png)
![image](https://user-images.githubusercontent.com/8667294/72838236-97efeb80-3c98-11ea-8729-61f265cb79a6.png)

https://youtu.be/2zWRxWFBTQQ

**Comment by Shevchik** [comment]
That's still some sort of workaround specific to // commands, will still break on /// and so on.
More generic workaround needs to be found for that.

**Comment by Leymooo** [comment]
It also works for more than // slashes. https://youtu.be/oI6c5WR3OLg

but i think we should not add / if start index is > 4 to not break arguments
![image](https://user-images.githubusercontent.com/8667294/72839331-cec70100-3c9a-11ea-8a45-ea1826accc51.png)

**Comment by Shevchik** [comment]
That is still a shitty workaround. Probably the inbound command should actually be remembered instead, and then on response it matches should be transformed based on start and end index.

**Comment by Leymooo** [comment]
start index is always `1` for any number of slashes. so we can simple add `/` if `start == 1` and match starts with `/`

**Comment by Shevchik** [comment]
Will try after 1.15.2 update. Still won't work in case it's not the server which responds and something custom instead, but if it works with default spigot/paper then it's good enough.

**Comment by Shevchik** [comment]
Applied additional workarounds, not it works. But due to nature of those workarounds it may break any moment.
