### ISSUE TITLE
Wrong music discs

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [ProtocolSupport/ProtocolSupport#1207]
im using the lastest version of paper and ps, and my server is on 1.15.1

In client version 1.15.1, when i put the record disc called "mall" into the jukebox, it played correctly
![1 15 1](https://user-images.githubusercontent.com/45261195/72785071-47ab6600-3c65-11ea-81cb-edff0bd95855.jpg)

In client verison 1.14.4, when i put the disc called "mall", it played "mellohi"
![1 14 4](https://user-images.githubusercontent.com/45261195/72785082-4ed27400-3c65-11ea-9c22-bb031869b016.jpg)

Hope u can fix it :)

**Comment by Shevchik** [comment]
Closing this until test without creative mode will be done.

**Comment by Aira-Sakuranomiya** [comment]
> Closing this until test not in creative mode will be done.

I have tested in both creative move and survival mod, and I also tested in another server which is running ProtocolSupport, they both have the issue
I’m using newest 1.15.2 paper and newest ProtocolSupport.
(´；ω；｀)

**Comment by Shevchik** [comment]
The exact question there, is the item you actually hold is a correct disc.

**Comment by Aira-Sakuranomiya** [comment]
It is a correct disc, because the disc in 1.15.2 and 1.14.4 is the same.
(I give myself a disc in 1.15.2, then I throw it to a player that is using 1.14.4, it is same)
It just played not correctly in the version lower than 1.15 using jukebox
"/playsound" command played correctly

(Sorry for my bad English)

**Comment by Shevchik** [comment]
All discs are offset by 1. That's because in 1.15.1 discs sound ids start with 1, while in lower versions they start with 0.

**Comment by Shevchik** [comment]
Fixed  by https://github.com/ProtocolSupport/ProtocolSupport/commit/bebe90584beb86aaf8a546991d5c5dfc968ace4b
