### ISSUE TITLE
MCPE branch bug

### ISSUE THREAD

**Issue by tuberiumf** [ProtocolSupport/ProtocolSupport#121]
I installed experimental version of Protocol Support with MCPE support, and .. NoCheatPlus says,that MCPE players use SurvivalFly or CreativeFly. Maybe you can fix this?

**Comment by MrPowerGamerBR** [comment]
Issue with NCP, not with ProtocolSupport, edit your NCP config to not warn when someone is using SurvivalFly or CreativeFly.

**Comment by Mabus13** [comment]
Where get experimental version of Protocol Support with MCPE support???

**Comment by swan201** [comment]
@Mabus13 usb MCPE Brunch

**Comment by Mabus13** [comment]
@swan201 please more explain for noob.

**Comment by swan201** [comment]
@Mabus13 https://github.com/ProtocolSupport/ProtocolSupport/tree/mcpe

**Comment by Mabus13** [comment]
@swan201 BIG THANK YOU

**Comment by nathampa0909** [comment]
@Shevchik Close this too, its a problem wuth nco+. Thanks!

**Comment by Shevchik** [comment]
The thing is, my nc+ doesn't say anything about surbibalfly or anything.

**Comment by nathampa0909** [comment]
In january if i dont have a mistake, nc+ was having a error with survival fly in all servers (all versions), the nc+ devs fixed this.
