### ISSUE TITLE
Mindfulnes Process CPU Brain

### ISSUE THREAD

**Issue by Escanor2019** [ProtocolSupport/ProtocolSupport#1213]
How much information do you process in your mind each day?

How do you prioritize information and decide what's important?

What motivates you? money? imortality?

Do you process the same amount of information every day?

How do you set deadlines for your projects?

Do you try to follow the Russian stereotype of the best programmer?

Do you look at biographies of billionaires, such as the Bill Gate 2019 documentary, walt disney and mc donald?

Do you believe in formal study and schools? how do you know that you didn't learn alone looking for ways to execute? What is study for you?

Why don't you create your own minecraft server?

How old are you?

Do you have knowledge of facial recognition and genetic sequencing?

**Comment by Shevchik** [comment]
This is wrong place for asking questions unrelated to the software itself. Use discord instead.
