### ISSUE TITLE
1.4.7 and 1.5.1 showing client out of date

### ISSUE THREAD

**Issue by PizzaGuy900** [ProtocolSupport/ProtocolSupport#1214]
I have noticed that all of the versions above 1.5.1 all don't show out of date but 1.5.1 and 1.4.7 show out of date. How is it possible that all of the ones above 1.5.1 work but 1.5.1 and 1.4.7 don't. I am willing to spend some time editing the plugin if I knew how 1.5.2+ don't show out of date.

**Comment by PizzaGuy900** [comment]
I have the source code downloaded and I have been looking around in it.

**Comment by Shevchik** [comment]
```
[1.4.7 and earlier] Server shows up as "incompatible" in the server list, impossible to fix due to the lack of an way to verify the client version during server list ping
```
I guess that should be changed to 1.5.1 and earlier, but the point still stands.

**Comment by PizzaGuy900** [comment]
I still would like to know how it doesn't do that on the other versions

**Comment by allbombson** [comment]
Its due to the fact u cant get client version when it pings the server, but you can when it joins. Possible fix: Some kind of 2nd port that serves version data for older versions and then just directs to main server port.

**Comment by PizzaGuy900** [comment]
But the server list shows as compatible on 1.5.2+. I would like to know where that code is located so I can use that for help

**Comment by allbombson** [comment]
It shows up as compatible as on 1.5.2+ it actually sends the client version to the server during ping, the only way you can fix this issue properly is by recoding ur client.

**Comment by PizzaGuy900** [comment]
So 1.4.7 and 1.5.1 don't send the client version then?

**Comment by allbombson** [comment]
Yes, i just fucking said that.

**Comment by PizzaGuy900** [comment]
Ok
