### ISSUE TITLE
impossible to catch another player with a fishing rod.

### ISSUE THREAD

**Issue by splintermik** [ProtocolSupport/ProtocolSupport#1215]
Hello, I would like to report a small bug, it is impossible for the player to catch another player with a fishing rod, the players are well in 1.15.2, and the server too.

the debug doesn't show anything special in the chat, I join you the server log in pastbin

Thanks a lot :)

log : 
https://pastebin.com/nLNhpwJK

protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.01.27 at 15:38:23 MSK, buildhost: build.true-games.org, buildnumber: 477, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:ebe85569a2e4e645e6b0121c23e53e6a5f752134)

This server is running Paper version git-Paper-105 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-90 (MC: 1.15.2)
You are running the latest version

**Comment by Shevchik** [comment]
FishingFloatEntityMetadataRemapper which is responsible for metadata remap for hooked entity display is not used in the code, that's probably why it doesn't work.

**Comment by Shevchik** [comment]
That is probably fixed now
