### ISSUE TITLE
Moving item from newer version in creative inventory causes it to be the client item

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [ProtocolSupport/ProtocolSupport#1216]
When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo) build 477
* Server version 1.15.2

When you /give yourself an item from an newer version and then move it around in your inventory while in creative mode, it becomes the item from client side.

(Also happens after removing all ProtocolSupport addons)

Video showing this: http://api.erdbeerbaer.tk/J2i5j7H8su.mp4

**Comment by krusic22** [comment]
> Items in creative mode may not work as expected, or may not work at all

**Comment by ihaveamac** [comment]
I think this is because picking up an item in the creative inventory tells the server to delete it (notice when closing the inventory here, the item doesn't drop). Placing it creates the item, and the client can only create items that it knows about.

**Comment by Shevchik** [comment]
^

Actually something can be done about this (for example storing the original type in nbt upon sending), but i don't have time for that right now.
