### ISSUE TITLE
Players get stuck on stairs and semi-blocks. Is it possible to fix it?

### ISSUE THREAD

**Issue by FrukTik** [ProtocolSupport/ProtocolSupport#1217]
Players get stuck on stairs and semi-blocks. Is it possible to fix it?
I use the latest version plugin on Paper 1.15.2

**Comment by Shevchik** [comment]
Unable to reproduce.

Attach a video showing the problem (no other plugins should be present on the server).

**Comment by FrukTik** [comment]
https://youtu.be/G1aKgq-Ahg4

**Comment by Shevchik** [comment]
Client version?

**Comment by FrukTik** [comment]
1.12.2

**Comment by Shevchik** [comment]
Make a screenshot of that place from 1.15.2

**Comment by FrukTik** [comment]
On 1.8.8 the same problem

**Comment by FrukTik** [comment]
![2020-02-22_02 42 16](https://user-images.githubusercontent.com/20886295/75080436-097fbb80-551d-11ea-8f48-60e8d2d219b5.png)
![Uploading 2020-02-22_02.42.22.png…]()

**Comment by Shevchik** [comment]
Well, as you can see the stairs are positioned differently on the >= 1.13.
< 1.13 client actually connects blocks, it automatically makes a corner stair, so it's impossible to remap those stairs.
