### ISSUE TITLE
Error on ping server on 1.4.7

### ISSUE THREAD

**Issue by nathampa0909** [ProtocolSupport/ProtocolSupport#122]
I get error on ping on 1.4.7. I dont know but I'm using a code for change motd:

```java
@EventHandler
public void onPing(ServerPingResponseEvent e) {
	if (ProtocolSupportAPI.getProtocolVersion(e.getAddress()).equals(ProtocolVersion.MINECRAFT_1_4_7)){
		e.setMotd("§b§lJairoCraft §c§lSuportamos versões a partir da 1.5.2!");
	}
}
```
![Ibagei](http://i.imgur.com/kRcfgt7.jpg)

The ping don't set motd and I only can join to the server directly

**Comment by Shevchik** [comment]
Not possible to detect protocol version from <= 1.5.2 ping. So it is always assumed as 1.5.2
