### ISSUE TITLE
can i edit sendMessage method from CommandSender using Reflection for call one Event Message Listener?

### ISSUE THREAD

**Issue by marinaluisa2020** [ProtocolSupport/ProtocolSupport#1222]
look
![image](https://user-images.githubusercontent.com/61571165/76171786-eb959600-616d-11ea-82a3-f3d826cd67c5.png)
I want make one plugin Translator like Hypixel but the dont exists Plugin Chat Send Message Event only
1.AsynPlayerChatEvent
2.PlayerChatEvent
3.BroadcastMessageEvent
4.PlayerCommandPreprocessEvent

will it be that if I do an event in this native class will it defect in protocolsupport or viaversion?

**Comment by Shevchik** [comment]
No. Actually no plugin will break if you keep the ABI (an you probably won't change the ABI by just inserting the event). Moreover both ProtocolSupport and ViaVersion actually transform  already encoded data, so they generally don't care about native packet structure.
