### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by pczmr8v5n454iycf** [ProtocolSupport/ProtocolSupport#1223]
This plugin is licensed under AGPL.
On some java implementations(for example: HotSpot), this plugin is dynamically linked to minecraft.On some other java implementations(for example: OpenJDK9 or IBM OpenJ9 with AOT), this plugin is statically linked to minecraft. So minecraft is affected by AGPL, and I have to publish minecraft source code to use this plugin?

**Comment by toxamin** [comment]
nobody cares about minecraft plugin licenses

**Comment by Shevchik** [comment]
The code isn't statically linked in source form on openj9 or in any other jvm.

**Comment by pczmr8v5n454iycf** [comment]
@Shevchik But some java implementations may do some inline and AGPL also affect dynamical linking.

**Comment by Shevchik** [comment]
Don't build fat AOT image then (doesn't make any sense anyway, doesn't give you anything). Current real world law application shows that dynamic linking doesn't affect license. Anyway, you should consult the real lawyer about this issue anyway.
