### ISSUE TITLE
Update Inventory Title Problem

### ISSUE THREAD

**Issue by Tobiti** [ProtocolSupport/ProtocolSupport#1224]
* ProtocolSupport version: 4.28
* Server version: Paper 1.13.2

Im the maintainer of mfhoppers. When I use reflection to update the hopper inventory title I get "Unknown Translation Key".

This is the source code
`final Object entityPlayer = player.getClass().getMethod("getHandle").invoke(player);

			final Object activeContainer = entityPlayer.getClass().getField("activeContainer").get(entityPlayer);
			final Constructor<?> chatMessageConst = getNMSClass("ChatMessage").getConstructor(String.class, Object[].class);

			final Object windowId = activeContainer.getClass().getField("windowId").get(activeContainer);
			final Object chatMessage = chatMessageConst.newInstance(ChatColor.translateAlternateColorCodes('&', title), new Object[0]);

			final Object packet;

			if (MinecraftVersion.newerThan(MinecraftVersion.V.v1_13)) {
				final Class<?> containersClass = getNMSClass("Containers");
				final Constructor<?> packetConst = getNMSClass("PacketPlayOutOpenWindow").getConstructor(/*windowID*/int.class, /*containers*/containersClass, /*msg*/getNMSClass("IChatBaseComponent"));

				final int inventorySize = player.getOpenInventory().getTopInventory().getSize() / 9;

				if (inventorySize < 1 || inventorySize > 6) {
					//System.out.println("Cannot update title for " + player.getName() + " as their inventory has non typical size: " + inventorySize + " rows");
					return;
				}

				final Object container = containersClass.getField("GENERIC_9X" + inventorySize).get(null);

				packet = packetConst.newInstance(windowId, container, chatMessage);

			} else {
				final Constructor<?> packetConst = getNMSClass("PacketPlayOutOpenWindow").getConstructor(int.class, String.class, getNMSClass("IChatBaseComponent"), int.class);

				packet = packetConst.newInstance(windowId, inventoryType, chatMessage, player.getOpenInventory().getTopInventory().getSize());
			}`

**Comment by Shevchik** [comment]
1. You are using a translatable component where you aren't supposed to do that.
2. You are using outdated version.

**Comment by Tobiti** [comment]
@Shevchik Can you tell me what I can use instead of a ChatMessage?
