### ISSUE TITLE
Warn when players logout

### ISSUE THREAD

**Issue by PapiCapi** [ProtocolSupport/ProtocolSupport#1228]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo)
PS build 482
* Server version
Paper 162 (1.15.2)

Hello, since i updated Paper on my servers i had to update PS too because it was shutting down the server. Since those updates, i got this WARN when some players disconnect : https://prnt.sc/rtfa1b
I only see PS to do this because it's the only plugin i changed between the updates.
I have no other plugin who is listening to player logout.

**Comment by Shevchik** [comment]
As always, try without other plugins first.
