### ISSUE TITLE
Horses cannot move

### ISSUE THREAD

**Issue by Saintzzzz** [ProtocolSupport/ProtocolSupport#1231]
Before submitting your issue, please check the following:
sry about ignoring the template, i apolgise
* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
there is no error in console
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo)
1.12.2
* Server version
Paper.1.12.2
When i summon a mount horses are stuck, they cannot move, i can confirm this issue is ProtocolSupport because i have deleted plugins 1 by 1 to see what the issue was, and ProtocolSupport was the last one i deleted and horses moved, i did the other way around too see if it was another plugin and so i deleted ProtocolSupport first and the issue was gone when i deleted it, so basiclly the horses cannot move, please fix it, and im really sorry about not following your template, it was my first time using github and i am new to this,
If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

**Comment by Shevchik** [comment]
WE don't support non latest protocolsupport build.

**Comment by Saintzzzz** [comment]
so it will never get fixed?

**Comment by Saintzzzz** [comment]
i though you meant the latest version of each 1,12,x
