### ISSUE TITLE
ProtocolSupport breaks boats on 1.15.2

### ISSUE THREAD

**Issue by Sneakometer** [ProtocolSupport/ProtocolSupport#1234]
On my 1.15.2 survival server, boats only allow 1 passenger.
Noticed this when trying to sit in a boat with a villager.
I'm using th latest ProtocolSupport build #482 from Jenkins, latest Paper build and unmodded Minecraft 1.15.2.

I tried switching to spigot but it did not help.

Any ideas?

**Comment by Shevchik** [comment]
WAI.
Disable all versions before 1.9 to reenable multiple passenger entities.

**Comment by Sneakometer** [comment]
How can i disable that? Can't find any configuration files.

**Comment by Shevchik** [comment]
Using any plugin that supports doing so using ProtocolSupportAPI.

For example ProtocolSupportStuff.
