### ISSUE TITLE
Block updates refuse to appear on 1.13.2 and older

### ISSUE THREAD

**Issue by forkiesassds** [ProtocolSupport/ProtocolSupport#1235]
On 1.13.2 clients and older block updates refuse to appear, I am not sure if it's caused by my plugins or by the fact I am using an outdated copy of Paper

**Comment by enescaglayan** [comment]
You should've at least give your client and server log to us.

**Comment by forkiesassds** [comment]
On the server and client console it does not output any erorrs, I am using 
ProtocolSupport commit 513e8f0 not sure what Paper version but I know it's out of date, sometimes it actually works but sometimes it does not, I know that AuthMe is a problematic plugin
