### ISSUE TITLE
Scoreboards messed up for lower versions.

### ISSUE THREAD

**Issue by ItsVinnyX** [ProtocolSupport/ProtocolSupport#1237]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo): https://gyazo.com/bd3923e43343c836c4a4b631b633834c
* Server version: 1.15.2

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

https://gyazo.com/97b51cb3872c6c28cea9b074586138f0

The scoreboard for users in 1.12 is messed up. I am assuming this is for all versions up to 1.15.2.

**Comment by Shevchik** [comment]
See already closed issues about the scoreboard changes in 1.13
