### ISSUE TITLE
protocolsupport.api.chat.ChatAPI$JsonParseException: Unable to parse json string You're on Red Team

### ISSUE THREAD

**Issue by ItsVinnyX** [ProtocolSupport/ProtocolSupport#1238]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo): https://gyazo.com/ae305d0a6ea47859286dca683adec847
* Server 1.15.2

https://hastebin.com/naguqegego.sql
The player got kicked while invisible, not sure if it has happened to other players as a different kit the player was on client 1.12.2

It can be reproduced but it happens once in a while. For example, within an hour we had it happen 3 times.

**Comment by Shevchik** [comment]
I may guess that item name or lore wasn't in the json format.

**Comment by ItsVinnyX** [comment]
`kitmeta.setDisplayName("§9§lMain menu §7(Right click)");`

**Comment by Blamo27** [comment]
I got this error too...

**Comment by Shevchik** [comment]
Added a workaround for that.

Something sends invalid json components, but since it's kinda safe to use them as raw text, i did that.
