### ISSUE TITLE
MCPE Support died?

### ISSUE THREAD

**Issue by NycuRO** [ProtocolSupport/ProtocolSupport#1239]
MCPE Support died or it's still in rewrite ?

**Comment by NycuRO** [comment]
@Shevchik It's hard to say something right?

**Comment by astei** [comment]
The answer for this question has been known ever since the old PE branch got yanked. The support is not dead, just under private development until it's ready for a full release.

**Comment by NycuRO** [comment]
@astei Are you working on that too?
