### ISSUE TITLE
Remove usless texture value when disconnecting

### ISSUE THREAD

**Issue by TheSilentPro** [ProtocolSupport/ProtocolSupport#1241]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo)
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.03.16 at 04:11:14 MSK, buildhost: build.true-games.org, buildnumber: 481, buildgit: **https://github.com/ProtocolSupport/ProtocolSupport:origin/master:7faca44da1740b9c455fc776f8043b2ccdb892b3)**

* Server version
**This server is running Paper version git-Paper-226 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

Texture value floods console
![image](https://user-images.githubusercontent.com/46107752/80834449-06760b00-8bf1-11ea-8707-edb5b7e22974.png)

**Comment by Shevchik** [comment]
Done
