### ISSUE TITLE
Unknown dimension network id 14 (or 13 or other)

### ISSUE THREAD

**Issue by CyanurePV** [ProtocolSupport/ProtocolSupport#1242]
Hi , i got a problem with your plugin, i'va addit on my server and now i get this problem.
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
>.... [15:23:19 INFO]: CyanurePV lost connection: Internal Exception: protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: ProtocolSupport(buildinfo: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.05.03 at 21:27:43 MSK, buildhost: build.true-games.org, buildnumber: 484, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:7e72880c9f8673654283456923b3a0d70e516bab)): Network exception occured(connection: protocolsupport.protocol.ConnectionImpl(profile: protocolsupport.zplatform.impl.spigot.SpigotWrappedGameProfile(name: CyanurePV, originalName: CyanurePV, uuid: 0cb5684a-ca5f-3e2a-9ea9-a0bb05f9b97b, originalUUID: 0cb5684a-ca5f-3e2a-9ea9-a0bb05f9b97b, onlinemode: false), player: CraftPlayer{name=CyanurePV}, address: MYIP, rawaddress: MYIP, version: MINECRAFT_1_15_2, metadata: {}))

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo)
>....=>.... [15:24:24 INFO]: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.05.03 at 21:27:43 MSK, buildhost: build.true-games.org, buildnumber: 484, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:7e72880c9f8673654283456923b3a0d70e516bab)
* Server version
Paper 1.15.2

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

**Comment by Shevchik** [comment]
One if your plugin is sending garbage data. Most likely skins plugins, SkinsRestorer, or any plugins that share same broken codebase.

**Comment by CyanurePV** [comment]
In facts, it was the fault of Skinrestorer. thx
