### ISSUE TITLE
Incompatibily with Citizens

### ISSUE THREAD

**Issue by Momonche** [ProtocolSupport/ProtocolSupport#1243]
Hello !

A recent update of Citizens make all of Citizens NPC invisible when ProtocolSupport is on the server
That issue start from this commit of Citizens https://github.com/CitizensDev/Citizens2/commit/0b922011bd951c6543373278297f3aeaaa4dbae1
I ask Citizens's devs and they said "It's ProtocolSupport jobs" https://github.com/CitizensDev/Citizens2/issues/2151

So can you take a look at this ?

* ProtocolSupport version : protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.05.11 at 23:13:16 MSK, buildhost: build.true-games.org, buildnumber: 486, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:f34959c3312a2e80b406e0e2155161da98afd55b)
* Server version : git-Paper-284 (MC: 1.15.2)

There is no errors in console, just all NPC invisible for players

**Comment by Shevchik** [comment]
ProtocolSupport injects it's own entity tracker, and citizens does it too. There is no real way of miaking them compatible.

Removal of entity tracker injection and replacing it with entity position cache is planned, but no idea when i will have the time to implement this.
