### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by voodootje0** [ProtocolSupport/ProtocolSupport#1244]
* ProtocolSupport version (/ps buildinfo)
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.05.17 at 20:16:35 MSK, buildhost: build.true-games.org, buildnumber: 487, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:c6c00cabfb2c012ff0cc4baa1b6ba790381bf52c)

* Server version 
Tuinity version git-Tuinity-"5cf4104" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

As you can see from https://spark.lucko.me/#4vTAKBJEON, my server is having 9gb in this heap dump. The server runs on max 10gb. I see almost a million instances of protocol support classes, which is not good.

**Comment by Shevchik** [comment]
You have 1k entity player references, which in turn hold ps objects alive. Nothing to do with protocolsupport.
