### ISSUE TITLE
Unable to join server on latest builds

### ISSUE THREAD

**Issue by danjb2000** [ProtocolSupport/ProtocolSupport#1246]
Unable to join on any version. @Shevchik 
Fresh server, latest PaperSpigot (Tried Spigot) build as of this morning and latest ProtocolSupport build.

Receive the following error:
https://hastebin.com/unopaheteb.md

PS: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.06.03 at 21:25:00 MSK, buildhost: build.true-games.org, buildnumber: 492, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:5a0a53480ec278326e045990d9129810dc124b03)

Spigot:  git-Spigot-2f5d615-8637ec0 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Shevchik** [comment]
Incomptibility with lilypad

**Comment by danjb2000** [comment]
Hi @Shevchik,

Just so I'm completely clear - are you saying that this would need to be fixed on the LilyPad side?

For information, I don't have the issue when removing ProtocolSupport.

I'm a bit lost here on how I can get this resolved (since these two plugins are the fundementals of my network if I want a 1.15 server).

**Comment by Shevchik** [comment]
The lilypad bridge needs to be adapted to use protocolsupport api for login handling.
