### ISSUE TITLE
Most 1.8 sounds broken after build #487

### ISSUE THREAD

**Issue by MatrixTunnel** [ProtocolSupport/ProtocolSupport#1247]
Sounds like damage, hitting, noteblocks, etc. are not working. Tested on latest and still the same

**PS Build Info for broken sounds:** 
> protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.05.17 at 20:16:35 MSK, buildhost: build.true-games.org, buildnumber: 487, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:c6c00cabfb2c012ff0cc4baa1b6ba790381bf52c)

**Comment by Shevchik** [comment]
Fixed in https://github.com/ProtocolSupport/ProtocolSupport/commit/5f712a969a3b6b795da3c8410076082d5f18f6fd
