### ISSUE TITLE
DecoderException 

### ISSUE THREAD

**Issue by VSpier** [ProtocolSupport/ProtocolSupport#1249]
I don't understand why this error occurs when using the plugin - [Pastebin](https://pastebin.com/2asq6jmF)

As I understand it, this is happening when I get closer to entity.

The wrong packets? On whose side? Is there a way to find out exactly what this error is related to?

**Comment by VSpier** [comment]
> Enable the debug

https://pastebin.com/bNvmMqAp - since the debug was enabled.

**Comment by Shevchik** [comment]
Try without other plugins. Somehow the packet data is wrong:
3 - packet id (varint)
-109, 1 - entity id (varint)
97, -122, 42, 49, 64, 120, 74, -103, -107, 53, -11, -22, 115, 34, -110, -75 - uuid (16 bytes)
62 - entity type (varint)
64, 115, -70, -81, -100, 72, 53, -76 - x (double)
64, 83, 64, 0, 0, 0, 0, 0 - y (double)
64, 124, 53, -101, 82, 19, -20, 120 - z (double)
-98 - yaw (byte)
0 - pitch (byte)
-98 - headPitch (byte)
0, -128 - motion x (short)
-3,-115 - motion y (short)
-1, 49 - motion z (short)
-1 - ????

**Comment by VSpier** [comment]
> Try without other plugins. Somehow the packet data send by server is wrong:
> 3 - packet id (varint)
> -109, 1 - entity id (varint)
> 97, -122, 42, 49, 64, 120, 74, -103, -107, 53, -11, -22, 115, 34, -110, -75 - uuid (16 bytes)
> 62 - entity type (varint)
> 64, 115, -70, -81, -100, 72, 53, -76 - x (double)
> 64, 83, 64, 0, 0, 0, 0, 0 - y (double)
> 64, 124, 53, -101, 82, 19, -20, 120 - z (double)
> -98 - yaw (byte)
> 0 - pitch (byte)
> -98 - headPitch (byte)
> 0, -128 - motion x (short)
> -3,-115 - motion y (short)
> -1, 49 - motion z (short)
> -1 - ????

I found an error. I have this code in my plugin - https://pastebin.com/ffM4X4gX. 
Here I need to get the DataWatcher from the PacketPlayOutSpawnEntityLiving. But the new version doesn't have it there. I tried to put it in myself, but it didn't work (ProtocolSupport swears). Is there another way to get this parameter? ;(

**Comment by Shevchik** [comment]
Entity metadata is no longer sent in the spawn living packet.
