### ISSUE TITLE
Error when use TitleApi

### ISSUE THREAD

**Issue by nathampa0909** [ProtocolSupport/ProtocolSupport#125]
Hello, I get a error when use TitleApi: http://pastebin.com/Ndm6piSs

Code:

TitleAPI.sendSimpleTitle(p, "§6§lBem vindo(a) ao §b§lJairoCraft", "§7§lSite: http://www.jairocraft.com.br/", 4, 5, 4);

**Comment by Shevchik** [comment]
The string variant one uses json, not simple strings, use TextComponent to send them.

**Comment by nathampa0909** [comment]
The method sendSimpleTitle(Player, BaseComponent, BaseComponent, int, int, int) in the type TitleAPI is not applicable for the arguments (Player, TextComponent, TextComponent, int, int, int)

**Comment by Shevchik** [comment]
You are using wrong text component, you should use protocolsupport one
