### ISSUE TITLE
Boats can't have two players/entity's

### ISSUE THREAD

**Issue by TheCompieter** [ProtocolSupport/ProtocolSupport#1251]
Before submitting your issue, please check the following:

*To reproduce the issue:*
Try placing an boat with an entity/player and try entering it or another entity.

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`) YES
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate YES
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport YES
* If possible, you should reproduce your problem with debug enabled (`/ps debug`) YES
* Check if the issue isn't listed as a won't fix on the project page. YES
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now! YES

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport 497
* Paper 1.15.2 Build 366

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

**Comment by Shevchik** [comment]
Disable versions below 1.9 to reenable.

**Comment by TheCompieter** [comment]
@Shevchik  you mean with protocolsupportstuff?

**Comment by Shevchik** [comment]
With any plugin that uses ProtocolSupportAPI. ProtocolSupportStuff should work.
