### ISSUE TITLE
DroppedItem custom names are not updated

### ISSUE THREAD

**Issue by OmerBenGera** [ProtocolSupport/ProtocolSupport#1252]
ProtocolSupport Version:
`protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.06.21 at 21:22:18 MSK, buildhost: build.true-games.org, buildnumber: 497, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:b8516a242a67644b0a73a71bbb6e8512e71012c4)`

Server Version:
`Paper version git-Paper-370 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

When changing DroppedItem's name (the actual entity that was dropped) using setCustomName, it doesn't update clients that join with 1.8 to the server. It works fine for 1.15 clients, and it works fine when having a 1.8.8 server with a 1.8 client.

**Comment by Shevchik** [comment]
Provide the actual code example that allows easily reproducing this.

**Comment by Shevchik** [comment]
Found the probably cause, for whatever reason custom name is transformed only for living entities.

**Comment by OmerBenGera** [comment]
> Found the probably cause, for whatever reason custom name is transformed only for living entities.

If you still need a code snippet, then it's just using setCustomName on a dropped item entity

**Comment by Shevchik** [comment]
Should probably be fixed by
https://github.com/ProtocolSupport/ProtocolSupport/commit/4fdd6833226aa8f4ea818da2eeec45ecd6eca659
