### ISSUE TITLE
1.16?

### ISSUE THREAD

**Issue by OrangeKale64** [ProtocolSupport/ProtocolSupport#1253]
Please add support for spigot 1.16.1. The plugin broke when I updated to 1.16.1 so it gives a packet error from any other version. Thanks!

**Comment by Dec1lent** [comment]
They are working on it, it would be kinda stupid to not , is use it for my modded server which has adventuremaps from 2013, tekkit classic, tekkit lite, and now im just waiting for 1.16 so i can use it when hexacord support 1.16 and if you want to have a bungee server then i would recommend not to use portals but something like serverselectorx and use the old blocks so the 1.4.7 and up also can see them (:

**Comment by MaximilianGaedig** [comment]
> They are working on it, it would be kinda stupid to not , is use it for my modded server which has adventuremaps from 2013, tekkit classic, tekkit lite, and now im just waiting for 1.16 so i can use it when hexacord support 1.16 and if you want to have a bungee server then i would recommend not to use portals but something like serverselectorx and use the old blocks so the 1.4.7 and up also can see them (:  

Ummmm.... What... That's just a bunch of gibberish

**Comment by OrangeKale64** [comment]
k thanks
