### ISSUE TITLE
[BUG] Bug and Error

### ISSUE THREAD

**Issue by Deathroner** [ProtocolSupport/ProtocolSupport#1257]
Error and bug when breaking a block in the "ItemsAdder" plugin.

I didn't think I would take this kind of trouble.
I leave a video for you to see what happens, I would appreciate if you can help me with this.

**Video:** https://youtu.be/PWbrou6Aqck
**Error:** https://pastebin.com/jcpNSGmX

**ProtocolSupport version:** 504
**Server version:** 1.16.1

I understand that it is a free plugin, so I am waiting for any change, I would appreciate it if it can be solved.

**Comment by Shevchik** [comment]
That's not the full error.

**Comment by Deathroner** [comment]
This is the complete error, I removed it from the log

https://pastebin.com/CAbL80uT

**Comment by Shevchik** [comment]
That's still not the full error, are you sure that debug is enabled?

**Comment by Deathroner** [comment]
Excuse me, could you explain from where should I activate it?

So I can send you the full error

**Comment by Shevchik** [comment]
/ps debug, server.properties.

Next time read the issue template fully.

**Comment by Deathroner** [comment]
https://pastebin.com/g8xE52VY

Now activate the command "/ ps debug" and that is the error that I got with the same situation

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/f7dd0a1f67e6e87f5f586c750e9cecd513367032
