### ISSUE TITLE
MCPE Issue.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ProtocolSupport/ProtocolSupport#126]
```Type id for protocol version MINECRAFT_PE doesn't exist for datawatcher valuetype VECTOR3F```

**Comment by nathampa0909** [comment]
I think this issue have be closed, because PS dont support MCPE version yet.

**Comment by nathampa0909** [comment]
You have this error yet? I make test's with latest version and I dont see this.

I think is fixed: https://github.com/ProtocolSupport/ProtocolSupport/commit/94e16d5f608df00d1c5c22bea367826100ad1b36
