### ISSUE TITLE
Kick when op on 1.16.1 server

### ISSUE THREAD

**Issue by Heliosard** [ProtocolSupport/ProtocolSupport#1260]
Hi,
I am automatically kicked of a Paper 1.16.1 server (last build: 47) with the reason "Connection reset by peer" while being op.
This happens when:
- I'm already op and join the server
- I'm logged in and I'm op with console

Tested with only two plugins installed: ProtocolSupport and ProtocolLib.

**ProtocolSupport version**
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.07.02 at 22:30:48 MSK, buildhost: build.true-games.org, buildnumber: 509, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:1f834da42dfc1171e5a76aa573e61821677708e9)

**Server version**
git-Paper-47 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

Thank you for your time,

**Comment by Shevchik** [comment]
That means that the connection was closed by the client for whatever reason. Check the client logs to figure out more.
