### ISSUE TITLE
Hex codes not being passed through

### ISSUE THREAD

**Issue by ShayBox** [ProtocolSupport/ProtocolSupport#1261]
Using ProtocolSupport the new 1.16 hex codes aren't correctly being passed through the ping event, which work without the plugin or with ViaVersion.

![image](https://user-images.githubusercontent.com/9505196/87182589-76b8a100-c2b2-11ea-82bd-56075b0ab1cd.png)
(Supposed to be a rainbow)
![image](https://cdn.discordapp.com/attachments/568058367692767242/731195354531233892/unknown.png)

```
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.07.09 at 22:14:57 MSK, buildhost: build.true-games.org, buildnumber: 513, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:44828238b1915a79265378f02bc0c293da059d8a)
```
```
This server is running Paper version git-Paper-75 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
```

EDIT: The expected behavior for pre-1.16 clients is to still pass it through as they parse it as nothing and do not color the text, same as vanilla behavior.

**Comment by Shevchik** [comment]
No, the expected behavior is for color codes to be converted to the closes color for < 1.16 clients.

**Comment by ShayBox** [comment]
That doesn't relate at all to the point of this issue, the behavior of hex codes to clients that don't support them is unrelated, ProtocolSupport is breaking hex codes for clients that DO support them, I don't mind it converting to the closest color for unsupported clients, but it's also not doing that too well.

**Comment by Shevchik** [comment]
What was that then?

EDIT: The expected behavior for pre-1.16 clients is to still pass it through as they parse it as nothing and do not color the text, same as vanilla behavior.

**Comment by ShayBox** [comment]
I was saying the normal vanilla expected behavior is the client ignores hex codes and shows uncolored text, I didn't realize you already handle converting colors which is more than I expected for this plugin

**Comment by Shevchik** [comment]
Found it. Happens because of to legacy -> from legacy conversion inside the status response handler

**Comment by Shevchik** [comment]
Implemented chat json support in motd. RGB color codes seems to work now (tested using ProtocolSupportMotd, which uses PS ServerPingResposeEvent). But i still need info about how do you set rgb colors on your end, to verify that it works using your method.
