### ISSUE TITLE
Chat JSON hoverEvent seems to be broken

### ISSUE THREAD

**Issue by Harveyplays02** [ProtocolSupport/ProtocolSupport#1262]
**Description Of Issue:**
When using a hover event in chat (either issued via a /tellraw or an advancement or a plugin-induced JSON chat message), the hover text does not show on any client versions, including 1.16.1. I have ran tests with this, removing everything but PS from the server, and if I remove PS from the server, hoverEvents work as normal.

**Server Software:** Paper 1.16.1 (build 86)

**Plugin Version:** protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.07.09 at 22:14:57 MSK, buildhost: build.true-games.org, buildnumber: 513, buildgit: https://github.com/ProtocolSupport/ProtocolSupport:origin/master:44828238b1915a79265378f02bc0c293da059d8a)

**Comment by Shevchik** [comment]
Yeah, 1.16.1 hover changes aren't implemented fully yet. You may use 1.15.2 style hover until it gets fixed.

**Comment by Nextopi** [comment]
> Yeah, 1.16.1 hover changes aren't implemented fully yet. You may use 1.15.2 style hover until it gets fixed.

how ?

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/72836fe08b82e7e132668abcae8edcc8b18322f6
