### ISSUE TITLE
VarInt too big

### ISSUE THREAD

**Issue by Hyronymos1337** [ProtocolSupport/ProtocolSupport#1263]
My players getting kicked (with 1.16.1) multiples time a day.

Bungee-Log: [00:35:16] [Netty Worker IO Thread #15/INFO]: [akwa9110] disconnected with: Internal Exception: io.netty.handler.codec.DecoderException: VarInt too big
[00:35:16] [Netty Worker IO Thread #15/INFO]: [/176.198.183.41:27851|akwa9110] -> UpstreamBridge has disconnected
[00:35:16] [Netty Worker IO Thread #15/INFO]: [/176.198.183.41:27851|akwa9110] <-> DownstreamBridge <-> [citybuild2] has disconnected

Screenshot: https://gyazo.com/d59454d9a67fe5c00ce655c5a937cb7f

* ProtocolSupport version: https://prnt.sc/tj914p
* Server version: 1.16.1

**Comment by MrPowerGamerBR** [comment]
Same here, clients are disconnected when getting near a certain area in the server

**Comment by Shevchik** [comment]
Need the debug log and map where it happens

**Comment by PapiCapi** [comment]
I got the same problem and made a schematic where i got this issue : 
[IleCrashSky.zip](https://github.com/ProtocolSupport/ProtocolSupport/files/4959949/IleCrashSky.zip)

**Comment by Hyronymos1337** [comment]
I found the issue, my players changed their plot biome to warped_forest, which is one of the new nether biomes, changing the biome back everywhere fixed it

**Comment by PapiCapi** [comment]
For me, it's in a BSkyblock world so nothing related to plots

**Comment by Shevchik** [comment]
It is biomes tho, PS doesn't read them right in some cases, will fix it soon.

**Comment by FrukTik** [comment]
I had the same error with players excluding when approaching one chunk, a regular sign with inscriptions was placed in it. I could not solve the problem, applied the regeneration of that area, until such problems arose again.
