### ISSUE TITLE
Lightning invisible when connecting to a 1.16.1 server with a 1.16.1 client.

### ISSUE THREAD

**Issue by applebee1558** [ProtocolSupport/ProtocolSupport#1264]
PS buildinfo: https://applebee1558.com/uploads/2020/07/javaw_Y5rUGfQJ7H.png
Server: Spigot 1.16.1/Paper 1.16.1 (happens on both)
Client: 1.16.1
The effects of a lightning bolt is seen, but the bolt itself is not seen. The sound effect can be heard though.

**Comment by Shevchik** [comment]
Probably missing a bolt entity id mapping somewhere

**Comment by applebee1558** [comment]
Oh ok

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/0a662e084e096d9d9d7b40d1aedb50c91b35556e

**Comment by applebee1558** [comment]
Thanks, works
