### ISSUE TITLE
Bedrock support

### ISSUE THREAD

**Issue by SubMGRru** [ProtocolSupport/ProtocolSupport#1265]
Sorry, I don't quite understand.  Does this plugin allow Bedrock Edition players to play on the spigot server?

**Comment by 7kasper** [comment]
Nope. This plugin allows older versions of minecraft (down to 1.4.7) to connect to the most recent (currently 1.16.1) minecraft servers. We have had successful experiments with bedrock multiplay as well (see #304). Currently some work is being done on private on that. You can also follow up on Discord, but progress is and will be slow. We are not very actively working on it. Maybe try Geyser? I think they are pretty active now and this might be the thing you are looking for.
