### ISSUE TITLE
Error connection 1.16.1

### ISSUE THREAD

**Issue by FrukTik** [ProtocolSupport/ProtocolSupport#1267]
Build # 517 (Jul 31, 2020 3:10:07 PM)
---
This server is running CraftBukkit version git-Spigot-0287a20-7560f5f (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
----
A player with a nickname from Russian letters with an underscore cannot connect to the server (10 characters in the nickname)
Gives an error message
Client log:
https://pastebin.com/raw/jSa3sDrD
Server log:
[17:14:31] [Server thread/INFO]: /127.0.0.1:55895 lost connection:
Without ProtocolSupport, logging into the server occurs without problems.
![gKnGnv5Rxu0](https://user-images.githubusercontent.com/20886295/89543104-30028c00-d809-11ea-860a-47842c1bd52b.jpg)

**Comment by Shevchik** [comment]
Enable debug on server and attach debug log.
