### ISSUE TITLE
Nameplates above heads different from 1.8 -> 1.7

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#127]
Namecolors above heads are normal in 1.8 and in 1.7 they have same color as chat namecolor set by /nick.
1.8
![NameColor 1.8](http://i.imgur.com/tDfIm6V.png)

1.7
![NameColor 1.7](http://i.imgur.com/0dR0egV.png])

**Comment by Shevchik** [comment]
Currently they have the same color as custom username field in tablist packet.

**Comment by Tom-III** [comment]
There should be a way to have different color name above head and different in tab list, how is it done in 1.8?  (Everything worked until we updated ProtocolSupport to 1.8.8, so the ability to have it correct exists)

**Comment by Shevchik** [comment]
Well, previously protocolsupport just ignored custom tablist name completely. Will fix it to use real username for above head nametag.

**Comment by Tom-III** [comment]
just make it ignore it again, don't force it to use real username because TagAPI breaks

**Comment by Shevchik** [comment]
Try now
