### ISSUE TITLE
Connecting in 1.16.2 to a 1.16.2 server

### ISSUE THREAD

**Issue by PapiCapi** [ProtocolSupport/ProtocolSupport#1271]
protocolsupport build : 541
server : paper-141 (1.16.2)

From my lobby (in 1.16.1 with viaversion and protocolsupport) i try to connect into my 1.16.2 server in 1.16.2, i got this error : http://prntscr.com/u5ix0c

In the console with /ps debug enabled i only have this output : http://prntscr.com/u5ixb7

**Comment by Shevchik** [comment]
Try connecting directly. From what i can see, the error happens on quite large packet, but not so many packets can be large, chunks being one of them, but your proxy isn't supposed to read them for real anyway.

**Comment by PapiCapi** [comment]
What do you mean by connecting directly ?
Do you suggest to remove some firewall rules so that players can join directly to the server without passing by the proxy ?

**Comment by Shevchik** [comment]
I mean that you setup a copy of the server that kicks players locally, and connect to it directly, so more useful log can be acquired.

**Comment by Shevchik** [comment]
Try the latest build, chances are that it was because of that one wrongly written field.

**Comment by PapiCapi** [comment]
Yeah, that works fine now !
Thanks
