### ISSUE TITLE
Json chat is broken on 1.16.2

### ISSUE THREAD

**Issue by TKwSni** [ProtocolSupport/ProtocolSupport#1272]
* ProtocolSupport version (/ps buildinfo)
![imagen](https://user-images.githubusercontent.com/9063912/91554681-9dcc4000-e8fd-11ea-91ca-c4d61627ab26.png)
https://github.com/ProtocolSupport/ProtocolSupport:origin/master:30794744f0a481014e6cda8457414858e645ffa9)

* Server version Paper-152

After upgrading to 1.16.2 json messages to chat show like this

![imagen](https://user-images.githubusercontent.com/9063912/91560091-3b783d00-e907-11ea-9418-28849f90f8b6.png)

Error:
https://paste.gg/p/anonymous/2c21e4751da94cd18dae72e46c1f6bb3/files/95ff0801bbc34787810df5fcba34baef/raw

json from plugins like venturechat work fine, but from plugins like customcrafting or ezauctions break like that.

**Comment by Shevchik** [comment]
The item hover value is invalid, it should be string that contains itemstack encoded in snbt, but instead it's a broken text component.

**Comment by Shevchik** [comment]
So it's some sort of quirk in legacy value parses. Item hover for whatever reason supports parsing an array of base components for legacy value and show_text, and it supports a single text component text as snbt string >_<.

**Comment by Shevchik** [comment]
Should be fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/1d0c2891f920aa1b4a6bcdc121e0a8949ba93464

**Comment by TKwSni** [comment]
Seems to be fixed, thanks
