### ISSUE TITLE
[1.16.2] White actionbars

### ISSUE THREAD

**Issue by Nick-kel** [ProtocolSupport/ProtocolSupport#1273]
**ProtocolSupport version (/ps buildinfo)**
![image](https://user-images.githubusercontent.com/42046014/91637261-92653b80-ea07-11ea-909d-97c15a113174.png)

**Server version**
![image](https://user-images.githubusercontent.com/42046014/91637266-9c873a00-ea07-11ea-9673-af772cfbe424.png)

All actionbars which contains colorcodes (e.g. §a) are completely white. Tested in minecraft version 1.8.9 and 1.12.2

**Comment by Shevchik** [comment]
Attach an example code that is used for sending action bar. Tho i may probably have an idea what's wrong. Title action bar supports color while chat action bar uses legacy text, so probably i'm missing a legacy text conversion somewhere.

**Comment by Nick-kel** [comment]
```
import net.md_5.bungee.api.ChatMessageType;
import net.md_5.bungee.api.chat.TextComponent;

p.spigot().sendMessage(ChatMessageType.ACTION_BAR, TextComponent.fromLegacyText(message));
```

**Comment by SureazDev** [comment]
Sending an ActionBar like that is deprecated.
Use this instead and your color problem is fixed:

player.sendActionBar(new TextComponent(message));
