### ISSUE TITLE
Some bugs :(

### ISSUE THREAD

**Issue by Playerliqht** [ProtocolSupport/ProtocolSupport#1274]
Hello,
I come to share the problems that I found on the latest of 09/10/2020 regarding ProtocolSupport.
Below is a list of the issues.

List :
- Golden Apple bug: the animation continues when you keep the apple in your hand when you are no longer eating.
- For 1.8 players, we do not see item / armor enchantments
- When a 1.8 player has the slowfalling effect, he also has slowness ... which shouldn't be the case
- Some textures in 1.8 of the beds in the villages are bugged
- The trident is not visible to 1.8 players
- 1.8 players cannot go below the half slabs and the "bug" to block high with the trapdoor persists (but 1.8 players cannot). Maybe it is necessary to deactivate this?

Server version : 1.16.2-r2.jar (Paper)
/ps info : 
![Screenshot_1](https://user-images.githubusercontent.com/41956661/92747231-478ee080-f384-11ea-8e1a-88365f90bd0d.png)

Good luck and thank you for your work !

**Comment by Shevchik** [comment]
Retest with latest build, since some fixes were done since then. Also create a separate issue for each issue listed.
