### ISSUE TITLE
Levitation bug

### ISSUE THREAD

**Issue by Playerliqht** [ProtocolSupport/ProtocolSupport#1275]
Server version : 1.16.2 R01 (PAPER)
/ps info : *screenshot* ![Screenshot_1](https://user-images.githubusercontent.com/41956661/92777365-6b601f80-f3a0-11ea-8620-4f625423c5ac.png)

Levitation bug : Players in 1.8 cannot move normally (normal speed) when they have this effect

**Comment by Shevchik** [comment]
Not fixable, since you need to propel players up, and you can only do this by setting player velocity, bit this will override player movement attempts.
