### ISSUE TITLE
Slow Falling effect

### ISSUE THREAD

**Issue by Playerliqht** [ProtocolSupport/ProtocolSupport#1276]
Server version : 1.16.2 R01 (PAPER)
/ps info : screenshot 
![Screenshot_1](https://user-images.githubusercontent.com/41956661/92777923-f6d9b080-f3a0-11ea-92fd-8b8989d832c5.png)

Slowfalling effect : 
Players in 1.8 do not have normal speed with this effect. A person in 1.16, for example, goes further than the player in 1.8.
The effect is visually unpleasant :x

**Comment by Playerliqht** [comment]
+ Players with this effect en 1.8 have slowness in the air

**Comment by Shevchik** [comment]
Same as with the levitation effect. Tho in this case the velocity will be only applied if the player in the air.
