### ISSUE TITLE
Golden Apple problem

### ISSUE THREAD

**Issue by Playerliqht** [ProtocolSupport/ProtocolSupport#1277]
Server version : 1.16.2 R01 (PAPER)
/ps info : screenshot
![Screenshot_1](https://user-images.githubusercontent.com/41956661/92778105-27b9e580-f3a1-11ea-9c10-0560b6cb5ad5.png)

The Golden Apple chug is canceled when a player in 1.8 takes damage, which is not the case in other versions.
Moreover, the animation continues when you keep the apple in your hand when you are no longer eating.

Thank you o/

**Comment by Shevchik** [comment]
Need more explanation. Does the animation continues from other player view or from your own?

**Comment by Playerliqht** [comment]
From the player who had the apple in his hand + 
The most important is the chug problem :(

**Comment by Playerliqht** [comment]
update: The visual bug is not always there. The gapple is sometimes eaten *anyway

**Comment by ludgart** [comment]
Hello,

I have the same problem. Minecraft version: 1.16.5 and ProtocolSupport 594. If you eat the golden apple you need to switch the hotbar item to get it canceled.

**Comment by Playerliqht** [comment]
> Hello,
> 
> I have the same problem. Minecraft version: 1.16.5 and ProtocolSupport 594. If you eat the golden apple you need to switch the hotbar item to get it canceled.

hey ! the problem does not come from protocol support!

**Comment by Playerliqht** [comment]
> > Hello,
> > I have the same problem. Minecraft version: 1.16.5 and ProtocolSupport 594. If you eat the golden apple you need to switch the hotbar item to get it canceled.
> 
> hey ! the problem does not come from protocol support!

Or it has been fixed, in any case I no longer have this problem using the latest versions of protocol support. Subject closed
