### ISSUE TITLE
Player tablist names not limited for < 1.8 clients

### ISSUE THREAD

**Issue by frash23** [ProtocolSupport/ProtocolSupport#128]
If any players have tablist names longer than 16 chars ( Player#setPlayerListName ), all < 1.8 clients will crash immediately.

I propose getting the raw name of players or truncating from the left.

**Comment by Shevchik** [comment]
Should be fixed, try now

**Comment by frash23** [comment]
Awesome, it works.
Any change you could make it clam from the right though? Doesn't look too pretty:

![Screencap](http://i.imgur.com/vtz6iwW.png)

**Comment by Shevchik** [comment]
Sorry, but no. You will have to account for it and use scoreboard teams to add prefixes, etc.
I may actually add an api for setting player tab usernames so you can do it per version.
