### ISSUE TITLE
Glitchs & height problem

### ISSUE THREAD

**Issue by Playerliqht** [ProtocolSupport/ProtocolSupport#1280]
Server version : 1.16.2 R01 (PAPER)
/ps info : screenshot
![image](https://user-images.githubusercontent.com/41956661/92788239-10cbc100-f3aa-11ea-98cb-9d9026ddb3ba.png)

The problem : 

![image](https://user-images.githubusercontent.com/41956661/92787879-c6e2db00-f3a9-11ea-8a5e-fc0f561ac46d.png)
![image](https://user-images.githubusercontent.com/41956661/92788155-001b4b00-f3aa-11ea-9e6d-1c1bf4448aaf.png)

Since we cannot move in 1.8 in this way, can we deactivate (cancel the movement) on movements of 1.5 blocks in height and even 1 block in height?
Hypixel disabled it on its server (1.8x -> 1.16) and it's fine

**Comment by Shevchik** [comment]
It's up to another plugin to modify an important mechanic such as that.
