### ISSUE TITLE
colors not supported

### ISSUE THREAD

**Issue by Stoniasawsome** [ProtocolSupport/ProtocolSupport#1282]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo)
* Server version

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)
using ProtocolSupport 1.16.2-3
on my paper spigot 1.16.2 server

10.09 17:08:38 [Server] INFO protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.09.10 at 23:39:23 MSK, buildhost: https://build.true-games.org, buildnumber: 563, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/6d46fc516440b9d134bd607754733c25408cb60c)

im running CMI and they allow for rgb colors using codes like this {#008070} with your plugin installed i cannot run those colors in my MOTD

**Comment by Shevchik** [comment]
CMI is not opensource, and bukkit doesn't have an option of setting rgb motd, so i don't know what may be even wrong. ProtocolSupport itself does support setting rgb motd using it's own event.

**Comment by Legoman99573** [comment]
Can confirm when trying to use RBG values on kicking the user even with trying my own way of doing it.

Tried modifying the blockversion plugin to support RGB Hex but to no success as it works fine on broadcasting, but not with messages from protocolsupport for some reason.

Kick message configured:
```
kickmessage: '&#EB6262%join-version% &#D98880is not supported on this server. &#D9CE801.16-%server-version% &#D98880supported.'
```

Code:
``` java
   public void onPlayerJoin(PlayerLoginStartEvent e) {
        if (this.mode.equalsIgnoreCase("whitelist")) {
            if (!this.versions.contains(ProtocolSupportAPI.getProtocolVersion(e.getAddress()).toString())) {
                e.denyLogin(RGBSupport.translateHexCodes(this.kickmessage.replace("%join-version%", ProtocolSupportAPI.getProtocolVersion(e.getAddress()).toString().replace("MINECRAFT_", "").replace("_", ".")).replace("%server-version%", Bukkit.getServer().getMinecraftVersion()), this));
            }
        } else if (this.versions.contains(ProtocolSupportAPI.getProtocolVersion(e.getAddress()).toString())) {
            e.denyLogin(RGBSupport.translateHexCodes(this.kickmessage.replace("%join-version%", ProtocolSupportAPI.getProtocolVersion(e.getAddress()).toString().replace("MINECRAFT_", "").replace("_", ".")).replace("%server-version%", Bukkit.getServer().getMinecraftVersion()), this));
        }

    }
```

Returned Result:
![image](https://user-images.githubusercontent.com/7460704/93178915-9036f880-f6fa-11ea-9cb2-bbbd66e5f420.png)

**Comment by Shevchik** [comment]
What exactly does RGBSupport do? Tho it uses legacy message, so no matter what you put in there, it won't support rgb codes, because it's a legacy chat message.

**Comment by Legoman99573** [comment]
> What exactly does RGBSupport do? Tho it uses legacy message, so no matter what you put in there, it won't support rgb codes, because it's a legacy chat message.
> Guess some API parts need to support the json components too.

its a messy way of adding support for configuration files. Here is the code snippet i use for my plugin and it works flawlessly with kicking users but seems to not be when denying someone from joining. Could probably be used to detect when someone is using a version older than 1.16 if it helps:
```java
package net.toxicugandamc.mc.Listeners;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import net.md_5.bungee.api.ChatColor;
import net.toxicugandamc.mc.Core;
import net.toxicugandamc.mc.checks.VersionEnums;

public class RGBSupport {
    private static final Pattern HEX_PATTERN = Pattern.compile("&#([A-Fa-f0-9]{6})");
    private static final char COLOR_CHAR = '§';

    public static String translateHexCodes(String message, Core plugin) {
        return translate(HEX_PATTERN, message, plugin);
    }

    public static String translateHexCodes(String startTag, String endTag, String message, Core plugin) {
        Pattern hexPattern = Pattern.compile(startTag + "([a-f0-9]{6})" + endTag);
        return translate(hexPattern, message, plugin);
    }

    private static String translate(Pattern hex, String message, Core plugin) {
        if (VersionEnums.getServerVersion().getVersionInt() < VersionEnums.VERSION_116.getVersionInt()) {
            return ChatColor.translateAlternateColorCodes('&', message);
        } else {
            Matcher matcher = hex.matcher(message);
            StringBuffer buffer = new StringBuffer(message.length() + 32);
            while (matcher.find()) {
                String group = matcher.group(1);
                matcher.appendReplacement(buffer, "§x§" + group.charAt(0) + '§' + group.charAt(1) + '§' + group.charAt(2) + '§' + group.charAt(3) + '§' + group.charAt(4) + '§' + group.charAt(5));
            }
            return ChatColor.translateAlternateColorCodes('&', matcher.appendTail(buffer).toString());
        }
    }
}
```

**Comment by Shevchik** [comment]
I see, you do attempt bungee chat string rgb color codes using §x. ProtocolSupport however doesn't parse legacy chat message, it wraps it to TextComoponent and sends it. That's why urls and §x color code hack doesn't work.

**Comment by Shevchik** [comment]
Currently working on adding base component support to more places, and also parsing legacy chat to json, but it will take some time to complete.

**Comment by Shevchik** [comment]
This should be fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/182a86c12dddfeac8e441e5a464064a5f577b8fa

**Comment by Stoniasawsome** [comment]
great, good lookin out! awesome plugin

**Comment by Legoman99573** [comment]
yep, this is resolved as RGB shows correctly instead of trying to use legacy colors only on a 1.16+ server.
