### ISSUE TITLE
death message

### ISSUE THREAD

**Issue by 100petr** [ProtocolSupport/ProtocolSupport#1283]
* ProtocolSupport version (/ps buildinfo): buildnumber: 563
* Server version: spigot 1.16.2 #2908

 I have an itemsadder plugin on the server and if I kill a player with Shotgun (textured crossbow) will write this https://pastebin.com/CsggGDR3
I have tried that it is PS. After removing it, it doesn't do it.
![2020-09-12_09 00 48](https://user-images.githubusercontent.com/29830635/92994291-6d89c180-f4f9-11ea-9617-40f401219639.png)
![2020-09-12_09 00 49](https://user-images.githubusercontent.com/29830635/92994295-6f538500-f4f9-11ea-86a0-351fa5041b51.png)

**Comment by Shevchik** [comment]
Should be fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/307df6cc98ca77f22457aeb8e7a8563aed0af956

**Comment by 100petr** [comment]
it is fixed
