### ISSUE TITLE
No lava damage sounds in 1.8.9 clients

### ISSUE THREAD

**Issue by TheDoctor025** [ProtocolSupport/ProtocolSupport#1284]
Server version: 1.16.3 PaperSpigot, build 196
Client version: 1.8.9 with OptiFine
/ps buildinfo: `protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.09.11 at 02:03:01 MSK, buildhost: https://build.true-games.org, buildnumber: 564, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/7914f24cf9bed285350030daf1a65ad48f210606)`

Behavior: Falling into lava in 1.8.9 does not play the sounds accompanying fire damage. However, the sound of the lava itself can be heard.

**Comment by Shevchik** [comment]
We do have emulation of lava/fire hurt effect already, guess something is up with it.

**Comment by TheDoctor025** [comment]
Would it help if I posted a video?

**Comment by Shevchik** [comment]
Yes

**Comment by TheDoctor025** [comment]
[video.zip](https://github.com/ProtocolSupport/ProtocolSupport/files/5227324/video.zip)
GitHub doesn't support uploading videos to issues, so I had to zip it.

**Comment by Shevchik** [comment]
The client plays hurt sound upon receiving or calculating the hurt effect.
But the player hurt by fire/water/lava sound doesn't exist in versions prior to 1.12, it always uses the same sound regardless of damage source.

**Comment by TheDoctor025** [comment]
So can the hurt sound be played at all? Because in the video it was completely silent

**Comment by Shevchik** [comment]
It does play, but only after some time after getting out from lava. I guess i need to figure out why it is delayed so much.

**Comment by Shevchik** [comment]
Hurt effect emulation now also works for lava damage itself
https://github.com/ProtocolSupport/ProtocolSupport/commit/334cf1ceba77650e06eca8b654abaf5f6ddbcd7d
