### ISSUE TITLE
baby piglin spawn

### ISSUE THREAD

**Issue by 100petr** [ProtocolSupport/ProtocolSupport#1285]
ProtocolSupport version (/ps buildinfo: buildnumber: 564
Server version:  PaperMC 1.16.3, Build 196
Tested client version: Optifine 1.16.3

Unable to spawn baby piglin.
With PS:
![2020-09-15_18 13 28](https://user-images.githubusercontent.com/29830635/93236518-37f60a00-f77f-11ea-83f7-f852fa6d0c43.png)
![2020-09-15_18 13 30](https://user-images.githubusercontent.com/29830635/93236489-30cefc00-f77f-11ea-847e-b0d446a5e829.png)
Without PS:
![2020-09-15_18 15 54](https://user-images.githubusercontent.com/29830635/93236794-8acfc180-f77f-11ea-82bc-5ed9604499fd.png)
![2020-09-15_18 15 56](https://user-images.githubusercontent.com/29830635/93236796-8c00ee80-f77f-11ea-9009-1e16d12729af.png)
The only plugin on the server was PS.

**Comment by Shevchik** [comment]
Does the entity spawn serverside?
Also debug and check for debug messages on spawn attempt. Also make sure you aren't in creative and that spawn egg is still a spawn egg.

**Comment by 100petr** [comment]
Only a piglin appears, not a baby.
![2020-09-15_20 31 01](https://user-images.githubusercontent.com/29830635/93250330-f707f080-f792-11ea-93f7-9de7ab90af6a.png)
![2020-09-15_20 32 38](https://user-images.githubusercontent.com/29830635/93250345-fc653b00-f792-11ea-9caa-439b7b3e705f.png)
![2020-09-15_20 33 07](https://user-images.githubusercontent.com/29830635/93250347-fe2efe80-f792-11ea-978e-d7ec112625ef.png)
ps debug doesn't write anything.

**Comment by Shevchik** [comment]
So piiglin appears instead of baby piglin?

**Comment by 100petr** [comment]
Yes

**Comment by Shevchik** [comment]
Found it, it was wrong meta index, zombification immunity index was used instead of is baby. Will fix soon (need to test that large entity transform refactor that i almost finished).

**Comment by Shevchik** [comment]
This should be fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/099f78500445570f0b48dc48c3850c186fc1683b

**Comment by 100petr** [comment]
I'll try soon and let you know.

**Comment by 100petr** [comment]
It is fixed.
