### ISSUE TITLE
Boat problem in 1.8

### ISSUE THREAD

**Issue by Playerliqht** [ProtocolSupport/ProtocolSupport#1286]
Server : PAPER 1.16.3
Buildinfo : ![image](https://user-images.githubusercontent.com/41956661/93254894-62ed5780-f799-11ea-9fc5-090bfb26dd28.png)

Players cannot move in boat in 1.8 ! They are sometimes glitches and the boat rollback when the player is on 1.8 client...
That was working in previous version of the plugin. 
![image](https://user-images.githubusercontent.com/41956661/93254851-51a44b00-f799-11ea-8c7d-3b64138edd72.png)

**Comment by Shevchik** [comment]
Literally in the readme
