### ISSUE TITLE
Border Color

### ISSUE THREAD

**Issue by StarozytnySky** [ProtocolSupport/ProtocolSupport#1288]
When posting the issue you also need to provide the following information:

* ProtocolSupport version: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2019.04.09 at 18:42:11 MSK, buildhost: build.true-games.org, buildnumber: 377)
* Server version: 1.13.2

I have install plugin SuperiorSkyblock2 ( https://www.spigotmc.org/resources/⚡%EF%B8%8F-superiorskyblock2-⚡%EF%B8%8F-the-best-core-on-market-⚡%EF%B8%8F-1-16-support.63905/updates ) and when i try change color border doesn't nothing happen. But if i disable protocolsupport color border is change. I can install latest version protocolsupport because i have server on version 1.13.2

**Comment by Shevchik** [comment]
Border doesn't have a way to set color. Did you mean something else, like it's not showing as expanded or shrinking?
Anyway, we don't support outdated server versions.
