### ISSUE TITLE
Holographic Displays plugin - Not showing Holograms for 1.7.10 client 

### ISSUE THREAD

**Issue by alicheek** [ProtocolSupport/ProtocolSupport#129]
Hey there so im using the plugins Holographic displays as they are a good way to show information rather than using a sign, im using a 1.8.8 build of spigot for the server hub with your ProtocolSupport plugin, when making the hologram it is not visible to a 1.7.10 client but for the 1.8.9 client it is visible.

Holographic displays: http://dev.bukkit.org/bukkit-plugins/holographic-displays/

Thank you for your time and your very amazing plugin :)

**Comment by alicheek** [comment]
Sorry for being a pain, ive just tried your newest version and it hasnt seemed to work, is this something that is possible to fix?

**Comment by swan201** [comment]
i m working fine lastest PS and HD Plugins.

**Comment by alicheek** [comment]
You can see the HD holos fine when your on a 1.8.9 client but try on a 1.7.10 client

**Comment by swan201** [comment]
@alicheek yeah all is fine. I try all 1.7.X Clinet.

**Comment by alicheek** [comment]
im on version Holographic Displays v2.1.10 and latest dev build of PS

**Comment by swan201** [comment]
@alicheek humm... I Update today PS Version now. Suddenly now i cant see HD. I think Some change make Broken HD Plugins. i use old Version PS.

**Comment by alicheek** [comment]
any chance you know what version you are using? :)

**Comment by Shevchik** [comment]
Holograms are different in 1.8 and 1.6.2-1.7.10. In new version they are armor stands, and in old they are horses and wither skulls. So it's up to your hologram plugin to support holograms on different versions.

**Comment by alicheek** [comment]
ah ok thanks for the heads up i shall use an old version of HD then :)

**Comment by swan201** [comment]
@Shevchik Knock, Knock. I use HDP 2.1.10 updated version. but still cant see any hologram in 1.7.X Client. HDP 2.1.10 support 1.6.4-1.8.8 spigot

**Comment by Shevchik** [comment]
Because HDP doesn't support client multiversion, it only supports running in different spigot versions.

**Comment by swan201** [comment]
@Shevchik I Found this plugins. https://github.com/filoghost/HolographicDisplaysPatch

Can you make see this source code and make compatibile plugins??

**Comment by Shevchik** [comment]
No, i'm not making or fixing hologram plugin.

**Comment by ZombieAssassin** [comment]
If you're lazy and you know it clap your hands.

 Thanks for supporting a widely used version Shevchik, really appreiciate the hard work you spend adding features bud. 

Oh well. A free plugin is a free plugin. Gotta make sure to do as little as possible, Am I right?

**Comment by Shevchik** [comment]
No, coz i don't have that much time to write everything. But if you had looked a bit better you could have found this
https://github.com/ProtocolSupport/ProtocolSupportLegacyHologram

**Comment by iDarkyy** [comment]
You people are new to minecraft apperantly, or just you aren't thinking.
Holograms are Armor Stands,
Armor stands do not exist in any 1.7 version or lower version

**Comment by gdude2002** [comment]
Holograms existed pre-1.8 via horses and wither skulls.

@iDarkyy Please don't necro issues without a good reason to - for example, an existing issue that has a new workaround, or similar. Vitriol is not a good reason.

I will be locking this thread to prevent more spam.
