### ISSUE TITLE
Players cannot see the chunks they spawn in and chunks near them

### ISSUE THREAD

**Issue by soshimee** [ProtocolSupport/ProtocolSupport#1291]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo)
`protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.09.11 at 02:03:01 MSK, buildhost: https://build.true-games.org/, buildnumber: 564, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/7914f24cf9bed285350030daf1a65ad48f210606)`

* Server version
1.16.3 Tuninity `This server is running Tuinity version git-Tuinity-"de1983b" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)`

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

![image](https://user-images.githubusercontent.com/45235204/96358641-7008b800-1144-11eb-9c88-f0e802335b94.png)

This happens when anyone joins on older versions.

Also, players glide down when in that area (and eventually fall out of the world).

**Comment by soshimee** [comment]
(Don't mind about those random ores, it's from paper anti-xray)

**Comment by Shevchik** [comment]
Try without all other plugins first.

**Comment by soshimee** [comment]
Will do soon.

**Comment by soshimee** [comment]
Cannot be reproduced without other plugins, but that could be because of the ping difference, as the server with the problem is hosted by a hosting company but the test server is locally hosted.

**Comment by soshimee** [comment]
I'll try to reproduce it with the plugins on the main server soon.

**Comment by Shevchik** [comment]
Any new info?
