### ISSUE TITLE
Feature Request: PlaceholderAPI placeholder support

### ISSUE THREAD

**Issue by soshimee** [ProtocolSupport/ProtocolSupport#1292]
Placeholders like:
`%protocolsupport_player_protocol_id%`
`%protocolsupport_player_protocol_version%`

**Comment by Shevchik** [comment]
Should be it's own extension.

**Comment by soshimee** [comment]
what do you mean

**Comment by soshimee** [comment]
> Should be it's own extension.

Could you please explain?

**Comment by Shevchik** [comment]
I mean that this doesn't make sense to be a part of ProtocolSupport itself. ProtocolSupport provides an API which can be used to write literally 20-30 lines of code plugin that does this. I personally see no value in implementing such extension, so i won't do it.

**Comment by soshimee** [comment]
Please, I do not know how to code plugins...
