### ISSUE TITLE
SetCooldown's items id do not rewrite for mc < 1.16 

### ISSUE THREAD

**Issue by Leymooo** [ProtocolSupport/ProtocolSupport#1295]
ProtocolSupport should rewrite SetCooldown packet for allowing displaying items cooldown for < 1.16 clients

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/5bfc6c670ad9ac21b905d4f98c530ff1c57f856e
