### ISSUE TITLE
Json mouse Hover don't show

### ISSUE THREAD

**Issue by qiuDar** [ProtocolSupport/ProtocolSupport#130]
Hello, I met this problem when using this plugin.
I'm sorry, my English is not good, is using Google translate.
My server version is 1.8.8, the client version is 1.7.10.
ProtocolSupport version is using the latest build on January 28th.

This is a test of the json parameters.
`/tellraw @p ["",{"text":"text1","clickEvent":{"action":"open_url","value":"www.baidu.com"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"mouse Hover test"}]}}}]`

I found in the json "mouse Hover test" can't display.
I'm very sorry, because my English is not good, may have to trouble you personally test.

**Comment by Shevchik** [comment]
Try now

**Comment by qiuDar** [comment]
Thank you, have no problem.
