### ISSUE TITLE
<1.16.4 clients can't sign books; Book and quill (text inside) is empty on lectern

### ISSUE THREAD

**Issue by TNTUP** [ProtocolSupport/ProtocolSupport#1303]
* ProtocolSupport version (/ps buildinfo): [0 05:07:39 INFO]: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2020.11.30 at 19:58:34 MSK, buildhost: https://build.true-games.org, buildnumber: 588, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/9f487df9538392a048c6ee1ec54d1d0e3993b1a2)

* Server version: Paper 1.16.4 Build 300
-----------

Tested with 1.16.3, I expect previous versions having the same issue (eg: 1.12.2, 1.13.2)

How to reproduce the bug:

1. Get a Book and Quill and write something in it. Sign it aand... nope. 

2. If you write something in the book and quill and click done, the text is still there. Put it on a lectern and poof... gone.

-------

I thought it was a Paper related issue but I tested with a 1.16.4 client and I could sign it and the lectern works as expected but not for 1.16.3 and lower (didn't test those yet, sorry)

**Comment by Shevchik** [comment]
For whatever reason held slot information isn't updated, which causes the transformer to always attempt to change book in slot 0.

**Comment by Shevchik** [comment]
Found it, it was literally a very very simple error, but hard to spot because it is literally 1 symbol.
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/a8ba65ef160db17c1cb8ea31a7eff628a427f265
