### ISSUE TITLE
Stuck in Block

### ISSUE THREAD

**Issue by JaLuMu** [ProtocolSupport/ProtocolSupport#1308]
1.16.4 Paper Server
1.8.9 Client

when i walk in north direction to a block and mine it,
i get stuck in it, if a plugin disable block breaking

**Comment by 7kasper** [comment]
Happy new year ^^

**Comment by Shevchik** [comment]
Was fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/2394215f51313944faef9a02162b78bf70cf0d9e
