### ISSUE TITLE
I would like to use this on 1.15

### ISSUE THREAD

**Issue by WolfyRed** [ProtocolSupport/ProtocolSupport#1310]
Before submitting your issue, please check the following:

Yes, I want my server to use 1.15 because I am more fond of how the old Nether generates.
This is literally one version lower. I want to play my server with Minecraft 1.15 and still use 1.16 client or 1.14 client to join it. That should be very simple. However ProtocolSupport does not like that! Please fix!

When posting the issue you also need to provide the following information:

* ProtocolSupport version [Output = "/protocolsupport help"]
* Server version [1.15]

**Comment by Camotoy** [comment]
You should probably use ViaVersion, ViaBackwards and ViaRewind instead, which all support 1.15 and are up-to-date. If you are insistent on getting a version of ProtocolSupport that supports 1.15 (you will still need ViaVersion), see here: https://protocol.support/old/.

**Comment by the-r3dacted** [comment]
> You should probably use ViaVersion, ViaBackwards and ViaRewind instead, which all support 1.15 and are up-to-date. If you are insistent on getting a version of ProtocolSupport that supports 1.15 (you will still need ViaVersion), see here: https://protocol.support/old/.

ViaRewind goes down to 1.7, your plugin goes down to 1.4.7.
