### ISSUE TITLE
Custom Potion

### ISSUE THREAD

**Issue by ludgart** [ProtocolSupport/ProtocolSupport#1317]
Hello,

if you create a custom throwable potion, example on this generator page : https://mcstacker.net/
then it display on 1.8 the normal potion instead of a throwable potion. 1.16 see it right.

Is there a way to fix it?
 
* ProtocolSupport version 594
* Server version 1.16.5 (Paper)

**Comment by Shevchik** [comment]
Add an exact example of the potion you trued

**Comment by ludgart** [comment]
give @p splash_potion{HideFlags:32,CustomPotionEffects:[{Id:1b,Amplifier:0b,Duration:1200}],Potion:"minecraft:water"} 1

**Comment by Shevchik** [comment]
This should be fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/66b494a8dd1e3e17bdc6a6d6b5535fe1013e973f

At least the provided potion works.
