### ISSUE TITLE
Protocol Error

### ISSUE THREAD

**Issue by UknownGino** [ProtocolSupport/ProtocolSupport#1318]
**ProtocolSupport version**
`protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2021.02.22 at 14:17:46 MSK, buildhost: https://build.true-games.org, buildnumber: 597, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/cc14bc5b08f97ad2f2eec4a79eb239a647c9608b)`

I currently have 2 servers behind flamecord with protocolsupportbungee. The first server has protocolsupport installed and the server version is Paper 487 1.16.5 . The second server is a Tekkit Lite server running MCPC+ 1.4.7 R1.1. When i try to join the tekkit lite server via the 1.16.5 main server it gives me a "Protocol error" in the tekkit lite server console and it doesn't connect. `Disconnecting /127.0.0.1:5326: Protocol error`

**Comment by Shevchik** [comment]
You need something implementing PS encapsulation protocol on the backend to make it work.
