### ISSUE TITLE
Disable specific version Protocol

### ISSUE THREAD

**Issue by WolfyRed** [ProtocolSupport/ProtocolSupport#1319]
**Description of Issue**
I would like to use ViaRewind for 1.7, which loads in perfectly with PS, but the connection defaults to ProtocolSupport 1.7

**Why is this an Issue?**
This is an issue because I feel that I want specific features from ViaRewind, yet still keep 1.4-1.6 connections in the server.

When posting the issue you also need to provide the following information:

* ProtocolSupport version: `build 586` "https://github.com/ProtocolSupport/ProtocolSupport/commit/3d24efeda683ebed09725c70c2544f336bb1fd85)"
* Server version: `version 1.16.4-R0.1-SNAPSHOT`

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

**Comment by Shevchik** [comment]
No plans for this.

**Comment by 7kasper** [comment]
What specific features of rewind do you want? I think most stuff is inside protocolsupport (stuff) already.

If you would really really want this, it is possible but very janky. You'd have to make sure that ViaRewind takes precedence over ProtocolSupport. Also you'd probably need to do some connection-version spoofing like viaversion does: https://github.com/ViaVersion/ViaVersion/blob/master/bukkit/src/main/java/us/myles/ViaVersion/bukkit/classgenerator/ClassGenerator.java#L217 
Then again we only support the latest version of protocolsupport and not using it with any other version adders except the normal version of ViaVersion to support future clients.

**Comment by WolfyRed** [comment]
> What specific features of rewind do you want? I think most stuff is inside protocolsupport (stuff) already.
> 
> If you would really really want this, it is possible but very janky. You'd have to make sure that ViaRewind takes precedence over ProtocolSupport. Also you'd probably need to do some connection-version spoofing like viaversion does: https://github.com/ViaVersion/ViaVersion/blob/master/bukkit/src/main/java/us/myles/ViaVersion/bukkit/classgenerator/ClassGenerator.java#L217
> Then again we only support the latest version of protocolsupport and not using it with any other version adders except the normal version of ViaVersion to support future clients.

Enlighten me
