### ISSUE TITLE
Changing license from GPLv3 to AGPLv3

### ISSUE THREAD

**Issue by Shevchik** [ProtocolSupport/ProtocolSupport#132]
ProtocolSupport is a serverside plugin. And GPLv3 only requires you to provide source code if you convey binaries. It allows people to modify protocolsupport and install it on their own server without releasing source code. To avoid this we should change license from GPLv3 to AGPLv3. There is more info available there http://www.gnu.org/licenses/why-affero-gpl.en.html.
To change the license all contributors should allow this, or their code should be removed/rewritten.

Current list of contributors are:
@Shevchik (me)
@BeYkeRYkt
@MrPowerGamerBR

They need to state their agreement to changing the license in the comments.

No pull requests are accepted until this issue is resolved

**Comment by MrPowerGamerBR** [comment]
:+1:
Em 2 de fev de 2016 07:12, "Shevchik" <notifications@github.com> escreveu:

**Comment by BeYkeRYkt** [comment]
If that is so necessary, I agree

**Comment by Shevchik** [comment]
License changed to AGPLv3
