### ISSUE TITLE
Advancement announcement descriptions missing on hover

### ISSUE THREAD

**Issue by Tyloon1e** [ProtocolSupport/ProtocolSupport#1323]
ProtocolSupport version (/ps buildinfo): protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2021.02.28 at 07:01:48 MSK, buildhost: https://build.true-games.org, buildnumber: 599, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/f188eb2ea839a4a0ce02b627c0ff8199d0d99d2a)
Server version: 1.16.5 Paper
Issue: Whenever an advancement is announced in chat and you hover over the specific advancement, it only shows the title and not the description of the advancement.

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/1a446f253faead99710e4808cf134fe4264ab77e
