### ISSUE TITLE
PaperMC Adventure causing problems

### ISSUE THREAD

**Issue by TheFruxz** [ProtocolSupport/ProtocolSupport#1324]
- protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2021.02.22 at 14:17:46 MSK, buildhost: https://build.true-games.org, buildnumber: 597, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/cc14bc5b08f97ad2f2eec4a79eb239a647c9608b)
- version git-Paper-534 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Problem: By switching from Paper(MC) to Adventure, the ActionBar colors no longer work, no matter if Plain-Text, BungeeCore-API-TextComponents or Adventure-Text-Components.

**Comment by Shevchik** [comment]
Action bar using chat packet only support legacy color codes, not component color codes. So big chances are this is not a PS issue. Dump packet contents using protocollib to see what it sends.
