### ISSUE TITLE
Unable to connect (custom biome)

### ISSUE THREAD

**Issue by 100petr** [ProtocolSupport/ProtocolSupport#1325]
PS buildnumber: 599, Purpur 1022 MC: 1.16.5
Unable to connect to server. Debug: https://pastebin.com/F06JyAzt
After deleting the ItemsAdder and deleting the world, the problem stopped. So something must be done by ItemsAdder.
Link to the discord where we dealt with it: https://discord.com/channels/284447770507608064/293148511372050432/822733249310490676

**Comment by 100petr** [comment]
Ok, I've been experimenting and it looks like it's caused by https://www.spigotmc.org/resources/liquids-colored-liquids-itemsadder-addon.84386/

**Comment by 100petr** [comment]
It will probably be a Custom boom.
![unknown-3](https://user-images.githubusercontent.com/29830635/111894541-bcb23100-8a0b-11eb-9cee-d70b9d4a1907.png)

**Comment by 100petr** [comment]
![Screenshot_20210322-223151_Discord](https://user-images.githubusercontent.com/29830635/112061222-73262b00-8b5e-11eb-92c8-b5d2c18a3ca5.jpg)

**Comment by Shevchik** [comment]
This is probably fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/5ba500d639a4cfa8daa7520560f6b4738e120ed8
Technically PS will still warn (in debug mode) on missing biome entry and will use ocean biome for custom biomes. API for setting custom biome mappings will be added later.

**Comment by 100petr** [comment]
ok thanks a lot
