### ISSUE TITLE
bug wall 

### ISSUE THREAD

**Issue by franxyk** [ProtocolSupport/ProtocolSupport#1328]
There is a problem that if the server is 1.16 and the client 1.8 and you enter the server and disconnect near a wall and enter again you get stuck.

**Comment by Shevchik** [comment]
Technically same things happen with anvils and grass path

**Comment by franxyk** [comment]
> 
> 
> Technically same things happen with anvils and grass path

Do you have a solution?

**Comment by Shevchik** [comment]
The walls and probably most of the other blocks stuck issue is probably fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/2394215f51313944faef9a02162b78bf70cf0d9e
