### ISSUE TITLE
Some players (inlucindg myself) time out on logging in

### ISSUE THREAD

**Issue by frash23** [ProtocolSupport/ProtocolSupport#133]
I'm getting the following error when trying to log in on BungeeCord:

```
14:02:28 [INFO] [/a.b.0.170:46878] <-> InitialHandler has connected
14:02:29 [INFO] [Zell0c] <-> InitialHandler has connected
14:02:30 [INFO] [Zell0c] <-> ServerConnector [prisoff] has connected
14:02:32 [INFO] [Dominos_] <-> ServerConnector [prisoff] has connected
14:02:59 [WARNING] [Zell0c] -> UpstreamBridge - read timed out
14:02:59 [INFO] [Zell0c] disconnected with: ReadTimeoutException : null
14:02:59 [INFO] [Zell0c] -> UpstreamBridge has disconnected
14:03:00 [WARNING] [Zell0c] <-> ServerConnector [prisoff] - read timed out
14:03:00 [INFO] [Zell0c] <-> ServerConnector [prisoff] has disconnected
```

This is only happening to some users. Zell0c is my alt, I can log in fine using my regular account.
No errors in the Spigot console.

I've tried with all combinations of `late-bind` and `use-native-transport` configurations.

**Comment by Shevchik** [comment]
If you use ProtocolSupportBungee, it is the reason why it happens. ProtocolSupportBungee is unstable and sometimes refuses to read packets from player.

**Comment by nathampa0909** [comment]
Me too. I dont use bungee cord.

**Comment by frash23** [comment]
I am not using ProtocolSupportBungee, just ProtocolSupport on a PaperSpigot server behind BungeeCord.

No logging ever happens on the Paper server, only Bungee.

**Comment by nathampa0909** [comment]
After first login when the players connect again display only this:

[17:51:13] [Server thread/INFO]: /ipofplayer:61964 lost connection: Disconnected

**Comment by nathampa0909** [comment]
Error: http://prntscr.com/9zxg8e

**Comment by Shevchik** [comment]
After which build problem appears?

**Comment by frash23** [comment]
I've been getting this for a while but tracking down the exact cause took a while. I believe I've been having this since build 339, but it became more apparent after updating to the latest stable on SpigotMC, same issue on latest jenkins build as well.

**Comment by frash23** [comment]
I'm not getting the issue with ProtocolSupport removed, confirming this is related to my network setup, not ProtocolSupport.

Sorry for the inconvenience. I'll update the issue if I find a solution.

**Comment by frash23** [comment]
Oops, I had two ProtocolSupport jars in my plugins folder. Issue disappears when removing all ProtocolSupport related jars.

**Comment by nathampa0909** [comment]
For me the problem delays a time to appears. Can you test for 1 hour for example?

**Comment by Shevchik** [comment]
Hmm, it actually did not matter, problem is somewhere else

**Comment by Shevchik** [comment]
Enable protocolsupport debug and see if it dislays [address] connected with protocol version [version].

**Comment by frash23** [comment]
How would I go about enabling debug?

**Comment by frash23** [comment]
I thought I had tried that when I realized I forgot to install the jar back.

Debug is enabled:
`[22:11:42 INFO]: Enabled debug`
But absolutely no output happens when trying to log in with my alt (Zell0c).
Logging in with my main account works without a problem:
`[22:13:19 INFO]: /127.0.0.1:42150 connected with protocol version MINECRAFT_1_8`
Both accounts are using 1.8.

Does the localhost IP have anything to do with it? My PaperSpigot server is configured with `bungeecord: true`, as shown when I use /seen on a player (same as the one logging in above):
```
[22:14:24 INFO]: CONSOLE issued server command: /seen frash23
[22:14:24 INFO]: Player [~] frash23 has been online since 1 minute 4 seconds.
[22:14:24 INFO]:  - IP Address: /a.b.0.170
```

**Comment by Shevchik** [comment]
It may have, try disabling bungeecord for a moment and check if the issue persists.

**Comment by nathampa0909** [comment]
@Shevchik In this moment Im using build 360 and dont have this bug. I will test other builds for detect the problem, but I think is the build that your change the Compressor.

**Comment by Shevchik** [comment]
It should have at least display the connected message if the reason is compressor, because compression activates only after player login.

**Comment by nathampa0909** [comment]
The bug appears a time after server is on, the players try to enter but a time after in console appears ip of player: Disconnected and in client receice message of Read Time Out.

**Comment by Shevchik** [comment]
Which spigot build do you use?

**Comment by nathampa0909** [comment]
>ver
[11:26:35 INFO]: This server is running CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by frash23** [comment]
Running it raw without bungeecord does indeed seem to fix it; debug output:
```
[12:43:09 INFO]: /a.b.0.170:52954 connected with protocol version MINECRAFT_1_8
[12:43:10 INFO]: /a.b.0.170:52968 connected with protocol version MINECRAFT_1_8
```

Though removing bungeecord is not a viable solution for me.
I'm curious why IPs are showing up as localhost when using bungeecord despite it being set up correctly - maybe you need to hook into bungee to get the real IPs or something?

I'm curious if you have any lead on a fix for this and possibly a time estimate so I can know if I should just drop ProtocolSupport for now or wait for a fix.

**Comment by nathampa0909** [comment]
@frash23 Use build 360

**Comment by frash23** [comment]
Build 360 has the same problem for me.

**Comment by Shevchik** [comment]
They are showing as localhost because protocol is detected first and only after that handshake data is parsed.

**Comment by nathampa0909** [comment]
@frash23 I'm using build 360 and dont have any errors like the latest build.

**Comment by Shevchik** [comment]
Also try removing any plugins that can hook network too (Exept for protocollib, it works 100%).

**Comment by Shevchik** [comment]
Also join gitter chat. I will provide a debug version for that case

**Comment by jiongjionger** [comment]
Did you use SkinsRestorer? I have same issue with SkinsRestorer.

**Comment by nathampa0909** [comment]
I use SkinsRestorer.

**Comment by Shevchik** [comment]
Also try setting late bind to true and adding -Dprotocolsupport.nonblockingconection=true to your startup script. Then check the logs if it really uses non blocking connection now. After that try again and see if something changed.

**Comment by Shevchik** [comment]
Also i added initial data printing so you try to debug it now.

**Comment by Shevchik** [comment]
So?

**Comment by nathampa0909** [comment]
Shevchik I will test today and post results after.

**Comment by nathampa0909** [comment]
I enabled debug and all the time appers like this:

[18:41:38 INFO]: /177.21.85.44:53965 data: [27, 0, 47, 21, 112, 118, 112, 46, 106, 97, 105, 114, 111, 99, 114, 97, 102, 116, 46, 99, 111, 109, 46, 98, 114, 99, -35, 1, 1, 0]
[18:41:38 INFO]: /177.21.85.44:53965 is >= 1.7, checking data
[18:41:38 INFO]: /177.21.85.44:53965 data readable: 30
[18:41:38 INFO]: /177.21.85.44:53965 data need length: 27
[18:41:38 INFO]: /177.21.85.44:53965 data readable: 29
[18:41:38 INFO]: /177.21.85.44:53965 HS data: [0, 47, 21, 112, 118, 112, 46, 106, 97, 105, 114, 111, 99, 114, 97, 102, 116, 46, 99, 111, 109, 46, 98, 114, 99, -35, 1]
[18:41:38 INFO]: /177.21.85.44:53965 connected with protocol version MINECRAFT_1_8

**Comment by Shevchik** [comment]
Well, it did connect accroding to log. I need debug log from cases when connection failed.

**Comment by nathampa0909** [comment]
Strange, uptime of 3 hours and the problem don't appears yet.

**Comment by Shevchik** [comment]
So?

**Comment by swan201** [comment]
zzzz I can feel Shevchik angry, maybe he think 'My code is alright why this f..k isuue are not close?'

many mean in that word. "So?"

**Comment by nathampa0909** [comment]
@Shevchik The problem for me dissapeared.

@swan201 I think Shevchik is waiting the @frash23 post results.

**Comment by Shevchik** [comment]
Yep, still waiting for @frash123 response.

**Comment by Shevchik** [comment]
The error occurs when data is split between packets, for some reason readerIndex doesn't reset properly, so handshake decode fails. This only happens behind bungeecord because packets are large enough to be split. Will fix it as soon as i will find ou why reader index resetting doesn't work.

**Comment by nathampa0909** [comment]
Hello @Shevchik, yesterday occurred the bug of timed out and I turned on the debug: http://pastebin.com/6Cq1SYyV

**Comment by Shevchik** [comment]
I am able to reproduce this problem now, so i will be able to fix it soon.

**Comment by nathampa0909** [comment]
Ok, I will wait thanks for attention @Shevchik

**Comment by Shevchik** [comment]
Wow, found it out, that was really stupid mistake >_<.

**Comment by Shevchik** [comment]
Should be fixed now.

**Comment by frash23** [comment]
Hey, I've been in the hospital and unable to test for a while, seems like a legitimate fix though, will post results as soon as I get some.

**Comment by nathampa0909** [comment]
@Shevchik Im getting this errors: http://prnt.sc/a5w35v http://prnt.sc/a5w2xb

**Comment by Shevchik** [comment]
Disable native transport

**Comment by nathampa0909** [comment]
@Shevchik What is native transport?

**Comment by Shevchik** [comment]
use-native-transport is server.properties

**Comment by nathampa0909** [comment]
@Shevchik Yep, but what native transport make on server?

**Comment by Shevchik** [comment]
Uses epoll socket channel instead of nio one. Usually using epoll socket channel works better than nio (generates less GC pressure), but due to outdated netty version in server it doesn't fully work.

**Comment by nathampa0909** [comment]
@Shevchik Ok thanks for attention
