### ISSUE TITLE
[Bug] Random kicks | Gamemode issue

### ISSUE THREAD

**Issue by MrLolok** [ProtocolSupport/ProtocolSupport#1331]
People gets kicked randomly whit this error: https://pastebin.com/BSuGwe08

* ProtocolSupport version (/ps buildinfo)
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2021.04.14 at 19:10:02 MSK, buildhost: https://build.true-games.org, buildnumber: 604, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/66b494a8dd1e3e17bdc6a6d6b5535fe1013e973f)

* Server version
This server is running Yatopia version git-Yatopia-ver/1.16.5-88 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by Shevchik** [comment]
Something sends invalid data in player list packet.

**Comment by MrLolok** [comment]
Can I set a default gamemode for invalid gamemodes to prevent those errors?

**Comment by Shevchik** [comment]
No. There is no valid way to handle invalid packet. While it's possible to make PS drop such a packet, it's not the best way.
You will have to find a plugin that does that.
