### ISSUE TITLE
Arrow pickup sound

### ISSUE THREAD

**Issue by ludgart** [ProtocolSupport/ProtocolSupport#1332]
Hello,

if you pickup arrows on ground it dont play the pickup sound for 1.8.x clients.

Server version: 1.16.5 - Paper-629
ProtocolSupport: 604

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/ce1e3dbf56d796fa9f9ed00d5557c6e5c0835db1
