### ISSUE TITLE
1.16 Players can go under blocks with slabs

### ISSUE THREAD

**Issue by Redblock6YT** [ProtocolSupport/ProtocolSupport#1333]
* ProtocolSupport version: https://prnt.sc/12wddu8
* Server version: 1.16.5

![Screenshot_26](https://user-images.githubusercontent.com/37982990/118203099-581ebb80-b429-11eb-8419-1e4afe5be1fe.png)
![unknown](https://user-images.githubusercontent.com/37982990/118203116-6371e700-b429-11eb-8d85-ab1b819ff832.png)

**Comment by Shevchik** [comment]
Yes, this is minecraft feature.
