### ISSUE TITLE
ProtocolSupport Standalone

### ISSUE THREAD

**Issue by WolfyRed** [ProtocolSupport/ProtocolSupport#1335]
As a suggestion, I think a ProtocolSupport standalone/AAS version would be a nice addition!

**Comment by Shevchik** [comment]
Due to the nature of PS such a thing won't really make sense, since only one backend server version is supported.
So it's quite questionable if such a thing is worth spending time on.

**Comment by WolfyRed** [comment]
> 
> 
> Due to the nature of PS such a thing won't really make sense, since only one backend server version is supported.
> So it's quite questionable if such a thing is worth spending time on.

Yeah? It could only work on 1.16.5 servers then. -_-
