### ISSUE TITLE
Firework Rocket dont boosts Elytra

### ISSUE THREAD

**Issue by DerMagsch** [ProtocolSupport/ProtocolSupport#1339]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo)
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2021.06.21 at 17:30:01 MSK, buildhost: https://build.true-games.org, buildnumber: 629, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/9035ec07ac506f5e8d8f48e025e36e945e67d9ba)

* Server version
paper-1.17-39

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/1f9aec7c9d795ea7d6968a1172cb27aaa3696669
