### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by MarcinWieczorek** [ProtocolSupport/ProtocolSupport#134]
Why won't you use maven?
I want to use your plugins API and need a maven artifact.

**Comment by MrPowerGamerBR** [comment]
It was already suggested before, but Shevchik likes the way the build system is right now.

Also you could just set the JAR as a file dependency, no need for a repo/maven artifact.

**Comment by MarcinWieczorek** [comment]
Maven was made to build projects without jar files included in the source code files. I've already copied latest ProtocolSupport jar to my maven repo, tho I did it manually.
Well, that's a shame. Thanks.

**Comment by sgdc3** [comment]
+1 for maven xD

**Comment by sgdc3** [comment]
@Shevchik What's wrong with maven? At least use gradle but no ant, please!

**Comment by Shevchik** [comment]
Maven is partially good for managing build with multiple dependencies,  but definitely not in this case.

Gradle is better because you don't have to write stupid xml, but i don't have plans for migrating from ant to gradle right now.

**Comment by MarcinWieczorek** [comment]
You know you have to write one file (pom.xml) and it takes a few minutes? After that it is done. Plus you supply a maven repository for other programmers. Maven is very popular among bukkit plugins. Your plugin provides an API, that's one more reason to migrate.

**Comment by Shevchik** [comment]
And install maven support in my ide, change buildserver settings, setup nexus and more...

**Comment by sgdc3** [comment]
I'll send my pom ;)

**Comment by games647** [comment]
@Shevchik Do you still want gradle? If so, I would make an pull request for you. I really like to use this project as dependency with maven/gradle repository.

**Comment by Shevchik** [comment]
Yea, wanted to migrate to gradle long time ago, but never had time to learn it properly.
