### ISSUE TITLE
Bug with PingStatus in Serverlist

### ISSUE THREAD

**Issue by EncryptSL** [ProtocolSupport/ProtocolSupport#1341]
Bug in ProtocolSupport version 1.17-1-dev, Latest Version

![](https://cdn.discordapp.com/attachments/855063999620317195/859499439030272000/unknown.png)

Server works normal, with joining and anothers functions. Only serverlist show bad ping of server.

**Comment by Shevchik** [comment]
Found out how that happens. Will attempt to fix that soon.

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/5abbf4261616747cacd6d468683fbaade2731f46

**Comment by EncryptSL** [comment]
Another problem in latest version Water and Lava, Redstone no working. In some one chunks.

I don't know why.

**Comment by Shevchik** [comment]
Create a separate issue with a full description including screenshots/videos. PS doesn't affect anything serverside, and block not working is way too broad issue definition.
