### ISSUE TITLE
Bug with Redstone, Water, Lava and Explosions

### ISSUE THREAD

**Issue by EncryptSL** [ProtocolSupport/ProtocolSupport#1343]
PS BuildInfo: protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2021.07.03 at 04:28:57 MSK, buildhost: https://build.true-games.org, buildnumber: 633, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/5abbf4261616747cacd6d468683fbaade2731f46)

Server Version:  git-Paper-75 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: cc063e1)

Steps to reproduce:
World with seed: 8657731759031971681

Problem with redstone and water teleport to: overworld/world -> 1558 78 -196
Location where is not a problem with redstone and water: overworld/world -> 2343 64 144
Problem with lava and explosives: nether -> 21 14 -171

Videos of bugs: 
Problem with water and redstone: https://www.youtube.com/watch?v=9b0j5IlI4Bk
Location where is not a problem: https://youtu.be/I_JRXrW0G6E
Location in Nether problem with Lava and Explosives: https://www.youtube.com/watch?v=F_P2DYa-Z1M

**Comment by Shevchik** [comment]
Also test without protocolsupport. This doesn't seem a thing protocolsupport could affect.

**Comment by EncryptSL** [comment]
Without PS, water works and redstone and explosions working correctly but with latest version not

We are now using this build
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2021.06.26 at 02:19:25 MSK, buildhost: https://build.true-games.org, buildnumber: 631, buildgit: https://github.com/ProtocolSupport/ProtocolSupport/commit/eafe538e35b1b22c263b55c04783028e26b0863d)

And there is no problem.

**Comment by Shevchik** [comment]
The build 631 has broken multi block change, but for 1.17 is was passthrough. I guess decoding packet fails then, will look into that.

**Comment by Shevchik** [comment]
Should be fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/c36a0f554a2ce9e3bfbc81e791a859b95a37ac5a

**Comment by EncryptSL** [comment]
I can confirm, fixed.
