### ISSUE TITLE
Shulker animation bug

### ISSUE THREAD

**Issue by EncryptSL** [ProtocolSupport/ProtocolSupport#1347]
Shulkers have bug with open animation.

Server version: git-Paper-98 (MC: 1.17.1)

Ps Build: [buildtime=2021.07.10 at 01:16:10 MSK, buildhost=https://build.true-games.org, buildnumber=639, buildgit=https://github.com/ProtocolSupport/ProtocolSupport/commit/2dffa9c9db8bc659fc3f63f386a437663453e619]

Without PS working

Bug with shulker here: https://youtu.be/bgQgUuIAq5U

**Comment by Shevchik** [comment]
It seems that attachment pos shulker metadata field was removed in 1.17, so a shift in ids caused PS to pick up wrong metadata.

**Comment by Shevchik** [comment]
Should be fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/245c32767502a281852c46d0c95068c49c95b3ae

**Comment by EncryptSL** [comment]
Seems fixed.
