### ISSUE TITLE
Dissconected

### ISSUE THREAD

**Issue by FunnyCraft** [ProtocolSupport/ProtocolSupport#135]
Привет, игрок спокойно играет и вылетает Disconnected, и войти нельзя.
Это уже продолжается 3 месяца, каждый день по 1-3 игрока вылетает, и
им приходится менять свой ник, так же можно войти и под аккаунтом
где пишет Dissconected но нужно изменить ip адресс, это проблема
наблюдается не только на моем сервере, а еще на многих серверах
собственно это и сподвигло меня написать сюда.
Когда убераю PS, то все спокойно входит без всяких Disconnected.
https://pp.vk.me/c628430/v628430630/48b72/i1gQBnxO0YI.jpg

**Comment by Shevchik** [comment]
Enable debug and check log, there should be an error then.

**Comment by FunnyCraft** [comment]
Хорошо, сейчас же попробую это сделать.

**Comment by FunnyCraft** [comment]
а где включать дебаг? нету же папки с конфигом.

**Comment by Shevchik** [comment]
Read wiki

**Comment by FunnyCraft** [comment]
дай ссылку пожалуйста

**Comment by FunnyCraft** [comment]
еще одно возможно тебе нужно это знать, когда я пытаюсь
в консоли нету даже намека на мой вход, что я пытаюсь присоединится.

**Comment by Shevchik** [comment]
Then it is duplicate of
https://github.com/ProtocolSupport/ProtocolSupport/issues/133

**Comment by FunnyCraft** [comment]
Можете написать сюда решения этой проблемы, пожалуйста.

**Comment by Shevchik** [comment]
It is not solved yet.

**Comment by FunnyCraft** [comment]
Это серьезная проблема, тут либо вы исправляете, либо нужно удалять.
Потому что я так стремительно теряю игроков, сегодня поступило порядка 10 жалоб.

**Comment by FunnyCraft** [comment]
Вот мой лог с дебага http://pastebin.com/u8R4srBP

**Comment by Shevchik** [comment]
Hmm, that log explains something, but still not sure why it happens.

**Comment by FunnyCraft** [comment]
Если я со своей стороны смогу чем-то помочь, то я помогу, может я смогу еще что-то сделать?
