### ISSUE TITLE
Invisible Players on Higher Versions.

### ISSUE THREAD

**Issue by the5gi** [ProtocolSupport/ProtocolSupport#1351]
Problem Where Players Are Invisible on higher versions.

Say your on 1.17.1: You cant see Players on lower versions but you can see other 1.17.1 players.
Say your on 1.8: You can see all players above your version and 1.8 players but not lower.

1.8 POV
![image](https://user-images.githubusercontent.com/86175493/126885695-143a710c-de4b-49a3-bdff-c576345c2297.png)

1.17.1 POV:
![image](https://user-images.githubusercontent.com/86175493/126885704-56c3d6f4-0b3e-4b47-87ee-bce367cfe7b0.png)

Not sure why this occurs. I think its a problem with TAB from NEZNAMY but it could be support issues.

NOTE:   !_5gi and Sooigee are on 1.8.9!       !AvaHappy is on 1.17.1!

**Comment by cmod31** [comment]
not invisible they move and make sounds but their skin doesn't move from where they joined and when you hit the skin they still get the damage

**Comment by Shevchik** [comment]
Make sure you tested it without all other plugins first. That sometimes happens because of plugins that use network entities in an invalid way (SkinsRestorer is one such example).

**Comment by cmod31** [comment]
Oh yeah then it should be skin restorer but when i used fastlogin skin forwarding it overwrites the floodgate skin forwarding but then its not your problem

**Comment by xknat** [comment]
> Oh yeah then it should be skin restorer but when i used fastlogin skin forwarding it overwrites the floodgate skin forwarding but then its not your problem.
> Edit: i told them maybe someone could reply

Did you disable fastlogin forward skin option?
Hmmm, maybe we should give more aggressive warnings about that

**Comment by cmod31** [comment]
I disabled the forwarding skin option from fastlogin so Skinrestorer is my only option and also because my friends with cracked want skins

**Comment by cmod31** [comment]
Why was it closed its an issue with both Skinrestorer and protocolsupport or we bring that issue to the Skinrestorer github doesn't matter
