### ISSUE TITLE
I have a plugin for non-standard enchantments, your plugin throws the player with such items to the server and does not allow him to enter.

### ISSUE THREAD

**Issue by FrukTik** [ProtocolSupport/ProtocolSupport#1354]
Hi.
I have a plugin for non-standard enchantments, your plugin throws the player with such items to the server and does not allow him to enter.
How to fix?
lost connection: Internal Exception: java.lang.IllegalArgumentException: Missing enchantment Enchantment[minecraft:haste, HASTE] legacy id

Kicks if I'm using a client version other than 1.17.1

**Comment by Shevchik** [comment]
Non standard enchantments are now removed from itemstack.
Technically it's up to the plugin that does hack in enchants to remove that, so while it works right now, there is no guarantee it won't break later.
