### ISSUE TITLE
Question - Feature request

### ISSUE THREAD

**Issue by EncryptSL** [ProtocolSupport/ProtocolSupport#1356]
Hello, i have question your plugin ProtocolSupport is great but is possible create separate plugin like a API for only PlayerLoginStartEvent, and PlayerProfileCompleteEvent with another functions what need this events.

Because i using only this plugin for easy setOnlineMode for players.

You can create this please i know there is source but your plugin is massive with another functions. I don't know how working, but you know.

Thanks you.

**Comment by Shevchik** [comment]
It is possible to create an API impl only version of PS, but yet again, i have no time for that.
