### ISSUE TITLE
ProtocolSupport fps dropping for 1.8 users

### ISSUE THREAD

**Issue by pabloalba16** [ProtocolSupport/ProtocolSupport#1363]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`![image](https://user-images.githubusercontent.com/49927979/137598079-02c96fbd-f75d-4bec-8959-b94013bbccdd.png)`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (
![image](https://user-images.githubusercontent.com/49927979/137598576-1aaa3aa6-4edc-4afb-86b3-aed5a9cff4fe.png)
)
* Server version (![image](https://user-images.githubusercontent.com/49927979/137598531-df53502d-5a65-40a0-8283-d161d04468bc.png))

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

My issue with ProtocolSupport is that im using kitbattle plugin and when i respawn in the 1.8 cient version, my fps starts to drop to literally 1 or 2 for 5-10 seconds. This happens every time i respawn and its so annoying. Here's a video where you can see it more clearly: https://streamable.com/thjg36

**Comment by pabloalba16** [comment]
Plugins used: 
![image](https://user-images.githubusercontent.com/49927979/137598604-b370557e-771e-49f7-b86f-cd8a8597ec26.png)

**Comment by Shevchik** [comment]
Capture a video with client debug menu open (along with profiler + frame time graph) when this happens.

**Comment by pabloalba16** [comment]
How to do that??

**Comment by pabloalba16** [comment]
https://streamable.com/50cslp

**Comment by pabloalba16** [comment]
Where is the profier saved?? i can't find it

**Comment by Shevchik** [comment]
See https://github.com/ProtocolSupport/ProtocolSupport/issues/1369
