### ISSUE TITLE
bug with shift-clicking any slot

### ISSUE THREAD

**Issue by hswhsw610** [ProtocolSupport/ProtocolSupport#1367]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/ (`/ps buildinfo`)
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)
* Check if the issue isn't listed as a won't fix on the project page.
* Please report PE-related issues to https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues for now!

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

When posting the issue you also need to provide the following information:

* ProtocolSupport version (/ps buildinfo)
![image](https://user-images.githubusercontent.com/48399282/139583022-f73910df-b22b-4098-9dd5-2561111fe80e.png)
* Server version
![image](https://user-images.githubusercontent.com/48399282/139583042-fba033e3-4cb8-4d99-b987-fa10d7d3af60.png)

If you fail to check the above and provide necessary information, your issue will be closed. Otherwise we're glad to help :-)

if i shift-click any slot, i get kicked by follwing message:
![image](https://user-images.githubusercontent.com/48399282/139583015-8eb58044-4a3b-4848-bc57-d65c5e41f602.png)

**Comment by Shevchik** [comment]
Fixed by https://github.com/ProtocolSupport/ProtocolSupport/commit/8264c9ab9cb34b2e153c48aa883a8e29f456f277

**Comment by hswhsw610** [comment]
ok solved
