### ISSUE TITLE
Inventory drop visual bug

### ISSUE THREAD

**Issue by hswhsw610** [ProtocolSupport/ProtocolSupport#1368]
yes im using latest everything like i said in previous issue.

ok so it seems this issue #1358 is happening again. if i join 1.17 server that has protocolsupport with 1.8 client, and drop any item with 'q' key, it drops but not removed from inv

**Comment by hswhsw610** [comment]
bump??

**Comment by Shevchik** [comment]
That shouldn't really happen, i see no reason why it wouldn't work now. Can you please provide a video on how exactly does it happen in your case, maybe i'm missing something.

**Comment by hswhsw610** [comment]
ok when i have some time

**Comment by VytskaLT** [comment]
Same issue, here is a video:
https://user-images.githubusercontent.com/35194709/141683506-88903219-3f24-4366-82c2-7a3a3babca3e.mp4

**Comment by Shevchik** [comment]
Please create a full copy of your server and send it to me. Something obscure is happening there, because the hand slot is updated on item drop event.

**Comment by VytskaLT** [comment]
> Please create a full copy of your server and send it to me. Something obscure is happening there, because the hand slot is updated on item drop event. (Maybe the event is cancelled and item is dropped manually, or item isn't updated before firing the event).

I just created a new server, with the latest PaperMC version and ProtocolSupport 1.17.1-1. Didn't change any configs, the bug is still here (even with a vanilla 1.8.9 client). I can send you the server folder if you still want it.

**Comment by hswhsw610** [comment]
ok closed
