### ISSUE TITLE
1.18 height change (pre-issue in the coming  1.18 release)

### ISSUE THREAD

**Issue by bes-ptah** [ProtocolSupport/ProtocolSupport#1370]
**This has nothing to do with the ProtocolSupport Plugin _right now,_ though I have question for ProtocolSupport; will the anticipated Minecraft 1.18 that has 320 blocks be supported in older versions through 1.4.7?**

**Comment by Shevchik** [comment]
Height change is 1.17 feature, 1.18 only adds the generator. And no, those versions wont see extended height.

**Comment by Seshpenguin** [comment]
> Height change is 1.17 feature, 1.18 only adds the generator. And no, those versions wont see extended height.

Should ProtocolSupport handle the void a little more gracefully perhaps? Right now if you dig to y=0, you'll "fall" into the void, but actually just get stuck clipped in the block that is actually there.
Maybe PS should have add a fake layer of bedrock there so those users wont get stuck.

**Comment by Shevchik** [comment]
Maybe, but that won't solve the problem of teleporting to -y locations. And i don't like the idea of implementing hardcoded solutions in the PS core itself, maybe that's a thing for PSLS. Also you can get client protocol version and acts from there in the outside plugin anyway.
