### ISSUE TITLE
Panda animation bug

### ISSUE THREAD

**Issue by EncryptSL** [ProtocolSupport/ProtocolSupport#1371]
**Actual Behaviour:** When player click on panda with bamboo second time, panda no sit on ground and not eat bamboo.

**Expected Behaviour:** When player click on panda with bamboo second time, panda sits on ground and eat bamboo. 
![2021-11-22_06 35 42](https://user-images.githubusercontent.com/9441083/142807055-c78e38cc-1b4b-4722-b6e6-1dbebbd24411.png)

Also this was tested with PS and without PS.
Result without PS animation working.

**Ps Build info:** [buildtime=2021.11.18 at 02:05:04 MSK, buildhost=https://build.true-games.org, buildnumber=661, buildgit=https://github.com/ProtocolSupport/ProtocolSupport/commit/aed01898d769701d07a3a66ad55b8524d9937e55]

Server version: This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)

Plugins: ProtocolSupport

**Comment by Shevchik** [comment]
Which client versions are affected?

**Comment by EncryptSL** [comment]
Bug not confirmed on versions 1.14.x, 1.15,x, 1.16.x
Bug is on 1.17.x
