### ISSUE TITLE
Entity freezing ,  Very High ping, Entities invisible

### ISSUE THREAD

**Issue by Swapneel665** [ProtocolSupport/ProtocolSupport#1375]
I am having problems with entities becoming invisible , freezing and very high ping even though I am next to my router 
Uname -a output
Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Mon Oct 25 00:28:34 CDT 2021 aarch64 aarch64 aarch64 GNU/Linux
Server files:
https://drive.google.com/folderview?id=1WuMyMWpyEwm6VI7dp308FkF2EGVT01Qe

**Comment by Shevchik** [comment]
Remove SkinsRestorer
