### ISSUE TITLE
< 1.18 Tile Entities don't remap correctly

### ISSUE THREAD

**Issue by smurfsmurfy** [ProtocolSupport/ProtocolSupport#1376]
Latest Purpur / Paper
PS version: [buildtime=2021.12.11 at 00:46:19 MSK, buildhost=https://build.true-games.org, buildnumber=665, buildgit=https://github.com/ProtocolSupport/ProtocolSupport/commit/e81aacf0432c9d213ed9574ed8fd4cac1289af7c]

As title says on 1.18 everything works fine of course, on 1.17 and below the skulls don't set the textures correctly when updating block state, unless you refresh the chunk & on 1.8 they don't even remap at all just skeleton heads? When looking into the issue I found that TileEntities network id's aren't updated to 1.18 but even then the issue still persists

1.16 / 1.17
![example](https://user-images.githubusercontent.com/95298930/148488874-9f426d0a-9b7d-4874-a8f0-caab7b22277b.png)

1.8
![example2](https://user-images.githubusercontent.com/95298930/148488876-a38d1522-3ed9-49df-8f2f-267cf62bd7aa.png)

**Comment by Shevchik** [comment]
If that happens only on tile data update, i guess i screwed up encoding tile data somewhere.

**Comment by smurfsmurfy** [comment]
Seems only when updating the tile, + the issue on 1.8 where they don't update ever and only showing the default skull block (skele) rotation doesn't update as well
