### ISSUE TITLE
Problem with custom Banners

### ISSUE THREAD

**Issue by EncryptSL** [ProtocolSupport/ProtocolSupport#1377]
Hello i found visual bug with banners, also tested without PS.

**Server Version:** 
This server is running Paper version git-Paper-145 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 3ea224d)
You are running the latest version
Previous version: git-Paper-137 (MC: 1.18.1)

**Ps Build:**
[buildtime=2021.12.11 at 00:46:19 MSK, buildhost=https://build.true-games.org, buildnumber=665, buildgit=https://github.com/ProtocolSupport/ProtocolSupport/commit/e81aacf0432c9d213ed9574ed8fd4cac1289af7c]

**Steps to reproduction**
You can craft banner with custom colors like a flag, for this example i craft flag of Czech Republic in loom.
When i placed banner on block, seems good but when you reconnect banner was replaced on white banner but after destroy in survival mode was dropped like a flag with same style when was crafted.

Same for Ominous Banner in pillager outpost.
When you copy flag in creative mode flag was white.

**Images to bug**
![2022-01-11_01 00 41](https://user-images.githubusercontent.com/9441083/148859149-fba37efa-fc81-467f-b581-ce6825d28920.png)
![2022-01-11_01 01 00](https://user-images.githubusercontent.com/9441083/148859155-0d468865-575d-480e-96db-70d11f61c0c9.png)

**Comment by Shevchik** [comment]
Whick client version is that? Might be related to https://github.com/ProtocolSupport/ProtocolSupport/issues/1376

**Comment by EncryptSL** [comment]
Tested on client version 1.18.1.
I tested now on 1.17.1 and bug not in this version.

**Comment by Shevchik** [comment]
Huh, so i screwed up everywhere, lol.

**Comment by EncryptSL** [comment]
Any news ?

**Comment by Doctacosa** [comment]
I haven't seen an update on this issue, but commit #[3c0fa27](https://github.com/ProtocolSupport/ProtocolSupport/commit/3c0fa271f6ca2e43d551750b36fe146523c23099) fixed this for me. Thanks!

**Comment by EncryptSL** [comment]
Yeah banners fixed
