### ISSUE TITLE
Please fix declare command packet :C

### ISSUE THREAD

**Issue by frog-commits** [ProtocolSupport/ProtocolSupport#1379]
Using the latest Purpur (fork of Paper) & ProtocolSupport

As the title states, this whole commands not working on any other version but the latest is just kind of an annoyance. I only ask for an update on when the packet will be properly handled for the latest changes of 1.18.2 and downscaled to support any other version? Thanks @Shevchik for all the hard work you do to keep supporting the latest versions.

![image](https://user-images.githubusercontent.com/95298930/160927036-1440adf6-83ad-4c4e-b46f-c8aab4e3dd1d.png)

**Comment by smurfsmurfy** [comment]
Any update?? ☹

**Comment by EncryptSL** [comment]
I think author is in time press.

**Comment by Shevchik** [comment]
Fixed in https://github.com/ProtocolSupport/ProtocolSupport/commit/1c6039b55e66b6da65a6ffa07f889c9fe3301c79

**Comment by frog-commits** [comment]
> Fixed in [1c6039b](https://github.com/ProtocolSupport/ProtocolSupport/commit/1c6039b55e66b6da65a6ffa07f889c9fe3301c79)

Ty so much, you're a beast
