### ISSUE TITLE
Jitpack don't find the build

### ISSUE THREAD

**Issue by Elikill58** [ProtocolSupport/ProtocolSupport#1381]
I was supporting ProtocolSupport, thanks to jitpack. But it breaked because it can't find the output. Example with actual latest commit `Disable command declare for now`: https://jitpack.io/com/github/ProtocolSupport/ProtocolSupport/1be3c57be3/build.log.

The last one that was successful seems to be : https://jitpack.io/com/github/ProtocolSupport/ProtocolSupport/master-ce24924c0e-1/build.log

Can you fix it, to make it easier to use ? (or upload to own repo if you have)

**Comment by Shevchik** [comment]
Seems that the BuildTools run for whatever reason completely ignores mavens opts, which results in spigot throwing all the maven garbage inside the main .m2 folder

**Comment by Elikill58** [comment]
This project is abandonned. I just stop support for it.
