### ISSUE TITLE
Holding shield in primary hand causes severe graphical glitches for 1.8 clients

### ISSUE THREAD

**Issue by Plazmaz** [ProtocolSupport/ProtocolSupport#139]
Shields should not be sent when held by 1.9 clients, as it causes extreme graphical glitches for 1.8 users.
[Example](https://i.gyazo.com/19a33703265c66aa5941e9bdf70e1cd3.jpg)

**Comment by Plazmaz** [comment]
Actually this occurs with any 1.9 item.

**Comment by Shevchik** [comment]
There is no remapping for new blocks and items. Other issues have the same reason.

**Comment by Plazmaz** [comment]
Will there be support added for this? Or is this something out of scope?

**Comment by Shevchik** [comment]
It will be, but later. Most items can be mapped to whatever comes in mind first, but it is not the same for blocks, you have to account to their sizes, passability and break speed.
