### ISSUE TITLE
Can't switch to empty inventory slot in 1.8 client

### ISSUE THREAD

**Issue by Plazmaz** [ProtocolSupport/ProtocolSupport#140]
When switching to an empty inventory slot in 1.8, it renders and acts as if you were holding the last item in your hand that was not an empty slot. For instance, if I am holding sand, then switch to an empty slot, sand is placed when I right click. This appears to occur randomly.

**Comment by Shevchik** [comment]
Test again, maybe it is fixed now

**Comment by Shevchik** [comment]
Test again, maybe it is fixed now
