### ISSUE TITLE
BungeeTabListPlus broken in 1.9

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#143]
We have a HexagonMC Bungee Server (the 1.7-1.9 one) and we use BungeeTabsListPlus 2.4.1 with BukkitBridge on all servers, the Hub Server is 1.9 with protocolsupport (all others are 1.8 with ProtocolSupport)  This means 1.9 players can join hub but no other servers and this works, however when you join hub in 1.9 you get the default tab list and when you leave your name stays in the tab list even if you have left and if you rejoin theres 2 names in tab list, then if you rejoin again 3 names etc etc.  Since this is a 1.9 only bug and not 1.8 bug, it could be related to ProtocolSupport...

**Comment by Shevchik** [comment]
ProtocolSupport doesn't modify 1.9 packets, so the problem is most likely on bungee side.

**Comment by Tom-III** [comment]
This has been fixed by BTLP Author, issue can be closed.
