### ISSUE TITLE
Chunks not rendering in 1.8.x

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#145]
Using latest version of ProtocolSupport from Jenkins, latest PSB from Jenkins and 1.7-1.9 BungeeCord when I join the 1.9 server in 1.8 I can't see chunks.  In 1.9 and 1.7.10 they appear fine and instantly.
![Invisible Chunks](http://i.imgur.com/wUWEdMF.png)

No errors in the console or anything, breaking a block in the invisible area makes it appear.  Also the blocks ARE solid in the invisible area which means they are loaded in memory just not displayed.  The world is generated in 1.9 and was generated recently, so no corruption.  (Tried regenerating another world, same problem)

**Comment by Shevchik** [comment]
The intresting thing is that you can walk in, break block and it will start to display again.

**Comment by Tom-III** [comment]
Yes, maybe its something to do with the way the initial chunks are sent cause if you walk to a new region the chunks are fine.  Another effect is Downloading Terrain... seems to take a bit longer in 1.8 than 1.7/1.9.  I think it might have to do with the timing of packets, like adding a 1 tick delay somewhere.

**Comment by nathampa0909** [comment]
[Imgur](http://i.imgur.com/SdWNtsm.gifv)

**Comment by Shevchik** [comment]
Does it still happen?

**Comment by nathampa0909** [comment]
Fixed. If error continue appears you should update the chunk for it reload again (Just walk or fly far and back to the bugged chunk and it fixed).

**Comment by BestMark** [comment]
Reopen this issue. I have this bug using 1.8.x versions on 1.10.2 server.
Latest build of ProtocolSupport, PaperSpigot core.
