### ISSUE TITLE
Config option to block certain client versions from joining

### ISSUE THREAD

**Issue by i9hdkill** [ProtocolSupport/ProtocolSupport#149]
Hi,
we are using a protocolhack 1.7.10/1.8 and a 1.9 lobby. However we want to move to clean 1.7.10 lobby and a 1.9 lobby with protocolsupport.
Because holograms are not working for 1.7 clients, we want to block access with 1.7 to the new 1.9 lobby.
With this in mind, a config option to disable support for some clientversions would be a great addition.

**Comment by MrPowerGamerBR** [comment]
I think that was already suggested before, and @Shevchik said he won't implement it because you can block other clients from joining by just using the ProtocolSupport API + a plugin
