### ISSUE TITLE
[1.4.7] No block place sound and other issues

### ISSUE THREAD

**Issue by kangarko** [ProtocolSupport/ProtocolSupport#150]
Hello,

I recently noticed that with 1.4.7 and running build #436:
**a)** Block place sound is not sent to the client.
**b)** If the gamerule doDaylightCycle is to false, and the time is set to example 1000, the sky is flickering.
**c)** Chest inventories have no name.
**d)** Cannot use spawn eggs (?)
**e)** I can visually break a command block (walking into it will push the player away) and when rejoin the command block is back.

Thank you for looking into it and I appreciate your work.

Sincerely,
kangarko

**Comment by Shevchik** [comment]
a) Should now work
b) 1.4.7 doesn't have a negative time functionality, so can't be fixed
c) Still didn't test it
d) Don't get items from creative on < latest client, that won't work nost of the time
e) The reason is different breaking speeds i think, can't be fixed right now.

**Comment by Shevchik** [comment]
Fix chest inventory names

**Comment by kangarko** [comment]
Thank you much. Just donated something to you, hopefully it will arrive successfully, haha.
