### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Xayanix** [ProtocolSupport/ProtocolSupport#152]
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoSuchFieldError: FROSTED_ICE

Lost connection with that exception and cant join anymore.

**Comment by Shevchik** [comment]
Are not using latest spigot 1.9 build.

**Comment by Xayanix** [comment]
Why logging in is taking so long (at Downloading terrain), then i can see that: http://scr.hu/0duk/xfews

**Comment by Shevchik** [comment]
See other issue
