### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Johandrex** [ProtocolSupport/ProtocolSupport#153]
This plugin is causing my Creative server to crash after 3-10 minutes, my other servers are fine though. (use-native-transport is set to disabled)

**Comment by Shevchik** [comment]
Need a crash log

**Comment by Johandrex** [comment]
There's not really any crash logs. When the plugin is enabled the server lags insanely much until it stops responding. When the plugin isn't enabled it's fine though.

**Comment by Shevchik** [comment]
Then i need a timings or any profiler report.
