### ISSUE TITLE
World changes

### ISSUE THREAD

**Issue by AshourAziz** [ProtocolSupport/ProtocolSupport#154]
Hello,
    It seems when running the latest spigot build changing worlds sometimes bugs out and disconnects the user.

There is no errors whatsoever, and native transport is indeed disabled.

If the client moves onto a 1.9 version, the issue is gone and switching to different worlds other then the main one has no problems.

I cannot find any errors which is very puzzling.

**Comment by AshourAziz** [comment]
Seems like I found an error when I stripped this down to our test platform.
pastebin.com/KFaxVyvS

Only happens when ProtocolSupport is installed, and on the test platform it's happening across all worlds. 

*Issues only appears for 1.8 clients*

**Comment by Shevchik** [comment]
Latest spigot changed how reading arrays work. Will fix it, but not any time soon.
