### ISSUE TITLE
Potions (1.9 server, 1.8 client)

### ISSUE THREAD

**Issue by thekeenant** [ProtocolSupport/ProtocolSupport#155]
I'm not sure what the status of this project is, but on a 1.9 server, 1.8 users (and older) cannot throw splash potions. They are removed from the inventory and replaced with a glass bottle.

**Comment by Zoiter7** [comment]
In the last, are ALL potions replaced with a water glass bottle. Wait a answer from dev

**Comment by Shevchik** [comment]
Potions should now display normally.

But they still won't work in creative, i won't fix that anytime soon.
