### ISSUE TITLE
exception when joining with 1.9 to a 1.9.2 spigot server

### ISSUE THREAD

**Issue by i9hdkill** [ProtocolSupport/ProtocolSupport#156]
`This server is running CraftBukkit version git-Spigot-1480adb-8b61cc5 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)`

`ProtocolSupport v4.23.dev Build 439`

No errors beside this one:
`I9hdkill[/95.91.230.159:58378] logged in with entity id 338 at ([advlobby]47.41685873553708, 66.0, -35.63285508716787)
[01:51:19] [Server thread/INFO]: I9hdkill lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.`
But I am aware that this one does not help you. But at least I wanna notice you that this does not work at the moment. If I disable Protocolsupport, I can join normally.
We are using BungeeCord
Also happens when joining with 1.8.9 and 1.9.2

**Comment by James137137** [comment]
i'm also getting an error: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: protocolsupport.protocol.PacketDataSerializer.b(I)Lnet/minecraft/server/v1_9_R1/PacketDataSerializer;

**Comment by James137137** [comment]
nvm fixed now. (seems you have to use a spigot 1.9 jar

**Comment by Shevchik** [comment]
Enable debug and post full exception

**Comment by i9hdkill** [comment]
You mean debug by doing /debug start?
Does not output any exceptions

**Comment by i9hdkill** [comment]
http://pastebin.com/npKFLsAn

**Comment by i9hdkill** [comment]
It works, thank you
