### ISSUE TITLE
disconnect when switchting with a 1.8.9 client from a 1.8.8 to 1.9.2 server (BungeeCord)

### ISSUE THREAD

**Issue by i9hdkill** [ProtocolSupport/ProtocolSupport#157]
Setup:
BungeeCord 1.7.10-1.9
Server1: 1.8.8 spigot
Server2: 1.9.2 spigot + Protocolsupport Build 443
Client: 1.8.9

When switching from Server1 to Server2 I am getting a disconnect:
http://pastebin.com/Z17vTMnV
When rejoining it's fine. This discoonect only appears when switching

**Comment by Tom-III** [comment]
try using protocolsupport on the 1.8.8 server

**Comment by i9hdkill** [comment]
Couldn't try it yet, but we are not using protocolsupportbungee.
So I don't think protocolsupport should be on the 1.8.8 server.
Will try later

**Comment by Tom-III** [comment]
Please try using protocolsupport on all your systems so your connections are handled properly

**Comment by i9hdkill** [comment]
Might be quitre ugly, because on some 1.8.8 servers is viaversion installed

**Comment by Tom-III** [comment]
ViaVersion and protocolsupport work nicely, make sure you use the HexagonMC 1.7-1.9 bungeecord and latest ProtocolSupportBungee and it will work, we have it setup that way on SkyPrison

**Comment by Shevchik** [comment]
Update to latest ProtocolSupport and try again, new error log will tell what's wrong.

**Comment by i9hdkill** [comment]
Thanks, updated to 479 and testing now. Couldn't reproduce it though. I will get in touch if I experience this issue again.

**Comment by TiTo-418** [comment]
@Tom-III 
> ViaVersion and protocolsupport work nicely

What do you mean? I always get kicked for "Unsupported protocol version 107"
