### ISSUE TITLE
1.9 block breaking and signs

### ISSUE THREAD

**Issue by ziutekkk** [ProtocolSupport/ProtocolSupport#160]
Hey
I use:
 This server is running CraftBukkit version git-Spigot-f6feaaa-f326992 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)
and
ProtocolSupportMCPE dev build #30 

Here are my bugs:
1) When player is logged via MCPE and breaks any block, he get kicked with this "255" message:
[15:45:22 INFO]: Player lost connection: 255

2) When someone places sign with set text on PC version, the text is not visible on MCPE.
Also when Player on MCPE tries place sign with text, he gets kicked with " Packet id 189 doesn't exist" message:
[15:42:23 INFO]: Player lost connection: Packet id 189 doesn't exist

I had no other plugins installed when I replicated those bugs.
I know its early version of 1.9.2 compatibility, but it may help to fix some things.
Thanks. Great plugin

**Comment by TroniQ89** [comment]
I agree.
When I try to destroy a block in MCPE, "255"...

Multiverse is working VERY well with MCPE.

Too, players on MCPE can't ride a Minecart or a boat, but they're inside the Minecart/Boat for MCPC players.
I am running latest Spigot version. 
I tried with PaperSpigot too, same thing.

**Comment by Shevchik** [comment]
Closing this issue because mcpe branch will be rewritten from scratch.
