### ISSUE TITLE
1.8 Resourcepack

### ISSUE THREAD

**Issue by File14** [ProtocolSupport/ProtocolSupport#162]
Hello!

I'm running a spigot server on 1.9.2. It's a resourcepack on that server that is being sent. On 1.9 clients it works without getting kicked. But if I use 1.8.9 I get kicked. What is causing this?  There must be a bug in your plugin.

I'm using the ProtcolSupport with buld 461.

**Comment by Tom-III** [comment]
Maybe it needs a way to send different resource packs depending on the client version?

**Comment by File14** [comment]
No, I'm running Viaversion on my 1.8 servers to allow 1.9 clients, and 1.9 users don't crash when they get the resourcepack.

**Comment by Shevchik** [comment]
It's most likely a bug in how i send resource pack, i actually never tested if it really works. Will check it next week.

**Comment by File14** [comment]
Okay, thanks a lot!

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by File14** [comment]
In what build? 463?

**Comment by File14** [comment]
I can confirm that it's fixed in build 463.

--Close Thread--
