### ISSUE TITLE
Creative mode on MCPE is not working perfectly

### ISSUE THREAD

**Issue by TroniQ89** [ProtocolSupport/ProtocolSupport#164]
Hi,

In MCPE, the Creative inventory is totaly empty, and there is problem while trying to break blocks (in Creative and survival) : In creative, block instantly reappear and in Survival the block is broken for the client, but not for the server (mobs can walk on...)

Thank you.

**Comment by Shevchik** [comment]
It works, but looks like you are trying to break block not at the middle of the screen or outside the pc reach distance.

**Comment by Shevchik** [comment]
Closing this issue because mcpe branch will be rewritten from scratch.
