### ISSUE TITLE
Lost connection caused by menu inventory

### ISSUE THREAD

**Issue by mariolars** [ProtocolSupport/ProtocolSupport#168]
Players on 1.7.10 are kicked after opening menu inventory. Only this message appear : 
`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(81) + length(1) exceeds writerIndex(81): UnpooledHeapByteBuf(ridx: 81, widx: 81, cap: 81)
`
BungeeCord : Hexagonmc build 59
Spigot: git-Spigot-4af49dc-23da8b0
ProtocolSupport build 507
ChestCommands v3.1.4 | v3.1.2 happens on both versions

**Comment by Shevchik** [comment]
Unable to reproduce, what is your server address so i can join it and test?

**Comment by mariolars** [comment]
178.33.49.29

**Comment by Shevchik** [comment]
This is a serverside error, enable debug and post full exception.

**Comment by mariolars** [comment]
http://pastebin.com/csVxHkRY

**Comment by Shevchik** [comment]
Try now

**Comment by mariolars** [comment]
All menus work now. Thank you. 
I found two new bugs but unfortunetly i'm not 100% sure if it is protocolsupport fault. InteractEvent is not fired when someone right click block. Second bug is when player puts block and event is canceled the block visually is not back to the inventory but appear only when you try to store something to the slot where the block was.
