### ISSUE TITLE
Disconnect when joining with 1.8 client on a 1.9.4 server ProtocolSupport Build 512

### ISSUE THREAD

**Issue by i9hdkill** [ProtocolSupport/ProtocolSupport#170]
Getting this error when the player joins:
http://pastebin.com/DF2d8Ypm

Must be something on his plot (survivalmode)

**Comment by Shevchik** [comment]
Some entity which is remapped wrongly, will add more debug info to exception later, so we can find out what entity causes this.

**Comment by Shevchik** [comment]
Try now, it should print more info.

**Comment by i9hdkill** [comment]
Thanks. Teleported to the location were the player got the disconnect, but the client isn't crashed. Looks like the entity despawned. I will let you know if I experience this disconnect again.

**Comment by i9hdkill** [comment]
It was an iron golem:
http://pastebin.com/BADyfdG8

**Comment by Shevchik** [comment]
In the server code this value index is a byte, do you have any plugins, that can modify entity metadata on the fly?

**Comment by i9hdkill** [comment]
In this case it might be SonarPet(EchoPet).
Just wondering, as 8 other pets are working fine.
