### ISSUE TITLE
Can't move on lilypads

### ISSUE THREAD

**Issue by mariolars** [ProtocolSupport/ProtocolSupport#172]
Players with 1.8 can't move on lilypads. Sometimes in console there is a message : "nicname" moved wrongly.

git-Spigot-4af49dc-4e19de1
ProtocolSupport #513
Without nocheatplus.

**Comment by mariolars** [comment]
Ofc players on version 1.9.4 doesn't face with this problem.

**Comment by ridalarry** [comment]
Im having the same problem maybe because its y location is a bit higher than the normal blocks and lower than slab location. Also for the moved wrongly its by spigot I think.

**Comment by CreaModZ** [comment]
Same problem with 1.7/1.8 client on 1.9.4 Spigot.

**Comment by Tom-III** [comment]
Make the server ignore lilly pads and make them pass through as solution

**Comment by Shevchik** [comment]
Should be fixed now
