### ISSUE TITLE
Potions showing as water bottles

### ISSUE THREAD

**Issue by imapav** [ProtocolSupport/ProtocolSupport#173]
When using Client Versions 1.8.X all potions get converted to show as water bottles.

1.8.9 Inventory
![189 Inventory](https://dl.dropboxusercontent.com/s/ni221aa8hhnmnor/javaw_2016-05-19_09-37-07.png)

1.9.4 Inventory
![189 Inventory](https://dl.dropboxusercontent.com/s/llv3ldcpcia0i0s/javaw_2016-05-19_09-37-48.png)

Using latest ProtocolSupport version and latest Paperspigot 1.9.4

**Comment by Shevchik** [comment]
Should be fixed now.
(As long as you don't try to get potions from creative).
