### ISSUE TITLE
Brewing completely broken

### ISSUE THREAD

**Issue by imapav** [ProtocolSupport/ProtocolSupport#174]
When using a brewing stand and try to make a potion with a water bottle and any ingredients it simply doesn't work.

e.g. (https://dl.dropboxusercontent.com/s/kk6gdstbgm8yfgy/javaw_2016-05-19_23-41-37.png)

Using latest ProtocolSupport version and latest Paperspigot 1.9.4

**Comment by Shevchik** [comment]
You didn't put a blaze powder and using invalid potion type, see 1.9 crafting.
