### ISSUE TITLE
Error when joining a 1.9.4 server from 1.7.10 client!!

### ISSUE THREAD

**Issue by MJRLegends** [ProtocolSupport/ProtocolSupport#176]
Right the server I am trying to join has beacon in the area to where my player is, and I believe they are speed and jump effects being given from them. The error below seems to be due to player effects as it says in the error from the console S1DPacketEntityEffect

Error message from console: http://pastebin.com/w6ezRAXD

**Comment by Shevchik** [comment]
9 bytes is the correct amount of bytes for this packet.
Try using vanilla 1.7.10 client.

Or send me your server ip, so i can join and test.

**Comment by MJRLegends** [comment]
Yeah works fine with a 1.7.10 vanilla client

**Comment by Shevchik** [comment]
Looks like it is a problem with your modified client, try joining vanilla 1.7.10 server, if it errors too, then i can't help there.
