### ISSUE TITLE
Double transform possible?

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#181]
If a fallback block is available in a lower version but in an even lower version even the transformed block is it possible to convert the transformed block into another transformed block?
Like Shield Item 1.9 -> Barrier Item 1.8 -> Red Wool Block 1.7

**Comment by Shevchik** [comment]
Yes, it is possible, fetch BlockRemappertControl for needed version via api, and do what you want. It doesn't support block data yet, but i'm working on it.
