### ISSUE TITLE
Shulker bullets

### ISSUE THREAD

**Issue by ridalarry** [ProtocolSupport/ProtocolSupport#182]
If an old client was shot by a shulker bullet they wont fly upwards as its supposed to

**Comment by Shevchik** [comment]
Shulker bullet adds levitation effect. That effect is clientside, and emulating that from server will look laggy for a client if ping is > 50.

**Comment by ridalarry** [comment]
What about disabling levitation for both to be fair as that will cause fall damage to the player.
