### ISSUE TITLE
Dragon head

### ISSUE THREAD

**Issue by ridalarry** [ProtocolSupport/ProtocolSupport#188]
Dragon head on hand will show the purple and black block for the old clients when its hold by hand and will show a skull when its placed

if it would be possible to change the packets to show a skeleton head or a player skull that has a simi dragon head

**Comment by Shevchik** [comment]
To do this i need a dragon head skin, i didn't find anything close on the internet, so somebody will have to draw it first.

**Comment by jiongjionger** [comment]
@Shevchik KingEndermen's skin is like a dragon.

**Comment by Shevchik** [comment]
Yea, looks like it, now the problem is that < 1.7.5 clients are using usernames for skins, so i need a confirmation that this skin accuont won't change.

**Comment by Shevchik** [comment]
There is a use named EnderDragon which has ender dragon skin, but i have no idea how to find it's owner.
