### ISSUE TITLE
1.8 got a bunch of bugs

### ISSUE THREAD

**Issue by i998979** [ProtocolSupport/ProtocolSupport#191]
sorry for previously wrong enter click

I was playing on a server that with protocolspuuort and protocolsupportbungee
then they faced these problems
after my own server test, i got these problems too
all bugs are related to 1.8, 1.9 got no problem

1: I can't move any vehicles like horse
2: I can't use brewing stand, after i put potion and material, it did nothing
3: I joined the server with 1.9, then enchant with 1.9 enchant, switch back 1.8, it will disappear for sure. But when i switch back to 1.9, enchant disappeared.
4. I can't use leash to any mobs, it will instatly drop
currently these bugs that I have discovered
Hope you can give me a way to solve it

**Comment by Shevchik** [comment]
Read readme and already closed issues before posting. Thosr issues are wontfix.
