### ISSUE TITLE
WARNING

### ISSUE THREAD

**Issue by FunnyCraft** [ProtocolSupport/ProtocolSupport#197]
http://pastebin.com/RzniXSRa

**Comment by Castar** [comment]
+1

**Comment by ridalarry** [comment]
+1

**Comment by Mabus13** [comment]
+1

**Comment by Shevchik** [comment]
Not fixable, those warnings will stay here to warn people that some blocks may glitch for clients when breaking them.

**Comment by Shevchik** [comment]
Now warnings will be printed only in debug mode
