### ISSUE TITLE
SUPPORT 1.10

### ISSUE THREAD

**Issue by FunnyCraft** [ProtocolSupport/ProtocolSupport#199]
You are going to support the 1.10 version?

**Comment by FunnyCraft** [comment]
don't even give an answer ...

**Comment by Shevchik** [comment]
Issues are for issues only.

**Comment by FunnyCraft** [comment]
I wrote on rubukkit you do not answer it., give an answer.

**Comment by MrPowerGamerBR** [comment]
@FunnyCraft he will update if he wants to, he is not obliged to provide updates to ProtocolSupport, since he makes ProtocolSupport for free.

Also, 1.10 was released today, AND SPIGOT 1.1.0 ISN'T RELEASED YET, how can he do a update to a software that DOESN'T EXISTS.

**Comment by FunnyCraft** [comment]
@MrPowerGamerBR I just asked whether to wait for the update 1.10, the support can be carried out with a 1.9.4 kernel, viaversion already done it.

**Comment by MrPowerGamerBR** [comment]
@FunnyCraft Shevchik always uses the latest version of Minecraft as a base.

**Comment by FunnyCraft** [comment]
@MrPowerGamerBR the situation is complicated,  1.9 many servers.
