### ISSUE TITLE
1.10 Support

### ISSUE THREAD

**Issue by AshourAziz** [ProtocolSupport/ProtocolSupport#200]
Just making an issue ticket so we can keep track of 1.10 support and reply with errors when theirs an update.

**Comment by DmitryRendov** [comment]
Good luck with 1.10 . http://pastebin.com/Xmf0L8vF

**Comment by JunkyBulgaria** [comment]
you can't just change the protocol ids and expect it to work :D

**Comment by wow4201** [comment]
What is the current state of ProtocolSupport?
1.9.4 Server + current ProtocolSupport = server goes into a restart loop.
1.10 server + Current ProtocolSupport = every client version gets disconnected.

**Comment by AshourAziz** [comment]
I believe support is still being worked on, but here is what I have if this helps @Shevchik 

1.8:
Works fine
1.9
https://www.ashour.pw/images/160612010940160601094006.png
1.10:
Works fine.

**Comment by TWSSYesterday** [comment]
1.9 support has been dropped, in #201 I've asked when it'll be re implemented if it hasn't been in dev builds already

**Comment by Shevchik** [comment]
It is already implemented.

**Comment by TWSSYesterday** [comment]
Fantastic!

**Comment by Bodyash** [comment]
![image](https://cloud.githubusercontent.com/assets/2454569/15994261/258610dc-3108-11e6-8b8e-209dedd5e81a.png)
Yeap, 1.9 is buggy

**Comment by lukechatton** [comment]
Should we be running this on 1.10? My goal is to support 1.9 clients on a 1.10 server.

**Comment by AshourAziz** [comment]
1.10 seems great, no issues so far.

@lukechatton latest build will run only on 1.10 and support 1.9.x 1.8.x etc.ON a 1.10 server.

**Comment by RabsCodes** [comment]
Please add 1.10 support :D
