### ISSUE TITLE
Join/Leave message doesn't work

### ISSUE THREAD

**Issue by maxlehot1234** [ProtocolSupport/ProtocolSupport#202]
HI, I just want to know if you can add something to make join/leave message works.

For the moment, I try 5 different plugins and this simply doesn't work....

Thanks again

**Comment by Shevchik** [comment]
Provide a list of those plugins please, default login/quit messages work fine for me.

**Comment by maxlehot1234** [comment]
Hi, I try to use deluxechat, firstjoinplus, skript and none of them if I am under 1.9.4, so 1.8.x players doesn't see it or if 1.8.x player join and I am under 1.9.x, I doesn,t join/leaver message...


Thanks

**Comment by Shevchik** [comment]
Give me your configuration for firstjoinplus.

**Comment by maxlehot1234** [comment]
I create a really small skript for join/leave message, but it works only if players use 1.9.x version.
If I am under 1.9.x and a player with 1.9.x join, I see the join message, BUT if a 1.8 player join, I DOESN'T see the join message.


If needed, this is my firstjoinplus config: http://pastebin.com/dEmXJ83g


This is my SMALL skript if needed: http://pastebin.com/q4y4EAM3



Thanks again for your reply.

**Comment by Shevchik** [comment]
I'm able to see join/quit messages just fine, so the problem is one of your plugins.

**Comment by Shevchik** [comment]
Can you give me your full list of plugins?

**Comment by maxlehot1234** [comment]
It was fix using a skript. I will close this.
