### ISSUE TITLE
[18:02:20 FATAL]: java.lang.NullPointerException on MCPE player join

### ISSUE THREAD

**Issue by TiTo-418** [ProtocolSupport/ProtocolSupport#205]
Simple as that, the player can't join
MCPE version: 0.15.0.0
Latest version of mcpe branch

**Comment by Shevchik** [comment]
PSPE doe only supports 0.14.2, and update to 0.15.0 won't be happening any time soon.
Some parts need to be rewritten because they are really shitty, and it's really hard to update them.

**Comment by Shevchik** [comment]
Closing this issue because mcpe branch will be rewritten from scratch.
