### ISSUE TITLE
Some players can't connect with 1.9

### ISSUE THREAD

**Issue by EMC3** [ProtocolSupport/ProtocolSupport#206]
Hello, I have the following issue: (latest spigot, latest dev build of protocol support)

Some players (NOT ALL) cannot connect with 1.9.x. They disconnect on login with this error message in the log:
<playername> lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

The players connect thru BungeeCoord. BungeeCoord says "[Proxy] lost connection to server"

**Comment by Shevchik** [comment]
Enable debug and paste full exception log.

**Comment by EMC3** [comment]
Here is the Exception: http://pastebin.com/65iiHuC9 ,seems to be caused by protocollib, i will try updating it

**Comment by EMC3** [comment]
With the "protocolsupport debug" command. It would be helpful to add a "protocolsupport help" command, but this is offtopic...

**Comment by Shevchik** [comment]
No, those errors are caused by some bug in chunk data transformer which i can't find yet.

**Comment by Shevchik** [comment]
Try latest dev build, i changed chunk decoder to use mojang code for now, lets see if it fixes something.

**Comment by Shevchik** [comment]
Okay, i added more info to exception, try to reproduce it now.

**Comment by Shevchik** [comment]
Same as #218
