### ISSUE TITLE
Holograms visible Armorstands

### ISSUE THREAD

**Issue by EMC3** [ProtocolSupport/ProtocolSupport#207]
Hello, The plugin breaks holograms.
When using a 1.10 server 1.9 and 1.8 clients see armorstands under holograms. These should be not visible...
using latest dev version and latest server version.

**Comment by Tom-III** [comment]
Its better than no holograms at all

**Comment by Tom-III** [comment]
Edit; this would be better implemented as a side plugin like PSBarAPI so PSHolograph

**Comment by Shevchik** [comment]
Should be fixed now
