### ISSUE TITLE
Players in 1.8+ see 1.7 players as Unknown until they are teleported.

### ISSUE THREAD

**Issue by ItzVinex** [ProtocolSupport/ProtocolSupport#209]
Players in 1.8+ see 1.7 players as Unknown until they are teleported to another location then you can see them. I'll need to check the error log next time it happens. Using Latest Dev Build.

**Comment by Shevchik** [comment]
Does it still happen?

**Comment by ItzVinex** [comment]
Not if they teleport, it happens when they join, it shows a Steve skin with a "Unknown" tag above their head, when they get teleported/moved to another world per say then their skin reappears a long with their name.
