### ISSUE TITLE
Crash on 1.7

### ISSUE THREAD

**Issue by ServerCrashes** [ProtocolSupport/ProtocolSupport#210]
Having this error when people log in using 1.7 - http://pastebin.com/3eX9Lupb

I'm using this (http://build.true-games.org/job/ProtocolSupport/388/) build of ProtocolSupport on Paper Spigot.
Output of /ver: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Attempted to use this thanks to ViaVersion adding a way for both to work together - Error occurs both with & without ViaVersion.

If there is a higher build of PS that works on 1.8.8, please do link me to it. Thanks.

**Comment by Shevchik** [comment]
I'm not supporting not latest protocolsupport version.
