### ISSUE TITLE
[1.7] Holograms not shown

### ISSUE THREAD

**Issue by VinexAx789** [ProtocolSupport/ProtocolSupport#211]
As a 1.7 client Holograms are not showing. Using Latest Dev Build.

**Comment by VinexAx789** [comment]
Did you fix it?

**Comment by Shevchik** [comment]
No, there is nothing to fix here.

**Comment by VinexAx789** [comment]
Why aren't they showing then?

**Comment by VinexAx789** [comment]
Using HolographicDisplays

**Comment by Shevchik** [comment]
Because armor stands didn't exist before 1.8
