### ISSUE TITLE
Players see themselves as a weird Steve skin but and can see other players skins

### ISSUE THREAD

**Issue by ItzVinex** [ProtocolSupport/ProtocolSupport#212]
Players see themselves as a weird Steve skin but and can see other players skins.

Latest Version and server version 1.10.

Client version: 1.7.9

Screenshot.
https://gyazo.com/3e901989f6831a173324a8cf8a31de50

**Comment by Shevchik** [comment]
Does it happen for all players, or to specific ones?

**Comment by VinexAx789** [comment]
It's honestly weird it happens sometimes then doesn't but majority it does I also noticed another problem if you wanna know what is not that big of a deal but it is for developers/gagdets.

**Comment by VinexAx789** [comment]
Yeah it only happens for the player that is steve they can't see their skin but others can but those others have the same issue.

**Comment by VinexAx789** [comment]
It's pretty much I can see your skin but I cannot see mine.

**Comment by VinexAx789** [comment]
To fix this I suggest making ProtocolVersion.java a version in the class 1.7.9 so i can just disable them from joining.

**Comment by Shevchik** [comment]
Not possible, 1.7.9 doesn't have a separate protocol version id.

**Comment by MrPowerGamerBR** [comment]
@VinexAx789 you are viewing you as a "weird steve skin" because you are running mods that allow bigger skins (or a resource pack that changes the Steve skin), on a vanilla Minecraft 1.7.9 client, you will see you as the default skin (Steve)

**Comment by VinexAx789** [comment]
I thought the same but that doesn't answer why it happens here and there

**Comment by Shevchik** [comment]
Not much i can do here, it's a client bug.

**Comment by ItzVinex** [comment]
I fixed it by coding a delay when they join, if they teleport it fixes it.
