### ISSUE TITLE
BUG Potions

### ISSUE THREAD

**Issue by adriancfbr** [ProtocolSupport/ProtocolSupport#216]
has an error in the potions system that does not appear in the inventory

**Comment by Shevchik** [comment]
WUT? didn't understand anything.

**Comment by adriancfbr** [comment]
In inventory when trying to get a potion is not possible .-.

**Comment by Shevchik** [comment]
Video pls.

**Comment by adriancfbr** [comment]
![captura de tela de 2016-07-05 15-55-47](https://cloud.githubusercontent.com/assets/11598976/16596185/268a5948-42c9-11e6-8bbb-04e862b5c696.png)
![captura de tela de 2016-07-05 15-55-55](https://cloud.githubusercontent.com/assets/11598976/16596201/3439894c-42c9-11e6-92d7-05193280dcc5.png)

It is not easy to record a video on ubuntu

When you get a potion and puts in the inventory has no effect

**Comment by Shevchik** [comment]
Item's in creative are not supported, read the description before posting issues.
