### ISSUE TITLE
1.9.4 client disconnects on 1.10 PS Build 539

### ISSUE THREAD

**Issue by i9hdkill** [ProtocolSupport/ProtocolSupport#218]
Hi,
Spigot 1.10.2
PS Build 539
When clearing a plot, the players gets a disconnect.

Maybe because of resending/generating the new chunks?
This is with /ps debug enabled, but I don't think that it will help.
http://pastebin.com/Hh3Ug5x1

**Comment by ridalarry** [comment]
same issue for me

**Comment by Shevchik** [comment]
You server folder should contains protocolsupport error log, try to find that log there, because the excaption cause stacktrace was cut.

**Comment by i9hdkill** [comment]
http://pastebin.com/BF0TSmxu
http://pastebin.com/0xMBYjwY
I will check the plotsquared config, maybe weird meta data on plot settings.

config/worlds.yml:
http://pastebin.com/a9eLCUgh

**Comment by Shevchik** [comment]
Chunk decoder now prints more info when exception happens, try to reproduce it now.

**Comment by i9hdkill** [comment]
Error generated with the latest dev build of Protocolsupport on 1.10.2
1.9.4 client tries to execute /plot delete
http://pastebin.com/8jpyBK44

**Comment by Shevchik** [comment]
ProtocolSupport errlog message is cut off btw, is this copy paste error, or log isn't written fully?

**Comment by Shevchik** [comment]
This issue should be fixed now

**Comment by i9hdkill** [comment]
No, the error was cut off in both logs.

**Comment by i9hdkill** [comment]
It works, thank you!
