### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by haelexuis** [ProtocolSupport/ProtocolSupport#221]
Why sounds not works? If I have server 1.10 and latest ProtocolSupport all of the sounds are diferrent, I try remove all plugins and change 1.10 version but it doesn't helps.

**Comment by Shevchik** [comment]
Because i didn't remap sound ids yet.

**Comment by haelexuis** [comment]
And when you do this?

**Comment by Shevchik** [comment]
Some day in the future

**Comment by haelexuis** [comment]
Can I help?

**Comment by Shevchik** [comment]
You may try to compare 1.10 and 1.9.2/1.9.0 sounds registries to find how sounds ids shifted

**Comment by BeYkeRYkt** [comment]
You can use this:
http://pokechu22.github.io/Burger/1.9.html#sounds
http://pokechu22.github.io/Burger/1.10.html#sounds

**Comment by haelexuis** [comment]
Hmm, I try do this with php

**Comment by haelexuis** [comment]
block.enchantment_table.use (ID 24) was added to 1.10 > (1.9 shift -1)
entity.husk.ambient (ID 249) was added to 1.10 (1.9 shift -2)
entity.husk.death (ID 250) was added to 1.10 (1.9 shift -3)
entity.husk.hurt (ID 251) was added to 1.10 (1.9 shift -4)
entity.husk.step (ID 252) was added to 1.10 (1.9 shift -5)
entity.polar_bear.ambient (ID 301) was added to 1.10 (1.9 shift -6)
entity.polar_bear.baby_ambient (ID 302) was added to 1.10 (1.9 shift -7)
entity.polar_bear.death (ID 303) was added to 1.10 (1.9 shift -8)
entity.polar_bear.hurt (ID 304) was added to 1.10 (1.9 shift -9)
entity.polar_bear.step (ID 305) was added to 1.10 (1.9 shift -10)
entity.polar_bear.warning (ID 306) was added to 1.10 (1.9 shift -11)
entity.stray.ambient (ID 365) was added to 1.10 (1.9 shift -12)
entity.stray.death (ID 366) was added to 1.10 (1.9 shift -13)
entity.stray.hurt (ID 367) was added to 1.10 (1.9 shift -14)
entity.stray.step (ID 368) was added to 1.10 (1.9 shift -15)
entity.wither_skeleton.ambient (ID 387) was added to 1.10 (1.9 shift -16)
entity.wither_skeleton.death (ID 388) was added to 1.10 (1.9 shift -17)
entity.wither_skeleton.hurt (ID 389) was added to 1.10 (1.9 shift -18)
entity.wither_skeleton.step (ID 390) was added to 1.10 (1.9 shift -19)
item.elytra.flying (ID 434) was added to 1.10 (1.9 shift -20)

Finally, I think it maybe helps :)

**Comment by Shevchik** [comment]
Ok, will try to implement it soon, (does block.enantment_table.use really have id 24?)

**Comment by haelexuis** [comment]
Yes, http://pokechu22.github.io/Burger/1.10.html#sounds:block.enchantment_table.use.

**Comment by Arcrimonia** [comment]
I would be very grateful if this was fixed. :)

**Comment by BestMark** [comment]
@Shevchik, please, fix this bug

**Comment by Shevchik** [comment]
Should be fixed now
