### ISSUE TITLE
Forge packets issue

### ISSUE THREAD

**Issue by hunter688** [ProtocolSupport/ProtocolSupport#222]
Situation:

bungeecord with spongepls plugin (allows forward forge packets)

lobby server - Spigot 1.10.2 with protocol support plugin

SpongeForge 1.8.9 server with some mods include Thaumcraft

When client connected to lobby, then can connect to modded server, normally play etc.. but.. some packets cannot go between client and server.

When removed plugin protocol support from lobby server and add modded server to priorities in the bungee config, all works.

It looks like yours plugin interfering with Forge networking. Could You please try to fix? If you need some debug output/info, testing, I'm ready to help.

See issue: https://github.com/SpongePowered/SpongeForge/issues/731

This is great plugin and will be cool have one lobby server as intersection.

**Comment by Shevchik** [comment]
As soon as you switch to another server what protocolsupport does is no longer important, so the problem is probably because your lobby server is vanilla, and that breaks all things because forge no longer inits properly, look for bungeecord forge support issues.
