### ISSUE TITLE
Texture pack custom sound crash clients

### ISSUE THREAD

**Issue by Fr33stylerMC** [ProtocolSupport/ProtocolSupport#223]
Sending a custom sound to a different client version than the server will crashe the client.

**Comment by Shevchik** [comment]
Need client crash log

**Comment by RoboMWM** [comment]
> 1.9.2 client and 1.10.2 server
> Either via a vanilla /playsound command or player#playsound. Sounds were custom sounds, did not test with normal sounds.
Wasn't able to get a crash log from the player, but it was consistent/reproducible.

**Comment by Shevchik** [comment]
I will check that, but i need a resorucepack with custom sounds.
Normal sounds also use custom sound packet, so not sure what went wrong here, but i will check.

**Comment by RoboMWM** [comment]
Used this pack (see releases for download): Http://github.com/mlg-fortress/mlg-resource-pack

**Comment by Shevchik** [comment]
Should be fixed now
