### ISSUE TITLE
Bug Visual ?

### ISSUE THREAD

**Issue by adriancfbr** [ProtocolSupport/ProtocolSupport#224]
Quando o jogador fica pulando muito alto em um bloco somente, para outros jogadores o jogador fica atravesando o bloco..

Inglês: When the player is jumping very high on a block only to other players the player is atravesando the block ..

Blocks crash minecraft 1.8 down
 - minecraft:repeating_command_block
 - minecraft:chain_command_block

**Comment by Shevchik** [comment]
Should be fixed now
