### ISSUE TITLE
Only 1.10 can connect

### ISSUE THREAD

**Issue by EMC3** [ProtocolSupport/ProtocolSupport#225]
If any other version than 1.10 tries to connect i get: "lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured."

A (short) stacktrace with client 1.9.2 and debug mode on: http://pastebin.com/CRPSRQCC

Server: Spigot 1.10.2

**Comment by EMC3** [comment]
In another server i could connect, but after a few seconds walking around i get this one:

http://pastebin.com/kFXaK8NL

**Comment by EMC3** [comment]
Does not happen with a spigot 1.10 version from the 18.6........

**Comment by Shevchik** [comment]
Same as #218
