### ISSUE TITLE
1.7.X Sign formating bug

### ISSUE THREAD

**Issue by piter909** [ProtocolSupport/ProtocolSupport#229]
1.7.X can not see any of formats on signs, like &l, &k - only colors.
Also, they can see only 13-14 characters instead of all 16 (yes, including color formating).
Please, fix it :<

**Comment by Shevchik** [comment]
Format should be fixed now, as for number of characters - use color only at the start of the line, otherwise converting from json components requires to add a ton of resets to make sure that everything displays properly.

**Comment by piter909** [comment]
With latest version (I do not know why) ProtocolSupport is stopping my server after start loading is finished, but version from 01 June is not doing things like this.
There is no logs with errors. Just messages that server is stopping after loading everything.
I am 100% sure that this plugin causes it, because after reupload old version it starts.

**Comment by piter909** [comment]
Ah, I am sorry, there is an single exception:
http://pastebin.com/n1FP2wrP
Probably, on your start code, there is Bukkit.shutdown() after error catch.

**Comment by Shevchik** [comment]
You are trying to use version for 1.9.4 on 1.10 server.

**Comment by piter909** [comment]
Is there version for 1.10? Version from 1 June was working without any problem :P

**Comment by Shevchik** [comment]
Latest dev build.

**Comment by piter909** [comment]
I have downloaded latest build from jenkins as I said and I got this exception what I sent. :(
It is not for 1.10.

**Comment by Shevchik** [comment]
Not possible, you are probably downloading wrong version, or copying worng one because you have 2 of them.

**Comment by piter909** [comment]
Oh.. I do not know why I have put there downloaded old version from spigot dev when I downloaded it from Jenkins. I am sorry. :x
Thank you a lot for helping, everything works perfectly right now!
Also, thank you for this amazing plugin!
