### ISSUE TITLE
Potions do not work.

### ISSUE THREAD

**Issue by Boomclaw** [ProtocolSupport/ProtocolSupport#233]
Hi,

Potions and splash potions do not work, this might be related to the same issue as spawn eggs. When they go into a player's inventory, they become water bottles and do not have any effects unlike spawn eggs which will spawn the entity.

**Comment by Boomclaw** [comment]
Just to clarify, this only affects 1.8 and below. 1.9 and 1.10 aren't effected, just like spawn eggs.

**Comment by Shevchik** [comment]
You are using creative mode, that is not supported.
