### ISSUE TITLE
1.7 & 1.8 versions can avoid 1.9+ attack cooldown

### ISSUE THREAD

**Issue by piter909** [ProtocolSupport/ProtocolSupport#235]
1.7 & 1.8 versions can avoid 1.9+ attack cooldown.
When players on this version attack entities&players, they have no attack cooldown, when 1.9+ has. 
Players with 1.9+ are hitting much slower and they can not hit multiple targets, when lower version can.
Is there any way to fix it, or it is ProtocolSupport failiture?

**Comment by Shevchik** [comment]
Tested it with single target and cooldown works fine, second attack from lower client versions deals less damage.

But there may be another problem, the cooldown is set after play sent animate packet, not after entity use, so maybe old clients just don't send this packet under some conditions.

**Comment by piter909** [comment]
As I have noticed, both versions are dealing same amount of damage, but lower can hit much faster and they can hit next target when highter version have cooldown :/
I think best way, before it will be fixed by antycheat, Mojang (or you :P), is remove this coolown and allow all players attack without cooldowns.

**Comment by Maxqia** [comment]
So, just use BukkitOldCombatMechanics?

**Comment by Shevchik** [comment]
Well, can't do anything here.
