### ISSUE TITLE
Rod Animation

### ISSUE THREAD

**Issue by SIM0NSTR** [ProtocolSupport/ProtocolSupport#238]
In 1.8 and below the rod animation is messedup. Would be great if its fixable, essential for PvP :/

**Comment by Shevchik** [comment]
Rod? Is there such an item?

**Comment by SIM0NSTR** [comment]
I am in vacation so making a video is quite difficult. Just join with 1.8, grab a fishing rod and eject it.

**Comment by Shevchik** [comment]
Works fine for me.

**Comment by SIM0NSTR** [comment]
I'll try to make a video

**Comment by SIM0NSTR** [comment]
https://youtu.be/uprd7sUFPg0 :]

**Comment by Shevchik** [comment]
Wow, send me your test server files, i guess that it won't be easy to reproduce.

**Comment by SIM0NSTR** [comment]
http://www.mediafire.com/download/cej9888x5m8n597/Server.zip
In the video i used LabyMod 1.8.8, but its the same with default 1.8.8 :/

**Comment by Shevchik** [comment]
Okay, i managed to reproduce this and found the issue most likely.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by SIM0NSTR** [comment]
Thank you so much! :]
