### ISSUE TITLE
Menu trade with npc crashes player 1.7

### ISSUE THREAD

**Issue by mariolars** [ProtocolSupport/ProtocolSupport#239]
http://pastebin.com/6jXMymkW
http://screenshot.sh/odygelW177I2z

**Comment by Shevchik** [comment]
Are you running latest protocolsupport build?

**Comment by mariolars** [comment]
oh.. wow You fixed it. Sorry. After reading commits in every update i thought you didn't fix this problem. 

But i have a next one : http://screenshot.sh/n9hnQFZQAFOaL

Players on 1.7 sees black characters with displayname "Unknown". Characters spawns when someones joins to the server.

**Comment by Shevchik** [comment]
Create a separate issue for that.
