### ISSUE TITLE
Player collission

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#241]
Can player collision be fixed in the protocol level because the scoreboard solutions don't seem to work probably because of conflicts with other scoreboard plugins.

The best would be if 1.9/1.10 packets were modified or had the anti collision injected on the fly so it would override any plugin.

**Comment by Shevchik** [comment]
No. Scoreboards are only way to disable collision.

**Comment by maxlehot1234** [comment]
@Tom-III 
You can use no-collision plugin on spigot for this, it works like a charm ;)
https://www.spigotmc.org/resources/no-collision.26347/
