### ISSUE TITLE
Players disconnect using 1.81.x and 19.4 on 1.10.2 server

### ISSUE THREAD

**Issue by maxlehot1234** [ProtocolSupport/ProtocolSupport#242]
Hi, I have this error in the procolsupport error file:

This is for 1.9.4: http://pastebin.com/3A1EgGj4
And this is for 1.8: http://pastebin.com/n2MWtQP3

Thanks again

**Comment by Shevchik** [comment]
Log tells that for whatever reason world to which that chunk belongs doesn't have skylight, but sent data contains skylight. Does this world have skylight or not. Also check your world dimension ids if possible, maybe there is something strange with them

**Comment by maxlehot1234** [comment]
What is skylight...
It works great with a 1.9.4 server.... But when I update my server to 10.0.2, troubles start...


This happen with 1.7.2 too...
http://pastebin.com/M32CteTG

For 1.4.7, I can't join the server, because minecraft told me that I am outaded...
1.5.2 crash the minecraft client, simply can't join and see this: http://pastebin.com/u8EHrJEy
AND THIS: http://pastebin.com/uhxGzkdm

Is it normal?

**Comment by Shevchik** [comment]
Is your world which players join first normal one or nether/end?

**Comment by maxlehot1234** [comment]
No I used a default world...

What do you mean by dump all packets? I need to add something into the protocollib config file?

**Comment by Shevchik** [comment]
Use command:
packet add play server true
And the join the server and paste here what i actually produced.

**Comment by maxlehot1234** [comment]
There it is: https://www.dropbox.com/s/wt24b5wxay5yy9f/latest.log?dl=0

Too long for pastebin :P 

Is it what you want?

**Comment by Shevchik** [comment]
Yea, this.

The main cause it this:

[ProtocolLib] Sent PacketPlayOutRespawn[51, legacy: 7] to maxlehot1234:
{ a = 13, b = { f = 1, g = "options.difficulty.easy", name = "EASY", ordinal = 1 }, c = { f = 1, g = "creative", h = "c", name = "CREATIVE", ordinal = 2 }, d = FLAT }

Something sends respawn packet with dimension id 13, that is not a valid dimension id. Not actually sure how the hell it even works.

**Comment by maxlehot1234** [comment]
Oh ok, so how I can fix this?

**Comment by Shevchik** [comment]
IDK, but i can create a workaround for that.

Minecraft actually accepts invalid dimension ids, just the world renderer will glitch for a few seconds while minecraft is creating generic world.

**Comment by maxlehot1234** [comment]
If you can, it could be really nice, so I can test it on my test server to will able to release it on my opublic server inn few days

**Comment by Shevchik** [comment]
Try now

**Comment by maxlehot1234** [comment]
It works now. Thanks again ;)
