### ISSUE TITLE
1.5.2 clients get kicked randomly.

### ISSUE THREAD

**Issue by Mr447** [ProtocolSupport/ProtocolSupport#243]
Hi i'm have a bungeecord network 1.8 and installed bungeeprotocolsupport and protcolsupport in all the servers 
i'm using spigot 1.8.8
and using protocolsupport for 1.8
=================
the problem is that the players that in 1.5.2 version get kicked randomly any time
and they return to the lobby and then they rejoin the server

in the console i found this when players get kicked
====
20.08 13:29:21 [Disconnect] User Xxkhalifa502xX has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: NettyChannelInjector.decode() did not read anything but decoded a message.
===
what should i do
i'm using protocolsupport 1.8 for spigot 1.8

**Comment by Mr447** [comment]
also this is my server ip 

urmagix.com

**Comment by Shevchik** [comment]
I'm only supporting latest dev build.
