### ISSUE TITLE
Не грузятся чанки на версиях 1.8.x

### ISSUE THREAD

**Issue by BestMark** [ProtocolSupport/ProtocolSupport#252]
Установив последнюю версию ProtocolSupport (#567), заметил, что при первом (и последующем) заходе с версий 1.8.x не грузятся чанки, разве только прозрачные каркасы блоков, не заполненные текстурами. На версиях 1.9-1.10 данная проблема не наблюдается.
Если сломать блок, баг пропадает и чанки начинают грузиться нормальным образом.

**Список плагинов:**
ProtocolLib 4.0.2, ProtocolSupport (#567)

**Ядро:**
CraftBukkit version git-Spigot-455072c-43ab266 (MC: 1.10.2)
![2016-08-28_18 03 33](https://cloud.githubusercontent.com/assets/18399104/18034340/de24b456-6d42-11e6-944a-5ee3c055cd66.png)

**Comment by Shevchik** [comment]
Upload your map somewhere and give me the link.

**Comment by BestMark** [comment]
@Shevchik http://rgho.st/6shWhSlMd

**Comment by Shevchik** [comment]
Unable t reproduce, need full server archive and client too.

**Comment by BestMark** [comment]
После замены ядра PaperSpigot на обычный Spigot, установки последней версии ProtocolSupport и регенерации мира, проблема решилась, но я сомневаюсь, что это не повторится.

**Comment by BestMark** [comment]
UP: Баг стал снова повторяться, когда я установил _view-distance_ в spigot.yml на значение _4_.

**Comment by BestMark** [comment]
После удаления NoCheatPlus, у игроков, которые жаловались на эту проблему, баг пропал, чанки стали грузиться безо всяких проблем.

**Comment by BestMark** [comment]
После удаления session.lock в папке world проблема решилась.

**Comment by BestMark** [comment]
Problem still exists, if player using Minecraft 1.8.x versions

**Comment by Shevchik** [comment]
As i already said, need a full server+client archive.

**Comment by Shevchik** [comment]
No files - no help, i waited a month.
