### ISSUE TITLE
1.5.2 Lily pad bug

### ISSUE THREAD

**Issue by EntryPointKR** [ProtocolSupport/ProtocolSupport#253]
When standing on lily pad, occurs problem.
https://giphy.com/gifs/3o6Zt323Dw3v4asyFa
Tested version: 1.5.2, 1.6.4, 1.7.10, 1.8.9

1.9.4 ↑ worked.

**Comment by EntryPointKR** [comment]
@Shevchik

**Comment by Shevchik** [comment]
Unable to reproduce. Make sure that your anticheat accounts for changed lilypad bounding box.
