### ISSUE TITLE
Deathmessage item preview shows ITEM INVALID on 1.7.10 and below.

### ISSUE THREAD

**Issue by Bonista** [ProtocolSupport/ProtocolSupport#254]
http://i.imgur.com/A0FqoAg.png

I think it's a JSON related bug. This is on the latest version of Spigot and ProtocolSupport.

**Comment by Bonista** [comment]
@Shevchik

**Comment by Shevchik** [comment]
Need this json on raw form to test

**Comment by Bonista** [comment]
@Shevchik No idea how I can get it, you can reproduce by renaming an item, and enchanting it then killing any player.

**Comment by Bonista** [comment]
On vanilla^

**Comment by Shevchik** [comment]
Don't see a weapon in default death messages.

**Comment by Bonista** [comment]
@Shevchik You must enchant and rename the item for it to show.

**Comment by Bonista** [comment]
@Shevchik Any update regarding this?

**Comment by Shevchik** [comment]
Found the reason, but it will take some time to fix that.

**Comment by Shevchik** [comment]
Should be fixed now
