### ISSUE TITLE
Критическая проблема, которую игнорируют

### ISSUE THREAD

**Issue by Sitmobedaf** [ProtocolSupport/ProtocolSupport#257]
Происходят сильные лаги при респавне и движении (при загрузке чанков клиентом).

И пока писал это сообщение, кажется понял, в каких моментах возникает данная проблема. Лаги не наблюдаются при загрузке обычного мира, при загрузке же пустоты, у клиентов 1.8.9 сильные лаги, на 1.7.2 и 1.9.4 лагов нет.

И чтобы не думали, что у меня комп глючит - проверяли на трёх компах дома, с видеокартами GTX 960, Intel Graphic 530 и GT 430. Два дня назад обновил BedWad на своём сервере, игроков стало в 2 раза меньше, хотя ничего у них не стёрлось, статистика осталась на MySQL, других поводов уходить не было, и многие жаловались на сильные лаги на БВ.

**Comment by Sitmobedaf** [comment]
Если проблему не устранить, то так и напишите, вернусь на ViaVersion.

**Comment by Dimatert9** [comment]
Может быть пинг большой до сервера?

**Comment by Sitmobedaf** [comment]
@Dimatert9, нет

**Comment by Shevchik** [comment]
Try now, maybe it is fixed.

**Comment by Sitmobedaf** [comment]
Да, исправлено, спасибо большое.
