### ISSUE TITLE
boats in 1.9 and up

### ISSUE THREAD

**Issue by popcorn9499** [ProtocolSupport/ProtocolSupport#260]
i was just wondering if it was possible to get boats to work with multiple people in this plugin. i can see it working well for 1.9 and up and 1.8.9 and down might be a problem. i was wondering if you could either make it so the player was teleporting or something for the other players. just ending up teleporting behind the player or a second boat linked somehow to this one that rendered on there screens.

just some sugestions. If i can help you with ideas on how to interprete that i will

**Comment by Shevchik** [comment]
I tried mounting players on arrow and moving that, but that looks horrible on a real server due to ping.
