### ISSUE TITLE
String longer than maximum 1.7

### ISSUE THREAD

**Issue by mariolars** [ProtocolSupport/ProtocolSupport#262]
Players on 1.7 version can not connect to the server on build 578.

http://scr.hu/0e4f/rxo3i

**Comment by Shevchik** [comment]
404

**Comment by mariolars** [comment]
sorry https://scr.hu/0e4f/4ten9

**Comment by Shevchik** [comment]
Most likely scoreboards. I thought i put a limit on them, but looks like i did not.
