### ISSUE TITLE
Crash client 1.5.2

### ISSUE THREAD

**Issue by Luuzzi** [ProtocolSupport/ProtocolSupport#264]
Stacktrace is empty. What is wrong?

http://pastebin.com/cjTRwFi2

**Comment by Shevchik** [comment]
Caused by a potion that didn't exist in that version.

**Comment by Luuzzi** [comment]
Server down when i set painting.

http://image.prntscr.com/image/3e12c175c678408fbc9fcc69f563699b.png

**Comment by Shevchik** [comment]
Create a separate issue for that.
