### ISSUE TITLE
Boat bug

### ISSUE THREAD

**Issue by Luuzzi** [ProtocolSupport/ProtocolSupport#267]
We have a player "A" and player "B". When player "B" sited on boat player "A" seen this normally. But when player "B" begins to moving player "A" sees that "B" player remains at the same place. Finally, when a player "B" get up from boat, he returns to place where he had seen player "A". An interesting point that boat for player "A" remains in place, but boat to player "B" is where he get up, and he cant move anymore... His throws to the spot where he got up.

Sorry for my english. I can explain in russian, if necessary.

![screenshot_1](https://cloud.githubusercontent.com/assets/13926595/18687755/3573a66e-7f8a-11e6-98ab-68611fa20edf.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/13926595/18687759/357da920-7f8a-11e6-9c6c-369309271050.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/13926595/18687757/35742fa8-7f8a-11e6-9938-158054ac5255.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/13926595/18687754/3573a6fa-7f8a-11e6-9b7f-95560e8b45c3.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/13926595/18687758/35756c1a-7f8a-11e6-86e7-e99a78dc944e.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/13926595/18687756/357413b0-7f8a-11e6-8983-56a4d431e03c.png)

**Comment by Luuzzi** [comment]
I'm using version 1.5.2.

**Comment by Shevchik** [comment]
Vehicles doesn't work for versions below 1.9, and it is written in the description.
