### ISSUE TITLE
Enchant anvil bug

### ISSUE THREAD

**Issue by Luuzzi** [ProtocolSupport/ProtocolSupport#269]
The enchantment table we can get such a book, put it into the anvil and get crash.

![screenshot_1](https://cloud.githubusercontent.com/assets/13926595/18714317/0926fc5c-801e-11e6-899e-27970c23957e.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/13926595/18714315/09246d7a-801e-11e6-97eb-9e65040c4f80.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/13926595/18714316/09255dac-801e-11e6-9505-f900d5edef77.png)

http://pastebin.com/4UUnpTyq

**Comment by Shevchik** [comment]
Enchantments books have their own enchantment storage tag, forgot about that.
Will try to fix it soon.

**Comment by Shevchik** [comment]
Try now, maybe it is fixed.
