### ISSUE TITLE
Clients 1.7.2

### ISSUE THREAD

**Issue by Sitmobedaf** [ProtocolSupport/ProtocolSupport#270]
У клиентов 1.7.2 краш сразу же после входа, на спавне.

**Comment by Shevchik** [comment]
Ну охуеть теперь, а краш лог где блять?

**Comment by Sitmobedaf** [comment]
Что случилось?

**Comment by Sitmobedaf** [comment]
Ошибся, клиент 1.7.10, сейчас уже не крашится, но лог пришлю - http://pastebin.com/KE1wjNje
И да, советую сходить погулять на свежий воздух.

**Comment by Shevchik** [comment]
Это результат различия работы скореборд команд в 1.7.10 и ранее, надо удалять старые помимо удаления скоребоарда.
