### ISSUE TITLE
Fishing rod

### ISSUE THREAD

**Issue by Luuzzi** [ProtocolSupport/ProtocolSupport#273]
She cannot be used.

![screenshot_1](https://cloud.githubusercontent.com/assets/13926595/18899211/096addec-8540-11e6-8808-df457d9c565f.png)

**Comment by Shevchik** [comment]
Works fine for me. ProtocolSupport doesn't modify how finishing rods work anyway.

**Comment by piter909** [comment]
It works fine for me. Maybe it is one of your plugins?
