### ISSUE TITLE
Error when player uses villager with modified content - pastebin

### ISSUE THREAD

**Issue by piter909** [ProtocolSupport/ProtocolSupport#274]
Here is an error when player clicks on villager, that has modified trade window (other things than default)
http://pastebin.com/JADSAf1h
Contain of Villager on my server was changed by plugin called "Shopkeepers".
Thanks for any help.

**Comment by Shevchik** [comment]
Need that plugin config to reporduce.

**Comment by piter909** [comment]
http://pastebin.com/qvSxFNPj
I have noticed that this problem is only on version 1.7.X. 
1.8+ does not have this problem

**Comment by Shevchik** [comment]
Shopkeepers change villager inventory using api, so you will have to give me the map which contains this villager.

**Comment by piter909** [comment]
Any villager with any change causes this exception

**Comment by Shevchik** [comment]
Works fine for me, make sure you are using latest dev build.

**Comment by piter909** [comment]
Thanks. I had a little older version :P
