### ISSUE TITLE
Cannot open written book

### ISSUE THREAD

**Issue by DNx5** [ProtocolSupport/ProtocolSupport#277]
**Server Version**: 
git-Spigot-c3e4052-1953f52 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
**ProtocolSupport** : Dev Build 589
**ProtocolLib** : 4.1.0-b325
**Plugins (2)**: ProtocolSupport, ProtocolLib
Step to reproduce:
Get a book and quill, write something on it, sign the book, and try to read using right click.

**Comment by Shevchik** [comment]
Most likely fixed with last commit
