### ISSUE TITLE
Error-spam in ProtocolSupport-errlog

### ISSUE THREAD

**Issue by piter909** [ProtocolSupport/ProtocolSupport#279]
After 5-7 days with ~ 100 players online, I have noticed that file ProtocolSupport-errlog is so heavy.
After opening it, there was in 99% errors like this one:
http://pastebin.com/RRZughPL
"Połączenie zerwane przez drugą stronę." means "Connection reset by peer."
I am using BungeeCord. Error log is from server, not proxy.
What is causing those errors?

**Comment by Shevchik** [comment]
Run your server under english utf 8 locale.
ProtocolSupport filter uneeded error messages by the messages itself, but some exception messages are localized, so they can't be filtered.

**Comment by piter909** [comment]
Thanks for reply!
en_US.UTF-8 is good locale?
Command locale-gen en_US.UTF-8 will change all messages?
