### ISSUE TITLE
Vanilla /stopsound command not stopping sound for 1.10.2 clients

### ISSUE THREAD

**Issue by RoboMWM** [ProtocolSupport/ProtocolSupport#280]
Server is also 1.10.2. Using Paper.

Also seems to affect Player#StopSound(string).

Version 4.25.dev (I'm generally grabbing the latest, so not sure which specific build number, sorry).

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by RoboMWM** [comment]
Indeed, thanks
