### ISSUE TITLE
Books(?) aren't properly sent on 1.10.2

### ISSUE THREAD

**Issue by RoboMWM** [ProtocolSupport/ProtocolSupport#281]
Both server and client are on 1.10.2.

Not entirely sure what the issue is here, but when I attempt to use things like the `/sf guide` (which is an enchanted book, which the slimefun plugin watches for an interactevent to deliver a customized json book), the book does not appear.

It may not be a book issue though, since it internally fires a command (that it filters from console, but viewable in PlayerCommandPreProcess).

The PlayerInteractEvent fires, and seems to be the same properties (cancel status, etc.) whether protocolsupport installed or not.

Latest version as of the time of posting this issue from the build server.

(Seems the latest updates have been breaking the 1.10.2 protocol.)

**Comment by Shevchik** [comment]
Most likely fixed with last commit

**Comment by RoboMWM** [comment]
Indeed, thanks
