### ISSUE TITLE
1.5.2 potion bug

### ISSUE THREAD

**Issue by MCReverse** [ProtocolSupport/ProtocolSupport#284]
Custom effects applied splash potion is changed to edible potion in 1.5.2.
If use this, looks like splash potion.

Sorry to my bad English :(

**Comment by MCReverse** [comment]
@Shevchik

**Comment by BeYkeRYkt** [comment]
[Please, stop](https://github.com/ProtocolSupport/ProtocolSupport/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20potion)

**Comment by swan201** [comment]
lol...
