### ISSUE TITLE
ProtocolSupport Server doesn't advertise as being a 1.4.7 server

### ISSUE THREAD

**Issue by Maxqia** [ProtocolSupport/ProtocolSupport#286]
When I add my server to my 1.4.7 client's server list, I can't join my server because it say's it's 1.10. 
With debug mode enabled I see "/127.0.0.1:42314 connected with protocol version MINECRAFT_1_5_2"
If I directly connect to the server, it works, with the message "/127.0.0.1:43484 connected with protocol version MINECRAFT_1_4_7"

**Comment by Shevchik** [comment]
Because it's not possible to detect ping versions < 1.6.1, so i assume it as 1.5.2
