### ISSUE TITLE
Проблемы при использовании анти-чита Reflex

### ISSUE THREAD

**Issue by Sitmobedaf** [ProtocolSupport/ProtocolSupport#289]
Если поставить Reflex на сервер с ProtocolSupport, то когда игрок пытается ударить по мобу, его кикает:
--------------------------------------------------------------
Smithfield lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
--------------------------------------------------------------
http://pastebin.com/hfZcep9T - PS log
Проверял только на мобах, и только на 1.7.2.

**Comment by Shevchik** [comment]
Reflex is not an opensource plugin, so can't help there.
