### ISSUE TITLE
Minecarts can cause a softlock, also other players see people switching between the wrong position and sitting

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#29]
In 1.5.2 when you enter a minecart everything appears fine at first (except being a bit lower than normal of course) however upon closer inspection your player is rapidly switching between the "Sitting in minecart" and "Standing looking at minecart" positions.  Because of this sometimes very rarely your player (the one in the minecart) gets teleported 2-3 blocks above the minecart and the game softlocks, as in everything is frozen except the chat (for that player).  Commands that kill the frozen player make the bone-breaking sound and health flashes however it does not seem to decrease or have any other effect.  Upon logging out and back in you get the "Game over" screen because the damage was actually applied and when you click respawn everything looks OK at first however other weird glitches arise such as you can't see projectiles in mid flight, falling sand disappears and re appears at bottom etc.
For other players, the player in the minecart is rapidly appearing riding the minecart and switching to a position in which he is standing close to the minecart and looking at it (constantly).  This can be verified by building a small minecart loop and running a cart inside it.  The player riding the minecart switches between looping around and being at the center and spinning around looking at the minecart.

If you stay in the minecart long enough (5 or 10 minutes) and press "Sneak" you might get a "End of stream" error

Glitched out of the cart
![Spazzing out](http://i.imgur.com/PlWLgSq.png)
Correct position inside the cart
![Sitting down!](http://i.imgur.com/kcmNC4t.png)

**Comment by Shevchik** [comment]
Don't have an idea why the hell it happens.

**Comment by Tom-III** [comment]
A possible fix would be to track players in the sitting position and boost them up a block or two by modifying their position packet to add +1 to their Y.  Also, is the player's stance supposed to change when they are in the riding position to adjust their collision box?

**Comment by Shevchik** [comment]
Didn't checked the stance, maybe it is important. But just fixing the height doesn't work at all, you still lag like hell. Probably we are missing something important.

**Comment by Tom-III** [comment]
The protocol wiki page is pretty incomplete and sometimes has wrong info, for example in 1.4.6 Packet Change Sepection in hotbar is two way but in 1.4.5 it's server to client but they have it always listed as two way.  The only way to be sure about the protocol is to use MCP and look at the packet files.  It also helps to use a tool that can highlight changes between files ( you can look at 1.5.2 and 1.6.2's packet.java file together).  If we are missing something it's probably hidden in one of those packet files

**Comment by Shevchik** [comment]
I chechked MCP. The problem is that there is the deffirence on packet handlers, not in packets.

**Comment by Tom-III** [comment]
NetClientHandler.java?

**Comment by Tom-III** [comment]
Idk why I did not think of this earlier, but have we checked if a 1.6 or 1.7 client sees them switching around and if a 1.5.2 client sees a 1.7 or 1.6 client switching?

So far I have only done tests with 1.5.2-1.5.2

(And 1.4.6-1.4.7 but that's out of the scope of this)

**Comment by Shevchik** [comment]
1.5.2 sees 1.8 switching around all the time. Didn't check other combinations.

**Comment by Tom-III** [comment]
So it must be the way packets are sent to 1.5.2, what did the 1.5.2 client see when the 1.8 client was in the cart?

**Comment by Shevchik** [comment]
More that 1 year passed, and i still have no idea how to fix this.

**Comment by robotman3000** [comment]
@Shevick Have you made any progress on this?

I had an idea, the description of the problem states that the bone breaking sound is played once the player is freed from the cart.  If I recall correctly, the bone breaking sound is played when the player collides with a block after falling.
So from that I conclude that the client thinks it is falling but at the same time it is riding the minecart entity. I have no idea how the client would get in this state but it is a valid explanation for the behavior described.

**Comment by EntryPointKR** [comment]
@Shevchik 
I found why it happens.
Below is a part of ItemMinecart class code

![ps](https://user-images.githubusercontent.com/16044565/39640742-e88fb08c-5006-11e8-975a-b5840767c210.png)

So each two version has the difference as much as 0.5 of y axis.
Then, the server would send EntityTeleportPacket every 20 seconds, and this makes the problem.

**Comment by Shevchik** [comment]
So we need to adjust position if player is inside the minecart.

**Comment by 7kasper** [comment]
The code above is from placing minecarts. However difference in server (and perhaps clientbound too) position difference might still be the problem.

**Comment by 7kasper** [comment]
@EntryPointKR btw have you joined the discord yet? I've seen you've been active here lately, but if you need any help in figuring out stuff or discussing about PS or something non-issue related we have an active community over there :smile:

**Comment by EntryPointKR** [comment]
And cause of the position problem is 1.12.2 sends PacketPlayOutMount(PLAY_SET_PASSENGERS) packet 3 times.

**Comment by Shevchik** [comment]
Well, this no longer occurs (except that on rejoin player looks flying in minecart, not sitting), so this can be finally closed.

**Comment by 7kasper** [comment]
Wooooo
