### ISSUE TITLE
Protocol Support 1.5.2 - 1.6.4 players crashing.

### ISSUE THREAD

**Issue by Thorney15** [ProtocolSupport/ProtocolSupport#292]
Hello, I have a network of servers and protocolsupport works perfectly on 90% of them. But a couple of server crash the players which are on 1.5.2 - 1.6.4 as soon as they try to join the server. I don't know what is causing it but here's a log.

1.5.2 crash log - http://pastebin.com/4x16p2SZ 

1.6.4 crash log - http://pastebin.com/iNBwfWsK

**Comment by Shevchik** [comment]
You have a world that has a non standard dimension. Stop server and check all worlds level.dat files.
Change all dimension ids that are not 1, 0, -1 to 0.

**Comment by Thorney15** [comment]
How do I do this? I open the level.dat file and it just brings up loads of random symbols.

**Comment by Shevchik** [comment]
You need nbt editor for that.

**Comment by Thorney15** [comment]
Ive opened the level.dat but I don't know how to change the dimension ids or what the dimension ids are

**Comment by Shevchik** [comment]
Found out that it is no longer here, so you will have to wait for a fix.

**Comment by Thorney15** [comment]
Ok how long do you think this will be bro?

**Comment by Shevchik** [comment]
IDK, the fix itself is 1 line, but i'm currently in the middle of refactoring some code, so i will have to finish it first.

**Comment by Thorney15** [comment]
Ok, hopefully it doesn't take too long. 👍

**Comment by Shevchik** [comment]
Okay, actually i just noticed that i already fixed dimension ids long time ago, so the problem is something else.

**Comment by Thorney15** [comment]
Ok when do you think this problem will be fix or when you'll be able to fix it.

**Comment by Shevchik** [comment]
Does this happen for those players  all the time or just sometimes?

**Comment by Thorney15** [comment]
All the time.

**Comment by Shevchik** [comment]
Give me your server address.

**Comment by Thorney15** [comment]
MC.pvpmasters.nn.pe:25566

**Comment by Shevchik** [comment]
Joined, but was unable to move, but didn't get that error.

**Comment by Thorney15** [comment]
You have to /register and join skyblock.

**Comment by Shevchik** [comment]
Okay, the dimension id reported is 15 for whatever reason. Try joining your skyblock server without bungeecord.

**Comment by Thorney15** [comment]
I tried to join on 1.5 without bungeecord and it still crashes the client.

**Comment by Shevchik** [comment]
I need a full server archive then.

**Comment by Thorney15** [comment]
How would I give you this?

**Comment by DaMatrix** [comment]
server archive would be _*ALL ZEH FILEZ*_

**Comment by Thorney15** [comment]
Ok, how do you want me to send the files?

**Comment by Shevchik** [comment]
Upload them to any file storage you want and give me the link

**Comment by Thorney15** [comment]
Ok I will upload them tomorrow

**Comment by Thorney15** [comment]
It's happening to 2 of my servers

**Comment by Thorney15** [comment]
@Shevchik 

https://filebin.net/anbnylofvbxsq5hn

**Comment by Shevchik** [comment]
That's an 1.8.8 server, i'm not supporting protocolsupport for 1.8.8.

**Comment by Thorney15** [comment]
Why? So you can't even fix my issue because it's a later version? I need this fixed it's a serious problem which is affecting my server... can't you just help me please?

**Comment by Thorney15** [comment]
Can you just have a little look into it please.
