### ISSUE TITLE
Invalid egg texture if display name is changed

### ISSUE THREAD

**Issue by FurmigaHumana** [ProtocolSupport/ProtocolSupport#293]
If you change anything in the egg metadata it won't display properly in any game version

![image](https://cloud.githubusercontent.com/assets/1264257/19455374/940d841c-949b-11e6-80a3-f2ef332b94de.png)

Game version: 1.10.2
Server version: 1.10.2-R0.1 (047f737-ae93d4f)
ProcotolSupport: #592

Same for throwable potions, they will only display properly if no metadata changes are made (displayname, lore, etc)

![image](https://cloud.githubusercontent.com/assets/1264257/19455503/f8496298-949b-11e6-8dee-6f3b573cce0b.png)

**Comment by Shevchik** [comment]
Unable to reproduce by renaming egg in anvil, or renaming lore using plugins.

Need more info on that. Which plugin do you use to change metadata?

**Comment by FurmigaHumana** [comment]
Sorry. turns out this happen in any spigot 1.10 alone, no plugins.
