### ISSUE TITLE
Objective already exists

### ISSUE THREAD

**Issue by Luuzzi** [ProtocolSupport/ProtocolSupport#294]
http://pastebin.com/6pgd1SHV

**Comment by Shevchik** [comment]
Don't think that it is protocolsupport issue.

**Comment by Luuzzi** [comment]
Wow, this is a problem. Okay, thanks

**Comment by Luuzzi** [comment]
On versions of the above - all OK

**Comment by Shevchik** [comment]
Scoreboard objective encoder is the same from 1.5.2 - 1.7, which means that 1.5 client has different logic for scoreboard handling, so i think that can't be fixed on protocolsupport side.

**Comment by Luuzzi** [comment]
Okay, thanks for support <3
