### ISSUE TITLE
Error spamming to server console related to API

### ISSUE THREAD

**Issue by VoidWhisperer** [ProtocolSupport/ProtocolSupport#296]
We've run into this issue with atleast 3 versions (4.24, 4.25-dev, and now the latest build #609 as of this issue)

Stacktrackes: http://hastebin.com/beyiraneta.vbs

That is the error we are getting. It just started happening recently.
Paperspigot version:
`
[09:37:40] [Server thread/INFO]: This server is running Paper version git-Paper-882 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
`

**Comment by Shevchik** [comment]
Run /ps list command and see if player settings that block is listed under any version.

**Comment by Shevchik** [comment]
I made changes to internal logic, so even if something fucks up network manager address, it will still return correct results when getting ProtocolVersion from Player, so this should work properly.
