### ISSUE TITLE
Проблемы совместимости с NoChestPlus

### ISSUE THREAD

**Issue by Sitmobedaf** [ProtocolSupport/ProtocolSupport#299]
Невозможно ходить по кувшинкам, и иногда по мятой траве. NCP блокирует движения за SurvivalFly. Без PSupport данной проблемы нет. Asofold пишет, что проблема в PSupport.

Ссылка на ответ разработчика NCP: https://github.com/NoCheatPlus/NoCheatPlus/commit/3d141f3125bb4ed2d88c419bf7282e4a36f5340c#commitcomment-19645509

**Comment by Sitmobedaf** [comment]
Не совсем понимаю, что он мне там написал, но он задел и тему распрыжек, это проблема у меня есть со многими анти-читами (NCP, AAC, AntiAura ...). Анти-читы ложно срабатывают на Speed, якобы клиент отправляет 30-40 move-пакетов, и это без читов, всё сам проверял. И ещё раз повторюсь -  с несколькими анти-читами.
Так же в AAC Glide постоянно срабатывает, практически при любых движениях, но я это не проверял без ProtocolSupport.

**Comment by Shevchik** [comment]
Там написано что делать.
