### ISSUE TITLE
Bow animation issue

### ISSUE THREAD

**Issue by FurmigaHumana** [ProtocolSupport/ProtocolSupport#301]
After commit [07f2867](https://github.com/ProtocolSupport/ProtocolSupport/commit/07f28677ec0a1263901257ffa162370a548e6619) bow animation is broken, not working in any game version.

At [abb3e14 ](https://github.com/ProtocolSupport/ProtocolSupport/commit/abb3e14b48704ccb8ad14dc31dfda94ff1290444) everyone could see the animation but not 1.10 clients, a few commits after that it started to stop working for a few game versions, the lastest build on jenkins nobody can see the animation not even from skeletons.

I compiled from [26d8b29 ](https://github.com/ProtocolSupport/ProtocolSupport/commit/26d8b294b9fdaf1a8351200f9adc5ae35e4a4f6c ) so its probably some changes before that

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by FurmigaHumana** [comment]
Yes partially, build #616 skeleton animation fixed, not yet for players, there is no animation when a player is shooting with a bow.

**Comment by Shevchik** [comment]
Easy to fix for 1.10 and 1.8, not so easy for other versions :(

tech info:
Starting from 1.9 eating/bow animation is drawn when active hand entity metadata is received, before that entity animation packet with id 3 was used. (id is is not used for swinging off hand).

**Comment by Shevchik** [comment]
Should now be fully fixed

**Comment by FurmigaHumana** [comment]
Thank you very much, tested and it is fixed indeed.
