### ISSUE TITLE
Errors io.netty.handler.codec.DecoderException

### ISSUE THREAD

**Issue by helptiger** [ProtocolSupport/ProtocolSupport#302]
Hi, we've got a lot of io.netty.handler.codec.DecoderException in our ProtocolSupport-errlog and I don't know what's the issue. Here is a small part of the logfile:
http://pastebin.com/3yk8j4hN
thx

**Comment by Shevchik** [comment]
No idea, seen the same in my log, but the packet reader is 100% correct. Unless you know the player which has this issue, i assume that is is some client with bad logic, or a network scanner that throws some random data at server, but for whatever reason this data looks close to minecraft protocol.
