### ISSUE TITLE
1.10.2 forge shows empty blocks

### ISSUE THREAD

**Issue by thomas15v** [ProtocolSupport/ProtocolSupport#303]
![Imgur](http://i.imgur.com/yhzvMwC.jpg)

I did some tests with moded and vanilla clients on my lobby server. And it looks like the forge client doesn't show the blocks. I don't really understand why it does that.

**Comment by DaMatrix** [comment]
probably some mod causing issues with block ids. try launching the client with no mods at all

**Comment by thomas15v** [comment]
@DaMatrix You are right, a plain forge version has no issue with this. But atm this has no functionality for me. I am trying to get 1.7.10 and 1.10.2 mod packs on the same lobby.

**Comment by Shevchik** [comment]
Most likely some mod doesn't init properly if the server is vanilla. Do a binary search to find out which, Anyway that is not a protocolsupport issue.

**Comment by hunter688** [comment]
I made some debug, removing mods step by step, and its random. With spigot 1.10+ProtocolSupport have no issues. there is no specific mod causing this.
