### ISSUE TITLE
Lilypads making lower versions (ex. 1.7) trapped with shaking screen when they are trying walking on it 

### ISSUE THREAD

**Issue by piter909** [ProtocolSupport/ProtocolSupport#305]
Lilypads making lower versions (ex. 1.7) trapped with shaking screen when they are trying walking on it.
It is because newest versions have disabled colisions with lilipads on water and it is impossible to walk on it, when on ~1.7 it was possible.
Is there any way to fix it?

**Comment by Shevchik** [comment]
It is already fixed, but your anticheat is blocking it. Configure it.

**Comment by piter909** [comment]
I am using nocheatplus. What option is blocking it? Do you know? 
Thanks for help.

**Comment by Shevchik** [comment]
See this nocheatplus commit description. https://github.com/NoCheatPlus/NoCheatPlus/commit/518f2f08dab4bc2d56b5e77b50ad073e3f8c8263

**Comment by piter909** [comment]
Thanks! It works..! But..
I have found another conflict or bug. When player is walking on blot called by bukkit enum "GRASS_PATH" or id: "108" , he is having same problems as he had with lilypad (he can not walk on it).
Thanks for your generous help :)!

**Comment by Shevchik** [comment]
Ask ncp dev about this, not me.

**Comment by piter909** [comment]
It can be ProtocolSupport bug, because this path is having less height than normal block (around 1/8 less, like soulsand). I can not test it without your plugin, because it will be impossible to connect via 1.7 or 1.8 ;/

**Comment by Shevchik** [comment]
Test without anticheat, it will work. Server only prevents players going thriugh blocks, not walking in air.

**Comment by piter909** [comment]
Ok, thanks :)
