### ISSUE TITLE
Invisible Shulker Boxes

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#313]
Shulker Boxes that exist before a chunk is sent to a player are invisible on an 1.10 client (they should display as enderchest)

If they are placed while the chunk is loaded they are visible as enderchest as expected

Version: v4.25.dev
Server: git-Paper-925 (MC: 1.11)

**Comment by Shevchik** [comment]
Actually now new blocks are properly remapped to old ones on chunk send for whatever reason.

**Comment by Brokkonaut** [comment]
The still are invisible in 1.10 or older clients if they existed before the chunk was sent to the client

**Comment by Shevchik** [comment]
Yeah, still no idea why only 1.11 blocks remap doesn't work.

**Comment by Shevchik** [comment]
Should be fixed now
