### ISSUE TITLE
Newly placed enchantment tables do not work

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#318]
If ProtocolSupport for 1.11 is on the server, newly placed enchantment tables do not work - if you put some item in, the 3 slots for enchanting stay empty.

If the plugin is removed the work again, but show no book above them.

Client: 1.11
Server: git-Paper-925, no plugins but ProtocolSupport

**Comment by Shevchik** [comment]
Injected with right name, now all enchantment tables don't work :(
Will have to check changes that mojang may have done to enchantment table.

**Comment by Shevchik** [comment]
Should be fixed now too

**Comment by Brokkonaut** [comment]
Thank you for the fast fixes :)

**Comment by Shevchik** [comment]
Close them if the fix did really work.
