### ISSUE TITLE
ProtocolSupport Lags near mob-spawners. 

### ISSUE THREAD

**Issue by FrukTik** [ProtocolSupport/ProtocolSupport#325]
ProtocolSupport Lags near mob-spawners.  Ver 1.10.2

https://youtu.be/c0k8aBOTbl4

**Comment by MrPowerGamerBR** [comment]
But it is FPS lag, how can it be ProtocolSupport's fault? (Well, unless PS is flooding packets, but I doubt that's the issue)

**Comment by Shevchik** [comment]
Because of unknown mob spawner nbt. It prints warning to log, which takes a shitload of time.

**Comment by FrukTik** [comment]
So now there is no stable support for previous versions. And you can, to fix it?

**Comment by Shevchik** [comment]
Found out why it happens, will fix it soon

**Comment by Shevchik** [comment]
Should be fixed now
