### ISSUE TITLE
[1.11] Empty world with 1.10 modpacks

### ISSUE THREAD

**Issue by dogboy21** [ProtocolSupport/ProtocolSupport#326]
We've updated our lobby from Minecraft 1.10.2 to 1.11 and also ProtocolSupport.
If i join our lobby with a 1.10.2 modpack no blocks will load.
With the 1.10.2 server and the 1.10.2 version of ProtocolSupport it worked fine. In 1.7.10 modpacks and 1.10 vanilla the blocks load fine with the 1.11 ProtocolSupport version.
![Screenshot](http://screenshots.myftb.de/hibTkq4j.png)

**Comment by hunter688** [comment]
I have same issue.

**Comment by CakeLancelot** [comment]
Might be a duplicate of #303

**Comment by Shevchik** [comment]
You will have to find out why that happens on your own, because i don't have time to debug why render breaks on forge client

**Comment by dogboy21** [comment]
I'll try to get an overview of the plugin. Maybe I can find something

**Comment by hunter688** [comment]
Its not only rendering bug, player when logged jumps on place and cannot move. It looks lke stuck when chunks not sent to client.

**Comment by dogboy21** [comment]
![](https://ss.myftb.de/hKfbQYTR.png)
Blocks receiving block updates render correctly. It's only the initial chunk data which is missing

**Comment by Shevchik** [comment]
Try logging in in area that consists of one block type only and then add more. ProtocolSupport uses global palette when sending chunks, maybe forge can't use when number of blocks registered missmatch between server and client (number of bits required to fit all blocks differ).

**Comment by dogboy21** [comment]
A region with only one block type doesn't help. Mods which add blocks seem to break ProtocolSupport. Btw, I pm'd you on Gitter

**Comment by Shevchik** [comment]
Which means that forge most likely doesn't like global palette.

**Comment by dogboy21** [comment]
Did you change something concerning the block palette? The 1.10 version of ProtocolSupport worked without any problem

**Comment by dogboy21** [comment]
[Minecraft Forge Issue](https://github.com/MinecraftForge/MinecraftForge/issues/3492), has nothing to do with ProtocolSupport

**Comment by hunter688** [comment]
With latest forge works! Thanks a lot for reporting to Forge.
