### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by NextPlayFF** [ProtocolSupport/ProtocolSupport#327]
1) Llamas are invisible (<1.11) also causing crash on <1.8
2) Can't set command in command block (<1.9)
3) Can't use brewing stand because that missing blaze powder slot (<1.9)
4) Nether wart block (wool) has red color when placed, but white in hand (<1.10)
5) Can't see EntityArmorStand holograms (<1.9) I tried use ProtocolSupportLegacyHologram but it doesn't work (What about detecting & remap hologram entity or creating built-in API?)
6) 1.4.7 support was dropped?
7) When I spawning vindicator players from 1.5.2 will be kicked. Also evoker attack will kick 1.5.2 players with same reason (Received string length longer than maximum allowed 39 >32 )
8) All horse types look as casual horse (<1.11). Also they causing crash on 1.5.2 (Skipping Entity with id 100)
9) What about making better items instead cobblestone?

**Comment by Shevchik** [comment]
1) Fixed
2) Will fix it later (lowest priority ever)
3) See ProtocolSupportBrewingStandFuel
4) Internal remapper doesn't support generic ata remap for itemstack right now, so it will be like that for a long time.
5) Works fine here
6) No, but i'm not testing < 1.7.10 when doing changes, but i managed to connect to server anyway, so it should still work.
7) Will check it later
8) Will be fixed soon
9) Suggest replacements then, i don't have time for that.

**Comment by NextPlayFF** [comment]
3. Thanks, now it works
5. Doesn't work with my custom holograms, but works with HolographicDisplays (I just switched to that)

10. Found crash with custom head texture on 1.7.7 and 1.7.8 (`com.google.common.util.concurrent.UncheckedExecutionException: com.mojang.authlib.yggdrasil.InsecureTextureException`)

**Comment by Shevchik** [comment]
Don't use custom head textures for 1.7.6, 1.7.7 and 1.7.8, they validated more strictly at those versions.

**Comment by Shevchik** [comment]
Please split the remaining issues to separate issues. Otherwise its hard to track them.

**Comment by Shevchik** [comment]
Fixed command blocks, now only 1.5.2 evoker attack issue left

**Comment by Shevchik** [comment]
Fixed evoker/villager. That was the last one bug you mentioned.
