### ISSUE TITLE
PVP: 1.9+ players have advantage

### ISSUE THREAD

**Issue by ethelcastano** [ProtocolSupport/ProtocolSupport#333]
Blocking is ineffective on players using 1.8 or below, which gives players using 1.9+ an advantage with shields. 1.9+ players can also use a sweep attack. When you fix, please make 1.8- players show blocking with shield to 1.9+ players. Thank you :). Also, when is the 1.11 version going to SpigotMC?

**Comment by Shevchik** [comment]
I'm not planning to fix that in protocolsupport itself, that will be done as a separate plugin when i have time. The release will be uploaded to Spigot when i will fix most issues.
