### ISSUE TITLE
Избавиться от поддержки 1.6.4 и ниже

### ISSUE THREAD

**Issue by Sitmobedaf** [ProtocolSupport/ProtocolSupport#335]
Никогда не видел на своих серверах клиентов ниже 1.7.2, у кого нибудь были? Плагин итак сложный, просто предлагаю больше не поддерживать старинные версии.

**Comment by Shevchik** [comment]
Due to the structure of the project maintaining those versions cost nothing, so there is no point in deleting the code. Also i'm not testing versions below 1.7 anyway.
