### ISSUE TITLE
1.11 enchantingtable issue. No suchField

### ISSUE THREAD

**Issue by i9hdkill** [ProtocolSupport/ProtocolSupport#336]
git-Spigot-f950f8e-b64d852 (MC: 1.11)
ProtocolSupport Build 645
Client: 1.10.2

Place an enchantingtable. Rightclick it and place an item in the enchant slot.

Error:
http://pastebin.com/JZ0SSQrj

**Comment by Shevchik** [comment]
Already fixed in build 646

**Comment by i9hdkill** [comment]
Oh, thx. Didn't see that commit.
