### ISSUE TITLE
Gamemode changed message

### ISSUE THREAD

**Issue by HAMMERxPL** [ProtocolSupport/ProtocolSupport#337]
Hi, when i'm on 1.10 server and i'm on 1.7 version i get 'Your gamemode has been changed' message twice.

**Comment by Shevchik** [comment]
Was unable to reproduce this, remove all your other plugins and try again.

**Comment by Cybermaxke** [comment]
In 1.7 was the 'Your gamemode has been changed' message client side, and in the latest versions server side. The message is only send when the `sendCommandFeedback` game rule is true.
The server shouldn't send the message to old clients.

**Comment by Shevchik** [comment]
Where exactly does server send a message? I wasn't able to find it in spigot source by inspecting CraftPlayer::setGameMode
