### ISSUE TITLE
1.11 server, 1.8/1.19/.10 clients. You cannot mine shulkerboxes

### ISSUE THREAD

**Issue by i9hdkill** [ProtocolSupport/ProtocolSupport#341]
Hi,
using latest spigot 1.11 and PS, but players are not able to mine shulkerboxes when not in 1.11.

Not sure if this is intended due to the complex functionality of that kind of chest/stash or is that an actual bug?

**Comment by Shevchik** [comment]
Most likely it is due to difference in block strengths, will have to find out another replacement block

**Comment by Shevchik** [comment]
Replaced with furnace, shold be correctly breakable now.

**Comment by i9hdkill** [comment]
Works, thank you!
