### ISSUE TITLE
Cannot connect 1.7.10 - says outdated client

### ISSUE THREAD

**Issue by tmoflash** [ProtocolSupport/ProtocolSupport#342]
As the title says I cannot connect to 1.7.10 Client to Spigot 1.11 using plugin. Tells me I am outdated. I did try 1.8 and it worked. Not sure what I am doing incorrectly. I tried a 1.7.10 Vanilla and a 1.7.10 Modpack both said the "Outdated Client"

I am using BungeeCord (latest version), Spigot 1.11, Plugin > Protocol Support (latest Version, that is the only plugin being used)

**Comment by Shevchik** [comment]
BungeeCord needs support for 1.7.10 too.

**Comment by tmoflash** [comment]
So you mean I need to put the plugin into BC also?
