### ISSUE TITLE
Invisibility is not applied to entities on 1.11.1 or higher clients.

### ISSUE THREAD

**Issue by Jalau11** [ProtocolSupport/ProtocolSupport#344]
Running the server on 1.11.2 and using ProtocolSupport will cause invisible armorstands to be shown visible to 1.11.2 clients but invisible to 1.11 and lower. Same for other entities with the invisibility potion effect. Removing ProtocolSupport will cause 1.11.2 clients to see the entities invisible again as intended.

**Comment by BiGUNMAN** [comment]
I can confirm this is an issue.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by lululombard** [comment]
Many thanks !
The last dev build fixed this issue, as well as a bug with elytra gliding ;)
