### ISSUE TITLE
Enchanting Broken

### ISSUE THREAD

**Issue by BiGUNMAN** [ProtocolSupport/ProtocolSupport#346]
Enchanting doesn't work. there are no errors in log. Here's a gif:
https://i.gyazo.com/747b72649a3fead19c9353a6276073f8.gif

**Comment by MrPowerGamerBR** [comment]
https://github.com/ProtocolSupport/ProtocolSupportEnchantingTable

**Comment by Shevchik** [comment]
ProtocolSupport no longer injects custom enchantment table. So whatever it is, it is not protocolsupport.

**Comment by BiGUNMAN** [comment]
Since when did it stop doing so? Just so I know if I should update my plugin or not.

**Comment by Shevchik** [comment]
7 days ago
