### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by xiTzJardix** [ProtocolSupport/ProtocolSupport#348]
Hi i had some questions about the notes that are in the README what do i need to change exactly?

`This plugin can't be reloaded or loaded not at server startup`
Does that mean late-bind needs to be false?

`This plugin doesn't work with netty native transport`
Do you still need to disable native transport in the server.properties?

What is required to change in the spigot settings to make this plugin work as best?

Thank you

**Comment by Shevchik** [comment]
1) No, it means that you can't reload the plugin via the /reload command and plugin managers.
2) Yes.

**Comment by xiTzJardix** [comment]
Oh okay thanks
