### ISSUE TITLE
Player disconnect on Login is handled uncorretclly

### ISSUE THREAD

**Issue by Xayanix** [ProtocolSupport/ProtocolSupport#349]
As in title, when using newest spigot build with newest ProtocolSupport and server is for example on whitelist, then i get kicked out of proxy (with correct reason) but it should just send message "Disconnected from server, reason: blabla". Just disallowing login events is handled as kick from server.

**Comment by Shevchik** [comment]
This is due to new logic handler which actually switches network to play stage. Will try to move PlayerLoginEvent to position where it doesn't happens yet.

**Comment by Xayanix** [comment]
Okay, thanks for reply and this awesome plugin.

**Comment by Shevchik** [comment]
Unfortunately i can't move the event and can't remove the API, so i guess i will have to write a bungee plugin that redirects player to the latest server if he was kicked before actual join.

**Comment by Xayanix** [comment]
My bad. Updated bungee and it's ok. :)
