### ISSUE TITLE
Eggs and snowball don't cause knockback on players.

### ISSUE THREAD

**Issue by JuliCarles** [ProtocolSupport/ProtocolSupport#350]
When using latest Dev build, snowballs and Eggs are not causing knockback to players on any version, this, causes issues on any anticheat and is causing kicks for AntiknockBack.

**Comment by haelexuis** [comment]
But it's true, my server has issue too (on SkyWars).

**Comment by JuliCarles** [comment]
Yes, and when removing ProtocolSupport the issue gets fixed.
I'm using ProtocolLib 4.2.1 btw. (latest spigot 1.11.2 server)

**Comment by helptiger** [comment]
We're also on both latest versions and knockback is fine as was before. Latest ncp as well. Maybe post a list of your plugins.

**Comment by JuliCarles** [comment]
SkinsRestorer, PowerfulPerms, MVdWPlaceholderAPI, Languages, OldPvP, PlaceholderAPI, MysteryBoxes, ConditionalCommands, AntiForceOP, ProtocolSupport, MysteryRewards, MultiSkyWars, ProtocolLib, AAC.
Here you are.

**Comment by helptiger** [comment]
After some testing I can confirm this issue. Knockback on mobs is fine but disabled on players. I can't say if it's related to ProtocolSupport.

Meantime you could use this little plugin. It adds little damage (you could adjust it) against players, so they will get knockback. https://www.dropbox.com/s/d60d2v76nplr8i6/ProjectileDamage-0.1.jar?dl=0

**Comment by FurmigaHumana** [comment]
Mojang removed knockback for 0 damage attacks, snowballs and eggs now deal no knockback. this has nothing to do with protocolsupport

**Comment by Shevchik** [comment]
According to this https://bugs.mojang.com/browse/MC-3179 0 damage attacks no longer knockback players. And protocolsupport never changed anything about that like i said,
