### ISSUE TITLE
Titles not works (from 1.11.2 server)

### ISSUE THREAD

**Issue by haelexuis** [ProtocolSupport/ProtocolSupport#351]
In spigot 1.11.2 is a method sendTitle(...)
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#sendTitle(java.lang.String,%20java.lang.String,%20int,%20int,%20int)
but not works on 1.10.2 clients and maybe lower versions of client.

**Comment by Shevchik** [comment]
Was unable to reproduce it, title shows fine. Try dumping the sent packet with protocollib, maybe only some specific values trigger the bug.

**Comment by haelexuis** [comment]
Hm, now I have latest version of server, protocolLib and protocolSupport and it works, so you can close it :)
