### ISSUE TITLE
Getting kicked from server when accessing a chest with /silentchest from OpenInv plugin enabled

### ISSUE THREAD

**Issue by vcdf** [ProtocolSupport/ProtocolSupport#353]
Spigot 1.11.2 server
MC 1.11.2 client
OpenInv 3.0.5 https://dev.bukkit.org/projects/openinv/files/2361658
Lastest ProtocolSupport development build.
This bug only happens if ProtocolSupport is enabled.

Error message on console:
CONSOLE: [INFO] <player name> lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Don't know how to convert container.chest

**Comment by Shevchik** [comment]
Container.chest is not a valid inventory name.
