### ISSUE TITLE
Double passenger boats dont work

### ISSUE THREAD

**Issue by Legoman99573** [ProtocolSupport/ProtocolSupport#355]
When i try to ride a boat with my wolf, i cannot hop on. Is that a bug or is it intentional in 1.9 and up? Couldnt 1.8 make double boats?

**Comment by Shevchik** [comment]
Intentional, clients < 1.9 can't use double boats.

**Comment by Legoman99573** [comment]
Is there an add-on to allow it? I dont want to downgrade tbh. Most like the passenger for wolves as they dont swim there. Can i make it a suggestion?
