### ISSUE TITLE
Potions do not have metadata in 1.8 and below

### ISSUE THREAD

**Issue by MeltedLux** [ProtocolSupport/ProtocolSupport#357]
1.9+: 
![xc0kxknw48g1](https://cloud.githubusercontent.com/assets/7466824/21964310/a42becfc-db41-11e6-8a88-0c03b3a8ab83.png)

1.8 and below: 
![il0vagmmtzyo](https://cloud.githubusercontent.com/assets/7466824/21964306/977550d4-db41-11e6-8584-580a47400c5e.png)

**Comment by Shevchik** [comment]
Use nbt explorer to get nbt, and put it here.

**Comment by Shevchik** [comment]
Closed due to inactivity
