### ISSUE TITLE
No item pickup sound on 1.8-1.8.9

### ISSUE THREAD

**Issue by Sitmobedaf** [ProtocolSupport/ProtocolSupport#359]
Использую не самый последний билд.

**Comment by Sitmobedaf** [comment]
Нет звука когда подбираются предметы.

**Comment by kamcio96** [comment]
English?

**Comment by Sitmobedaf** [comment]
Проверил с последним билдом ProtocolSupport, проблема актуальна (нету звука при подборе предметов).

**Comment by Shevchik** [comment]
Provide a full list of sounds that are missing. ALso check client console, it should notify about unknown sound if it is not remapped.

**Comment by maxim19116** [comment]
Это не из-за protocolsupport, а так-же пиши на английском впредь.

**Comment by Dimatert9** [comment]
Почему он должен писать на английском если на русском легче описать проблему и более подробно?

**Comment by Shevchik** [comment]
Because i may stop developing PS any time, and issues in language that is not understood by the next maintainer will be closed obviously.

**Comment by Dimatert9** [comment]
Ну а если у человека проблемы с английским, и он не может нормально написать, что случилось то, что? Ему чтоли плакать в подушку и ждать пока ктото другой наткнётся на эту ошибку и соизволит написать её сюда?

**Comment by Sitmobedaf** [comment]
В логах никаких ошибок не нашёл @Shevchik.

**Comment by Shevchik** [comment]
If he has problems with english, he must learn english then. I will no longer accept not english bug reports from now on.

**Comment by Dimatert9** [comment]
Вот я не понимаю твою логику. Почему человек, зная что ты понимаешь русский,  должен писать проблему на языке который он не знает? Ведь  русский язык поидее твой родной язык, так почему ты пытаешся его избегать? Ведь если человек нашел ошибку он ведь должен хоть както ее донести до тебя, а не ждать пока пройдет месяц и ее кто-то другой зарепортит ее на английском языке и объяснит как ее воспроизвести.

**Comment by BeYkeRYkt** [comment]
Он же ранее писал, что может в любой момент бросить PS и следующий разработчик может быть не русскоязычным (англоязычный например), и он может забить болт на баги в других языках. Ну или если шевчик не сможет по каким-либо причинам пофиксить этот баг, то может заграницей кто-то сможет.

**Comment by Dimatert9** [comment]
Я это читал. Только мне почемуто кажется, что если он бросит этот плагин, то обновлять его наврятли кто-то будет, а если и будет то тогда и перестанут сюда писать по русски. А попросить описать проблему на англ в текущих репортах не сложно будет.
Да и баги никто и не фиксит из репортов, обычно если только сами нашли , то сами и пофиксили, а задно реквест создали. А так чтобы ктото чекал и фиксил таких вроде тут нет.

**Comment by EntryPointKR** [comment]
@Shevchik 
1.8 seems to send a **PacketPlayOutNamedSoundEffect** packet when item pickup.
What do you think?

**Comment by Shevchik** [comment]
So mojang screwed pickup effect at 1.8. I'm not surprised any more.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by Sitmobedaf** [comment]
Звук подбора предметов есть, а вот опыта - нет.

**Comment by Shevchik** [comment]
There is no event for exp pickup, so i guess it will stay like that until a workaround is found.

**Comment by Shevchik** [comment]
Fixed.
