### ISSUE TITLE
error server pinger isonline

### ISSUE THREAD

**Issue by Diclo** [ProtocolSupport/ProtocolSupport#360]
[http://pastebin.com/raw/t20DHW0N](url)

**Comment by Shevchik** [comment]
Try removing all your other plugins, i'm unable to reproduce this, and error shows that an empty buffer was somehow passed to the pipeline, which shoudn't occur normally.

**Comment by Diclo** [comment]
Thanks a lot for the prompt response and apologies for the inconvenience, after reviewing every plg, I found out that protocolib was the problem, but it was my mistake since I first check if there was no update and when I update the problem solved.
