### ISSUE TITLE
NoCheatPlus slab movement error

### ISSUE THREAD

**Issue by Jafforo** [ProtocolSupport/ProtocolSupport#362]
I'm getting bugs with nocheatplus and the protocolsupport. It keeps sending player back on slabs. I'm using the latest nocheatplus (and with compact / also same issue with just nocheatplus) The server jar is: http://prntscr.com/dzf12z

Here's what the bug looks like: https://youtu.be/KhEQbyM5QVM

**Comment by Shevchik** [comment]
Update to 1.11 and try again. Also try updating NoCheatPlus.

**Comment by Jafforo** [comment]
I tried with 1.11 it caused issues, but I just found there was a 1.10 version of NCP, so resolved.
