### ISSUE TITLE
Books created in 1.8 have broken content

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#363]
If you create a book in 1.8 and sign it, newlines appear as "\n" in the text and some characters display as "\u003d" and similar and there are double quotes around the whole text.

**Comment by MrPowerGamerBR** [comment]
Can confirm, 1.8.9:
![http://i.imgur.com/jq84Pek.png](http://i.imgur.com/jq84Pek.png)
![http://i.imgur.com/QMB1Q0e.png](http://i.imgur.com/QMB1Q0e.png)
![http://i.imgur.com/GH33CjF.png](http://i.imgur.com/GH33CjF.png)

**Comment by Shevchik** [comment]
Books in 1.8.9 are written using json components, while at later versions they are just raw strings.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by EntryPointKR** [comment]
@Shevchik Crash when book open

[06:00:22 INFO]: EntryPoint lost connection: Internal Exception: io.netty.handler.codec.DecoderException: protocolsupport.libs.com.google.gson.JsonSyntaxException: protocolsupport.libs.com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $
[06:00:22 INFO]: EntryPoint left the game

**Comment by Shevchik** [comment]
Which version?

**Comment by EntryPointKR** [comment]
Client 1.8.9
Server 1.11.2 PaperSpigot

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by EntryPointKR** [comment]
1.8 is fixed but 1.4 ~ 1.7 is crash.

**Comment by Shevchik** [comment]
Should be fixed now.
