### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sitmobedaf** [ProtocolSupport/ProtocolSupport#365]
Look this - http://pastebin.com/dMnp8v7r

**Comment by Shevchik** [comment]
Don't replace jars at runtime.

**Comment by Sitmobedaf** [comment]
Я и не заменял

**Comment by Shevchik** [comment]
You certainly did. This class is only present at non latest dev build of PS, so NCDF excpetion can be caused by 2 reasons: You replaced ProtocolSupport jar while server was running, so jvm lost a link to file and wasn't able to load class, or you deleted this class from jar manually.
