### ISSUE TITLE
Incompatible with Lilypad

### ISSUE THREAD

**Issue by Mikgreg** [ProtocolSupport/ProtocolSupport#370]
Hi there,

Been running ProtocolSupport fine on one of my servers on my network the past week or so and been amazed at how stable it is. I updated my plugin to the latest version the other day and it doesn't seem to let people join anymore. 

https://hastebin.com/gunuhofuwa.md

Let me know if this is something I should talk to lilypad about and not you guys :)

**Comment by Shevchik** [comment]
Plugins that inject into the network generally won't be compatible with each other. Nothing can be done here. Lilypad guys can try to use ProtocolSupport api, maybe it can do what they need.
