### ISSUE TITLE
Cannot connect to 1.11.2.

### ISSUE THREAD

**Issue by Zilacon** [ProtocolSupport/ProtocolSupport#372]
Using Hexagon Bungee and PaperSpigot with ProtocolSupport and the server does not show up when pinged and cannot connect to it. I have updated protocolsupport, bungeecord, and paperspigot to latest releases no changes. Hexagon Bungee said its an issue with Protocol Support.

Disabled ProtocolSupport and started server same issue, IDK why they claim its ProtocolSupport but if its not enabled and its still having the issue i dont think thats the case.

**Comment by Shevchik** [comment]
Remove ProtocolSupportBungee
