### ISSUE TITLE
Kick: Invalid book data!

### ISSUE THREAD

**Issue by govnojon** [ProtocolSupport/ProtocolSupport#373]
1. The books can not write.
2. When signing kicked from server error (see picture).
In the console:
[05:48:55] [Server thread / INFO]: Lokha lost connection: Invalid book data!
[05:48:55] [Server thread / ERROR]: Lokha / InvalidBookSign: Invalid book tag!
![image](https://cloud.githubusercontent.com/assets/18377011/22536798/684542c2-e90d-11e6-8338-3c556e6d79fb.png)

**Comment by govnojon** [comment]
Server Version: PaperSpigot 1.11.2
Client Version: Any
Plugin Version: The last of Jenkins

**Comment by govnojon** [comment]
hell, already have such a task. how soon will be fixed?

**Comment by BestMark** [comment]
I have same issue. Please, resolve it.
