### ISSUE TITLE
Generating a error log (Exception message: 69 is not a valid packet id):

### ISSUE THREAD

**Issue by M9GLiquid** [ProtocolSupport/ProtocolSupport#376]
[http://pastebin.com/xW6dXC68](PasteBin)
Spigot Version: 1.11.2 #83 Behind...
... Bungee Version 1.11.2 #1222
Need any more information please do bug me :)

Regards,
Thomas

**Comment by Shevchik** [comment]
You were pinged with something that is not minecraft.
