### ISSUE TITLE
Protocol Version

### ISSUE THREAD

**Issue by DrJedikiah** [ProtocolSupport/ProtocolSupport#377]
Hi, maybe that's not an issue but I have a question.
Can I change my server's protocol version with this source? Because I want to make something different and I wanna make it only accessible on 999(maybe?) due preventing connection with an unmodified client.

**Comment by kamcio96** [comment]
Yea, you can clone and edit source 😄 You can also do it with craftbukkit/spigot/paperspigot source

**Comment by DrJedikiah** [comment]
Yeah but I think its very hard to edit. I tried BuildTools but it checks the hash of server jar.

**Comment by Shevchik** [comment]
Just use protocollib.

**Comment by DrJedikiah** [comment]
Thanks. Your code is amazing, I'm starting to get it how to use protocol lib.
