### ISSUE TITLE
Error stopping server

### ISSUE THREAD

**Issue by NEZNAMY** [ProtocolSupport/ProtocolSupport#379]
On server startup, I sometimes get this error and server instantly shuts down.

http://prntscr.com/e677zy

It's extremely rare so basically unable to reproduce if you need it.

**Comment by Shevchik** [comment]
And uninitialized connection was added to a list. Set late-bind to true so connections can't be established before ProtocolSupport fully injected.

**Comment by Shevchik** [comment]
Should be fixed now
