### ISSUE TITLE
Vexes are shulker bullets to 1.11.2 clients

### ISSUE THREAD

**Issue by RoboMWM** [ProtocolSupport/ProtocolSupport#380]
I'm guessing these random floating shulker bullets are supposed to be vexes, but I'm not sure. Server is running paper 1.11.2, client is running 1.11.2 (with optifine).

If more details are needed, I'll be happy to provide

**Comment by Shevchik** [comment]
Mobs are not remapped for 1.11.2. You will have to use some sort of serverside entity scanner to find out what is that.

**Comment by RoboMWM** [comment]
Well, turns out a plugin I was blindly slipped in this neat little feature. https://github.com/oshcon/ProjectKorraMobs/blob/5da87480135d4ae7fd81cfd298e3e78145ba1d69/src/main/java/com/jedk1/projectkorra/mobs/listener/MobListener.java#L104

TL;DR, no issue with ProtocolSupport
