### ISSUE TITLE
Sponge API

### ISSUE THREAD

**Issue by ArcasCZ** [ProtocolSupport/ProtocolSupport#383]
Good day,

I want to ask you if you will port this plugin to SpongeAPI, 'cause lot of functions are not included in basic Sponge API.

**Comment by Shevchik** [comment]
Not BukkitAPI platfroms are not supported and never will.

**Comment by ArcasCZ** [comment]
Why? Sponge is way much better API than Spigot / Bukkit, 'cause gives you more events, better compatibility with mods and allows NMS in such better way...

**Comment by DaMatrix** [comment]
Sponge has bad support, few other plugins, and is horribly inefficient. No.

**Comment by ArcasCZ** [comment]
But is there any other option than Sponge for me, if I have to run Forge server with plugins on 1.10? There's no server core for this...

**Comment by Shevchik** [comment]
No, SpongeAPI is not better, it's the same, just named differently and over engineered. Not worth porting to it.
Compatibility with mods - i don't care at all (why would you even care about this, you won't be able to use a mod on outdated client when connecting to the latest server).
Also sponge is actually spongeforge which is horribly slow and spongevanilla which never works right.

**Comment by ArcasCZ** [comment]
I know you don't care, but in Czech republic I can't do just spigot server, 'cause vanilla is boring and there are lot of servers with minigames. So I decidet to do modded servers with plugins, but here comes the problem - I'm stucked on 1.7.10 and there's no core for 1.10, which supports Forge and Spigot API. So, I'm asking you if you don't know any better core than Sponge?

**Comment by Shevchik** [comment]
YOu don't need a ProtocolSupport for modded server, it will never work anyway.

**Comment by DaMatrix** [comment]
What Shevchik is saying is that there are no multiversion mods around. So even if you got ProtocolSupport working on forge, you still wouldn't be able to connect because the mods would be different versions.

**Comment by ArcasCZ** [comment]
Actually, at 1.7.10 Thermos ProtocolSupport works well and I use FastAuth based on this plugin, so...

**Comment by Shevchik** [comment]
Use FastLogin then.

**Comment by ArcasCZ** [comment]
FastLogin is based on ProtocolSupport, 'cause uses it's event to change online-mode to true or false.

**Comment by Shevchik** [comment]
It's can work without protocolsupport.

**Comment by ArcasCZ** [comment]
Oh, I found out that it has alternative - ProtocolLib. But same problem here :D

**Comment by Outfit8TSB** [comment]
WE SUPPORT SPONGE!
RIP BOZO! :skull:
![image](https://github.com/user-attachments/assets/93097cfd-bc4f-4452-9cdc-b6360792e1fe)
ProtocolSupport/ProtocolSupport = 🤡 BOZO
GAME-CLI-SRV-DEV/ViaVersionProtocolSupport = Σ Sigma

i called ProtocolSupport a Bozo, because PS is Based Off NMS. So It Does Not Work On Proxy Like Bungeecord. also, PS is not works With Floodgate and ProtocolSupportBungee Blocks Floodgate. Even Worse, it does not support Sponge or Rainbow, nor run with ViaVersion. That is So Tragic.
