### ISSUE TITLE
Render and crash issues with new items

### ISSUE THREAD

**Issue by FurmigaHumana** [ProtocolSupport/ProtocolSupport#384]
New blocks can crash or cause render issues when dropped or while being held in hands by a 1.11 player near a 1.8.9 player, other versions might be affected aswell, this can be easily reproduced by doing this:

1. take a new block, which can be seen in the image below it is properly being remapped without issues.
![image](https://cloud.githubusercontent.com/assets/1264257/22899554/61442912-f212-11e6-8cf4-a7fa37eff5a6.png)

2. If the 1.11 player put that item in hands while near an 1.8.9 player, the older player will have several render glitches
![image](https://cloud.githubusercontent.com/assets/1264257/22899599/868e8258-f212-11e6-90bb-44c23aea3230.png)

3. if the 1.11 player proceed to drop that item near the other player, that player will instantly crash.
crashlog: http://pastebin.com/Jq9V3wPj

**Comment by Shevchik** [comment]
Strange, i'm sure it was remappend.

**Comment by FurmigaHumana** [comment]
Sorry, this is fixed on the latest build on jenkins, maybe it was broken only in one or two builds.
