### ISSUE TITLE
Glowstone version

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#385]
Which version of glowstone is protocolsupport compatible with?
Also, since glowstone is not based on minecraft server or craftbukkit couldn't Protocolsupport be implemented into glowstone as a core-feature?  It would give glowstone a huge advantage over any other software, knowing that multiversion is part of the server itself.

**Comment by Shevchik** [comment]
The latest one. Implementing as a core feature isn't worth it, too much maintaining cost (merging all changes to another project) for no advantages.
