### ISSUE TITLE
Run on BungeeCord

### ISSUE THREAD

**Issue by DaMatrix** [ProtocolSupport/ProtocolSupport#386]
I'm not sure if this has been asked yet or not, but I'm going to put it out there again even if it has: will there ever be a way to PorotcolSupport to run ONLY on bungee, and not have to install it on all subservers? There are two key advangates of this that I can see:
 - Players would be able to connect to servers that haven't updated to newer versions
 - All alternate server softwares would be able to use ProtocolSupport (e.g. Cuberite (C++))

Thanks, and again sorry if this has already been asked.

**Comment by Shevchik** [comment]
No/
