### ISSUE TITLE
Constant error in the console

### ISSUE THREAD

**Issue by Johandrex** [ProtocolSupport/ProtocolSupport#390]
I'm constantly receiving the error down below, in my console. It's litteraly impossible to view anything else in the console but that error. I'd be greatful if you could fix it.

Version: Build 13
Error: https://hastebin.com/azesidibew.bash
ProtocolSupport-errorlog: https://hastebin.com/emirevoguv.lua

**Comment by Shevchik** [comment]
Something fires an event for non connected player, or the player remote address change via non bungee way.

**Comment by Shevchik** [comment]
Most likely same as #393

**Comment by Johandrex** [comment]
Appears to be working fine after updating NameTagEditAPI.
