### ISSUE TITLE
BlockPlaceEvent error in console

### ISSUE THREAD

**Issue by TWSSYesterday** [ProtocolSupport/ProtocolSupport#393]
https://hastebin.com/qusikawesu.vbs is the error, I'm using paperspigot #1059 and currently latest bar one of PS on jenkins.

**Comment by Shevchik** [comment]
Do you have bungee?

**Comment by TWSSYesterday** [comment]
No bungee

**Comment by TWSSYesterday** [comment]
I am using ProxyPipe though for DDoS protection

**Comment by Shevchik** [comment]
I guess it changes the player remote address which causes this issue.

**Comment by TWSSYesterday** [comment]
Any way to ignore that or have a bypass?

**Comment by Shevchik** [comment]
No because it breaks a lot of things not just this one. You will have to patch ProxyPipe plugin to change player remote address using ProtocolSupport API.

**Comment by TWSSYesterday** [comment]
@coelho maybe could bring some of his insight into this

**Comment by Shevchik** [comment]
The main problem is that there is no way to get notification about network manager spoofed remote address change which produces incompatibilities between plugins.

**Comment by TWSSYesterday** [comment]
Obviously since this is spamming console it's quite irritating, any work around?

**Comment by Shevchik** [comment]
Remove protocolsupport or proxypipe, no other choice. As i already said a shitload of other things stop working if player address changes not by protocolsupport, this may even result in unrecoverable damage to userdata.

**Comment by Shevchik** [comment]
I tried to reach spigot with this problem, but no luck: https://hub.spigotmc.org/jira/browse/SPIGOT-3080

So i guess nothing can be done here, those plugins will have to use ProtocolSupportAPI, or you will have to remove ProtocolSupport or that plugin.

**Comment by TWSSYesterday** [comment]
Thanks very much for your help anyway

**Comment by coelho** [comment]
@Shevchik I think using the SocketAddress as a key in the ProtocolStorage is a pretty awful idea to begin with. ViaVersion does not break at all by the usage of ProxyPipe's plugin, and the fact we have to compensate for bad design in this case is pretty silly to have to agree.

ProtocolSupport is constantly a moving target. I even have code to compensate for it in LilyPad, and when you guys make a breaking change for no reason, I have to compensate again. My code works with ProtocolLib. 

My code works with ViaVersion. My code works with every other plugin on the face of the earth that touches the protocol. Why not ProtocolSupport?

That's my only beef with this project. I'm a little bit annoyed by getting blamed for your guys incompatibility :)

**Comment by Shevchik** [comment]
It's the worst idea i ever had, but it was the only way out back then. And now there is an API that accepts socket address as a parameter which i can't remove due to backwards compat. And unfortunately spigot decided to do nothing about remote address change notifications. The partial solution is to use raw address instead of spoofed one as a key (but still additionally use spoofed due to backwards compat).
