### ISSUE TITLE
Compacted version

### ISSUE THREAD

**Issue by nerdtron123** [ProtocolSupport/ProtocolSupport#396]
Hello developer, for my server I only need something that allows 1.8 clients along with the 1.10 clients I have right now. I don't want anything else to be in there such as debug mode etc. If you cannot do this can you tell me what I need to get in order to only take that and support only those versions?

**Comment by EntryPointKR** [comment]
You can use [this](https://github.com/EntryPointKR/ProtocolSupportController/releases)
