### ISSUE TITLE
NullPointerException when PlayerInteractEventityEvent 

### ISSUE THREAD

**Issue by HardwellMC** [ProtocolSupport/ProtocolSupport#397]
Hello, i'm getting this error on my console sometimes (I'm using the latest version of the time if you see):
![61a292e1baf29f55acfdf1e366c6367e](https://cloud.githubusercontent.com/assets/25549828/23165993/83996804-f81d-11e6-8102-30d78a00dc51.png)
There's nothing much to say about that so... thanks and best regards :)

**Comment by Shevchik** [comment]
Should be fixed now
