### ISSUE TITLE
Possibly broken 1.6 support?

### ISSUE THREAD

**Issue by Speentie8081** [ProtocolSupport/ProtocolSupport#399]
Versions 1.4, 1.5, 1.7, 1.8, 1.9, 1.10, 1.11 all work fine on my public server.
But, when you join on 1.6, you cannot see a single thing, its all void.
I mean, sometimes for a split second you can see land, but that's it really.

The address is skorrloregaming.ddns.net:25565 if you want to experience this first hand.

Chat, commands, sounds, tab complete, everything you could thing of works.
Just nothing shows up on screen for 1.6 in my case? I even tried using forge and MultiMC.

No errors occur in console, nothing. It may also be worth noting we don't have ProtocolLib installed.
I will reply back to this thread in the morning, about if any problems are lifted by using ProtocolLib.

**Comment by Shevchik** [comment]
Confirmed on a local server

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by Speentie8081** [comment]
Issue resolved, thanks for the help. Simple bug probably, since it was fine a week or two ago on 1.11.0.
