### ISSUE TITLE
Quartz blocks are invisible for 1.4.7 clients (Quartz was released in 1.5)

### ISSUE THREAD

**Issue by Speentie8081** [ProtocolSupport/ProtocolSupport#400]
Quartz blocks are invisible for 1.4.7 clients (Quartz was released in 1.5).
Could you replace Quartz blocks for 1.4.7 clients with something more friendly like snow or wool.
This is a problem, since the default roads for PlotSquared are quartz, yes...
Since Quartz blocks are invisible for 1.4.7 clients, the roads show as an endless pit.

**Comment by Shevchik** [comment]
Should be fixed now
