### ISSUE TITLE
enderchest not  visible

### ISSUE THREAD

**Issue by caspervanneck** [ProtocolSupport/ProtocolSupport#403]
do you know how to fix on de mcpe branch

**Comment by MrPowerGamerBR** [comment]
@caspervanneck MCPE branch is in early development and it is even uncertain when it is going to be finished.

Of course Shevchik knows that a lot of things in that branch is broken and creating issues for every single thing you find broken in that issue will only flood the ProtocolSupport repo with useless issues.

**Comment by caspervanneck** [comment]
ok @MrPowerGamerBR ):

**Comment by Shevchik** [comment]
All blocks that has tiles are invisible actually, because tile nbt sending is not implemented yet. Nothing except basic chunks and movement is implemented yet.
