### ISSUE TITLE
Issues with horses

### ISSUE THREAD

**Issue by SofieHL** [ProtocolSupport/ProtocolSupport#404]
1.10 or 1.11 server with 1.8.9 client: players cant see saddles on horses, open horse inventory, or ride horses.

**Comment by Speentie8081** [comment]
Yeah this has been coming up a lot lately, though, it doesn't bother me personally.
Also that #404 number though on this issue thread, so funny.

**Comment by CakeLancelot** [comment]
The README states:

> Known wontfix issues:
>     [1.8 and earlier] Can't control vehicle

Now if this applies to horses I'm not sure - the bugs involving inventory and saddles are probably valid though.

**Comment by Shevchik** [comment]
Duplicate of already existing bugs, horses meta is unimplemented.
