### ISSUE TITLE
MCPE?

### ISSUE THREAD

**Issue by NycuRO** [ProtocolSupport/ProtocolSupport#408]
You can continue MCPE branch ,please?

**Comment by kamcio96** [comment]
https://github.com/ProtocolSupport/ProtocolSupport/tree/mcpenew
Hmm, I think it's in progress :wink:

**Comment by NycuRO** [comment]
@kamcio96 You can help me how work "ProtocolSupport" ? Is one proxy-server for protocol adaptage or?

**Comment by kamcio96** [comment]
Put it in plugins folder.
Use forum for support: https://www.spigotmc.org/resources/protocolsupport.7201/

**Comment by NycuRO** [comment]
@kamcio96 Ohh, is spigot plugin?

**Comment by NycuRO** [comment]
@Shevchik Is spigot plugin?

**Comment by kamcio96** [comment]
Yes

**Comment by NycuRO** [comment]
Ok
