### ISSUE TITLE
Minecraft PE: Cannot teleport -- game crashes

### ISSUE THREAD

**Issue by Speentie8081** [ProtocolSupport/ProtocolSupport#409]
Once you get teleported on Minecraft PE, the game crashes.
Another issue, once the game crashes, the player is not disconnected from the server.
Props on adding almost everything already to the Minecraft PE though.

EDIT: The crash is not absolutely guaranteed, I can sometimes get through without crashing.

**Comment by Shevchik** [comment]
Usually  don't crash, but sometimes i get a game freeze.

**Comment by Speentie8081** [comment]
Yeah it seems to not crash now, maybe a one time thing for me, or I just messed up something
