### ISSUE TITLE
Minecraft PE: Executing commands -- flooded chat

### ISSUE THREAD

**Issue by Speentie8081** [ProtocolSupport/ProtocolSupport#410]
On my Android tablet when executing commands on PE, it floods chat.
I mean the commands "work", but the messages are all jumbled up and repeated.

**Comment by DaMatrix** [comment]
Can we have a screenshot?

**Comment by Speentie8081** [comment]
Sure one second

**Comment by Speentie8081** [comment]
![screenshot_2017-03-08-11-05-27](https://cloud.githubusercontent.com/assets/12576827/23711979/5dfeb710-03ef-11e7-8bb4-08acf7e2ed66.png)

**Comment by Speentie8081** [comment]
![2017-03-06_20 17 59](https://cloud.githubusercontent.com/assets/12576827/23712044/3559eb8e-03e7-11e7-9777-c7a96c6b17f8.png)

This is how it is supposed to look

**Comment by DaMatrix** [comment]
Yeah, that's a bug with MCPE (it happens on Nukkit and PocketMine servers too). Closing the chat window and re-opening it fixes that. (AFAIK)

**Comment by Speentie8081** [comment]
Hmm, that does seem to resolve that issue, interesting.

**Comment by caspervanneck** [comment]
@Speentie8081 how do command for /help dont work

**Comment by Speentie8081** [comment]
> @Speentie8081 how do command for /help dont work

You type "./help" in chat not "/help" for now.
