### ISSUE TITLE
Cant run and can not walk on stairs and slabs

### ISSUE THREAD

**Issue by caspervanneck** [ProtocolSupport/ProtocolSupport#411]
If I run with mcpe I can't move on the newmcpe beanch

**Comment by caspervanneck** [comment]
And can not walk on slaps an stairs

**Comment by Speentie8081** [comment]
To be more specific, you can walk on slaps and stairs, but once you do you constantly get teleport-ed back to that block (roughly every 20 ticks). Also @Shevchik knows about the cannot run glitch, but that is not his highest priority right now fyi.

**Comment by caspervanneck** [comment]
@Speentie8081 ok (:

**Comment by Shevchik** [comment]
PE issues don't go there, only at discord, because everything may change any moment.
