### ISSUE TITLE
Not showing version

### ISSUE THREAD

**Issue by Mikgreg** [ProtocolSupport/ProtocolSupport#412]
Hello!

I've updated my ProtocolSupport recently and after the update BlockVersion and ClientStats don't see which version people are connecting with anymore. Everything just shows as "unknown". I've updated both of these plugins too and it doesn't seem to fix it.

Is this an issue on ProtocolSupport's end or the other plugins? I posted here because both of them broke simultaneously.

PS version: 4.26.dev
Spigot ver: Paper 1062

**Comment by Shevchik** [comment]
You have some other plugins that change player remote address via non bungee way.

**Comment by Shevchik** [comment]
So, which plugin was that?

**Comment by Mikgreg** [comment]
Sorry for not responding, I kinda thought your previous comment was to close the issue.

I assume the plugin causing the issue is bukkit-connect (lilypad).

**Comment by Shevchik** [comment]
Yeah, now way to fix that on my side.
