### ISSUE TITLE
Failed to parse chunk data

### ISSUE THREAD

**Issue by RoboMWM** [ProtocolSupport/ProtocolSupport#413]
Happened randomly to me, not sure how to reproduce but yea.

https://gist.github.com/RoboMWM/60f579ceccbf4204cc8eb7d63e2b3ada

**Comment by Shevchik** [comment]
Also paste the stacktrace

**Comment by Shevchik** [comment]
The second chunk sections reports having 34 bits per block, which is not a valid value. Check your plugins, maybe on of them sends chunk data manually and fails to do that.

**Comment by RoboMWM** [comment]
I recall it happening during nighttime, though I don't know if day/night cycle is of any concern for skylight calculations. I'm not aware of anything that sends chunks, and there was no teleportation occurring at this time. The chunks were newly generated, though (still haven't pregenerated my world, and random teleport will often place a player in unexplored land).

**Comment by Shevchik** [comment]
Skylight data is present only in overworld (0 dimension id), and not present in others. So the reason is the world teleportation (or rogue dimension switch packets, but they should reload chunks so it's noticeable).

**Comment by Shevchik** [comment]
So, anything new?

**Comment by RoboMWM** [comment]
Haven't had it happen again (to me at least), and I couldn't reproduce it when fighting endermen. So, nothing new :/

**Comment by Shevchik** [comment]
This should be reproducible when switching worlds, not when fighting endermen.
