### ISSUE TITLE
Protocol Support 4.6 no longer available?

### ISSUE THREAD

**Issue by plsStarving** [ProtocolSupport/ProtocolSupport#415]
I was trying to find this version of protocol support because i wanted to use protocol support for 1.7 clients on a 1.8 jar my question is if you still have it available because the old link is now non existent. If you no longer have it available why remove it? There are many more reasons why I would like this specific version but stating them isn't necessary, I would really appreciate it if you would respond at least saying something thank you!

**Comment by Shevchik** [comment]
Because people keep asking me to fix bugs in outdated versions, so i removed it. And now people are asking me where to get it...

**Comment by MrPowerGamerBR** [comment]
If you really want it, compile it yourself! :)
