### ISSUE TITLE
<1.9 players can't take potions from creative

### ISSUE THREAD

**Issue by NEZNAMY** [ProtocolSupport/ProtocolSupport#419]
When on a 1.11.2 server with 1.8.9, I can't take potions from creative mode. They will all change into water bottles. Using build 30.

**Comment by NEZNAMY** [comment]
Why ?

**Comment by Speentie8081** [comment]
Because he knows about this issue already, and not willing to fix it right now.
Don't take that the wrong way, he will probably fix it in the future, but he has more important things to do.
He is working on the Minecraft: Pocket Edition branch right now.

**Comment by MrPowerGamerBR** [comment]
And he probably closed it because the issue is mentioned in the readme, so he already knows about it so submitting another issue about something that he already knows is just redundant.

> [Anything that is not latest] Items in creative mode may not work as expected, or may not work at all
