### ISSUE TITLE
Error when joining PE server

### ISSUE THREAD

**Issue by DaMatrix** [ProtocolSupport/ProtocolSupport#425]
Sometimes (about 1/10 times when I join the server) my server gets flooded with this:
[https://cdn.discordapp.com/attachments/286106780189065216/293046504502067200/PS-errors.txt](https://cdn.discordapp.com/attachments/286106780189065216/293046504502067200/PS-errors.txt)
I know it says out of memory, but the server was at 4% memory load before the player joined.

**Comment by Shevchik** [comment]
Implemented login dc packet, everything should work now.

**Comment by DaMatrix** [comment]
thanks
