### ISSUE TITLE
Arrows not showing in f5 [1.8] Only

### ISSUE THREAD

**Issue by ItzVinex** [ProtocolSupport/ProtocolSupport#427]
I shot my buddy with an arrow and he says he doesn't see it within 1.8 but I see it when he does it to me when I'm on 1.11.2.

https://gyazo.com/e5b73fa593f20428bc140e5c53032949

Not too sure if this is causing it or not but might as well give it a go.

**Comment by gaberilde** [comment]
what arrows?
normal or 1.11 arrows
1.11 arrows wont work in 1.8 because they dont exist

**Comment by ItzVinex** [comment]
Normal

**Comment by MrPowerGamerBR** [comment]
Reproduced this issue with the latest ProtocolSupport dev build, using 1.8.8 and 1.12.

**1.12**
![http://i.imgur.com/FjARrup.png](http://i.imgur.com/FjARrup.png)

**1.8.8**
![http://i.imgur.com/OJUhBY2.png](http://i.imgur.com/OJUhBY2.png)

**Comment by Shevchik** [comment]
Okay, so you mean arrows count in player doesn't work. Should be easy to fix, most likely a remapper issue.

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by ItzVinex** [comment]
Ok thanks :)
