### ISSUE TITLE
Players getting random kicks

### ISSUE THREAD

**Issue by DenAbr** [ProtocolSupport/ProtocolSupport#431]
Stack trace in console http://pastebin.com/w3D898Dp
Using latest dev build

**Comment by Shevchik** [comment]
The equipment packet is not properly encoded. What other plugins do you use which may caused that?

**Comment by DenAbr** [comment]
It happens only on production server(probably with 1.8 players only) and I can't find plugin that may cause this

**Comment by Shevchik** [comment]
Check all plugins that may send packets. I'm not sure how the packet was encoded badly by the server, but it happened somehow. I had someone with same issue recently, and it was the same packet.

**Comment by DenAbr** [comment]
Problem caused by Reflex anticheat

**Comment by Shevchik** [comment]
Unfortunately i can't provide help for non opensource plugins for obvious reasons.
