### ISSUE TITLE
Error pack

### ISSUE THREAD

**Issue by NEZNAMY** [ProtocolSupport/ProtocolSupport#433]
I have a bungeecord network, and here is the list of all error files that are not empty:

http://www.filedropper.com/pslogs

If and error is just because "something that is not minecraft is sending packets to the server" can you just not print the stack trace ?

Used build 35.

You can close my other tickets since this one contains everything.

**Comment by Shevchik** [comment]
I can't because i know it only from reading this log.

**Comment by NEZNAMY** [comment]
What ?..

One of the errors is kicking players from the server, can you try to fix it ? Why you closed this instantly ?

**Comment by Shevchik** [comment]
Split the erros to separate issues then.
