### ISSUE TITLE
protocolsupport 4.22/protocolsupport 4.22.1? (need for 1.8.8)

### ISSUE THREAD

**Issue by CheatSupport** [ProtocolSupport/ProtocolSupport#439]
protocolsupport 4.22/protocolsupport 4.22.1? (need for 1.8.8)

**Comment by CheatSupport** [comment]
@Shevchik please link me?

**Comment by MrPowerGamerBR** [comment]
@CheatSupport ProtocolSupport 1.8.8 is buggy and unsupported.

Do you want it? Then compile it yourself.

**Comment by CheatSupport** [comment]
How? @MrPowerGamerBR

**Comment by CheatSupport** [comment]
Link me a download so I can compile

**Comment by gdude2002** [comment]
Only the latest version of ProtocolSupport is supported.

Everything you need to compile an older version is present in this repository - doing so is left as an exercise to the reader. If you can't figure out how to do that, then you're not going to be equipped to handle the catastrophic bugs present in older versions.

The following screenshot is taken from the FAQ on the Discord server.

![](https://dl.dropboxusercontent.com/s/5runs8vsd093v10/Discord_2017-03-26_11-35-13.png)
