### ISSUE TITLE
Add support for Sponge servers.

### ISSUE THREAD

**Issue by me4502** [ProtocolSupport/ProtocolSupport#441]
Basically the title.

As Mixins would probably be required, this'd make sense to make for SpongeVanilla. If SpongeForge was required in the future as well, a version for Forge would make more sense.

**Comment by MrPowerGamerBR** [comment]
Shevchik already said before that he won't add support for Sponge.

![http://i.imgur.com/ZzlGeE2.png](http://i.imgur.com/ZzlGeE2.png)

![http://i.imgur.com/8DYIXMM.png](http://i.imgur.com/8DYIXMM.png)

![http://i.imgur.com/N0QtTMd.png](http://i.imgur.com/N0QtTMd.png)

(Okay, he never said he wouldn't implement, but he dislikes Sponge and I doubt he would go through all of the hassle to implement a server software that he personally dislikes)

**Comment by me4502** [comment]
He seems to have an inaccurate view of Sponge.

The original idea was to integrate Spout, not Bukkit, on top of Forge. The events that were added to Forge for server-side mods were also mostly added by the Sponge team, so that Sponge plugins could better integrate with mods.

**Comment by Shevchik** [comment]
Anyway no bukkit api and spigot api - no port.

**Comment by me4502** [comment]
There's partial support for the Bukkit API through the PoreRT Extension. It gets more added when Maxqia gets time to do it. Assuming you're using the basics, like configs, etc, and none of the super advanced stuff, there should be enough of the API there to run it through PoreRT.

**Comment by Shevchik** [comment]
Someone will have to write an implementation for PoreRT than, because i don't have interest in it right now.

**Comment by Outfit8TSB** [comment]
wonder why this plugin is bozo while mine is sigma
+1 Bozo Momento
