### ISSUE TITLE
WrapperPlayServerEntityEquipment error

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#442]
Hi, when I'm trying to set armor to spawned NPC using ProtocolLib there is an error in the console and it kicks the player. I'm using [this ](https://github.com/dmulloy2/PacketWrapper/blob/master/PacketWrapper/src/main/java/com/comphenix/packetwrapper/WrapperPlayServerEntityEquipment.java)packet to set equipment. 

Spigot: This server is running CraftBukkit version git-Spigot-96235ab-257d6cd (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Newest ProtocolLib nad ProtocolSupport.

**Comment by gdude2002** [comment]
We're going to need the full error.

**Comment by DanielAlves123** [comment]
Sorry, I forgot to paste that:
`[Netty Epoll Server IO #3/ERROR]: java.lang.NullPointerException
[Netty Epoll Server IO #3/WARN]: io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(2) exceeds writerIndex(4): UnpooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 256)
[Netty Epoll Server IO #3/WARN]: 	at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:52)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.write(ChannelInjector.java:263)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[Netty Epoll Server IO #3/WARN]: 	at protocolsupport.protocol.pipeline.common.LogicHandler.write(LogicHandler.java:46)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_11_R1.NetworkManager$4.run(NetworkManager.java:200)
[Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:340)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[Netty Epoll Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[Netty Epoll Server IO #3/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(2) exceeds writerIndex(4): UnpooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 256)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175)
[Netty Epoll Server IO #3/WARN]: 	at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:589)
[Netty Epoll Server IO #3/WARN]: 	at protocolsupport.protocol.serializer.ItemStackSerializer.readItemStack(ItemStackSerializer.java:29)
[Netty Epoll Server IO #3/WARN]: 	at protocolsupport.protocol.packet.middle.clientbound.play.MiddleEntityEquipment.readFromServerData(MiddleEntityEquipment.java:21)
[Netty Epoll Server IO #3/WARN]: 	at protocolsupport.protocol.pipeline.version.AbstractPacketEncoder.encode(AbstractPacketEncoder.java:47)
[Netty Epoll Server IO #3/WARN]: 	at protocolsupport.protocol.pipeline.version.AbstractPacketEncoder.encode(AbstractPacketEncoder.java:20)
[Netty Epoll Server IO #3/WARN]: 	at protocolsupport.utils.netty.MessageToMessageEncoder.write(MessageToMessageEncoder.java:37)
[Netty Epoll Server IO #3/WARN]: 	... 27 more
[Server thread/INFO]: TestingPlayer lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(2) exceeds writerIndex(4): UnpooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 256)`

**Comment by MrPowerGamerBR** [comment]
@DanielAlves123 Update to 1.11.2 and stop using obsolete versions.

**Comment by Shevchik** [comment]
You have some other plugin that is malforming network data.

**Comment by MrPowerGamerBR** [comment]
@Shevchik of course, he is using PacketWrapper for 1.11.2 in 1.8.8, that's why it is creating malformed data.

**Comment by MrPowerGamerBR** [comment]
Or maybe he is using PacketWrapper for 1.8.8 in 1.11.2...

**Comment by MrPowerGamerBR** [comment]
I don't know what he meant by "I'm using version 1.8.9"

**Comment by Shevchik** [comment]
He meant client version i think. Packet wrapper can't send malformed data, because it actually uses native packet encoder. So something else in the pipeline does read/write packets, and does it wrong.

**Comment by DanielAlves123** [comment]
I only use this plugin to send this packet. It happens since I updated spigot to the newest version, I don't have it's history to check which one caused this.
Code:
`    private static void setNPCArmorContent(Player p, int npcID, ItemStack item, ItemSlot slot) {
        if (item == null) {
            return;
        }
        WrapperPlayServerEntityEquipment wrapper = new WrapperPlayServerEntityEquipment();
        wrapper.setEntityID(npcID);
        wrapper.setSlot(slot);
        wrapper.setItem(item);
        wrapper.sendPacket(p);
    }`
Spigot:
This server is running CraftBukkit version git-Spigot-625bc00-d09304e (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Plugins:
- my plugin to spawn npcs;
- ProtocolLib (the newest);
- ProtocolSupport (the newest);

Client version: 1.8.9

**Comment by Shevchik** [comment]
I'm unable to reproduce it, uplpad the exact spigot jar you use and plugins jars, including yours.

**Comment by DanielAlves123** [comment]
It happens when you try to send WrapperPlayServerEntityEquipment to player, where the ItemSlot is MAINHAND and the item is null/air or something.

**Comment by Shevchik** [comment]
NMS can no longer serialize and operate null itemstacks anyway, it uses special empty itemstack instead of null now.
