### ISSUE TITLE
Internal error - Kicking players

### ISSUE THREAD

**Issue by Sckaletz** [ProtocolSupport/ProtocolSupport#443]
https://pastebin.com/DahVA4JH

My players receive it from time to time and gets kicked with an internal error when they try to join.
It looks like if I join the server and go to their last location and they try again, they are able to join. Maybe some kind of chunk error? It has happened many times lately and on different servers with different players.

Using build 38 of Protocolsupport
Latest Spigot version "CraftBukkit version git-Spigot-96235ab-257d6cd (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)"

According to Spigot, this problem has to do with Protocolsupport. It use to work fine and without problems. No other plugins have been update. Only updating done is on Protocolsupport. 

https://hub.spigotmc.org/jira/browse/SPIGOT-3155

**Comment by Shevchik** [comment]
Not a protocolsupport issue.
