### ISSUE TITLE
Server kicks players with mc under 1.8

### ISSUE THREAD

**Issue by mariolars** [ProtocolSupport/ProtocolSupport#451]
ProtocolSupport build 38
Paper version git-Paper-1079
Travertine Lastest (Happens on hexagon's bungeecord too)

No special logs from server but bungeecord throws errors 

https://pastebin.com/bj6kbcJE

-31911 is size of array that bungee is trying to create.

**Comment by Shevchik** [comment]
Something related to scoreboards

**Comment by mariolars** [comment]
In bungeeord I am blocking packet team 62 for players on 1.7 and everything seems to working fine.

**Comment by mariolars** [comment]
Scoreboard now crashes 1.7. 
Minecraft Logs: https://pastebin.com/LDvNT0Cs
Travertine fresh lastest without plugins
Spigot 1.12 git-Spigot-b78586d-f3356f1
ProtocolSupport #64

**Comment by Shevchik** [comment]
You need to dump the raw received packet data somehow. Otherwise i won't be able to help.
Scoreboard packets encoding for 1.7 is correct (at least no mistakes in the middle packet encoder itself).
