### ISSUE TITLE
command blocks do not show 1.8 on rejoin

### ISSUE THREAD

**Issue by gaberilde** [ProtocolSupport/ProtocolSupport#452]
this has something do with new command blocks because the id is different and 1.8 docent recognise it even if it was placed in 1.8

![2017-04-09_15 40 08](https://cloud.githubusercontent.com/assets/6341453/24838249/62d6b75e-1d3c-11e7-8671-8a704ff2abcf.png)

**Comment by Shevchik** [comment]
New command blocks are remapped for every version before 1.8, i guess i messed up somewhere else.

**Comment by gaberilde** [comment]
every version before  1.8?
what about 1.8 it self?

**Comment by Shevchik** [comment]
Before 1.9 i mean.

			registerRemapEntry(Material.COMMAND_CHAIN, Material.COMMAND, ProtocolVersionsHelper.BEFORE_1_9);
			registerRemapEntry(Material.COMMAND_REPEATING, Material.COMMAND, ProtocolVersionsHelper.BEFORE_1_9);

Does remapping breaks only for command block? Does it work while you hold it in hand not in creative?

**Comment by gaberilde** [comment]
i think it lets me hold it but when i place it it is only visible to me and nobody else on the server also if i rejoin it wont even for for me anymore in 1.8

**Comment by Shevchik** [comment]
Are your command blocks in conditional mode?

**Comment by gaberilde** [comment]
they are in the normal mode that 1.8 puts them in since the option isnt in 1.8 idk what that is im assuming conditional is it

**Comment by Shevchik** [comment]
Unable to reproduce locally, send me a schematic of that place, or a world copy.

**Comment by gaberilde** [comment]
here u go 
[http://ddl2.data.hu/get/333221/10488967/loltest1.schematic](url)

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by gaberilde** [comment]
ok wheres the latest plugin download too

**Comment by Shevchik** [comment]
At jenkins build server

**Comment by gaberilde** [comment]
yes is fixed pleas mark this is resloved
