### ISSUE TITLE
Missing Optifine capes, 3D skins and elytra

### ISSUE THREAD

**Issue by Sckaletz** [ProtocolSupport/ProtocolSupport#455]
With the newest version players can no longer see capes from Optifine and 3D skins. Also Elytra isn't working.

Using the latest build of Protocolsupport and
Spigot 1.11.2 (git-Spigot-d276ab1-d219213 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by 7kasper** [comment]
@Sckaletz Can you check if the things you mentioned still work in  build #38. (https://build.true-games.org/job/ProtocolSupport/38/)
