### ISSUE TITLE
Cant get spawn eggs in 1.8

### ISSUE THREAD

**Issue by gaberilde** [ProtocolSupport/ProtocolSupport#458]
if you get a spawn egg in 1.8 from the inventory it will change to just Spawn with nothing else and will change to what looks like a ghast spawn egg but a bit brighter this could be to with the new spawn eggs or something

you can get all 1.8 spawn eggs in 1.11 and have them work in 1.8 if you switch version

but if you get a 1.11 mob and go to 1.8 same thing happens (i understand this one because 1.11 mob dosent exist in 1.8) but i cant even get the 1.8 mobs in 1.8 for some reason

at this point i should disallow 1.8 version if its going to be so buggy XD (sorry no offence lol doing this must be quite hard to get everything working right)

**Comment by Shevchik** [comment]
Read the README before posing issues.

**Comment by adiantek** [comment]
There aren't any informations about eggs in README on spigotmc and github.

**Comment by Shevchik** [comment]
[ProtocolSupport/ProtocolSupport] New comment on issue #458: Cant get spawn eggs in 1.8
There aren't any informations about eggs in README on spigotmc and github.

There is, in the creative not working
