### ISSUE TITLE
Players are unable to enchant items on version 1.7.x (1.6 not tested)

### ISSUE THREAD

**Issue by Xayanix** [ProtocolSupport/ProtocolSupport#461]
As in title.
Tested it on newest 1.11 server with newest ProtocolSupport dev build.

**Comment by Xayanix** [comment]
Pro tip:

[`@EventHandler
	public void onOpen(InventoryOpenEvent event){
		Inventory inventory = event.getInventory();
		InventoryType type = inventory.getType();
		
		if(type == InventoryType.ENCHANTING){
			inventory.setItem(1, new ItemStack(Material.INK_SACK, 64, (short) 4));
		}
	}`

Fixes problem.

**Comment by Shevchik** [comment]
Pro-tip: install auxiliary protocolsupport plugins.

**Comment by Xayanix** [comment]
Link?

**Comment by Shevchik** [comment]
They are pinned in the organization
