### ISSUE TITLE
Block packet glitch?

### ISSUE THREAD

**Issue by HeyZeer0** [ProtocolSupport/ProtocolSupport#465]
When i connect using forge no blocks are shown but the map contains several blocks
http://prntscr.com/ez3r94

Packages are probably not being sent correctly, I already tried to remove all my plugins.

Using ProtocolSupport latest version with use-native-transport false.

Minecraft version: >= 1.8
In 1.7.10 works perfectly

Thanks =)

**Comment by Shevchik** [comment]
Make sure you are running latest forge.

**Comment by HeyZeer0** [comment]
Apparently the bug is related to some mod, I'll check and return soon.

**Comment by Shevchik** [comment]
Make sure you are running latest forge, it had a bug with chunk data parsing which was fixed some months ago.

**Comment by HeyZeer0** [comment]
I've removed all my mods and the bug seems to have disappeared, it's probably some mod's fault, I'm looking for the one at the moment

**Comment by HeyZeer0** [comment]
I solved the problem, however I had to downgrade the lobby and ProtocolSupport to version 1.10.2. I do not know exactly what was causing the bug.

**Comment by Shevchik** [comment]
It will reappear as soon as you add enough mods that add blocks, so the blocks registry will take more than 13bits per block. Update your forge to latest.

**Comment by HeyZeer0** [comment]
He is already in the last version

**Comment by Shevchik** [comment]
Print the exact used forge version here.

**Comment by HeyZeer0** [comment]
1.10.2 - 12.18.3.2281

**Comment by Shevchik** [comment]
That's not the latest forge version (because it's not 1.11)

**Comment by HeyZeer0** [comment]
I have a network and modpacks in several versions have no way to always use 1.11.
My lobby server is running spigot.

**Comment by Shevchik** [comment]
Can't fix it anyway because it's a forge problem.

**Comment by HeyZeer0** [comment]
No problem

**Comment by Eufranio** [comment]
How can it be a forge problem if a client running forge will not have problems, plus will not have problems if running the same modpack but on a 1.10.2 lobby?

**Comment by Shevchik** [comment]
Because 1.10.2 protocolsupport was different and wasn't recoding chunk data.

**Comment by Eufranio** [comment]
Couldn't you DON'T do it for 1.10 clients?
