### ISSUE TITLE
Colors on 1.7 (and maybe up) are very bugged.

### ISSUE THREAD

**Issue by piter909** [ProtocolSupport/ProtocolSupport#466]
EDIT:
I do not know where is cause - when I am writing on chat, everything is ok.. Was testing with Skript's effect send "&btusk" to player
EDIT2:
Yes, probably cause is something in Skript, but everything works on version 1.11 without protocolsupport, weird.. Maybe they are using component chat or json chat and it is bugging with ProtocolSupport?
EDIT3:
There is something wrong with using only colour without format, like "&btest". 
When I do "&b&lTEST" everything is ok..

When we use any color, like &btest, version 1.7 see it like "est" colored on light blue.
Also, if there is symbol that gives format or color after disapeared character, the format/color of text is incorrect (example: "&btusk" - it will be blue without first character  with &u format).
Hope it will be fixed :)
Thanks for this amazing plugin!

**Comment by Shevchik** [comment]
Component json is not recoded for 1.11 clients, which means that protocolsupport does not affect this. For previous version it recodes it to fix legacy errors, so it is possible that ps decoder/encoder breaks components. Use protocollib to dump what is sent buy server.

**Comment by piter909** [comment]
This is line of code in Skript that is causing this problem:

> ((Player) s).spigot().sendMessage(components);
> 
> https://github.com/bensku/Skript/blob/4d7e76a6b626db37b95acea768d16d712fa40802/src/main/java/ch/njol/skript/effects/EffMessage.java (LINE 90)

**Comment by Shevchik** [comment]
Use protocollib do dump the chat packet contents when sending message via script, i don't have time to debug it myself.

**Comment by utkabobr** [comment]
Maybe `((Player) s).sendRawMessage(components);` can fix that?
