### ISSUE TITLE
1.7 players are being bugged and dragged back to 1 place

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#468]
Hi, 1.7 players are often bugged in 1 place, they can move, but only client-side and they are being dragged back to the same place really quick. Other players sees them as they dont move, they dont receive knockback, they can eat, attack or use things, but they can't open any server inventories. If you leave the server or be teleported, you can walk normally for some time.

**Comment by Shevchik** [comment]
Does it happens on some specific blocks or randomly?

**Comment by DanielAlves123** [comment]
I think it's random.

**Comment by Speentie8081** [comment]
Same thing happened on my server, specifically when the person walked into a specific part of the kitpvp map where a secret tunnel lies. I won't go too in-depth, it is pretty much all stone, it goes down like 2 blocks, and it there is no skylight, their (if I recall correctly) the ceiling is 3 blocks high.

**Comment by DanielAlves123** [comment]
@Shevchik Can you fix that? It's really game breaking. It freezes you in the air or in the water, maybe it's something with loading chunk. And it only happens with 1.7 players.

**Comment by Speentie8081** [comment]
@Shevchik Yes you should really fix this issue, if you can

**Comment by Shevchik** [comment]
Floating point is at fault here i guess.

**Comment by Shevchik** [comment]
try now, if i guessed the reason right, it should be a lot better now.

**Comment by DanielAlves123** [comment]
Yup, I think it's fixed. Thanks for now. :D

**Comment by Speentie8081** [comment]
Thank you so much for fixing this issue @Shevchik.
I added back 1.7.6 through 1.7.10 support back to my server now.
