### ISSUE TITLE
Crashing on B49.

### ISSUE THREAD

**Issue by andrewkm** [ProtocolSupport/ProtocolSupport#469]
Updating from ProtocolSupport B48 to B49 caused player crashing.
https://www.ecocitycraft.com/forum/threads/java-errors.165351/

Reverting the plugin to B48 fixed it.

I myself was able to reproduce on 1.11.2 client and Java 8 u 131.
(Server Java is on 8 u 131 - doubt this has anything to do with it though, just thought I'd mention.)

PS: Making this issue in case you guys don't notice the commit comment.

**Comment by Shevchik** [comment]
Those ids were autogenerated. Which means that we have an actual bug somewhere else (or my generator broke). Will check that when i have time, deleted B49 from build server for now.

**Comment by andrewkm** [comment]
Adding this in case useful:
Error: java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Integer

Clients were shooting this error during the crashes.

Currently on B48 for 15 minutes with zero reports of crashing.

**Comment by Shevchik** [comment]
Found out why it happens, just have to fix it and figure out why generator broke now.

**Comment by Shevchik** [comment]
Fixed it
