### ISSUE TITLE
Players automatically disconnecting when trying to join

### ISSUE THREAD

**Issue by Xeroxity** [ProtocolSupport/ProtocolSupport#470]
Some players are unable to join. When they try to, they get disconnected and gets a message "Internal Server Error". However, a majority of players can join.

Spigot Version: 1.11.2 {Latest Build]
ProtocolSupport: Latest Development Build No. 52

Error Log: https://pastebin.com/aHk6TUBS

**Comment by Shevchik** [comment]
Post ProtocolSupport-error log

**Comment by Xeroxity** [comment]
The ProtocolSupport-error-log is empty.

**Comment by Shevchik** [comment]
Enable debug by /ps debug and post a full server log from the start next time the exception happens.

**Comment by Xeroxity** [comment]
The ProtocolSupport-error-log file is empty after a player that is affected tries to join. However errors pop up in the console.
Errors: https://pastebin.com/ZiEVCVgQ

**Comment by Shevchik** [comment]
Nothing to do with protocolsupport, you have a corrupted map. Next time check without ps first.
