### ISSUE TITLE
Сервер стопается с ошибкой

### ISSUE THREAD

**Issue by Keksik9000** [ProtocolSupport/ProtocolSupport#471]
Использую самый новый билд TorchSpigot и ProtocolSupport. 
Иногда сервер стопается с такой ошибкой:

https://pastebin.com/0AqLZRUA

однако на обычном Spigot'e все работало отлично. 
Можешь посмотреть, в чем проблема?

UPD: Отписал разработчику TorchSpigot'а, посмотрим что он скажет.

**Comment by Shevchik** [comment]
No
