### ISSUE TITLE
Cant throw eggs at other players

### ISSUE THREAD

**Issue by gaberilde** [ProtocolSupport/ProtocolSupport#473]
when you throw eggs at another player it dosent hit them like in god mode even if they arnt in it

**Comment by Shevchik** [comment]
Test without protocolsupport first.

**Comment by gaberilde** [comment]
wait it happens even with no plugins??? WTF!

**Comment by gaberilde** [comment]
i still wana know even if it isnt this -_-

**Comment by Shevchik** [comment]
This issue tracker is for protocolsupport bugs only, if you want to ask why it happens - try asking on spigot forums or at our discord, maybe somebody will be able to help.
