### ISSUE TITLE
Teleporting

### ISSUE THREAD

**Issue by maol3** [ProtocolSupport/ProtocolSupport#475]
When telepoing using /tp <x> <y> <z> without ProtocolSupport, you teleport to the desired position without affecting your yaw and pitch. However when using /tp <x> <y> <z> with ProtocolSupport, it teleports you to the desired position, but looking straigt to north.
 
I'm performing the following command with a commandblock without ProtocolSupport
/tp @a[m=!3,team=!Tavling,score_Slantar_min=1,r=1,x=-1411,y=22,z=-952,ry=100,rym=80] -1413 22 -952
 
On my Spigot 1.11.2 server with ProtocolSupport 4.26dev, I'm performing the exact same command.
 
This is the desired behaviour (which occurs without ProtocolSupport): https://gyazo.com/7c4c07be336f5b67bd5fee3a375c6bec
This is what happens when using the same world without ProtocolSupport, nothing changed: https://gyazo.com/f2172ea99ed7bb832a149b09b0720f26
 
The world is no different, the blocks are exactly the same. Thanks in advance!

I am running ProtocolSupport 4.26dev. Issue does not occur without ProtocolSupport.

**Comment by gdude2002** [comment]
Link from the original unedited ticket, for the sake of completeness: https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-3227?filter=allissues

---

Are you using the latest build from Jenkins? https://build.true-games.org/job/ProtocolSupport/

**Comment by maol3** [comment]
Yes, I am using the latest version from Jenkins.

**Comment by Shevchik** [comment]
What is the client version?

**Comment by maol3** [comment]
I am using the latest build (#54) on Spigot 1.12.2-R0.1-SNAPSHOT. The client version I am playing with is 1.11.2.

Same issue with the latest dev build.

**Comment by Shevchik** [comment]
Does it reset the pitch too?

**Comment by maol3** [comment]
It doesn't reset the pitch, only the yaw.

**Comment by maol3** [comment]
Mind checking if this is easy to solve? :/
Thanks in advance!

**Comment by Shevchik** [comment]
Unfortunately i wasn't able to find the reason quickly, and now i'm busy with preparing 1.12 update, so all bugs will have to wait.

**Comment by Shevchik** [comment]
I'm unable to reproduce this with latest protocolsupport dev build.

**Comment by MrPowerGamerBR** [comment]
Couldn't reproduce this with latest ProtocolSupport dev build, client: 1.8.8.
