### ISSUE TITLE
crash 1.7.10 and lower

### ISSUE THREAD

**Issue by mat41997** [ProtocolSupport/ProtocolSupport#478]
logs
https://gist.github.com/mat41997/a32841b6087a5f6a62ba146a916db58c

timings
https://timings.aikar.co/?id=46e43f0569da45b282c6b5c7dcac5a5e

torch
https://github.com/TorchSpigot/Torch/issues/96

**Comment by Shevchik** [comment]
You are trying to register the same scoreboard team twice to the client. 1.7- and 1.8+ have different scoreboard logic, so make sure that you manually remove player from scoreboard team when it it is not needed anymore.
