### ISSUE TITLE
Essential update to pre 5 spigot

### ISSUE THREAD

**Issue by Fonzee9** [ProtocolSupport/ProtocolSupport#480]
Before you close this please read this plugin is essential on pre 5 to get new players on the server as it's easy because right now people have to change to 1.12 pre 5 some don't know how to and this plugin would just let them join on pre 5 this plugin is even more essential on a pre release.

**Comment by MrPowerGamerBR** [comment]
https://github.com/ProtocolSupport/ProtocolSupport/tree/1.12

Compile it yourself.

It may also explode your server! (or maybe not)

**Comment by Fonzee9** [comment]
I know to use buildtools to compile spigot but how do I compile this do I need to download another jar?

**Comment by MrPowerGamerBR** [comment]
@Fonzee9 I haven't used Gradle since a long time ago, but it should be like this:

(Using git bash)

```
git clone https://github.com/ProtocolSupport/ProtocolSupport.git
git checkout -b 1.12
sh ./gradlew build
```

Or something like that.

**Comment by Fonzee9** [comment]
Do I have to download gradle or can I use buildtools? Also link to gradle if I do

**Comment by Fonzee9** [comment]
Thanks
