### ISSUE TITLE
(pre5) Does not work on Windows

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#481]
When i start a spigot server with latest ProtocolSupport on windows 10 it does not work - I can compile it and start a server - but when I join using Minecraft 1.11.2 or Minecraft 1.12 pre 5, I can join but get a time out some seconds later - on my linux server the same build works.

If I run the server without ProtocolSupport on Windows I can join using 1.12 pre 5.

**Comment by Shevchik** [comment]
Enable debug and check the error log

**Comment by Brokkonaut** [comment]
The errlog is empty even with debug enabled. This is the server log:

[15:55:57] [Server thread/INFO]: Enabled debug
[15:56:31] [Netty Server IO #1/INFO]: [ProtocolSupport] /127.0.0.1:50394 connected with protocol version MINECRAFT_1_11_1
[15:56:32] [Netty Server IO #2/INFO]: [ProtocolSupport] /127.0.0.1:50395 connected with protocol version MINECRAFT_1_11_1
[15:56:34] [LoginProcessingThread/INFO]: UUID of player Brokkonaut is 06d29950-2262-474c-acd6-fcab8e632ae1
[15:56:34] [Server thread/INFO]: Brokkonaut[/127.0.0.1:50395] logged in with entity id 71 at ([world]243.5, 64.0, 161.5)
[15:57:04] [Netty Server IO #2/WARN]: io.netty.handler.timeout.ReadTimeoutException
[15:57:04] [Server thread/INFO]: Brokkonaut lost connection: Timed out
[15:57:04] [Server thread/INFO]: Brokkonaut left the game

**Comment by Shevchik** [comment]
Client didn't send anything for 30 seconds, or it didn't read the timeout handler. No idea why it happens, maybe there is something wrong with netty, or the way how we use it.

**Comment by Brokkonaut** [comment]
It looks like the server somehow does not read the clients packets - If I type some text or command in the client it never shows in the servers log.

Is there anything else I can do to help debugging this?

**Comment by Shevchik** [comment]
Install protocollib and dump all packets.

**Comment by Brokkonaut** [comment]
How can I dump all packets?

**Comment by Fonzee9** [comment]
Brok can i have a download link to your compiled ProtocolSupport? I really need it for pre 5

**Comment by Brokkonaut** [comment]
When I have
use-native-transport=false
in my server.properties on linux, I have the same problem (No player can connect) - When I set it to true it works.

**Comment by MrPowerGamerBR** [comment]
@Brokkonaut as far as I know Mojang removed the "use-native-transport" option from the "server.properties" in 1.12

**Comment by Brokkonaut** [comment]
When I set it to false, I cannot join the 1.12 server with ProtocolSupport active - When I set it to true I can. So I think this setting still has some effect.

**Comment by Shevchik** [comment]
Yeah, for some reason nio transport doesn't work.

**Comment by Shevchik** [comment]
It is something related to netty autoread. If you force read after join, it will work again. setAutoRead should handle that automaticly, but it doesn't happen for whatever reason.

**Comment by Shevchik** [comment]
It's also somehow related to protocolsupport handling login packets in different thread. If i shift hadling back to network thread everything starts working again. Which means the real cause is somewhere in the netty. Pushed a workaround, but now i need to create minimal reproduction example and report it to netty.

**Comment by Shevchik** [comment]
This issue should be fixed now.

**Comment by Brokkonaut** [comment]
thanks :)
