### ISSUE TITLE
Determined protocol messages

### ISSUE THREAD

**Issue by T1MOXA** [ProtocolSupport/ProtocolSupport#484]
Messages in the server console:
`Determined protocol 316 `
I think this is due to the ProtocolSupport (But I'm not sure)

**Comment by gdude2002** [comment]
You're going to need to give _a lot_ more info than this. For example:

* What version of Spigot are you using?
* What version of Minecraft are you connecting with?
* Are you using the absolute latest ProtocolSupport from [Jenkins](https://build.true-games.org/job/ProtocolSupport/)?

Additionally, we'll need more context than that single line. Perhaps paste the full error from your logs instead?

**Comment by T1MOXA** [comment]
As I understand it the debug messages, but I would like to remove them.

1) git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2)
2) These messages arise as I realized when getting the MOTD of the server
3) Yes

**Comment by gdude2002** [comment]
Please supply all the info I asked for.

> * What version of Minecraft are you connecting with?
> * Does it cause any unwanted behavior?

---

> These messages arise as I realized when getting the MOTD of the server

You mean, when the client grabs the server's information from the server list?

**Comment by Shevchik** [comment]
No such debug message exists in protocolsupport

**Comment by T1MOXA** [comment]
> You mean, when the client grabs the server's information from the server list?
Yes

> Does it cause any unwanted behavior?
Like no, except for spam, nothing bad noticed

> What version of Minecraft are you connecting with?
I understand that with 1.11
