### ISSUE TITLE
on join speed walk 0

### ISSUE THREAD

**Issue by mat41997** [ProtocolSupport/ProtocolSupport#485]
you can add AutoCommand /speed 1
to fix this bug

**Comment by gdude2002** [comment]
More context required.

* What version of Spigot are you using?
* What version of Minecraft are you connecting with?
* Are you using the absolute latest ProtocolSupport from [Jenkins](https://build.true-games.org/job/ProtocolSupport/)?
* How are you reproducing this problem?

**Comment by mat41997** [comment]
latest, latest, latest

ohh.. This bug does not occur every time

**Comment by gdude2002** [comment]
So you're using Spigot for 1.11.2 and ProtocolSupport #54, and connecting with Minecraft 1.11.2?

Why do you think ProtocolSupport is causing the problem?

**Comment by mat41997** [comment]
yes, and i not can moved on my server
i must use command /speed 1
to i can move

see timings
https://timings.aikar.co/?id=4aecc428732446729a459fb88f9073f8

torchspigot
https://github.com/TorchSpigot/Torch
https://yivesmirror.com/downloads/torch

I have this problem for a long time, I have reported it many times
It has not been repaired, although the solution is simple

**Comment by gdude2002** [comment]
We do not support TorchSpigot. Unless you can reproduce this problem on Spigot, PaperSpigot or Glowstone, there's nothing we can do to help you.

**Comment by mat41997** [comment]
torch is a fork of paperspigot : /
i have this same bug on paperspigot

**Comment by gdude2002** [comment]
It's a fork of PaperSpigot, yes, but it changes a great deal of underlying code, especially with relation to multi-threading. That can break all kinds of things.

What version of PaperSpigot? Do you have a list of plugins?

**Comment by mat41997** [comment]
i no have a server to test this bug on paperspigot
As I wrote, it does not happen every time

You can fix it very simply

```
on join:
	reset walk speed of player
	stop
```

**Comment by gdude2002** [comment]
It's unlikely that we would add a fix like this without a reproducible setup. As mentioned, if you're going to be using TorchSpigot, then we're likely not going to be able to help you.

If you can't reproduce this using a supported platform, then I'm going to have to recommend that @Shevchik closes this ticket.

**Comment by gdude2002** [comment]
One of our users attempted to reproduce this issue on TorchSpigot and was unable to.

![](https://dl.dropboxusercontent.com/s/jwqnrtmlu3goujx/Discord_2017-05-27_15-26-13.png)
![](https://dl.dropboxusercontent.com/s/i0t3oxc6jr8maoh/Discord_2017-05-27_15-26-26.png)

**Comment by MrPowerGamerBR** [comment]
I tried reproducing this issue with TorchSpigot (https://github.com/TorchSpigot/Torch/commit/42b10302ab43c6ad63816e3200f2333dd278346b) and the latest ProtocolSupprot dev build and I couldn't reproduce it.

I tried joining my server 5 times with 1.11.2 and none of them had the issue described in this reported issue.
