### ISSUE TITLE
Unable to join my Pre 6 Server with ProtocolSupport

### ISSUE THREAD

**Issue by Fonzee9** [ProtocolSupport/ProtocolSupport#489]

**Comment by Shevchik** [comment]
Because it is still pre5

**Comment by Fonzee9** [comment]
Eta on update??

**Comment by gdude2002** [comment]
Nope.

**Comment by gdude2002** [comment]
1.12 releases for real on Friday, so maybe check back at the end of the weekend

**Comment by Fonzee9** [comment]
This plugin doesn't even work on windows thats a big problem

https://github.com/ProtocolSupport/ProtocolSupport/issues/481

**Comment by gdude2002** [comment]
In another ticket today, Shev pointed out that there are some issues with Netty on Windows.

It may be out of his hands, but he's already looking at it.

**Comment by Fonzee9** [comment]
What about FurnitureLib support because when i used it on my linux server it messed up the furniture for all versions even for 1.12 pre 5 FurnitureLib works on 1.12 pre 5 but once you put this plugin in it gets messed up. This is a big problem for me and its really annoying.

**Comment by gdude2002** [comment]
FurnitureLib advertises support for ProtocolSupport. That said, the 1.12 branch is alpha-quality software, you can't expect it to work properly when there isn't even a stable build of that version of Minecraft.

Wait for the stable releases.
