### ISSUE TITLE
Lots of users can't login: Failed to parse chunk data

### ISSUE THREAD

**Issue by ArtNRG** [ProtocolSupport/ProtocolSupport#490]
Paper-1095 (MC: 1.11.2)
protocolsupport.protocol.legacyremapper.chunk.ChunkTransformer$ChunkDataParseException: Failed to parse chunk data

Full error log: https://pastebin.com/ttk6qXsW

**Comment by Shevchik** [comment]
According to what i see the server sent chunk without skylight, but the world player is in has the skylight. On which world does it happen exactly?
