### ISSUE TITLE
ArmorStands are displayed without arm/leg/.. rotation (1.12)

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#496]
When protocolsupport is installed, all armorstands are displayed in the "default" position for 1.11.2 and 1.12 client - without arm and leg rotations. without protocolsupport the normal rotations are sent to the (1.12) client

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by Brokkonaut** [comment]
thank you :)
