### ISSUE TITLE
Llama spit kicks everyone from the server (1.12 client on 1.12 server)

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#500]
When a llama spits, everyone who sees that is kicked from the server. this does not happen without protocolsupport

[20:45:13] [Server thread/INFO]: Brokkonaut lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

**Comment by Shevchik** [comment]
Enable debug and try again

**Comment by Brokkonaut** [comment]
https://pastebin.com/raw/tXk5bz5m

**Comment by Brokkonaut** [comment]
Another test on a server with only protocolsupport and nothing else:
https://pastebin.com/raw/jZ3pgSqm

**Comment by Shevchik** [comment]
Should be partially fixed now. it won't crash anymore, but i still need to add entry for llama spit metadata remapper.

**Comment by Brokkonaut** [comment]
thx :)
