### ISSUE TITLE
1.12 Kick on connect (tested with 1.11.2 and 1.12 client)

### ISSUE THREAD

**Issue by jorisguffens** [ProtocolSupport/ProtocolSupport#501]
Console:
[Disconnect] User iGufGuf has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown gamemode network id -1

Spigot:
Paper #1108

Protocolsupport:
Latest (1.12 branch)

Debug log:
https://paste.projectdev.org/utunokexav.vbs
(While looking at this error I noticed 1 stacktrace line from our custom plugin, using packetlistener)

We use latest waterfall (bungeecord)

**Comment by Shevchik** [comment]
Something sends login packet with invalid gamemode id.

**Comment by jorisguffens** [comment]
I found the problem, when sending the spawn packet for a custom npc this will disconnect the player. The default gamemode of the npcs is EnumGameMode.NOT_SET (-1) so I've set their gamemode to creative.

**Comment by Shevchik** [comment]
Yeah, the -1 (NOT_SET) is not a real gamemode that can be transferred safely in all versions.
