### ISSUE TITLE
Error when someone ping the server or try to connect

### ISSUE THREAD

**Issue by maxlehot1234** [ProtocolSupport/ProtocolSupport#502]
Hi, I GET THIS ISSUE when someone refresh his server list.
Players can't login on my server.

https://pastebin.com/AQKmSFmZ

Of course, I use it on my computer for testing, so I just test with my account and my test account.

I am under 1.12.

Thank you if you can fix this issue.

Have a nice day @Shevchik

**Comment by Shevchik** [comment]
Channel wen't inactive before it even went active. Try reproducing this with only ProtocolSupport.

**Comment by maxlehot1234** [comment]
EDIT: I spam the refresh button at least 20 times and now, I am able to connect on the server, but it generate at least 3000 lines of error

**Comment by maxlehot1234** [comment]
@Shevchik Not sure if you see this

**Comment by Shevchik** [comment]
I see this, but as i already said the log explicitly says that ProtocolSupport is not the problem.

**Comment by maxlehot1234** [comment]
It was caused by protocollib. So sorry for this. Have a nice day/night to you

**Comment by maxlehot1234** [comment]
@Shevchik I have this error again.
ProtocolLib up-to-date

**Comment by Shevchik** [comment]
You can't be having the same issue unless you somehow downgraded ProtocolLib

**Comment by maxlehot1234** [comment]
But I confirm that I have the same issue.
I NEVER downgrade my plugins except if they have a huge glitch in it.

I have this error each time a player refresh his servers list: https://pastebin.com/w6yMiRpB

Player need to spam at least 20 times to be able to see the server online and join it,

**Comment by Shevchik** [comment]
Then remove ProtocolLib and try again.

**Comment by maxlehot1234** [comment]
Fix the issue, but I need protocol lib on my server :P

So not a great solution...

**Comment by Shevchik** [comment]
Can't help there, it's a ProtocolLib issue.
