### ISSUE TITLE
On Spigot 1.9.4 i have to use version 4.23 - but newer players than 1.9.4 cant connect

### ISSUE THREAD

**Issue by sannielollie** [ProtocolSupport/ProtocolSupport#503]
On Spigot 1.9.4 i have to use version 4.23 - but newer players than 1.9.4 cant connect - people just get kicked with the message "you are already connected to this server" (default bungeecord message)
So, in fact my question is - can there be added support to the plugin for older minecraft-versions aswell? (Working with viaversion - without protocolsupport everyone can join except for 1.8 users)

**Comment by Shevchik** [comment]
No
