### ISSUE TITLE
[1.4.7] Day light blinking  - DayNight cycle

### ISSUE THREAD

**Issue by kangarko** [ProtocolSupport/ProtocolSupport#504]
Hello,

I connected to a 1.12 server with the build 55 of ProtocolLib and the day light started to blink. The sun appears to set itself to another position and back to the correct one in frequent intervals, and to not respect commands such as /time properly. 

How to reproduce:  

```
/time night
/time day
```

**Comment by Shevchik** [comment]
Do you have daynight cycle disabled?

**Comment by kangarko** [comment]
Yes, it is disabled via /gamerule.

Also I noticed that I cannot respawn once I got killed by a stray skeleton (/spawnmob strayskeleton) (spawns a normal skeleton in armor). After hitting Respawn button, nothing happens. I had to reconnect with 1.12 client to perform the respawn.

**Comment by Shevchik** [comment]
1.4.7 doesn't support daynight cycle disable. Which means that such behaviour is expected.

**Comment by kangarko** [comment]
I see now. Would it be possible if you could send an extra time packet to prevent blinking, or maybe prevent sending time update at all?

**Comment by Shevchik** [comment]
Not preventing, but you actually need to translate negative time offsets to positive, it is possible, but i don't have time for that rn.

**Comment by kangarko** [comment]
Okay, no problem!

**Comment by Shevchik** [comment]
Fixed. Sun will still move a bit and jump back, but at least not complete day/night change.

**Comment by kangarko** [comment]
Oh thank you what a great news!
