### ISSUE TITLE
Where's Jenkins for ProtocolSupportPE? 

### ISSUE THREAD

**Issue by TroniQ89** [ProtocolSupport/ProtocolSupport#506]
Hi,
I noticed that the ProtocolSupportPE plugin no longer has a Jenkins CI.
is it normal ?
It is possible to give me a .jar ? 

Thank you.

**Comment by DaMatrix** [comment]
I'm unofficially hosting a jenkins excusively for the PE version [here](http://jenkins.daporkchop.net/job/ProtocolSupportPE/lastSuccessfulBuild/artifact/target/), if you want.

**Comment by TroniQ89** [comment]
Thank you very much, let's try it :)

**Comment by gdude2002** [comment]
Please note that, officially, we (as in, myself and Shevchik) typically don't allow other users to post builds of the plugin anywhere for security reasons. We trust @DaMatrix but I'm still going to have to ask him to remove the link.

I'd do it myself but I don't have repo access, just admin on Discord :P

**Comment by DaMatrix** [comment]
Alrighty, will do. Sorry :/

**Comment by gdude2002** [comment]
Thanks - Don't worry, you're not in trouble or anything, I just don't want
to have uneven enforcement. It's not fair on everyone else.

**Comment by Legoman99573** [comment]
Setting it up as a gradle build in Jenkins is all you need to do. I wont link, but I do plan on testing the PE part later on
