### ISSUE TITLE
Skipping BlockEntity and kick

### ISSUE THREAD

**Issue by Feerko** [ProtocolSupport/ProtocolSupport#513]
I DELETE ALL OF PLUGINS
the same plugins are on my second server and this error doesn't exists.
The problem is on map. 

`Skipping BlockEntity with id minecraft:bed
Skipping BlockEntity with id minecraft:bed
Skipping BlockEntity with id minecraft:bed
Skipping BlockEntity with id minecraft:bed
Skipping BlockEntity with id minecraft:bed
Skipping BlockEntity with id minecraft:bed`

How can I fix this? I will not delete the map. Beds are on every map.
Can you tell how to modify your plugin to not kick players?

**Comment by Shevchik** [comment]
The problem is some entity, not the block.

**Comment by Feerko** [comment]
Can you help me edit your plugin to prevent kicking player or find another solution to fix it? Please... I'm trying fix this about 10 hours...

**Comment by Shevchik** [comment]
No. Remove all entities from your map using MCEdit and make sure you don't have a plugin that spawns such entities anymore.

**Comment by Feerko** [comment]
I'm sure because this error exists only on one map. I will try MCEdit. Please keep issue open. Thanks.

**Comment by Feerko** [comment]
It's weird... This error casues your plugin together with multiverse. Weird.
