### ISSUE TITLE
Not Letting 1.11 clients join

### ISSUE THREAD

**Issue by Snickerzzz** [ProtocolSupport/ProtocolSupport#516]
Hi,

So my server is currently 1.11.2 and I try to use protocol support but it doesn't work.

It works for all the other clients except 1.11 clients.
I get this error: https://gyazo.com/e309a5c8a594895ea8feace7587477e5

In the console, it doesn't show any errors it just says that the player disconnected.

I have set the native to false in the server properties. I don't know what else to do.

**Comment by Shevchik** [comment]
Invalid json was sent somewhere. Try finding out at which position in happens and why.

**Comment by Snickerzzz** [comment]
I'm not really good at this stuff so I don't know what that means haha.

**Comment by Shevchik** [comment]
Post server ip then

**Comment by Shevchik** [comment]
....
