### ISSUE TITLE
Rainbow API support.

### ISSUE THREAD

**Issue by IsaiahPatton** [ProtocolSupport/ProtocolSupport#517]
Hello, I was wondering if you would add support in ProtocolSupport for the Rainbow API. Rainbow has a Bukkit bridge but it doesn't have OBC/NMS.  Link for Rainbow is http://project-rainbow.org/

Rainbow: https://github.com/Codecrafter47/Rainbow

**Comment by Shevchik** [comment]
Our top priority now is mcpe support, so this will have to wait for a long time.

**Comment by Legoman99573** [comment]
And the reacton when they saw it in the discord
![image](https://user-images.githubusercontent.com/7460704/27247756-50acc324-52c1-11e7-840a-519453fe7d3e.png)

But I don't think anyone knows what rainbow is tbh. But as @Shevchik said. "It will be a long time"

**Comment by Shevchik** [comment]
Seems ded.
