### ISSUE TITLE
1.11.2 clients sometimes get kicked

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#528]
https://pastebin.com/raw/zunpFhGY

**Comment by Shevchik** [comment]
Client sent invalid animation packet, will check it later.

**Comment by Brokkonaut** [comment]
I have seen only very few instances of this exception (and only from 2 players for now), so maybe they are using some modified client that sends broken data.

**Comment by Shevchik** [comment]
Yeah, client didn't send used hand in a packet.
