### ISSUE TITLE
Players on 1.8 and below cannot brew potions.

### ISSUE THREAD

**Issue by Dank9131** [ProtocolSupport/ProtocolSupport#531]
Hey, so I have a server which runs 1.11.2 PaperSpigot and I am using the latest version of Protocol Support. So today I stumbled upon two issues, regarding the same category.

The first issue is that players running on the version 1.8 and below cannot brew potions, via a brewing stand. I believe that this is due to the fact that in Minecraft 1.9, Mojang introduced a new brewing mechanism (you need to add blaze powder to fuel the brewing stand). However, I would like to know if there is a way to fix it so that my 1.7 and 1.8 players can brew potions.

Lastly, the second issue is that in creative mode, when I drag potions from my inventory, the potions turn into water bottles. I searched the internet for this and it looks like you are currently fixing the problem. However, this is not my priority of the post, the priority is the first issue. So can you please tell me how to make it so that 1.7+ users can brew or can you fix the plugin.

Cheers - Dank.

**Comment by xNaXDy** [comment]
Regarding the creative mode issue, refer to the README.md:

> Known issues:
> [Anything that is not latest] Items in creative mode may not work as expected, or may not work at all

Regarding your first issue: Seeing that the new interface for the potion stand is a client-side inventory modification, I very much doubt that it is possible to fix this issue. (I'm not a ProtocolSupport dev though, so take that with a grain of salt) What I suggest you do is write your own plugin, that automatically puts in blaze powder into the brewing stand, if the player has blaze powder in their inventory. It's not the best solution, but it'll work.

**Comment by Pablete1234** [comment]
Try hoppers to put in the blaze automatically, again, not perfect, but better than nothing

**Comment by Shevchik** [comment]
Use ProtocolSupportBrewingStand
