### ISSUE TITLE
1.11.2 clients are kicked when they click shulker shell in inventory

### ISSUE THREAD

**Issue by wasder** [ProtocolSupport/ProtocolSupport#535]
![](http://i.imgur.com/YikRXIp.png)
PS build #64.
Nothing in logs, just disconnected.

**Comment by xNaXDy** [comment]
<img width="601" alt="screen shot 2017-06-26 at 17 48 49" src="https://user-images.githubusercontent.com/4532582/27547968-cf2662cc-5a97-11e7-8e47-372d5c553ed4.png">
works without a problem on these versions.

**Comment by Shevchik** [comment]
Server debug log is needed.
