### ISSUE TITLE
Chat spam

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#538]
The chat is being spammed by "chat.type.advancement.task". I'm playing on version 1.8 and I have the latest spigot and Plib/Psupport versions.

**Comment by Shevchik** [comment]
It's an unsupported translation. ProtocolSupport sohuld translate unsupported translations serverside, but thats a low priority.

**Comment by xNaXDy** [comment]
If you want to disable all advancement announcements (including this weird one), use the gamerule command to disable them on every world, and you will be fine.

**Comment by Shevchik** [comment]
Now translations that are not supported by client should be translated serverside.
