### ISSUE TITLE
Request: Display Glazed/Regular Terracotta as colored Hardened Clay on 1.11.2 and lower instead of Bricks

### ISSUE THREAD

**Issue by xNaXDy** [ProtocolSupport/ProtocolSupport#539]
low priority.

**Comment by Shevchik** [comment]
You can change remapping via api. The default won't change because hardened clay has faster break time than hardened clay.

**Comment by xNaXDy** [comment]
Ah okay, that makes sense. I hadn't even considered break time, thanks for clarifying!
