### ISSUE TITLE
[1.5.2/1.6.x/1.7.x] Carpets glitch the player

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#54]
Because carpets were added a slight "Step" in 1.8 the server knows that the client should go up a bit however in 1.7 and below the clients don't know that and don't go up resulting in the server glitching them a bit where the carpet is.

**Comment by Shevchik** [comment]
Not sure if i can even fix that.

**Comment by phase** [comment]
@Tom-III 
> resulting in the server glitching them a bit where the carpet is
What happens to them?

**Comment by Tom-III** [comment]
It makes the players go back to where the carpet was
(Its what happens if you turn noclip on in multiplayer and try to go through a wall)

**Comment by MrPowerGamerBR** [comment]
I tested this issue in 1.5.2 and 1.7.2.

No "glitching" was detected, maybe @Shevchik fixed this issue and forgot to close this issue?

Tested with a user with no OP and without any permissions in PermissionsEx.

**Comment by Tom-III** [comment]
Give yourself a speed 2 potion and you will start to notice it.
It gets worse if you have NoCheat installed.

**Comment by Shevchik** [comment]
Well, set carpets as IGN_PASSABLE in NoCheatPlus config.
