### ISSUE TITLE
Various Commands kicking players with ProtocolSupport Enabled

### ISSUE THREAD

**Issue by GhotiMayo** [ProtocolSupport/ProtocolSupport#541]
[https://hastebin.com/tulecupaza](https://hastebin.com/tulecupaza)
Various plugins have been kicking players from the game. I believe they all use ProtocolLib, but the error is pointing to this. This only occurs when ProtocolSupport is installed. This has been the case with all 1.12 compatible builds so far.

**Comment by Shevchik** [comment]
Something is wrong with click action on one of the json components. Also try getting the same log with debug enabled.

**Comment by GhotiMayo** [comment]
[https://hastebin.com/otevecimay.lua](url)
I don't know why it says its a lua, but I repeated everything with with debug enabled.

**Comment by GhotiMayo** [comment]
[https://hastebin.com/otevecimay](url)

I repeated everything with debug enabled.

**Comment by Shevchik** [comment]
Reproduce this with new build with debug enabled

**Comment by GhotiMayo** [comment]
[Here](https://hastebin.com/gutosipexo) is the new log.

**Comment by Shevchik** [comment]
This json chat string isn't valid, some of the client events doesn't contain values.
{"extra":[{"text":"§7§m+--------------------------------------------+§8[§e"},{"clickEvent":{"action":"run_command"},"text":"§7«"},{"clickEvent":{"action":"run_command"},"text":"§8/§a"},{"clickEvent":{"action":"run_command","va
lue":"/furniture list 2"},"text":"§a»"},{"clickEvent":{"action":"run_command","value":"/furniture list 2"},"text":"§8]"}],"text":""}

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by GhotiMayo** [comment]
Yes, it appears to work now.
