### ISSUE TITLE
Lack of sound

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#545]
I don't hear hitting/damage sound when I'm on fire. I'm playing on 1.8. Also when I'm drowning i can't hear this sound.

**Comment by ItzVinex** [comment]
I can confirm this is the exactly the same bug I get.

**Comment by 7kasper** [comment]
I am able to reproduce this aswell. All versions below 1.12 are affected. I think 1.12 doesn't send the hurt animations..

**Comment by DanielAlves123** [comment]
This bug is still existing.

**Comment by 7kasper** [comment]
@DanielAlves123 I assume you mean the drowning part right?

**Comment by 7kasper** [comment]
@DanielAlves123 Should be fixed now.
