### ISSUE TITLE
Shooting someone

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#546]
Often when I try to shoot someone with bow for example I hit him but it doesn't damage him etc. Same with shooting myself.

**Comment by xNaXDy** [comment]
Are you sure it's ProtocolSupport related? Also, try to find out exactly when this occurs. There has to be something triggering it. Tracking random occurrences is very difficult.

**Comment by Shevchik** [comment]
ProtocolSupport doesn't change anything about damaging entities.
