### ISSUE TITLE
1.8 spawner crash

### ISSUE THREAD

**Issue by Pablete1234** [ProtocolSupport/ProtocolSupport#547]
When using 1.8 forge, if a spawner has both SpawnData and SpawnPotentials the client crashes.

Steps to reproduce, setblock 3 spawners
on spanwer 1: `/blockdata ~ ~-1 ~ {SpawnPotentials:[{Entity:{Item:{id:"minecraft:arrow",Count:1b,Damage:0s},id:"minecraft:item"},Weight:1}]}`
on spawner 2: `/blockdata ~ ~-1 ~ {SpawnData:{Item:{id:"minecraft:arrow",Count:1b,Damage:0s},id:"minecraft:item"}}`
each spawner has one different thing, no crash yet, now
on spawner 3: `/blockdata ~ ~-1 ~ {SpawnData:{Item:{id:"minecraft:arrow",Count:1b,Damage:0s},id:"minecraft:item"},SpawnPotentials:[{Entity:{Item:{id:"minecraft:arrow",Count:1b,Damage:0s},id:"minecraft:item"},Weight:1}]}`

and you crash

**Comment by Electroid** [comment]
👍 Although this is a partially Forge's fault, every server has so many Forge clients I think it would be in the best interest of everyone to fix it. Only sending `SpawnPotentials` fixes the issue and works fine with Vanilla clients.

**Comment by Shevchik** [comment]
The funny thing is that protocolsupport removes the SpawnPotentials from tile entity update packet or at least tries to do so.

**Comment by Shevchik** [comment]
Yeah thats it, actually event spawner 2 crashes the client. Minecraft 1.8 can't render non living inside mob spawner. Vanilla just skips rendering, forge crashes. Will have to restrict entity data to living entities only.

**Comment by Shevchik** [comment]
Removed some entity types from remapping table, spawner won't display anything now for old clients.
