### ISSUE TITLE
Server start error

### ISSUE THREAD

**Issue by MAXIMMAS1** [ProtocolSupport/ProtocolSupport#550]
Hello,

On our server, we have a little problem, every time when we start the server we get this error:
protocolsupport.protocol.pipeline.common.LogicHandler$NetworkException: Network exception occured(address: /ip:XXXXX, username: null, version: UNKNOWN)
All the "X" are numbers from a different port (every time it shows different numbers so a different port?)(I have changed the numbers of the server ip to the name "ip").
Thanks for helping

Kind regards
MAXIMMAS (Maxim)

**Comment by Shevchik** [comment]
Paste the full log. But most likely it's just some sort of software pinging the port with invalid data.
