### ISSUE TITLE
Inventory Transfer Bug

### ISSUE THREAD

**Issue by op-Hen** [ProtocolSupport/ProtocolSupport#552]
This occurs if a player is not on 1.12 with the latest ProtocolSupport from github.

If a player on a lower Minecraft version shift clicks items from their inventory to fast transfer items as shown in this video:

[https://www.youtube.com/watch?v=qAFER-GwWHc](url)

The items will flash into the chest and then reappear in the players inventory.

**Comment by Shevchik** [comment]
Unable to reproduce on local test server, reproduce this with only ProtocolSupport.
