### ISSUE TITLE
Постоянные ошибки

### ISSUE THREAD

**Issue by enly1337** [ProtocolSupport/ProtocolSupport#555]
В консоли постоянно появляются ошибки, связанные с ProtocolLib независимо от плагинов.

![3](https://user-images.githubusercontent.com/29000881/28304899-e1d460d0-6bc3-11e7-91ba-f78217d37142.png)
![4](https://user-images.githubusercontent.com/29000881/28304902-e2afb6bc-6bc3-11e7-90e1-3f161e1b3a15.png)

Paperspigot 1.12 1152

**Comment by Shevchik** [comment]
A plugin uses protocollib to listen for packets, but sometimes player is not yet logged in, so this error happens in protocollib. Nothing can be done here.

**Comment by enly1337** [comment]
Can I hide it?
