### ISSUE TITLE
Potions are not displayed correctly for 1.8 clients (but they work fine)

### ISSUE THREAD

**Issue by GotoFinal** [ProtocolSupport/ProtocolSupport#557]
Brewing potions works fine, but players think it is not due to how awkward potions are displayed: (no creative was used here)

![](http://i.imgur.com/CTBRItZ.png)
![](http://i.imgur.com/rVaPE2E.png)

It would be great to display it like in normal 1.8:
![](http://i.imgur.com/HnJFkSQ.png)

(This same for other kind of water potions)

**Comment by Shevchik** [comment]
Server -> client potions should be remapped. Not idea why it doesn't work. Try dumping slot itemstacks nbt content, maybe the used nbt changed.

**Comment by GotoFinal** [comment]
@Shevchik in 1.8 awkward potion don't use any special NBT, it is just item with id 373:16, for nbt in 1.11 tho:
![](http://i.imgur.com/Lq04upo.png)
And from single player 1.8:
![](http://i.imgur.com/jbljaWJ.png)

And from what I see client is still getting 1.9+ one, I could try debug outgoing packet from server to client using plib, but I hope this is enough.

**Comment by Shevchik** [comment]
Should be fixed now. The basic potion was remapped (a custom name was applied to item), but the method that was setting itemstack display name was invalid.

**Comment by GotoFinal** [comment]
@Shevchik thanks.
You are not supporting older versions? If I want that for 1.11 I need to fork from 1.11 commit and merge that commit?

**Comment by Shevchik** [comment]
Yes

**Comment by GotoFinal** [comment]
@Shevchik can you tell me which commit was used for 1.11 build? as I can't find valid one ;/

**Comment by gdude2002** [comment]
This is the last commit for 1.11, as far as I know. https://github.com/ProtocolSupport/ProtocolSupport/commit/cca690b6d27849345e119524a0b6ffa2555d267b
