### ISSUE TITLE
Passengers in boats

### ISSUE THREAD

**Issue by haugsvar** [ProtocolSupport/ProtocolSupport#560]
It would be nice to have a support for 1.9, 1.10 and 1.11 clients to ride with passengers in boats while running with ProtocolSupport on a 1.12 server. At least, a configurable option to turn on/off if server owner want's to break/exclude < 1.9 clients.

Related previous issues filed:

https://github.com/ProtocolSupport/ProtocolSupport/issues/355
https://github.com/ProtocolSupport/ProtocolSupport/issues/260

**Comment by Shevchik** [comment]
No. If you really want this, then clone repo, remove the check and < 1.9 clients supports.

**Comment by Shevchik** [comment]
Actually i can do something about it. A new api will be added that allows disabling some of the versions support, if you disable support for all < 1.9 versions, multiple passengers will be allowed.

**Comment by haugsvar** [comment]
That sounds great. Thank you for all the work you put into this code. We are all very greatful for it.
