### ISSUE TITLE
Memory usage problems on the latest versions

### ISSUE THREAD

**Issue by HLF-Raideer** [ProtocolSupport/ProtocolSupport#567]
We noticed that the new versions of ProtocolSupport (MC 1.12 and above) are using a lot of memory (at least double than older versions). We have a lot of minigame arena servers (so 1 arena/server) and using protocolsupport on them .. and this is a big problem for us, because after the 1.12 update, our servers are allocating (and using) more than 1 GB of memory on startup.

Before i wrote this issue-ticket we checked the following:

- The startup command (it is the same as in the older versions)
- The other plugins (removed all of them .. only PS remain and that cause the problem - only spigot allocates 128MB as in the Xms value)

**Comment by Shevchik** [comment]
Because with every version more and more memory needed to hold all the remappers.
