### ISSUE TITLE
1.8 players freeze after a random amount of time ver 4.25

### ISSUE THREAD

**Issue by rewtie** [ProtocolSupport/ProtocolSupport#572]
people playing on 1.8 will get a glitch that they basically freecam around the server and cant break blocks or even move until they relog. when they log back in they log in where they were at when they logged out on their screen.
example: my alt is standing here according to my main account: http://i.imgur.com/29ejgLw.png
on my alts screen i am here and unable to break blocks: http://i.imgur.com/OAcj70e.png
i tried this on a server with just the most recent version of 1.11.2 paperspigot and protocolsupport and the bug was reproduced, with no errors in console

**Comment by Shevchik** [comment]
We are not supporting not latest version.
