### ISSUE TITLE
Potions

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#575]
I see all potions in my inventory as water bottles, I'm playing on 1.8 and I'm using the newest version.

**Comment by gdude2002** [comment]
This is a known issue, and to my knowledge there are no plans to fix it at the moment as the mechanics of how potion items work changed post-1.8.

**Comment by Shevchik** [comment]
They do work and display properly, unless you took them from creative.

**Comment by DanielAlves123** [comment]
@Shevchik i have them from plugin that gives kits, all potions work but they appear as water bottles.

**Comment by Shevchik** [comment]
Post a potion nbt here.

**Comment by Shevchik** [comment]
Okay, found the issue.

**Comment by DanielAlves123** [comment]
Splash potions appear as normal.

**Comment by Shevchik** [comment]
Should be fixed now
