### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by steven5297norton** [ProtocolSupport/ProtocolSupport#578]
I have changed my IP to XXX.XX.XXX.XXX

26.07 17:37:40 [Server] INFO [ProtocolSupport] /XXX.XX.XXX.XXX:42867 connected with protocol version MINECRAFT_1_12
26.07 17:37:50 [Server] INFO [ProtocolSupport] /XXX.XX.XXX.XXX:42884 connected with protocol version MINECRAFT_1_12
26.07 17:38:00 [Server] INFO [ProtocolSupport] /XXX.XX.XXX.XXX:42913 connected with protocol version MINECRAFT_1_12
26.07 17:38:04 [Server] WARN java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30022ms.
26.07 17:38:10 [Server] INFO [ProtocolSupport] /XXX.XX.XXX.XXX:42928 connected with protocol version MINECRAFT_1_12
26.07 17:38:20 [Server] INFO [ProtocolSupport] /XXX.XX.XXX.XXX:42957 connected with protocol version MINECRAFT_1_12
26.07 17:38:30 [Server] INFO [ProtocolSupport] /XXX.XX.XXX.XXX:42974 connected with protocol version MINECRAFT_1_12
26.07 17:38:35 [Server] WARN java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30006ms.

**Comment by gdude2002** [comment]
This set of logs has nothing to do with ProtocolSupport. It looks like whatever you're using for your SQL database is broken or very slow, but PS doesn't use SQL - that'll be some other plugin.

**Comment by steven5297norton** [comment]
No one can connect to my server due to this error.

**Comment by MrPowerGamerBR** [comment]
@steven5297norton ...this isn't a ProtocolSupport error, it is another plugin that is causing this issue.

The only thing ProtocolSupport is doing is logging the joins, just because it is doing that doesn't mean that it is who is causing your issue.
