### ISSUE TITLE
Potion translation problem

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#580]
when in 1.8.9 and below splash potions do not work at all and getting any potions from the creative menu turn into water bottles. Im hoping this will be patched, pretty annoying for kitpvp.

**Comment by MrPowerGamerBR** [comment]
Read the readme before submitting issues.

![http://i.imgur.com/dGpclB3.png](http://i.imgur.com/dGpclB3.png)
