### ISSUE TITLE
Book and Quill Glitch?

### ISSUE THREAD

**Issue by HyKurtis** [ProtocolSupport/ProtocolSupport#581]
On my server there is this issue that happens every few days where every player on the server has their whole inventory filled with fake book and quill items.

The only known way the fix the issue is to restart the server. This issue is apparently caused by protocol support reacting to a hacked client. Hopefully you can fix it!

This is what it looks like:
![image](https://user-images.githubusercontent.com/17110585/28692708-9dc2f7aa-7319-11e7-8d11-a03df66a3386.png)

If this isn't to do with your plugin I'm very sorry but it's what everyone is telling me.

**Comment by HyKurtis** [comment]
The screenshot was not taken by me it's from someone that has the same issue, I haven't taken a screenshot myself yet but it looks the exact same.

**Comment by Shevchik** [comment]
You will have to confirm it's protocolsupport first somehow. So you will have to find out how extacly it happens first, and then come back.
