### ISSUE TITLE
EntityDamageEvent NPE

### ISSUE THREAD

**Issue by Joannou1** [ProtocolSupport/ProtocolSupport#582]
This one is a bit spammy, it doesn't seem to affect gameplay and is really inconsistent on when it occurs.
Using latest build (#107) https://hastebin.com/mulujewili.vbs - also occurred in the last 10 or so builds.

In this case, with nobody on the server except myself, I'm spawning 5 wolves per 3 seconds 20 blocks in the air, when they hit they ground this exception is thrown _sometimes_.

**Comment by Shevchik** [comment]
Fixed now
