### ISSUE TITLE
ProtocolSupport it does not working for "PaperSpigot 1.11.2"

### ISSUE THREAD

**Issue by craftrise** [ProtocolSupport/ProtocolSupport#583]
/version output:

"This server is running Paper version git-Paper-1104 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)"

And, latest ProtocolSupport build:

[01:16:36] [Server thread/INFO]: [ProtocolSupport] Loading ProtocolSupport v4.26
[01:16:36] [Server thread/ERROR]: [ProtocolSupport] Unsupported server implementation type

**Comment by Castar** [comment]
You can try to edit source code.

**Comment by MrPowerGamerBR** [comment]
The latest ProtocolSupport development build only works with 1.12, if you need 1.11.2, you can download it from Spigot, however it is now unsupported.
