### ISSUE TITLE
Config option to choose wich versions we want to accept

### ISSUE THREAD

**Issue by dartasen** [ProtocolSupport/ProtocolSupport#585]
It would be very cool if the plugin could propose a config option to select only certain versions we want to accept on our server.
For example if I want to accept 1.10 and more but not 1.9 and less clients.

Sorry for my bad english.

**Comment by gdude2002** [comment]
https://www.spigotmc.org/resources/blockversion-for-protocolsupport.21202/

**Comment by Shevchik** [comment]
Check addons before actually creating issue.
