### ISSUE TITLE
a mcpe branch bug with protocollib

### ISSUE THREAD

**Issue by Asuna-Yuuki** [ProtocolSupport/ProtocolSupport#586]
if i install ProtocolLib and am already login with mc mcpe cant connect

idk if tish can help

[14:18:16 INFO]: StormFireBoy6661 lost connection: Internal Exception: io.netty.
handler.codec.EncoderException: java.lang.IllegalArgumentException: object is not an instance of declaring class

Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Windows 8.1 6.3 amd64

**Comment by Asuna-Yuuki** [comment]
i know its pauzed for mcpe 1.2

**Comment by 7kasper** [comment]
I had this problem too. PE connects, all fine but PC can't join and if PC joins first. All fine. PE can't join. Weird problem that is only caused in combo with ProtocolLib. Has to be solved before release, but that won't be in a while ^^

**Comment by Shevchik** [comment]
ProtocolLib tries to cache some methods for some channels handlers. Which doesn't work because they are not the same for pc and pe
