### ISSUE TITLE
Custom skull texture does not work on <1.7.10

### ISSUE THREAD

**Issue by phenomax** [ProtocolSupport/ProtocolSupport#590]
I'm using the most recent PaperSpigot 1.12 with ProtocolSupport v4.26.
When creating a new skull with custom GameProfile and modify the SkullMeta profile like this
```
 final Field field = meta.getClass().getDeclaredField("profile");
                field.setAccessible(true);
                field.set(meta, gameProfile);
```
the skull does appear on 1.8 - 1.12; on 1.7.10 I only get a normal Steve skull.

**Comment by MrPowerGamerBR** [comment]
Are you setting a custom skin to the skull or a custom name on the skull?

Correct me if I'm wrong but as far as I know custom skins on skulls (by using the texture value of an skin) only works in 1.8+, pre-1.8 clients can only apply a player name to a skull.

**Comment by phenomax** [comment]
I've never really worked with versione pre 1.8 - could you please check your theory with the custom skull data? I'll too.
Another indication for this, is that a regular created skull 
```
final ItemStack skull = new ItemStack(Material.SKULL_ITEM, 1, (short) 3);
        final SkullMeta iM = (SkullMeta) skull.getItemMeta();
        iM.setOwner("MHF_TNT");
        skull.setItemMeta(iM);
```
does also display a Steve head on 1.7.10.. :(

**Comment by MrPowerGamerBR** [comment]
@phenomax hm yeah when I think it is an issue with ProtocolSupport.

While I'm not sure if 1.7.9-1.7.10 supports skins from a texture value (since it was that period when everything was switching to UUID and it was the first time we could swap player skins if I recall correctly) I'm 100% sure pre-1.7.9 doesn't support texture values, only usenames.

**Comment by Shevchik** [comment]
Need to check the skull owner nbt tag. Does this affects only item skulls, or blocks too?

**Comment by phenomax** [comment]
@Shevchik I'll test this.
Update: My 1.7.2 tests failed because I wasn't even able to join the server due to a client side crash:
```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 31.07.17 18:20
Description: Ticking screen

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at bls.a(SourceFile:270)
	at bls.a(SourceFile:220)
	at azd.a(SourceFile:1675)
	at azd.a(SourceFile:1633)
	at biv.a(SourceFile:113)
	at gu.a(SourceFile:70)
	at gu.a(SourceFile:13)
	at ef.a(SourceFile:164)
	at bbe.c(SourceFile:76)
	at azd.o(SourceFile:1318)
	at azd.ad(SourceFile:753)
	at azd.e(SourceFile:704)
	at net.minecraft.client.main.Main.main(SourceFile:103)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at bls.a(SourceFile:270)
	at bls.a(SourceFile:220)
	at azd.a(SourceFile:1675)
	at azd.a(SourceFile:1633)
	at biv.a(SourceFile:113)
	at gu.a(SourceFile:70)
	at gu.a(SourceFile:13)
	at ef.a(SourceFile:164)
	at bbe.c(SourceFile:76)

-- Affected screen --
Details:
	Screen name: bbe

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Non-integrated multiplayer server
Stacktrace:
	at biz.a(SourceFile:284)
	at azd.b(SourceFile:1951)
	at azd.e(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:103)
```

**Comment by phenomax** [comment]
@Shevchik When creating a skull block with this code
```
 final Skull skull = (Skull) block.getState();
        skull.setSkullType(SkullType.PLAYER);
        skull.setOwningPlayer(Bukkit.getOfflinePlayer("Notch"));
        skull.update();
```
or get the OfflinePlayer by any UUID, the end result looks like this:
![image](https://user-images.githubusercontent.com/12475496/28792579-604597ba-7630-11e7-8433-407ab272671e.png)
Note: The server is running in online mode

**Comment by Shevchik** [comment]
IDK about API, but giving head via /give (my name) minecraft:skull 1 3 {SkullOwner: md_5} definitely works

**Comment by phenomax** [comment]
@Shevchik It's a bit weird... When I inject a GameProfile into a TileEntitySkull using this code
```
final TileEntitySkull tileEntity = (TileEntitySkull) ((CraftWorld) skull.getWorld()).getHandle()
                .getTileEntity(new BlockPosition(skull.getX(), skull.getY(), skull.getZ()));

        tileEntity.setGameProfile(gameProfile);
        tileEntity.update();
```
the skull's texture can be displayed on 1.7.10 & 1.8+....
But when I inject the GameProfile using reflection into a skull_item it doesn't

**Comment by Shevchik** [comment]
Strange, for me it displays md_5's skull, which works as expected

**Comment by phenomax** [comment]
Which code snippet have you used?

**Comment by phenomax** [comment]
ping @Shevchik

**Comment by Ev3ryShir** [comment]
the same code isn't used for <=1.7.10 while it is accepted by 1.8+ why can't you use the skull command and put it on the floor? it will work 100% in all versions (/skull (nickname)) [needed essentialsX] stop to make the things harder...

PS: The skin must be compatible with the last Steve or it will show a totally bugged skin...
PS2:Why you guys from @ProtocolSupport (@MrPowerGamerBR ) not create any skin converter for skins 1.8+ show normally in 1.7.10 or less versions xD?

**Comment by Ev3ryShir** [comment]
#Update NOW all versions any skin is working... except 1.9+ servers with just ONLINE MODE ON (Just for Original)

**Comment by MrPowerGamerBR** [comment]
I can confirm this happens with *placed* skulls on a world, I gave myself a skull with the owner = "MHF_Pig", placed the skull on 1.12.2... then after switching to 1.5.2 all skulls were Steve skulls (while they still showed up fine in 1.12.2)

I will try checking what did happen, maybe Mojang stripped the owner from the skull after placing it?

**Comment by Shevchik** [comment]
Versions < 1.7 grab the skin by name. So i guess something broke in skull nbt transformation.

**Comment by MrPowerGamerBR** [comment]
Mojang retired the old skin servers: https://bugs.mojang.com/browse/WEB-985

So probably this issue doesn't even matter too much anymore... :cry

**Comment by Shevchik** [comment]
So that's it, mojang killed the old skin download server, so clients < 1.7 are no longer able to download skins.
