### ISSUE TITLE
Concrete Blocks are Bricks when using <1.12

### ISSUE THREAD

**Issue by MrSpock78** [ProtocolSupport/ProtocolSupport#592]
Is it possible to change Concrete-Blocks to Wool-Blocke like Concrete-Powder?
1.12 players start to build pixelarts and other things with 1.12 colored concrete-blocks.
It really looks ugly for 1.8-1.11.2 players when pixelarts are filled with bricks.

**Comment by MrPowerGamerBR** [comment]
https://www.spigotmc.org/resources/protocolsupportstuff.44527/
