### ISSUE TITLE
Random disconnects

### ISSUE THREAD

**Issue by TWSSYesterday** [ProtocolSupport/ProtocolSupport#596]
Using latest Bar one of Paper Spigot and latest 1.12 version of Protocol Support
Pastebin https://hastebin.com/tatamefape.md

**Comment by gdude2002** [comment]
There's not enough in that log to tell us too much. A full log would be appreciated.

**Comment by TWSSYesterday** [comment]
The log has nothing in it, no error messages and normal startup

**Comment by gdude2002** [comment]
The fact is that this ticket does not have enough information to work with. You are probably not looking for what we are looking for.

Also, you need to give your test case - how do you replicate this? Be detailed.

**Comment by Shevchik** [comment]
Enable debug and try again

**Comment by TWSSYesterday** [comment]
That was with debug enabled

**Comment by Shevchik** [comment]
This log only shows that disconnection happened on the other side

**Comment by TWSSYesterday** [comment]
Okay so updating the server version and protocol support worked lol... No idea what happened there.
