### ISSUE TITLE
autocrafting does not work/ client desync (1.12 client on 1.12.1 server)

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#601]
when i click items in the crafting book they are put in the crafting field but i cannot craft the result - when i close that inventory the inventory is just desycnced until i move something in the inventory to the crafting field

**Comment by Shevchik** [comment]
The crafting packet between 1.12 and 1.12.1 differs too much, so it won't work.

**Comment by Brokkonaut** [comment]
Is it possible to send at least some inventory refresh for the client to avoid desynced inventories?

**Comment by Shevchik** [comment]
Maybe.
