### ISSUE TITLE
Possible change with paperspigot that causes protocolsupport to not work with plugins

### ISSUE THREAD

**Issue by johnb165** [ProtocolSupport/ProtocolSupport#606]
The full issue can be viewed here: https://github.com/drtshock/Essentials/issues/1442 as I am having the same problem. Wondering if protocolsupport can work around this issue

**Comment by Shevchik** [comment]
We are targeting spigot api, not paperspigot one. Will try to find a workaround later, probably just implementing those methods will be enough.

**Comment by Shevchik** [comment]
Should be fixed now
