### ISSUE TITLE
Ping Appears as No connection with ProtocolSupport (1.12.1 PaperSpigot)

### ISSUE THREAD

**Issue by CDAGaming** [ProtocolSupport/ProtocolSupport#607]

**Comment by gdude2002** [comment]
What're you talking about exactly? Retrieving the MOTD in the client's server list?

**Comment by CDAGaming** [comment]
Like the connection icon in server list. ITll usually display something like "60MS" but for me and my players, it would display "(No connection)". After Removing it, ping went to normal.

**Comment by gdude2002** [comment]
Is that for all versions of Minecraft on the client, or just some versions?

**Comment by CDAGaming** [comment]
For me, so far ive only tested it on 1.12.1

**Comment by CDAGaming** [comment]
Closed, issue was with a new plugin called ProtocolSupportPotions.

**Comment by gdude2002** [comment]
Thanks for that clarification.

I'm actually looking into that plugin as well, I hadn't heard of it before. I appreciate you bringing it to my attention.

**Comment by CDAGaming** [comment]
Your Welcome. Hopefully support can be added to it so i ma re-add it back one day. The Plugin is newly release, so i wasn't that surprised a bug of this sort was found. :P

**Comment by gdude2002** [comment]
Don't forget to report it. :P

**Comment by CDAGaming** [comment]
I won't :)
