### ISSUE TITLE
System Chinese translation error

### ISSUE THREAD

**Issue by Mgazul** [ProtocolSupport/ProtocolSupport#608]
System translation such as: gamemode 1, after the input instruction prompts:鐢ㄦ硶锛?/gamemode <妯″紡> [鐜╁]  ，浣犵殑娓告垙妯″紡宸茶鏇存柊涓?鍒涢?犳ā寮?  Hope to repair in time

**Comment by Mgazul** [comment]
Use the latest build # 127
Server version 1.12.1

**Comment by Shevchik** [comment]
I'm not familiar with chinese. What exactly is wrong here?

**Comment by Mgazul** [comment]
Is the localized language wrong? When I uninstall this plugin, I get back to normal

**Comment by Shevchik** [comment]
What do you mean exactly? Wrong locale? Wrong translation? Wrong arguments (missplaced)?

**Comment by Mgazul** [comment]
UTF-8 and ANSI coding between the problems. According to the error display instructions, is ANSI encoded display of Chinese, the correct code should be UTF-8 (English is not good, do not mind)

**Comment by Shevchik** [comment]
What is the client version used?

**Comment by Mgazul** [comment]
Server version spigot1.12.1, client version 1.12.1, server system windows 2008, i just tested multiple versions (Jenkins # 124 above), ok the error only appears in # 127.

**Comment by Mgazul** [comment]
When I change the zh_cn.lang under the il8n file to ANSI (the default UTF-8), this error will not exist and all the content will work properly. But the previous version of # 127 does not need to be modified to ANSI

**Comment by Shevchik** [comment]
Your system is not using the utf-8 as default encoding then. Will force the resources to be read as utf-8 later.

**Comment by Mgazul** [comment]
Probably the problem is solved, thanks!

**Comment by Shevchik** [comment]
Should be fixed now.

**Comment by Mgazul** [comment]
Need to manually change the lang code, should be independent of the system, because the plug-in update to # 127 after the problem. I am not very sure.

**Comment by Shevchik** [comment]
Should be really fixed now, forgot to push commit
