### ISSUE TITLE
chat.type.admin

### ISSUE THREAD

**Issue by dhkim0800** [ProtocolSupport/ProtocolSupport#615]
![``](http://userapps.net/s/error.png)
This problem is due to this.
Turning this off does not cause these problems.
Sorry for using translator. 

In the translation file : 
chat.type.text=<%s> %s
chat.type.emote=* %s %s
chat.type.announcement=[%s] %s
chat.type.admin=[%s: %s]

**Comment by gdude2002** [comment]
What exactly are you doing here? Command block `/say`?

**Comment by dhkim0800** [comment]
Nope. It's command block feedback.
/say xx => chat.type.announcement
This issue occurs even if i remove all other plugins.

**Comment by gdude2002** [comment]
Is there a specific Minecraft version that has this problem, or is it all of them?

**Comment by dhkim0800** [comment]
1.12 => same problem

**Comment by dhkim0800** [comment]
wait

**Comment by dhkim0800** [comment]
1.11.2 => same
1.10.2 => same
1.9.4 => same
1.8.9 => same
Do you need more?

**Comment by gdude2002** [comment]
Nope, that should be sufficient. I'll let @Shevchik take a look at it.

**Comment by dhkim0800** [comment]
This issue also occurs in the newly built spigot too.

**Comment by Shevchik** [comment]
This is an untranslated message. No idea why it wasn't able to translate, try to catching chat packet and printing it's contents.

**Comment by dhkim0800** [comment]
How about use force unicode font?
or I can give you my server file.

**Comment by dhkim0800** [comment]
When I uninstall protocolsupport it prints well
[``](userapps.net/s/noerror.png)

**Comment by gdude2002** [comment]
@Shevchik I don't think they're going to be able to debug this for us.

Surely we have enough info to attempt to reproduce?

**Comment by Shevchik** [comment]
I already attempted this, feedback messages are printed fine.

**Comment by dhkim0800** [comment]
ok, i'll upload my server file.

**Comment by dhkim0800** [comment]
Well, this problem happens only in my language.

**Comment by gdude2002** [comment]
@dhkim0800 Are you using the latest build from [Jenkins](https://build.true-games.org/job/ProtocolSupport/)?

**Comment by Shevchik** [comment]
Which language does your client use?

**Comment by dhkim0800** [comment]
Yes, and this problem is solved after I modify spigot files.

**Comment by dhkim0800** [comment]
My language is Korean. In game 한국어(대한민국).

**Comment by dhkim0800** [comment]
oh this problem wasn't solved. My current language was en_us.

**Comment by Shevchik** [comment]
Now i was able to reproduce, will try to find out what goes wrong.

**Comment by Shevchik** [comment]
ko_kr lang extracted from mc 1.12 assets doesn't contain chat.type.admin translation. Mojang did some shit again i guess

**Comment by Shevchik** [comment]
Should be fixed now
