### ISSUE TITLE
Bug with books

### ISSUE THREAD

**Issue by Xayanix** [ProtocolSupport/ProtocolSupport#616]
Sometimes ProtocolSupport is getting bugged, and every player has a lot of writable book is his inventory whose are unable to remove them.

Screenshot: http://i.imgur.com/bNC9H6J.png
Paper b1155
ProtocolSupport b117

**Comment by Shevchik** [comment]
Dump all inventory related packet contents when it happens, and provide there.

**Comment by Xayanix** [comment]
Why is it needed? I checked it, and these items are not sent by packet only, they exist in players inventory. Player can drop then, move etc. Restarting server fixes problem, they are no longer spawning in every player's invnetory but they still exist in it.
![2017-08-09_18 14 54](https://user-images.githubusercontent.com/12672902/29134003-9a5ac52c-7d35-11e7-9fef-3bf83d8fa1c3.png)

**Comment by Xayanix** [comment]
It'll be pretty hard to debug this issue because it happens very randomly and rarely.

**Comment by Shevchik** [comment]
If those items are not ghost items, then ProtocolSupport is not responsible for it. We don't modify player inventory in any way.

**Comment by Xayanix** [comment]
Then what causes this problem? It happens even on HUB with 1 my custom plugin + ProtocolSupport...

**Comment by MrPowerGamerBR** [comment]
@Xayanix were you in creative when you found this issue? If you were in creative and then switched to survival, those "ghosts" items would become "real" items (because that's how creative mode works)

As Shevchik said, you need to dump the inventory related packets when this happens.
