### ISSUE TITLE
PS isn't letting 1.4.7-1.5.1 clients join

### ISSUE THREAD

**Issue by S10MC2015** [ProtocolSupport/ProtocolSupport#620]
Steps to reproduce 
on a Glowstone version 2017.8.1-SNAPSHOT.18dddfd-MC1.12.1 (Implementing API version 1.12.1-R0.1-SNAPSHOT)
Use
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2017.08.09 at 18:03:32 MSK, buildhost: build.true-games.org, buildnumber: 132)
and client stats.

Try to join with 1.4.7 to 1.5.1 client (Doesnt happen on 1.5.2)

![](https://media.discordapp.net/attachments/293148511372050432/344925519139307522/unknown.png?width=841&height=473)

**Comment by Shevchik** [comment]
Force join works.

**Comment by S10MC2015** [comment]
![image](https://user-images.githubusercontent.com/30575036/29174748-27b344f4-7ddf-11e7-94cc-6026de088929.png)
It doesnt work

**Comment by Shevchik** [comment]
Direct connect -> connect

**Comment by S10MC2015** [comment]
ok i guess
