### ISSUE TITLE
Unknown Command Spam in Logs (PaperSpigot)

### ISSUE THREAD

**Issue by CDAGaming** [ProtocolSupport/ProtocolSupport#625]
On 1.12 and on 1.12.1, every 30 minutes my server is online, i get "Unknown command. Type /help for help."

I've used a secondary server with my same plugins but without ProtocolSupport and it works fine, no log spam of unknown commands

**Comment by Shevchik** [comment]
Definitely not ProtocolSupport.

**Comment by CDAGaming** [comment]
Yes sorry. It was Protocol support stuff NOT you guys
