### ISSUE TITLE
"Unknown translation key" on all actionbar messages

### ISSUE THREAD

**Issue by Joannou1** [ProtocolSupport/ProtocolSupport#628]
I believe the latest update to the locale/translation files may have messed something up.

https://github.com/ProtocolSupport/ProtocolSupport/blob/ef392a23993519976e0c04d8c20778b6b5b3c80b/src/protocolsupport/protocol/utils/i18n/I18NData.java#L42

^ That line is what gets put infront of all actionbar messages.
![image](https://user-images.githubusercontent.com/997747/29192730-5cd12abe-7dd7-11e7-992d-ffceb590e317.png)

**Comment by Shevchik** [comment]
Well, the translation key actionbar to Enable entities is not a valid translation key.

**Comment by Joannou1** [comment]
Sorry, but I think this is a real issue.
What am I meant to do to fix this? I'm not going to make translations for all the messages, no way.

**Comment by Shevchik** [comment]
Stop using the translate component to send the messages.

**Comment by Joannou1** [comment]
Quite a few plugins are doing it this way, and I mean a LOT.
A lot of NMS usages as well, example:

`PlayerConnection connection = ((CraftPlayer) player).getHandle().playerConnection;

IChatBaseComponent titleMain = IChatBaseComponent.ChatSerializer.a("{\"text\": \"" + title + "\"}");
PacketPlayOutTitle packetPlayOutTitle = new PacketPlayOutTitle(PacketPlayOutTitle.EnumTitleAction.TITLE, titleMain);
connection.sendPacket(packetPlayOutTitle);`

**Comment by Shevchik** [comment]
This one example uses the correct component to display simple message.
If some plugins for whatever reason use the wrong component - then it's really not my problem.

**Comment by Joannou1** [comment]
That example actually produces the issue I posted above, just tested it.

**Comment by Shevchik** [comment]
The test example you provided show title, not action bar, and it works correctly, only displays test on my screen.

**Comment by Joannou1** [comment]
My bad, copied wrong method, try this:

`PlayerConnection connection = ((CraftPlayer) player).getHandle().playerConnection;`
`PacketPlayOutChat chat = new PacketPlayOutChat(new ChatMessage(message), `ChatMessageType.GAME_INFO);`
`connection.sendPacket(chat);`

**Comment by Shevchik** [comment]
ChatMessage is a translate component. Why do you use a translate component for sending simple message?

**Comment by Joannou1** [comment]
I don't anymore, I use p.sendActionBar() now, but the example was used in a plugin that hasn't received an update in a while and used reflection for that NMS method.
