### ISSUE TITLE
Major Issue Glitch Books filling inventory

### ISSUE THREAD

**Issue by UberMC** [ProtocolSupport/ProtocolSupport#632]
Spigot latest version
1.12.1
On my creative server, everyday this happens, everyones inventory on the server fills with books. and quills But they don't actually exist you can't use them it's a visual glitch.

They fill all empty inventory spots including your armor. You can't use any items.
electroniccat told me every time he hears this issue they're using ProtocolSupport.

https://www.spigotmc.org/threads/heads-up-op-book-hack-in-1-12-spigot.251154/
As described here, although they don't provide actual solutions in my opinion or accurate description.

**Comment by Shevchik** [comment]
Search the already closed issues before reporting something.

**Comment by Brokkonaut** [comment]
I can confirm this bug, had it 2 times, so i added a guard to the empty item stacks to see what changes it: https://pastebin.com/raw/jX0ULbdm
in this stack trace you can path to the illegal modification

**Comment by Dimatert9** [comment]
Напишу на русском. У четырёх других проектов в снг тоже самое появляется.
У меня такое было в лобби для мг. А набор плагинов там минимальный.
Общие плагины получились: NCP, PS, PL,EssX,Pex, Vault.
У всех ядро 1.12.1, у когото папер, у когото обычный спигот.

**Comment by Shevchik** [comment]
Finally some useful info. Will look into that.

**Comment by Shevchik** [comment]
Should be fixed now i guess.

**Comment by Xayanix** [comment]
Thx.

I reported it first.
#616
