### ISSUE TITLE
Boss heathbar updates

### ISSUE THREAD

**Issue by dobrac** [ProtocolSupport/ProtocolSupport#64]
The boss healthbar updates only when player teleports (Maybe when he will do another action, but not normal).

Spigot version: 1.8.8
ProtocolSupport version: 4.20

Client version: 1.7

**Comment by Shevchik** [comment]
Boss bar updates just fine for me. Under which conditions does this issue happen?

**Comment by dobrac** [comment]
It can be maybe my code. I did it without BossBar, so If there is no bug, you can throw it away.
