### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#640]
Why does protocolsupport.protocol.utils.i18n.I18NData class takes so much RAM?
"The class "protocolsupport.protocol.utils.i18n.I18NData", loaded by "org.bukkit.plugin.java.PluginClassLoader @ 0xab5b2fc8", occupies 58 850 080 (33,23%) bytes. The memory is accumulated in one instance of "java.util.HashMap$Node[]" loaded by "<system class loader>"."

**Comment by MrPowerGamerBR** [comment]
Well, ProtocolSupport needs to store all the translation files *somewhere* 🤷‍♀️

**Comment by Shevchik** [comment]
58mb is not that much.
