### ISSUE TITLE
Player kicked on 1.12

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#643]
I got kicked with this reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoClassDefFoundError: protocolsupport/protocol/packet/middleimpl/clientbound/play/v_9r1_9r2_10_11_12r1_12r2/BossBar$1

**Comment by Shevchik** [comment]
Your jar is definitely corrupted, or you have 2 protocolsupport jars.
