### ISSUE TITLE
I need to know what i can do to make health potions splash without turning to water bottles

### ISSUE THREAD

**Issue by john2k22** [ProtocolSupport/ProtocolSupport#647]
Anyone who figured out how to fix splash potions tell me and either give me a fixed copy of the plugin or advice

Thank you for the help

**Comment by Shevchik** [comment]
They work properly in non inventory (and somewhat in creative, only specific set of ids work). If you mean that thrown potions doesn't display texture - it's a wontfix now

**Comment by john2k22** [comment]
how can i make instant healths work
