### ISSUE TITLE
Bug with BOOK AND QUILL

### ISSUE THREAD

**Issue by Xayanix** [ProtocolSupport/ProtocolSupport#653]
Sometimes ProtocolSupport is getting bugged, and every player has a lot of writable book is his inventory whose are unable to remove them.

Screenshot: http://i.imgur.com/bNC9H6J.png
Paper b1155
ProtocolSupport b117

This happens very rarerly, idk how to debug this.

**Comment by MrPowerGamerBR** [comment]
Duplicate of https://github.com/ProtocolSupport/ProtocolSupport/issues/632

This issue is already fixed in the latest ProtocolSupport version, please update your ProtocolSupport before creating new issues.
