### ISSUE TITLE
Potion particles on entities

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#659]
Hi, is it possible to show potion particles when someone has fire resistance etc.? I can't see it under every version under 1.9 I think.

**Comment by 7kasper** [comment]
Do you mean that versions of 1.9 and up do not show the particles?

**Comment by DanielAlves123** [comment]
> I can't see it under every version under 1.9 I think.

**Comment by DanielAlves123** [comment]
@Shevchik ?

**Comment by Shevchik** [comment]
Didn't check yet, but most likely it is related to entity metadata. Do you see particles on non-player entities?

**Comment by Shevchik** [comment]
Was unable to reproduce, at least i can see potion particles on player entity from 1.7.10 client.
Try narrowing down where it works and where it does not.

**Comment by DanielAlves123** [comment]
@Shevchik if you are on 1.8 for example and someone will eat enchanted golden apple you wont see any particles.

**Comment by DanielAlves123** [comment]
@Shevchik @7kasper When you eat enchanted golden apple you don't see any particles, then when you throw splash potion of regeneration, then speed for example it will get you kicked.

Logs with debug from having this situation 2 times:
https://pastebin.com/raw/FLxsirui

**Comment by DanielAlves123** [comment]
@Shevchik could you look at this? After you eat enchanted golden apple you see very very small particles. Maybe you should prioritize regeneration and fire resistance particles? Because when you throw for example splash potion of regeneration on the player you see normal particles.

**Comment by Shevchik** [comment]
The server does send a particle it wan't to show in the entity metadata. If you are not happy with that - change the server.

**Comment by DanielAlves123** [comment]
@Shevchik go to singleplayer and eat golden apple enchanted or not. You will see how exactly it should work, while with ProtocolSupport with normal golden apples you wont see very small and bad visible particles, with enchanted golden apples you will see something similar.
How it should work:
- with golden apples you should see blue absorption particles.
- with enchanted golden apples you should see regeneration particles, then fire resistance.

Please fix this its very frustrating in every type of server.

**Comment by DanielAlves123** [comment]
@Shevchik maybe you totally ignore regeneration 4 particles?

**Comment by Shevchik** [comment]
No PS:
![2018-09-05_17 45 10](https://user-images.githubusercontent.com/1553020/45101165-682f5a80-b11a-11e8-9937-d60a2525f668.png)
PS, client 1.13.1:
![2018-09-05_17 47 58](https://user-images.githubusercontent.com/1553020/45101309-b47a9a80-b11a-11e8-984e-67eabe47aa60.png)
PS, client 1.8.9:
![2018-09-05_17 49 00](https://user-images.githubusercontent.com/1553020/45101392-e12eb200-b11a-11e8-9400-39c831affa60.png)

I don't really see any differences between all of that.

**Comment by DanielAlves123** [comment]
@Shevchik With regeneration 4 (like old golden apples) you dont see any particles.

**Comment by Shevchik** [comment]
Same thing.
The particles near the client are based on the ambient potion color sent in the entity metadata.
And the way how this color is encoded and handled is the same between all versions. And this color is calculated serverside. So if the particles are not showing, that means that they are not sent by the server for whatever reason in your case.

**Comment by DanielAlves123** [comment]
@Shevchik But that's the point, you should see normal particles not hardly seen. It's not normal behaviour. You should see at least regeneration particles then fire resistance.

Also when you shoot an arrow with full power you wont see any particles behind the arrow on 1.7/1.8, I don't know about other versions.

**Comment by Shevchik** [comment]
And i see normal particles in all cases. So post a video how exactly to reproduce this.  (Latest spigot 1.13.1, latest protocolsupportx no other plugins installed.)

**Comment by DanielAlves123** [comment]
@Shevchik Try using plugins like this to get old enchanted golden apple effects:
https://www.spigotmc.org/resources/1-8-pvp-for-1-9-1-10-and-1-11.19291/

**Comment by Shevchik** [comment]
Those plugins apply ambient potion effects on entity on apple eat. (Because by default spigot potion effects are ambient). 

The issue template clearly states:
Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport

You failed to even do this. Get out.

**Comment by DanielAlves123** [comment]
@Shevchik here you go:
https://cl.ly/c0a3677ca803
https://cl.ly/c8d3c4bde8c1

**Comment by Shevchik** [comment]
1. Still has installed plugins besides protocolsupport
2. Custom resourcepack.

**Comment by DanielAlves123** [comment]
1. Without old enchanted golden apples you have some particles, but still not very accurate.
2. https://cl.ly/f54720e40828

**Comment by Shevchik** [comment]
They are what the server sends them.

**Comment by DanielAlves123** [comment]
@Shevchik but they are not what you should see. You should see at least normal regeneration particles, then fire resistance. Do not bother about mixing them or something. Could you do that?

**Comment by Shevchik** [comment]
It's not my job to fix anything in the server.

**Comment by DanielAlves123** [comment]
@Shevchik but it's not how it should work with ProtocolSupport, it's very annoyting when you cant see someone's particles :/

**Comment by Shevchik** [comment]
If you want everything to behave to exactly how it was in that legacy version, and not how it works in new one, then you should probably use that old server version, or implement the required changes yourself.

We only provide protocol support, we don't add legacy recipes, pvp, legacy server bugs behaviour, etc.

**Comment by DanielAlves123** [comment]
@Shevchik don't you think that particles are the things that should work normally with ProtocolSupport?

**Comment by Shevchik** [comment]
They are working normally (like they work on 1.13.1)
