### ISSUE TITLE
So sorry

### ISSUE THREAD

**Issue by NycuRO** [ProtocolSupport/ProtocolSupport#661]
Man i'm so sorry about ..
Please 👎 
I don't like get ban on discord :( 

@gdude2002

**Comment by gdude2002** [comment]
This tracker is an avenue for technical support. I know that you know this.

Alas, the fact that you decided to ignore that is exactly in line with the terms of your ban.

**Comment by NycuRO** [comment]
@gdude2002 But what i'm say for ban (latest time) ?

**Comment by gdude2002** [comment]
To be clear, you were issued at least three official warnings, two timeouts, and a softban (kick removing messages), you were 100% aware of the reasoning for each of them, and you decided to ignore both the requests of the staff and of the majority of the active users on the server.

In addition, you decided to directly copy a quote from one of our major contributors which was a draft for some information to address some very specific problems, and posted them somewhere that was completely inappropriate - thus ensuring that those concerns would not be addressed on that particular platform.

Unfortunately, at this point, there is no contesting the reason. Your reputation precedes you, and you have done a stellar job of proving our presumption - that you would be able to adapt to the community with enough work - wrong. We feel that you have been given plenty of chances to improve yourself - this is the result.

---

Here's a short-hand list:

* Spamming in on-topic channels
* Mass-mentioning contributors
* Constantly nagging contributors about things that they're working on or have already planned on doing
* Directly disobeying the requests of staff
* Advertising
* Bad-mouthing and swearing about and at staff and other users, as well as insulting them
* Telling staff members to "kys" on occasion when you were reprimanded

The list goes on, but this should be enough on its own.

As a result, you have broken 5 of our 7 rules - which I feel must be some kind of record. I do not think this warrants an unban, and especially not on the same day you were banned.

You may keep yourself up-to-date by watching this repo and keeping an eye on Spigot.
