### ISSUE TITLE
Resource posting on mc-market.org

### ISSUE THREAD

**Issue by gdude2002** [ProtocolSupport/ProtocolSupport#665]
Further to our private discussions, I'd like to pose that we post an official resource for ProtocolSupport on [Minecraft Market](http://www.mc-market.org/threads/233450/#post-2294768).

* They have been very co-operative and helpful with my concerns about third-party distribution on their network
* It would be a secondary location for users to obtain our "stable" builds for those that dislike Spigot's forums
* It's a good avenue to make users of that site aware of the official channels to download our old builds in a safe way, providing a better alternative than third-party uploads or "leaks"

We've already agreed to this on Discord, but I'd like to keep this issue as a public record of this intention, and to show that @Shevchik supports this idea.

When approved, the resource URL is http://www.mc-market.org/resources/4607/

**Comment by Shevchik** [comment]
Yea. Will keep this issue open until link to resource is posted, then it can be added to readme.

**Comment by gdude2002** [comment]
I have submitted the resource. When it's approved, it should be available at [this link](http://www.mc-market.org/resources/4607/). Might take a few days.

**Comment by gdude2002** [comment]
The resource is now live!
