### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by pchard** [ProtocolSupport/ProtocolSupport#667]
> [13:16:59 INFO]: [ProtocolSupport] Enabling ProtocolSupport v4.28-dev
> [13:16:59 ERROR]: [ProtocolSupport] Plugin ProtocolSupport v4.28-dev has failed to register events for class protocolsupport.listeners.FeatureEmulation because org/bukkit/event/entity/EntityPickupItemEvent does not exist.

**Comment by MrPowerGamerBR** [comment]
Update your server

**Comment by pchard** [comment]
Here's the thing @Shevchik 

I'm trying multiple things.

I have a bungeecord server, a hub with Spigot 1.9 - (tried all versions above too!)
And connected to the bungeecord is several modpack servers.

All from 1.7.10 to 1.10.2.

1.10.2 versions works fine with ViaVersion, but when it comes to ProtocolSupport (which I need to get the players with 1.7.10 to join), the server crashes on start up... Will you be willing to assist?

**Comment by MrPowerGamerBR** [comment]
@pchard only the latest ProtocolSupport version (for 1.12.1) is supported.

**Comment by pchard** [comment]
Okay, so what you're saying here is, update my spigot to 1.12.1 and all versions below can join?

**Comment by MrPowerGamerBR** [comment]
Yes

**Comment by pchard** [comment]
A player with 1.7.10 just tried this, and got in, but got kicked right away with this error:

https://gyazo.com/0f8b5ede53586c2a8a2fb12c3169848d
