### ISSUE TITLE
MCPE can't connect to world

### ISSUE THREAD

**Issue by egkoppel** [ProtocolSupport/ProtocolSupport#673]
I have installed the pe version of protocol support and the latest version of spigot and put the server in offline mode. However when I try to connect from MCPE (on both port 19132 and 25565) nothing appears in the server console (with debug mode enabled) and MCPE says it can't connect to the world

**Comment by MrPowerGamerBR** [comment]
Because it is in *development*

If you know how to code you can figure out what is the PE server port. (hint: it isn't the default PE server port)

**Comment by renorris** [comment]
25565
