### ISSUE TITLE
Can author make 1.7.10 client see title and actionbar

### ISSUE THREAD

**Issue by engineer1109** [ProtocolSupport/ProtocolSupport#678]
There is a client mod 1.7.10 supporting title and actionbar.
A new 1.7.10 server https://git.xjboss.net/UraniumDev/Uranium  support title and actionbar.
However the 1710 client mod can't see the title on spigot 1.8-1.12
can you open the title and actionbar support to 1.7.10?

**Comment by Shevchik** [comment]
No.
