### ISSUE TITLE
1.7.10 and under doesnt work

### ISSUE THREAD

**Issue by SoulWolfX** [ProtocolSupport/ProtocolSupport#680]
For some reason, every version except 1.7.10 and under can join but i want 1.7.10 players 2 be able 2 join is there a fix to this?

**Comment by Shevchik** [comment]
Error log?

**Comment by SoulWolfX** [comment]
It doesnt give a server error but this is what it gives to the client

https://pastebin.com/p8B5FMPy

**Comment by gdude2002** [comment]
Looks like an incompatible plugin or Scoreboard setup.

For example, a plugin (or the Paper setting) that turns off player collisions. You'd need to use one that is aware of ProtocolSupport.

**Comment by SoulWolfX** [comment]
any recomendations i currently use title manager.

**Comment by gdude2002** [comment]
Test without, see if it works.

**Comment by SoulWolfX** [comment]
it work tysm
