### ISSUE TITLE
Add prevent-proxy option

### ISSUE THREAD

**Issue by games647** [ProtocolSupport/ProtocolSupport#681]
A while ago Mojang[ introduced another (optional) IP parameter](http://wiki.vg/Protocol_Encryption#Server) to their session server API. It's already in the standard Minecraft server implementation (can be enabled using the server properties) and in[ BungeeCord it's always enabled](https://github.com/SpigotMC/BungeeCord/blob/ef326dba192fe532dc6509e0975266715da5ccea/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L409). This option prevents users from using authentication proxies like MCLeaks. 

So it might be great for some administrators if this could be added. Maybe with a configuration option.

Current Session-server call:
https://github.com/ProtocolSupport/ProtocolSupport/blob/74ca013e2c373b60ade1bccba7713f6f59b8ce0f/src/protocolsupport/protocol/utils/authlib/MinecraftSessionService.java#L22-L23

**Comment by gdude2002** [comment]
Could you elaborate more on what this means and what it has to do with ProtocolSupport?

**Comment by games647** [comment]
>Could you elaborate more on what this means

Mojang compares if the same IP connecting to the server is also used for authenticating against the Mojang Session-Servers. MCLeaks, a service that gives out free Minecraft accounts for temporarily use, uses an authentication proxy that they don't have to give out the credentials of those accounts.

>what it has to do with ProtocolSupport?

AFAIK ProtocolSupport overrides the Minecraft server implementation to intercept and modify the packets. It re-implements the how the server handles authentication and calls the Session server on it's own.

https://github.com/ProtocolSupport/ProtocolSupport/blob/74ca013e2c373b60ade1bccba7713f6f59b8ce0f/src/protocolsupport/protocol/packet/handler/PlayerLookupUUID.java#L36-L51

https://github.com/ProtocolSupport/ProtocolSupport/blob/74ca013e2c373b60ade1bccba7713f6f59b8ce0f/src/protocolsupport/protocol/utils/authlib/MinecraftSessionService.java#L22-L42

**Comment by gdude2002** [comment]
Aha, okay, so you would like us to implement that same check. @Shevchik?

**Comment by Shevchik** [comment]
Will implement this soon.

**Comment by Shevchik** [comment]
Added
