### ISSUE TITLE
Losing position on teleport/lag back

### ISSUE THREAD

**Issue by MClausz** [ProtocolSupport/ProtocolSupport#682]
I saw a "fix losing position" in commits but apparently this issue still happen in the most recent build of ProtocolSupport.
Basically player are able to move client side, but they don't actually move in the server. This usually happen to players with a high ping after a lag back teleport when a network lag strike occured.
When I try removing ProtocolSupport for a day, this issue doesn't happen.
I'm using latest build of ProtocolSupport, PaperSpigot.

**Comment by Shevchik** [comment]
Try reproducing this running ProtocolSupport only. We don't skip any movement packets anymore, so it may be something else.

**Comment by MClausz** [comment]
For some reason I can't reproduce this running ProtocolSupport only, as it requires many players in the server.

**Comment by Shevchik** [comment]
Made some improvement to position and teleport handling, try now. If it still persists try removing plugins that work on network level.
