### ISSUE TITLE
Permanent disconnects for 1.8 players on join since build 155

### ISSUE THREAD

**Issue by i9hdkill** [ProtocolSupport/ProtocolSupport#685]
If a 1.8 players dies (?) he gets a disconnect and can't rejoin. (1.12.1 seems to be fine)
Was fine on Build 154, but Build 155 causes this error/disconnect

Spigot version:
git-Spigot-da42974-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

Protocollib version:
ProtocolLib_Build378

Log when players tries to join:
https://pastebin.com/SjB6cUBA

I am aware that there is a Protocollib line in this stacktrace, but I am confident that this isn't related, as this worked before updating Protocolsupport.

Eventually this broke it?
https://github.com/ProtocolSupport/ProtocolSupport/commit/bf3a8b97af6515c5e31d97166ba74886dc712053

**Comment by Shevchik** [comment]
This log is cut off, there is an npe at the end, but it's stacktrace doesn't exist. Try getting log from the fresh server start.

**Comment by ghacproductions** [comment]
Thats the error with the last version (build 156):

https://pastebin.com/eMBJK1qv

**Comment by Shevchik** [comment]
Still no stacktrace in the end. Configure your jvm to not suppress and not cut the exception logs.
Btw, the player has a null raw address, that definitely not normal.

**Comment by DanielAlves123** [comment]
I think i have the same thing: 
https://pastebin.com/raw/t4bHLmrJ

**Comment by Shevchik** [comment]
Most likely, but this time exception is present, will look into it.

**Comment by Shevchik** [comment]
Should be fixed now i think

**Comment by akatsuki** [comment]
If you don't feel annoy, please check with dispenser.
In my case, Dispenser makes disconnect with under 1.9 versions client.
