### ISSUE TITLE
Getting kicked and can't log in after creating named NPC

### ISSUE THREAD

**Issue by Capri205** [ProtocolSupport/ProtocolSupport#687]
Using the latest vesion and also tried with v4.28-dev. Running latest spigot 1.12.1 build.

I am using a shop plugin that let's you create NPC shops (for example a parrot named Polly). These seem to work fine in 1.12.1 but after adding ProtocolSupport I get kicked from the server when creating one and can't log back in, or can't log in if there are named NPC shops in the world.

There aren't any exceptions in the log, just "Error: Player not found".

I I remove ProtocolSupport I can log in fine whilst there are named NPC's in the world, likewise if I change the config of the shop to chest instead of NPC I can log in, so entirely something to do with NPC.

This is not citizens. The plugin uses NMS calls.

I do maintain the code to the shop plugin (didn't originally write) so I can tell you more about how these are spawned if you need.

I generated the attached with /ps debug when creating a new mob (parrot called Polly) if it helps. There's no exception when trying to join, just "Error: Player not found".

Hope this helps.

[PS-debug-error-named-NPC-09142017-1939.txt](https://github.com/ProtocolSupport/ProtocolSupport/files/1304907/PS-debug-error-named-NPC-09142017-1939.txt)

**Comment by Shevchik** [comment]
Caused by: java.lang.IllegalArgumentException: Unknown mob network type id -1

You are sending a mob spawn with invalid entity type id. That's an issue with your npc or other plugin, not with prototocolsupport.
