### ISSUE TITLE
Can't connect items in the Anvil - client crash

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#689]
How I reproduce it:
Try to connect these Diamond swords in the anvil:
- sharpness 5, fire aspect 2, durability 836
- looting 3, unbreaking 3, max durability
Version: 1.8.9.
Logs in the Minecraft client: https://pastebin.com/raw/mfK1UfmV
I don't think something more shows on the server or client, you can check it by yourself too I think.

**Comment by Shevchik** [comment]
Enchantment skipping table needs update

**Comment by Shevchik** [comment]
Try now, should be fixed now.
If it is still not, packet the schematic with those swords and put it here.
