### ISSUE TITLE
KeepAlive kick

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#694]
I get kicked after joining and get this error on debug: https://pastebin.com/raw/xy8kqeUx

**Comment by gdude2002** [comment]
You're not using the latest dev build, as far as I can tell.

But that's not stable at the moment either. Best stick with a 1.12.1 server for now.

**Comment by Shevchik** [comment]
The keep alive packet wasn't encoded properly. Test without bungeecord.

**Comment by DanielAlves123** [comment]
It works on 159 build. Maybe I don't have latest Spigot version.

**Comment by DanielAlves123** [comment]
It works with the build that you linked in the 1.12.2 update.
