### ISSUE TITLE
1.12.2 bug

### ISSUE THREAD

**Issue by mat41997** [ProtocolSupport/ProtocolSupport#697]
i not can join to my server in 1.12.1

timings
https://timings.aikar.co/?id=a1ef567218384476a464b27653c59658

ss
![2017-09-20 21_25_53-minecraft 1 12 1](https://user-images.githubusercontent.com/5884000/30663290-78c7b344-9e4a-11e7-8223-454706ebfd94.png)
![2017-09-20 21_26_21-new issue protocolsupport_protocolsupport](https://user-images.githubusercontent.com/5884000/30663291-78ca37e0-9e4a-11e7-8277-df05f647389c.png)

**Comment by Shevchik** [comment]
Did you update protocolsupport to latest dev build?

**Comment by mat41997** [comment]
see
![2017-09-20 21_40_40-aikar s timings viewer](https://user-images.githubusercontent.com/5884000/30663889-62fee5b2-9e4c-11e7-8297-bf4e6734602c.png)

**Comment by Shevchik** [comment]
That version means nothing. Dev builds are numbered by build number which is visible in /ps buildinfo

**Comment by mat41997** [comment]
"That version means nothing. "
you can fix this information in next update.

**Comment by Shevchik** [comment]
Nope, i won't, this number is incremented on every release only.

**Comment by mat41997** [comment]
ok.
![2017-09-20_21 46 36](https://user-images.githubusercontent.com/5884000/30664216-3a074a68-9e4d-11e7-98cb-2b89c49f7d36.png)

**Comment by Shevchik** [comment]
162 is not the latest dev build. Read the issue template before posting one next time.

**Comment by mat41997** [comment]
ohh. sorry
