### ISSUE TITLE
Prefixes in Tab issues

### ISSUE THREAD

**Issue by ChavitaHD** [ProtocolSupport/ProtocolSupport#698]
Hey,

Currently having issues with prefixes in tab not showing up on 1.8 and below clients, 1.9 and above can see them just fine.

1.9.x+
https://i.gyazo.com/3efc08a318b9c5651e138d4dc5a315e9.png

1.8.x-
https://image.prntscr.com/image/yiBVMMioTh6OtOZhBwCMRQ.png

**Comment by MasterDash5** [comment]
Not gonna lie, this looks like a problem with the plugin

**Comment by Shevchik** [comment]
Most likely those prefixes were appended using teams. And for some versions the score should use player entity name, and for some of them it should use the tablist display name. Unfortunately i can't really fix that, plugin will have to properly handle it tiself (send scores for both player name and tablist display name.)
