### ISSUE TITLE
Exception by packet KeepAlive

### ISSUE THREAD

**Issue by MinelandTeam** [ProtocolSupport/ProtocolSupport#699]
Exception. 
https://pastebin.com/FEhYFY0z
The exception is thrown when reconnect on servers. In this case, the player will kick with the inscription [Proxy] Lost connection or Timed out.
The problem has appeared, only on the last build, with the transition to 1.12.2.
BungeeCord also updated.
Also, an error can appear, with fast reconnects on the servers.
For example, miniGame -> auth -> miniGame.

**Comment by MClausz** [comment]
same issue

**Comment by Shevchik** [comment]
Not a protocolsupport problem.
