### ISSUE TITLE
Skull Heads Skin only loads when a Skull is placed, and the Skull Head skin doesn't show if the user logouts and connects again [1.5.2/1.6.X/1.7.X]

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ProtocolSupport/ProtocolSupport#70]
Spawning a head using "/skull MrPowerGamerBR"

If you place a Skull Head with Skin on the world, the skin appears normally, however, if you logout and connect again, the Skull will have a Steve Skin.

This doesn't happen in 1.8.X.

Maybe a Skull Block transformer is needed for versions below 1.8?

Here's a video demonstrating the issue: https://dl.dropboxusercontent.com/u/93092749/ShareX/2015/10/2015-10-24_18-09-15.mp4 (Sorry for the graphical glitch on the video)

**EDIT:** Here's the video on YouTube, if Dropbox is causing issues to play the video: https://youtu.be/CGAzF_WGtcc

**Comment by MrPowerGamerBR** [comment]
**Update:** This issue doesn't affect Skull Heads on Entities.

**Comment by MrPowerGamerBR** [comment]
**UPDATE 2:** Doesn't happen in the latest version in Spigot Resources (v4.20)

I will test every dev build until I find what commit breaks the Skin on a Player Skull.

**Comment by MrPowerGamerBR** [comment]
**UPDATE 3:** @Shevchik, this is the latest build that Skulls with Skin works: http://build.true-games.org/job/ProtocolSupport/205/ (Build 205)

After this commit: 4a2969725c6fd8b3159436c1609bac5541251294 (Build 206), every Skull with a Skin that is already placed in the world before logging in with a Minecraft 1.5.2/1.6.X/1.7.X client will show up as a generic skull (without Skin/Steve Skin)

**Comment by Shevchik** [comment]
That's because skull data is actually sent by tile nbt packet. Before this commit item skulls transformer used original itemstack so old style nbt was set to skull block. With the new transformer all transformation is applied to the copy of itemstack. So i now need to add transformer for skull tile entity.

**Comment by MrPowerGamerBR** [comment]
Any progress on fixing this bug? :neutral_face: It is not a game-breaking bug, but it would be nice to this to be fixed (after all, it is one of the only bugs that ProtocolSupport is affecting me)

**Comment by Shevchik** [comment]
I'm in process of refactoring some things to deal with magic constants and simplify future 1.9 update, so i didn't event started working on this issue

**Comment by MrPowerGamerBR** [comment]
:+1: 

I tried doing this fix myself (by copying the BlockSkull and TileEntitySkull and adding it to th ServerInjector.java), however, I broke more things than I fixed, so it would be better to ask if a fix was incoming than try to break more things trying to fix this.

Also, yay for 1.9 support :smile:

**Comment by nathampa0909** [comment]
@Shevchik is there any progress on fixing this bug? I know this isn't a major bug, but it would be very nice to have proper skull heads support on pre-1.8 clients.

Thanks for attention.

**Comment by Shevchik** [comment]
Nope, i'm currently busy with mcpe branch

**Comment by nathampa0909** [comment]
Thanks for replying! I was checking the mcpe branch and it seems very cool (and it is actually working fine! With the exception of some bugs)

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by MrPowerGamerBR** [comment]
I forgot to say that it is working (I didn't test before because my Server is running 1.7.10 Protocol Hack due to of some issues in 1.8.8, however @nathampa0909 tested the latest version and said that heads are working :smile: )
