### ISSUE TITLE
Hindrance In Chest Shift-Double-Click

### ISSUE THREAD

**Issue by LucidEcstasy** [ProtocolSupport/ProtocolSupport#700]
Running the latest Spigot(1.12.2.) & latest ProtocolSupport dev build,

The Vanilla function,

Assume a chest is full of an item, e.g. iron ingots. Holding shift while double clicking on just one of the iron ingots would collect all of the ingots in the chest and place them into the player's inventory.

This is not possible with ProtocolSupport, it seems as if it's ignoring the double click function.

I've checked around and haven't found any mention of this so I am hoping this is able to get resolved.

Thanks!

**Comment by krusic22** [comment]
Are you using any other plugins? Like ViaVersion (Via has the [same](https://github.com/MylesIsCool/ViaVersion/issues/739) bug).

**Comment by LucidEcstasy** [comment]
Never mind, plugin issue, apologies
