### ISSUE TITLE
Crash on startup. Only with protocolsupport installed.

### ISSUE THREAD

**Issue by PaziHD** [ProtocolSupport/ProtocolSupport#702]
It happend originally with #163 and I updated to #164 today and it still happens.
It just crashes without any messages, no time to use /ps debug. 
I made a fresh server with some basic plugins, doesn't happen.

Is there a list of incompatible plugins I can look at?
![image](https://user-images.githubusercontent.com/7887281/30780168-61e15064-a137-11e7-9acd-1d46331a32db.png)
![image](https://user-images.githubusercontent.com/7887281/30780171-7003ea44-a137-11e7-86a5-409b179d5f3d.png)

**Comment by Shevchik** [comment]
Because you need to read the full server log.
