### ISSUE TITLE
Action bars in 1.8 - 1.10 don't show

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#707]
I mean not really much to say. 1.11 made a new packet and removed the old method.

**Comment by Shevchik** [comment]
They didn't remove the old method tho.

**Comment by MasterDash5** [comment]
they didn't? im a developer myself and doing the old method didn't work. Maybe you send the packet differently.

**Comment by Shevchik** [comment]
Fixed
