### ISSUE TITLE
Display blocks / entities

### ISSUE THREAD

**Issue by FrukTik** [ProtocolSupport/ProtocolSupport#708]
Hello!
Why concrete looks like bricks, it would be better if it was clay.
Is it possible to make a parrot chicken?
http://img12.lostpic.net/2017/10/02/43c1038bdd7404913eeb6be5fc228a3e.jpg

**Comment by gdude2002** [comment]
From [the site](http://protocolsupport.true-games.org/):

> Where blocks and items are present on the server but not on the client, they are replaced by something else. Most blocks are replaced by something of equal hardness, to avoid issues related to the timing of breaking blocks. If you'd like to change how things are remapped, see the ProtocolSupportStuff addon.

---

No, it's not possible to make it a chicken, it must be an animal that may be owned - so a wolf or ocelot.
