### ISSUE TITLE
Can't compile the PSPE 

### ISSUE THREAD

**Issue by AlexCreeper25** [ProtocolSupport/ProtocolSupport#709]
I absolutely want the PSPE plugin for my server, btw i can't cuz idk why the gradle console crashes when i open it. can any1 give me a link to a prebuilt jar or tell me how i can fix this?
(I'm sure i have JDK 1.8.0 installed)

**Comment by MrPowerGamerBR** [comment]
No, you don't want to use it.

If you don't know how to compile it, then you shouldn't use it. There is an reason of why there isn't a pre-compiled JAR yet.

**Comment by AlexCreeper25** [comment]
it's not that i don't know how to compile it, it's just that my gradle console crashes when i open it

**Comment by AlexCreeper25** [comment]
I tried re-installing the jdk, i tried re-downloading the repo, i also tried to import it in eclipse and export it as jar file, but nothing. Eclipse seems to not want to import it and compile it into jar

**Comment by 7kasper** [comment]
You could just use terminal or CMD and run the compilation command. I cannot imagine your CMD crashing.. But if that is the case you should make issue with gradle or windows 😉

**Comment by AlexCreeper25** [comment]
ok
