### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Sitmobedaf** [ProtocolSupport/ProtocolSupport#711]
У меня тут недавно новая ошибка появилась. Причина явно не в MySQL-сервере и не в отдельных плагинах, которые инициализируют эту ошибку. Причина или в MySQL-драйвере (которое в ядре) или в каком-нибудь ProtocolSupport. Или в любом другом плагине, который вмешивается в такие процессы.
Ошибка:
https://pastebin.com/MYHSSr5j
Происходит когда тот или иной плагин пытается подключиться к MySQL. В StackTrace PS упоминается.

**Comment by Shevchik** [comment]
No a protocolsupport problem
