### ISSUE TITLE
Map and Item Frame PE issuse

### ISSUE THREAD

**Issue by AlexCreeper25** [ProtocolSupport/ProtocolSupport#713]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

If you fail to check the above, your issue will be closed.

**Comment by MrPowerGamerBR** [comment]
ProtocolSupportPE is experimental, we aren't accepting user reported issues about it.

(And we already know about 99% of the issues it has)

**Comment by AlexCreeper25** [comment]
Oh, ok
