### ISSUE TITLE
Texture on 1.8-1.8.7

### ISSUE THREAD

**Issue by SeDark** [ProtocolSupport/ProtocolSupport#714]
When I connect with a client version between 1.8 and 1.8.7, the textures are not displayed correctly, with 1.8.8 already looking normal.

I have checked it only by having protocolsupport
https://i.gyazo.com/9d873523eb5ee2977a8c569dc24e3556.jpg

Spigot 1.12.2
https://gyazo.com/d2fa96f915107b8e6e3d9ecbba9c6ab5

ProtocolSupport -173
https://i.gyazo.com/b97e504d0b8becc40da8bbacdd2d8a04.png

[13:41:09] [Netty Server IO #1/INFO]: [ProtocolSupport] /127.0.0.1:5104 connected with protocol version MINECRAFT_1_8
[13:41:11] [Netty Server IO #2/INFO]: [ProtocolSupport] /127.0.0.1:5108 connected with protocol version MINECRAFT_1_8

**Comment by MrPowerGamerBR** [comment]
Are you using a resource pack?

That looks like a resource pack issue.

**Comment by SeDark** [comment]
Yes, sorry, I just realized, is that it does not change almost anything, I do not understand why in 1.8.8 if that works.

Anyway I close this, I feel the confusion again
