### ISSUE TITLE
Ground Entities Issue

### ISSUE THREAD

**Issue by ChavitaHD** [ProtocolSupport/ProtocolSupport#715]
It seems that using the newest PaperSpigot, ProtocolSupport, WaterFall, & ProtocolLib versions and it seems that on 1.11+ anytime a player drops a block on the ground with q, or really any dropped block or item, it is invisible. If the player is on 1.10.2 or lower, it works fine, and the player can see the block or item fine.

The plugin combination does not matter, as it happens on my Hub, Creative, and SkyBlock server.

**Comment by Shevchik** [comment]
No really able to reproduce (tested without WaterFall). Test without waterfall first.

**Comment by Shevchik** [comment]
Closed due to inactivity
