### ISSUE TITLE
1.8 CustomNameVisible tag

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#720]
for some reason using {CustomNameVisible:1} on an entity will not show up in 1.8. This doesn't happen on any other version, not even 1.7

1.7: http://prntscr.com/gz89jd
1.8: http://prntscr.com/gz89qs

**Comment by Shevchik** [comment]
It just how it works on those versions.

**Comment by MasterDash5** [comment]
so you're not going to do anything about it?

**Comment by Shevchik** [comment]
I can't without tons of hacks. That's just how client works on those versions.
