### ISSUE TITLE
Cannot get Player Version

### ISSUE THREAD

**Issue by DrProfesor** [ProtocolSupport/ProtocolSupport#721]
I am using the latest version of protocolsupport, and am getting UNKNOWN back for player version with the API. With debug enabled I see the PS is getting the correct version.

Side question: Also, is there any way to set it so that PS gets its packets after ProtocolLib does?

**Comment by Shevchik** [comment]
1) You have something that changes raw remote players addresses, or you are using epoll
2) Not quite sure what you mean

**Comment by DrProfesor** [comment]
Does LilyPad change raw remote addresses? And we are not using epoll. 
And disregard the second part, I looked through some PS source, and it does not seem possible

**Comment by MylesIsCool** [comment]
Pretty sure it still does, last time I used PS with it, it did

https://github.com/LilyPad/Bukkit-Connect/pull/33
