### ISSUE TITLE
1.5.2 users crash everytime they try to join

### ISSUE THREAD

**Issue by xBoneso** [ProtocolSupport/ProtocolSupport#722]
I use Spigot 1.12, ProtocolSupport latest version and when a 1.5.2 user joins the server they crash and the console says this: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown dimension network id 13

**Comment by xBoneso** [comment]
Here is the crash log: https://pastebin.com/zsn3xZci

**Comment by MrPowerGamerBR** [comment]
Are you using 1.12.2? Only the latest ProtocolSupport version (for 1.12.2) is supported.

**Comment by xBoneso** [comment]
Yes

**Comment by xBoneso** [comment]
And right now if i try to join as 1.8 i get this error:
[02:35:24 INFO]: xBones lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(8) exceeds writerIndex(2): PooledUnsafeDirectByteBuf(ridx: 1, widx: 2, cap: 256)

**Comment by xBoneso** [comment]
1.5.2 users get 2 errors:
Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
and  Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown dimension network id 13

**Comment by Shevchik** [comment]
1) You have a missmathc between ps and server versions. Make sure that you use spigot 1.12.2 and latest dev builds
2) One of the plugins sent invalid data

**Comment by xBoneso** [comment]
I use both latest versions, it might be because of some other plugin.

**Comment by Shevchik** [comment]
As for the client crash - it's something related to scoreboards. Most likely something sends the data in non supported way.
