### ISSUE TITLE
"Disconected" error.

### ISSUE THREAD

**Issue by KrifixYT** [ProtocolSupport/ProtocolSupport#724]
Hi! I have problem when i join server! I join for 0.4 second and kicked for "Disconected".
Error: https://pastebin.com/ZLb0q0UR
Server Log: https://pastebin.com/t10YStH4
Plugin version: Newest
Paper Info: https://timings.aikar.co/?id=8258603c9b2a45caa27a35532e6cc4a1

**Comment by Shevchik** [comment]
You are not using latest PS dev build
