### ISSUE TITLE
"Disconected" error #2

### ISSUE THREAD

**Issue by KrifixYT** [ProtocolSupport/ProtocolSupport#725]
I have error with "Disconected". 
NOW I INSTALED VERSION 4.27

ERROR: https://pastebin.com/uXqGZCcB
SERVER INFO: https://timings.aikar.co/?id=578de9b519114498b88c74609b02543e

Sorry, but every time when i install it, IT NO WORK!

**Comment by KrifixYT** [comment]
I installed the newest version of ProtocolLib, this same.

**Comment by KrifixYT** [comment]
Now - ProtocolLib 4.3.0
Error: altmanagerelo lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.

**Comment by Shevchik** [comment]
4.27 is not the latest dev build.
