### ISSUE TITLE
Hp bar not shown on 1.8

### ISSUE THREAD

**Issue by TheKnight787** [ProtocolSupport/ProtocolSupport#727]
The problem is that when you use ProtocolSupport and Heroes plugins at the same time, then the health bar is not shown to the players who are using 1.8.

![awumakd](https://user-images.githubusercontent.com/5339339/31950051-b213e95e-b8d2-11e7-95f3-3380cc579e35.png)

I am using the latest Spigot version, latest dev build of ProtocolSupport and the latest Heroes version.
I think this is caused by players having more than 20 hp (or 10 hearts).
Kainzo (creator of Heroes) said that "This is a ProtocolSupport issue with how it handles the health values, im quite sure." (https://www.spigotmc.org/threads/heroes-minecraft-rpg-plugin-paid.155426/page-109)

**Comment by Shevchik** [comment]
We don't provide support for non opensource plugins.
So you will have to debug that on your own.

**Comment by TheKnight787** [comment]
The debug doesn't throw any errors.

**Comment by 7kasper** [comment]
I have seen the same problem but then on mcpe...
Though the cause might be entirely unrelated, this requires further investigation.

**Comment by lululombard** [comment]
This issue has nothing to do with ProtocolSupport, or at least from what I see.

Latest build of ProtocolSupport, latest build of PaperSpigot, and CMI to set player's max HP.

![Screenshot](https://up.kingdomhills.fr/25270511009267805)

**Comment by Shevchik** [comment]
Closed due to inactivity
