### ISSUE TITLE
Crash Server 

### ISSUE THREAD

**Issue by FrukTik** [ProtocolSupport/ProtocolSupport#728]
Hello!
Is it possible to fix it?
https://pastebin.com/Deb2nbur

**Comment by MrPowerGamerBR** [comment]
```
com.Acrobot.Breeze.Utils.InventoryUtil.getItemsStacked(InventoryUtil.java:320)
```

Seems to be a ChestShop issue

**Comment by FrukTik** [comment]
Here is what the developer writes:
https://github.com/ChestShop-authors/ChestShop-3/issues/78

**Comment by Shevchik** [comment]
ProtocolSupport threads are in blocked state because server holds a lock on plugin manager instance due to it's currently processing an event in main thread.

**Comment by FrukTik** [comment]
I crashed the server for 2 hours. I do not understand your answer. Tell me how to solve the problem?

**Comment by MrPowerGamerBR** [comment]
@FrukTik Shevchik said it isn't an issue with ProtocolSupport, it is an issue with another plugin. (maybe PermissionsEx?)

**Comment by MrPowerGamerBR** [comment]
Seems to be fixed in the latest ChestShop build: https://github.com/ChestShop-authors/ChestShop-3/commit/61c08a3b185aedb702c6fedcf0ff911a34980abf
