### ISSUE TITLE
Mob Spawners in 1.10.2 and lower

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#734]
1.11 and higher: http://prntscr.com/h3deyw

1.10.2 and lower: http://prntscr.com/h3df3q

In case you're wondering what i'm doing, i'm making a texture pack for my server that turns those mob spawners into concrete.

Edit: heres the command i used to make them: 

give @p minecraft:command_block 1 0 {"BlockEntityTag":{"auto":1b,"Command":"setblock ~ ~ ~ minecraft:mob_spawner 0 replace {\"SpawnData\":{\"id\":\"minecraft:armor_stand\",\"ArmorItems\":[{},{},{},{}],\"HandItems\":[{\"id\":\"minecraft:leather_boots\",\"Count\":1,\"Damage\":15,\"tag\":{\"Unbreakable\":1,\"display\":{\"color\":16777215}}},{}],\"Pose\":{\"RightArm\":[30f,0f,0f],\"LeftArm\":[30f,0f,0f]}},\"RequiredPlayerRange\":0,\"MaxNearbyEntities\":0}"}}

**Comment by MasterDash5** [comment]
I played around with this more but armor and held items don't show in 1.10.2 and lower either

**Comment by Shevchik** [comment]
Fixed
