### ISSUE TITLE
client kick 1.7.10 + shulker box 1.12.2

### ISSUE THREAD

**Issue by PhanaticD** [ProtocolSupport/ProtocolSupport#736]
When right clicking a shulker box from paperspigot 1.12.2 with a vanilla 1.7.10 client I get kicked with this message: https://gyazo.com/68afdc42a1dafe95c515a647f64d6e1b

there is no error in travertine logs or in the paperspigot logs

**Comment by Shevchik** [comment]
Should be fixed now
