### ISSUE TITLE
ProtocolSupport LilyPads bug

### ISSUE THREAD

**Issue by ridalarry** [ProtocolSupport/ProtocolSupport#737]
Sometimes on teleport or step on lilypads it would make you get stuck. Also it happens if you don't have a permission to break the lilypad and you are standing on it.

Best way to make sure it happens use /pt from essentials and set it to anything then stand on the lilypad and try to break it with your powertool. Make sure you are in survival mode and fly off

**Comment by Shevchik** [comment]
Check your anticheat.

**Comment by MasterDash5** [comment]
uh... that sounds like an essentials problem, either that or you're using nocheatplus

**Comment by ridalarry** [comment]
@Shevchik I tried with no plugins on the server except protocolsupport and the problem still occur latest spigot latest ps dev build and no other plugins

**Comment by MasterDash5** [comment]
did you try it *without* protocolsupport?

**Comment by Rida94** [comment]
@MasterDash5 yes I did and it doesn't happen.

**Comment by Ev3ryShir** [comment]
Check your anticheat. ProtocolSupport doesn't send no Packet of PlayerPosition... the plugin just transform the Server Packets by client versions; Your Anticheat is 1.12 for this reason it doesn't happen on 1.12, while anyone is 1.8 or less it happen because the Anticheat thinks is a strange movement for  a 1.12 Player to do...

**Comment by Ev3ryShir** [comment]
I tried it on my Own Server, tested with 1.5 and 1.8 (with Hax and Without) and nothing happen, it works exactly as it should...

**Comment by Disorbs** [comment]
still have this issue as well on a local server with the latest PS dev and i don't even have any anti cheats enabled yet and i set flight: true on server.properties in case it might of been that.

**Comment by Shevchik** [comment]
The latest ps build doesn't inject the lilypad bounds. So yeah, you will have a problems with older clients until i update the lilypad bounds injector to 1.13.1

**Comment by 7kasper** [comment]
Should be fixed now.
