### ISSUE TITLE
Implement Paper's PlayerHandshakeEvent

### ISSUE THREAD

**Issue by lucko** [ProtocolSupport/ProtocolSupport#739]
Paper implements a `PlayerHandshakeEvent` in these patches:

https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0034-Add-handshake-event-to-allow-plugins-to-handle-clien.patch

https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0112-Add-handshake-event-to-allow-plugins-to-handle-clien.patch

It allows plugins to handle handshaking logic themselves, without the need to perform server-side modifications. This allows anyone running a custom proxy solution (BungeeCord, LilyPad, etc - forks included) to handle authentication themselves, without performing modifications to the server.

When running ProtocolSupport, this event is never called, as PS uses it's own implementation.

I understand it's possible to achieve a similar effect by registering a `SpoofedData` parser in the `SpoofedDataParser` class, but I'd be nice if PS could support Paper's event too. :)

Among other things, the event allows you to define the failure reason, which is handy, as the default one used by PS doesn't apply to all situations.

> Ip forwarding is enabled but spoofed data can't be decoded or is missing

Just for reference, this is the plugin which made me notice this issue: https://github.com/lucko/BungeeGuard

I might attempt a PR if I get some time in the next few weeks (and if you indicate you'd accept this change). Only slight issue is it means somehow depending on the Paper API to gain access to the event, or just copying the class into ProtocolSupport. I understand Glowstone also forks off Paper, so I don't think this would be an issue?

**Comment by Shevchik** [comment]
The paper dependency should be a soft depend.

PS has ConnectionHandshakeEvent, but it is broken right now, should fix that.
