### ISSUE TITLE
Boat Issue

### ISSUE THREAD

**Issue by dartasen** [ProtocolSupport/ProtocolSupport#746]
Hi there ! 

I'm having an issue on my 1.12.2 spigot server with ProtocolSupport : 
 When PS is enabled, players can't go two at a time in a boat as minecraft allows it 👎

**Comment by MrPowerGamerBR** [comment]
This happens because if the server allowed it, it would cause HUGE issues with pre-1.9 clients.

If you don't care about 1.8/1.7/1.6/1.5/1.4, use an plugin to disable every version before 1.9, then boats will work.
