### ISSUE TITLE
1.12 Items with metadata and NBT from 1.12 show up as missing textures.

### ISSUE THREAD

**Issue by milkmoron** [ProtocolSupport/ProtocolSupport#752]
Hi There is an issue on 1.12.2 using items with metadata and NBT tags. 1.8 clients show up as purple blocks for items that I use that use 1.12.2 tags and metadata I believe. The plugin adding tags and data is DivineItemsRPG. Could this issue be fixed?

**Comment by milkmoron** [comment]
Is it possible for an item with 1.9+nbt tags to be spoofed as a item with no 1.9+ nbt tags?

**Comment by 7kasper** [comment]
🤔 I think we already skim out nbt that makes the game crash. If you have any particular NBT data in mind that causes issues we might be able to help.

**Comment by milkmoron** [comment]
Here's a quote from the plugin dev.

There are a lot of tags used in this plugin. If it possible you can add a mask or something like this for all tags that starts with "DIVINE_"

**Comment by Shevchik** [comment]
nbt shouldn't really affect this, but metadata (data values) can. But i leave it as won't fix because in 1.13 data values doesn't exist, so fixing this == spending really much time for nothing,
