### ISSUE TITLE
Лишний текст

### ISSUE THREAD

**Issue by Sitmobedaf** [ProtocolSupport/ProtocolSupport#753]
Привет разработчик.
Убери пожалуйста лишние надписи, которые появляются когда игрок не смог подключиться:
 Disconnecting protocolsupport.protocol.utils.authlib.GameProfile...
textures=protocolsupport.api.events.PlayerPropertiesResolveEvent$ProfileProperty@26e210...

Так, чтобы там была только самая нужная информация.

**Comment by Shevchik** [comment]
That's the same data that vanilla minecraft server prints, just the class names are printed along with data.
