### ISSUE TITLE
Compiling failed

### ISSUE THREAD

**Issue by AlexCreeper25** [ProtocolSupport/ProtocolSupport#756]
Still having problems on compiling the mcpenew-mcpeinv. branches: the errors seems to be regarding glowstone again. Here's a pastebin link of the error: https://pastebin.com/4hqvRVP5
Please, fix this A.S.A.P.

**Comment by MrPowerGamerBR** [comment]
Private paste and it works for me, you didn't update your local fork.

**Comment by AlexCreeper25** [comment]
Ah, my bad, btw, here's the paste: https://pastebin.com/JKuLHZsj
And, what do you mean by "update your local fork"?

**Comment by GoNotCougsWA** [comment]
I am getting the same problem but it getting fixed.

**Comment by AlexCreeper25** [comment]
Please help, I'm still getting the error...

**Comment by 7kasper** [comment]
Did you do a `git pull`?

**Comment by MrPowerGamerBR** [comment]
You need to merge `master` into the `mcpenew` branch

**Comment by GoNotCougsWA** [comment]
I did that but i still have missing stuff.

**Comment by AlexCreeper25** [comment]
Thanks for help, I fixed it!!
