### ISSUE TITLE
Boat Bug

### ISSUE THREAD

**Issue by LordStave** [ProtocolSupport/ProtocolSupport#757]
Hello,
as soon as you enter a boat and drive around a bit and leave it, you are teleported back again.
I'd love to use ProtocolSupport, but that's only possible when the bug is fixed.

Server Version: 1.12.2
ProtocolSupport Version: latest
Other Plugins: None

Bug Version: 1.7-1.8

**Comment by gdude2002** [comment]
You've forgotten to include the relevant version info. For example:

* Server software and version
* Minecraft client versions that have this problem
* Whether you've tested with only ProtocolSupport on its own

**Comment by Shevchik** [comment]
Known wontfix issues:
    [1.8 and earlier] Can't control vehicle
