### ISSUE TITLE
Wolf collar color is wrong in pre 1.8 versions

### ISSUE THREAD

**Issue by Tom-III** [ProtocolSupport/ProtocolSupport#76]
The wolf collar colors are different between versions, in 1.8 light green / yellow is blue in 1.7
In 1.7
![Color difference 1.7](http://i.imgur.com/4eXU6vi.png)
In 1.8
![Color difference 1.8](http://i.imgur.com/PU9avBn.png)
And yes we are talking about the same wolf :)

**Comment by MrPowerGamerBR** [comment]
It seems that the color are shifted :open_mouth: 

In 1.8, the wolf collar colors are this:
Ink Sac, Rose Red, Cactus Green, Cocoa Beans, Lapis Lazuli, Purple Dye, Cyan Dye, Light Gray Dye, Gray Dye, Pink Dye, Lime Dye, Dandelion Yellow, Light Blue Dye, Magenta Dye, Orange Dye, Bone Meal

However, in pre 1.8, the wolf collar colors inverted, so, if I apply a black (ink sac) collar on a wolf, it will appear as a white collar, and, if I use the rose red collar, they will appear as a orange collar.

This also applies to you screenshot, if you see, in 1.8, the wolf was a dandelion yellow collar, and, in pre 1.8, they have a lapis lazuli collar.

**Comment by Tom-III** [comment]
Has this been fixed or no

**Comment by MrPowerGamerBR** [comment]
@Tom-III no :cry:

**Comment by Shevchik** [comment]
Should be fixed now
