### ISSUE TITLE
Inventories not being Updated on Server Side 1.5 or Older

### ISSUE THREAD

**Issue by Ev3ryShir** [ProtocolSupport/ProtocolSupport#768]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

If you fail to check the above, your issue will be closed.

**Comment by Ev3ryShir** [comment]
When any player in 1.5 vest something with Shift inside the Inventory or change the Items from their places after pick up the server isn't updating at all... causing the Player have a lot of Rollbacks in his inventory.
The Inventory just suffer any update after the player eat something or use any Item...
Player View:
https://prnt.sc/ibbsax
https://prnt.sc/ibbte0

Other Player View:
![image](https://user-images.githubusercontent.com/36229297/35914089-a3a5cf0a-0c0a-11e8-89e6-e7b2b5a62375.png)

After Eat something and Receive RollBack Update (Player View):
https://prnt.sc/ibbtpg

**Comment by Shevchik** [comment]
Video pls, can't really understand what you mean exactly.

**Comment by MrPowerGamerBR** [comment]
I tried reproducing this bug in 1.5.2 by...

* Opening the inventory and equipping the armor by clicking
* Opening the inventory and SHIFT clicking the armor
* Right clicking the item in the hot bar

And I couldn't reproduce this bug, the issue report *seems* very similar to https://github.com/ProtocolSupport/ProtocolSupport/issues/719 but I don't know if it is really the same underlying issue

**Comment by Ev3ryShir** [comment]
Bug Fixed!
Errror or Bug caused by Anticheat, (NoCheatPlus from 1.9) where in versions higher than 1.8 you gota limit of Items and how fast you can change the position from your items in your inventory...
