### ISSUE TITLE
Error when a client pings the server [Glowstone]

### ISSUE THREAD

**Issue by DoppelnullYT** [ProtocolSupport/ProtocolSupport#769]
Hello :)

I'm using glowstone (newest version, latest build by website) and only ProtocolSupport (newest jenkins version) in addition.
When the server starts and a client pings the server, the server won't answer (therefore no one can connect).

Everytime a connection should be established or a client pings, the following error will be thrown:

``
[/127.0.0.1:10100] kicked: read error: net.glowstone.net.pipeline.MessageHandler.getSession()Ljava/util/concurrent/atomic/AtomicReference;
``

I have tried the porkaxe method, and it didn't help.

**Comment by momothereal** [comment]
This is likely caused by this commit: https://github.com/GlowstoneMC/Glowstone/commit/cdb41383cb6c8a51090399de447f79baf06687da

The method was re-added in https://github.com/GlowstoneMC/Glowstone/commit/679a0b4dafefc5795cc4e574925956c424591c20. Using the latest Glowstone build (1978) should fix this issue.

**Comment by DoppelnullYT** [comment]
@momothereal 
Thanks 👍 It now works, but a change to the class name of the PlayerProfile (-> now GlowPlayerProfile) destroyed the imports in ProtocolSupport - so now it's a issue for @Shevchik :,D

Class: https://github.com/GlowstoneMC/Glowstone/blob/0cfbb0692a4aafb282a6d68b26f780102bdec666/src/main/java/net/glowstone/entity/meta/profile/GlowPlayerProfile.java

Commit: https://github.com/GlowstoneMC/Glowstone/commit/0cfbb0692a4aafb282a6d68b26f780102bdec666#diff-bd59b1c2be78b091d2e887be7f414fe2

Both (server & plugin) are on the newest version.

Thanks!
