### ISSUE TITLE
Everytime, when player with version ~1.7 is trying to join, the plugin is having exception

### ISSUE THREAD

**Issue by MiMic10110** [ProtocolSupport/ProtocolSupport#770]
When players is trying to join the server, this exception is appearing in server console:

[12:38:49 INFO]: protocolsupport.protocol.utils.authlib.GameProfile(uuid: |online-uuid|, name: |my-nick|, properties: {}) (/|my-ip:my-port|) lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown gamemode network id -9

I think the cause of this problem is this plugin.

EDIT:
The case of this exception is when player is beeing disconnected when he is joining to the server, for example, when whitelist is on and he is not on the whitelist. Player in this case is having forever "Logging in" info in his minecraft instead of disconnect reason.

**Comment by gdude2002** [comment]
You'll need to provide a lot more information than that.

For example: What server software and build? What version of ProtocolSupport? Where did you download ProtocolSupport?

**Comment by piter909** [comment]
Everything newest. I have build spigot 15 minutes before, and downloaded protocolsupport from spigot site ~10 minutes ago.

**Comment by gdude2002** [comment]
Then you're not using "everything newest". You'll want to download [the latest ProtocolSupport build from Jenkins](https://build.true-games.org/job/ProtocolSupport/lastSuccessfulBuild/artifact/target/ProtocolSupport.jar).

**Comment by piter909** [comment]
I will try with this build and I will inform if this problem disappeared or not. Give me few minutes.

**Comment by piter909** [comment]
Newest build is having still same problem. Exception is the same.

**Comment by MrPowerGamerBR** [comment]
Did you try testing without any plugin?

**Comment by piter909** [comment]
I will try. At this moment I have 4 plugins, but I do not think that they can affect protocolsupport. Give me few minutes.

**Comment by piter909** [comment]
Removing all plugins did not help.
I forget to add - I am using debian 10 and java 8.

**Comment by MrPowerGamerBR** [comment]
@piter909 make a backup of your world, delete the world folder and join again

**Comment by piter909** [comment]
I will try. It is a dev server, so I backups are not necessary :). Give me few minutes

**Comment by piter909** [comment]
It did not help. New world generated.

**Comment by MrPowerGamerBR** [comment]
Can you check what versions are affected?

**Comment by piter909** [comment]
How to check version of protocolsupport?

**Comment by piter909** [comment]
I have tested it now on debian 7 wheezy and everything works fine. I can now join to the game without any exception. Hmm.. Maybe it is OS problem? But how can it affect this plugin? As I know Java is having its own virtual enviroment.

**Comment by MrPowerGamerBR** [comment]
I was talking about the client versions (to see if versions before 1.7 are affected too) buuuut if you also want to check where this bug started happening you can use `/protocolsupport buildinfo`

**Comment by piter909** [comment]
I have discovered that this exception is appearing when login is too long or player is being disconnected in join event due to something. This is the case of this error. I had firewall that was delaying connections by 5 seconds (anti bot rules) and when this exception appeared it was forever "Loging in" in player's minecraft window.

**Comment by piter909** [comment]
Yeah, this is the case. Also, if player is unable to connect, because for example whitelist is on, he is having forever "Logging in" in his minecraft instead of disconnect reason.

**Comment by Shevchik** [comment]
When disconnecting 1.7 player at login a start game packet is sent before disconnecting, maybe something is wrong with it, will check.
