### ISSUE TITLE
ProtocolSupport incompatible with Glowstone (Client below 1.9)

### ISSUE THREAD

**Issue by DoppelnullYT** [ProtocolSupport/ProtocolSupport#772]
Hey 

I've the newest version of Glowstone and ProtcolSupport.
Actually i figured out a list of problems (as far as i could test it).

Actually, all clients below 1.9 (1.4.7 - 1.8.9) have the following Exception, when they place a block:
https://gist.github.com/DoppelnullYT/7909e20d14566207c40ed9aac42e1684

In this gist (comments) are some more exception, which are thrown when using clients like 1.7 :)

Do you need some more informations?

**Comment by Shevchik** [comment]
Should probably insert a null check, or produce a fake packet for glowstone impl

**Comment by Shevchik** [comment]
Should be fixed now
