### ISSUE TITLE
Levitation effect for 1.8 clients should work in reverse when amplfier is >127

### ISSUE THREAD

**Issue by RoboMWM** [ProtocolSupport/ProtocolSupport#778]
Basically, instead of applying the opposite (falling quickly over 128, or hovering when near 255), the player is rocketed upwards.

**Comment by Shevchik** [comment]
I guess i forgot that i need to cas amplifier to byte

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by MasterDash5** [comment]
before this closes, would it be possible to emulate the levitation particle for 1.8 clients?

**Comment by MasterDash5** [comment]
Just did some testing with the latest dev build (201). Levitation's speed isn't correctly emulated and amplifiers of 128 and higher have strange behavior, for example 140 acts weird when you jump and around 145 still sends you upwards.

**Comment by RoboMWM** [comment]
I haven't tested with a 1.8 client myself but another player who was on 1.8 has and they still rocketed upwards with amplifier at 250.

**Comment by Shevchik** [comment]
Should be fixed now.
