### ISSUE TITLE
Broken Build Server for ProtocolSupport

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ProtocolSupport/ProtocolSupport#78]
Due to the repo move, it seems that the Build Server isn't compiling ProtocolSupport any more.

http://build.true-games.org/job/ProtocolSupport/

The latest version still is the "Those chat components give me a headache" commit, however a new commit was already pushed to the repo.

**Comment by Shevchik** [comment]
Yea, i know, didn't have to to fix jenkins yet
