### ISSUE TITLE
BossBar problem on 1.8 client on 1.12 server

### ISSUE THREAD

**Issue by thecrafterjt** [ProtocolSupport/ProtocolSupport#788]
Hay!

ProtocolSupport: Build #205

 I figured out a problem with the ´Bukkit.createBossBar();´ method:
When i join with a 1.12.2 client i can see the BossBar as it is supposed to, but then i joined with a 1.8 Client and i couldn't see the BossBar. Server runs on latest spigot build (1.12.2).
No errors in the console so far.

Sry for my English

**Comment by Shevchik** [comment]
See ProtocolSupportLegacySupport
