### ISSUE TITLE
Some BUGs with PE.

### ISSUE THREAD

**Issue by MikuSnow** [ProtocolSupport/ProtocolSupport#793]
Here are some bugs that I have find.
1. Can not craft book_shelf.
2. Can not use/drop bucket, lava_bucket, water_bucket
3. Can not use enchantbook with anvil.
4. Can not open enchantment table.(Click it will open a hopper gui)
5. Can not send true time to PE player if gamerule doDaylightCycle = false.(12 hours later)
6. Can not attack some mob's body. Only can attack feet. Like skeleton.
7. Can not hit normal damage. Use diamond sword only can hit 1 damage.
8. Some times can not craft chest.( I have test , it happened a few times.)
9. I forget.

**Comment by Shevchik** [comment]
We don't accept pe issues on this repo right now. You can join discord and send it there.
