### ISSUE TITLE
"Cannot interact with self!" kick when disguised

### ISSUE THREAD

**Issue by Drc-DEV** [ProtocolSupport/ProtocolSupport#795]
Using ProtocolSupport  (Build 209)
Using PaperSpigot 1.12.2 (Build 1350)
Tested with a 1.12.2 client (premium)
This bug is related to LibsDisguises' disguises. When disguised, if you interact with a chest (for example) you get kicked for "Cannot interact with self!". I think this could be a PS issue as it does not happen with LibsDisguises alone, and I've seen from their source that they block the interact kick via packets, and I suppose that something in PS may override that protection, causing the kick. Idk
I also reported on the LibsDisguises github issues the problem.

**Comment by Speentie8081** [comment]
https://github.com/libraryaddict/LibsDisguises/issues/282
^ just linking the issue that he posted on LibsDisguises

**Comment by 7kasper** [comment]
"They block the kick via packets" 🤔 
Well I suppose he means https://github.com/libraryaddict/LibsDisguises/blob/383c9ecaca6877919199e26d1c07efa4a1e5053c/src/main/java/me/libraryaddict/disguise/utilities/PacketsManager.java#L128. Which is true. The server kicks is the player is sending interaction with itself as eId.

We could just drop the packet if the player is interacting with self, though I am not sure if that's orthodox. The plugin's packet listener should just work. I'm not sure how our transforming makes something slip trough the crack.

**Comment by Shevchik** [comment]
Needs retesting with 1.13.2 and latest libs disguises.

Anyway the cancel is done like that:
https://github.com/libraryaddict/LibsDisguises/blob/383c9ecaca6877919199e26d1c07efa4a1e5053c/src/main/java/me/libraryaddict/disguise/utilities/packetlisteners/PacketListenerClientInteract.java#L42
And i'm not sure what can fail there (with the exception of possible race condition).

**Comment by Shevchik** [comment]
Wasn't able to reproduce with latest protocolsupport. I guess something was fixed since that time.
