### ISSUE TITLE
1.8.8 and lower squid and wolf issue

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#800]
Squids and wolves in 1.8.8 and lower have a weird behavior. I've tested this in 1.8.8, 1.8.9, and 1.12

1.8.9 and higher: http://prntscr.com/j01isa
1.8.8 and lower: https://youtu.be/PxQnoNH4arA (a video better shows whats happening)

**Comment by MasterDash5** [comment]
Turns out this is a graphical issue with my computer, sorry about that.

**Comment by 7kasper** [comment]
Hahaha that looks awesome! 😄
