### ISSUE TITLE
Player Position Desync

### ISSUE THREAD

**Issue by MatrixTunnel** [ProtocolSupport/ProtocolSupport#802]
This issue only occurs with 1.8 clients on 1.12 servers (that I know of).

When the desync happens, players don't display in the location they should. This is most prominent when other players are bridging.

1.8 client recording: https://gfycat.com/UniqueImpressionableKronosaurus

**Information**
> Server Version: `Paper#1390`
> Plugin Build: `#230`

**Comment by Shevchik** [comment]
Same as #666

**Comment by DanielAlves123** [comment]
@Shevchik can you fix it?
