### ISSUE TITLE
1.7 Players can't join due to this error

### ISSUE THREAD

**Issue by ItzVinex** [ProtocolSupport/ProtocolSupport#803]
Before submitting your issue, please check the following:

* Ensure you are using the latest version of ProtocolSupport from Jenkins: https://build.true-games.org/job/ProtocolSupport/
* Ensure you are using the latest version of Spigot, PaperSpigot or Glowstone as appropriate
* Make sure the problem is actually related to ProtocolSupport - try to reproduce it using only ProtocolSupport
* If possible, you should reproduce your problem with debug enabled (`/ps debug`)

Remember, we only support the latest version of ProtocolSupport and the latest server version. Make sure you are not using an old version!

If you fail to check the above, your issue will be closed.

https://gyazo.com/006591590f5aa81740286f922307c13a

Using the latest build of PaperMC which is PaperSpigot and the latest version of ProtocolSupport.

**Comment by Encode17** [comment]
Exactly same problem here.

**Comment by MrPowerGamerBR** [comment]
@Encode17 can you enable `debug` on `server.properties` and reproduce the bug?

Also, please share your client log!

**Comment by Speentie8081** [comment]
@Encode17 This normally happens when plugins try to do something to a client that only 1.8 and above clients support. I have had this issue personally quite a lot. This often has to do with player display names in tab, length of text on scoreboard, or length of text in bossbar.

**Comment by Encode17** [comment]
I was testing it without plugins. Test it with two digit number of online players. In other situation, 1.7 will usually join to the game.

**Comment by MrPowerGamerBR** [comment]
@Encode17 please send your server IP here to help debugging (because debugging this issue is a bit trickier)

**Comment by Encode17** [comment]
I found the cause. Problem is when scoreboard is moved to PLAYER_LIST and we will set prefix of player.
It does not disconnect 1.7.x players instantly. Only when they want to join to the server.

**Comment by Shevchik** [comment]
Try now, maybe it is fixed, this most likely was caused by long above head names.
