### ISSUE TITLE
Weird crash issue, may not be related to procolsupport

### ISSUE THREAD

**Issue by Cobwebster** [ProtocolSupport/ProtocolSupport#811]
We're trying to find the plugin causing this crash issue, https://github.com/PaperMC/Paper/issues/1102

would you happen to know if this is protocol support related and if not do you know what it could be?

**Comment by MrPowerGamerBR** [comment]
As far as I know ProtocolSupport does not use the Bukkit API in any network thread, but I will keep this issue open.

About your crash: I already had the same issue before, what I ended up doing is editing Paper, `try ... catch` the exception and figuring out what plugin was causing the issue.

**Comment by Cobwebster** [comment]
in your case what was it? We don't really have that many plugins loaded, especially ones which would cause the issue, I provide our plugin this on the post above. I believe editing paper personally to catch the cause may be beyond my ability.

**Comment by Shevchik** [comment]
We don't modify server internals in non main thread.
You will have to add async catcher to PlayerChunkMap code yourself to find out the cause.
