### ISSUE TITLE
Protocol + FlatColoredBlocks

### ISSUE THREAD

**Issue by Danymaddox** [ProtocolSupport/ProtocolSupport#825]
Lastest version of Spigot 
Lastest version of ProtocolSupport
Lastest version of FlatColoredBlocks
Lastest version of Optifine

Every time I try to make a server with Protocol + Forge + Optifine + FlatColoredBlocks this happens:

![image](https://user-images.githubusercontent.com/10263870/40283452-bf0b1786-5c7e-11e8-98dc-c52c80420f27.png)

My game does not render any block until it is updated

Protocol + vanilla = fine
Protocol + vanilla + OptiFine = fine
Protocol + forge = fine
Protocol + forge + OptiFine = fine
Protocol + forge + FCB = fine
Protocol + forge + OptiFine + FCB = Not fine

**Comment by 7kasper** [comment]
What version is this? From what you say it seems like optifine is causing the issue (when you introduce it, it goes wrong) Also try without ProtocolSupport. It seems that combo you you have not tried: Forge + OptiFine + FCB

**Comment by Danymaddox** [comment]
I've already tried. The problem is with FCB and Protocol I think

**Comment by Shevchik** [comment]
Which client version is that?
Does it also break when you have ps + forge + optifine + any other mod that adds many blocks?

**Comment by Danymaddox** [comment]
MC version: 1.12.2 
Forge: 14.23.4.2703

*Spigot (server) 1.12.2-R0.1-SNAPSHOT
Protocol Support (server) BuildTime 2018.05.13 at 00:16:12 - BuildNumber: 229
OptiFine_1.12.2_HD_U_D3 (client)
flatcoloredblocks-mc1.12-6.6 (client)

**Comment by Shevchik** [comment]
Does this still happen?
