### ISSUE TITLE
Add a maximum chunk interval queue

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#828]
Mostly to fix long queues, I've gotten 2 minute queues before. Not much else to say about this.

**Comment by Shevchik** [comment]
The interval between chunk sending for 1.8 clients can be configured by protocolsupport.chunksend18interval system property.

**Comment by Shevchik** [comment]
https://github.com/ProtocolSupport/ProtocolSupport/wiki/Properties

**Comment by MasterDash5** [comment]
Setting the property to 0 doesn't fix the queue times. It helps, but there are still overly long queues.
