### ISSUE TITLE
ItemWorldMap being ticked every 3 seconds instead of one

### ISSUE THREAD

**Issue by MClausz** [ProtocolSupport/ProtocolSupport#829]
I made a clock plugin, rendered by a filled map, and it need to be updated every second. But with the latest build of ProtocolSupport (build 238), the map ticked every 3 seconds.
Without ProtocolSupport, or with the older build of it (dunno which the exact build, maybe a really old one), it works fine.
Tried looking into your SpigotEntityTrackerEntry.java and couldn't find anything, it says a%10 == 0, every 10 ticks? ¯\_(ツ)_/¯
https://youtu.be/qw3cQuesQGs

**Comment by Shevchik** [comment]
Spigot entity tracker updates map once per 10 ticks and paper one once in 20 ticks. So it is related to something else.

**Comment by MClausz** [comment]
I tried changing to 20 ticks and it works
But y tho
