### ISSUE TITLE
chunksend18interval property doesnt work as expected

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#830]
Plugins with packet implementation (such as ProtocolLib) slow down the chunk interval queue. Also making the protocolsupport.chunksend18interval property almost useless

**Comment by MasterDash5** [comment]
found out this issue is caused when getUnlockDelay() method inside ChunkSendIntervalPacketQueue returns -1.

**Comment by MasterDash5** [comment]
I downloaded the source code and compiled ProtocolSupport myself to see what caused it. Its caused when processPackets0 sets the state to waiting_unlock_schedule.

(I suck at explaining so heres a screenshot): https://imgur.com/a/XskQiHf

**Comment by Shevchik** [comment]
By commenting out this line you basically disabled the queue

**Comment by MasterDash5** [comment]
what if you make a property that toggles the entire queue in general
