### ISSUE TITLE
Command Blocks dont work for 1.8.9 and lower

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#831]
1.9 - 1.12.2: http://prntscr.com/jqh2f3
1.8.9 and lower: http://prntscr.com/jqh2ml

1.8.9 and lower can edit command blocks.

**Comment by MasterDash5** [comment]
Setting a new command is perfectly fine, they don't see any commands already previously entered

**Comment by Shevchik** [comment]
For now all pre 1.13 versions can't edit command blocks.
