### ISSUE TITLE
Memory leaks, long map loading on change world

### ISSUE THREAD

**Issue by mariolars** [ProtocolSupport/ProtocolSupport#833]
https://pastebin.com/jkmhie9W
git-Paper-1418 but it happens on every recent build
ProtocolSupport 238

ProtocolSupport build 188 is totolly fine i dont really know which commit messed up but issue exists since 4 months. I didn't know about command /ps leakdetector for long time and hoped that someone will face this too.

**Comment by Shevchik** [comment]
Might be related to 1.8 chunk queue.
