### ISSUE TITLE
Игроки с версий .1.5.2 и ниже не могут писать в чат

### ISSUE THREAD

**Issue by Sitmobedaf** [ProtocolSupport/ProtocolSupport#834]
http://img12.lostpic.net/2018/06/10/6b46e3b954afe158867c4dcd5c21a72f.jpg
В чат отправляются кракозябры.

**Comment by Sitmobedaf** [comment]
И ещё: игроки с 1.8 не могут лазить по лестницам. Давно кстати.

**Comment by Shevchik** [comment]
Works fine here, try testing without other plugins (also make sure you have a utf locale set in the system).

**Comment by Sitmobedaf** [comment]
Тоже не получилось воспроизвести. Буду тогда спрашивать у таких игроков, что у них за система.
