### ISSUE TITLE
1.9 kick

### ISSUE THREAD

**Issue by Xayanix** [ProtocolSupport/ProtocolSupport#835]
![image](https://user-images.githubusercontent.com/12672902/41264727-90067d50-6dee-11e8-84aa-7b0662604736.png)

**Comment by Shevchik** [comment]
That's an invalid json message somewhere. Test with other versions. Or post a server ip so we can join and see.

**Comment by Xayanix** [comment]
Join my discord: https://discord.gg/tu8wVVg
I will guide you to reproduce issue.

**Comment by Xayanix** [comment]
https://youtu.be/330SNaRR7UI

**Comment by MasterDash5** [comment]
this actually happens in 1.9 - 1.9.2

**Comment by Shevchik** [comment]
I need the server address, that message can be sent from literally anywhere.

**Comment by Xayanix** [comment]
Join with 1.9 on nssv.pl -> RealLife server and move to X: 2269 Y: 75 Z: 1837.

**Comment by Shevchik** [comment]
You have a sign with invalid string content at 2261,67,1900

**Comment by MrPowerGamerBR** [comment]
Probably not, try joining with a client that can go there (1.12.2) and see the sign contents.

**Comment by Xayanix** [comment]
Actually removed this sign but im pretty sure that it only affects 1.9-1.9.2. 1.7-1.8.9 & 1.9.3-1.12.2 are fine.
