### ISSUE TITLE
Major performance issues

### ISSUE THREAD

**Issue by Despawned** [ProtocolSupport/ProtocolSupport#843]
We're experiencing major performance issues with ProtocolSupport that's showing up on basically all of our servers running it (version 4.29-dev). 

The spark profiling diagnostic showing the issue is here: 
https://sparkprofiler.github.io/?aBE2WPRlwM

Can this be fixed? There are no good alternatives to this plugin, and you guys did a great job minus these performance issues

**Comment by caoli5288** [comment]
There is no big lag led by protocolsupport in your profile

**Comment by Shevchik** [comment]
^

**Comment by astei** [comment]
@Shevchik I urge you to take another look at this.

Here's a new 1-minute CPU profile: https://sparkprofiler.github.io/?NQodDbNwPc

As you can see, our plugins now consume an insignificant amount of time (after much optimization work), but ProtocolSupport sticks out like a sore thumb, consuming nearly half of the time that remains running in the server tick.

**Comment by Shevchik** [comment]
In this profiler output i still not see where does ProtocolSupport consumes any amount of time. The only place where protocolsupport even exists in this log is the entity tracker, but ProtoocolSupport doesn't consume much time there, the called methods do.

**Comment by astei** [comment]
Hmm, so we might need to do some more investigation... perhaps it has to do with the epoll transport that Minecraft is using? We could try switching back to NIO and see if that does the trick.

**Comment by caoli5288** [comment]
@astei do not sampling in very low workload

**Comment by astei** [comment]
We eventually resolved the issue. It was due to us constantly despawning and respawning entities. That issue is fixed now.
