### ISSUE TITLE
175 crash item in inventory in 1.6.4

### ISSUE THREAD

**Issue by andris155** [ProtocolSupport/ProtocolSupport#85]
Plugin version: latest dev.
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/11275056/18a239e6-8edc-11e5-8e6a-980561ec4b97.PNG)

**Comment by MrPowerGamerBR** [comment]
It seems thaty some remappers are wrong (example: that and the packed ice remapping)

**Comment by MrPowerGamerBR** [comment]
Created pull request fixing this bug #87

**Comment by andris155** [comment]
All 175 id items inventory = crash

**Comment by MrPowerGamerBR** [comment]
@andris155 yeah, my pull requests maps every 175 item to a yellow flower (well, that's what happens in 1.5.2, I just changed a line of code to remap for 1.6 too)

**Comment by Shevchik** [comment]
Packed ice remapping is correct, packed ice is not opaque block while just ice is.
