### ISSUE TITLE
Bug does not eat golden apple

### ISSUE THREAD

**Issue by Retrumek** [ProtocolSupport/ProtocolSupport#854]
Hi, I have bug with golden apple:

https://www.youtube.com/watch?v=tduTZ4AbQfU

**Comment by DanielAlves123** [comment]
@Shevchik same: https://www.youtube.com/watch?v=6JsHfEzrAqQ

**Comment by DanielAlves123** [comment]
@Shevchik It happens on 1.8 for example when you switch from golden apple to enchanted golden apple for example.

**Comment by Retrumek** [comment]
fix this problem ?

**Comment by Remu-2018** [comment]
@Retrumek fix it your self if its to slow

**Comment by Remu-2018** [comment]
It Works fine

**Comment by DanielAlves123** [comment]
@Shevchik Be on 1.8, start eating golden apple, while eating switch to enchanted golden apple then you will be able to hold button infinitely. Sometimes you simply cant eat too.

**Comment by WesleyVanNeck** [comment]
@DanielAlves123 i used 1.8 1.7 of Works fine

**Comment by 7kasper** [comment]
I believe this problem only occurs when switching between golden apple types. Have you tried that @wesleyvanneck?

**Comment by WesleyVanNeck** [comment]
Yes

**Comment by DanielAlves123** [comment]
Well you have recordings so whats the problem?

**Comment by WesleyVanNeck** [comment]
@DanielAlves123 @Retrumek  probely its a plugin issue like plugin oldcombat

**Comment by WesleyVanNeck** [comment]
yhat custumise notch apple or golden apple effects
