### ISSUE TITLE
Missing /playsound translation 1.8.9 and lower

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#855]
Newer /playsound sound names don't translate for 1.8.9 and lower

Examples:
1.9+: /playsound entity.enderdragon.death master @p ~ ~ ~
1.8.9 and lower: /playsound mob.enderdragon.end master @p ~ ~ ~

**Comment by Shevchik** [comment]
Apparently this was intended (most likely to load resourcepack new style sounds). But i guess i can remap this.
