### ISSUE TITLE
Severe problems with Glowstone

### ISSUE THREAD

**Issue by BlackHawk2306** [ProtocolSupport/ProtocolSupport#856]
Plugin seems to load fine, but with every ping(those that can be seen as "Initial handler connected....." on Bungeecord) prints this error into the console:
14:45:47 [INFORMATION] [/127.0.0.1:64596] kicked: read error: net.glowstone.net.pipeline.MessageHandler.getSession()Ljava/util/concurrent/atomic/AtomicReference;

Also, every ~30 seconds there's a Java error (NoSuchMethodError): 
https://hastebin.com/inadamezej

No problems connecting with MC 1.12.2

**Comment by Shevchik** [comment]
You need latest ps dev build and latest glowstone for that to work.

**Comment by BlackHawk2306** [comment]
I downloaded both from spigotmc within the last 30 minutes. Is Glowstone outdated there?

**Comment by BlackHawk2306** [comment]
So the latest normal one on SpigotMC(both) won't work?
