### ISSUE TITLE
Server Freezing

### ISSUE THREAD

**Issue by MithrandirCraft** [ProtocolSupport/ProtocolSupport#863]
Hello. I am NOT using the latest version of Protocol Support, because I can't. But that's not even my main issue.

My main issue is that with my current version in use, 4.29-dev, my Hub server is freezing every 12h average, making it impossible for anyone to access any of the network's servers, and forcing me to restart the hub. I did a memory dump in the exact moment a freeze started, and found the following memory leak suspect using eclipse memory analizer: https://i.imgur.com/fycj6kp.png

Therefore I thought the best course of action would be to update protocolsupport to the latest dev version on all servers, just in case it got rid of the problem, however I cannot update it due to an error showing once I do:
https://hastebin.com/hewuzeceku.css

I also read on your main spigot page that you recommend setting "use-native-transport" to false if the server kicks players and stops working (which isn't entirely the case, it just kinda "freezes" and no one can get in, but it still responds), but I'm not convinced about disabling something that optimizes packet sending for ubuntu.

Spigot for MC 1.12.2 with Bungee.

**Comment by MithrandirCraft** [comment]
@Speentie8081 xD ok then. I didn't want to do this, but I'll give it a shot.

**Comment by Shevchik** [comment]
You describing exactly the native transport enabled problem. Server still ticks main thread, but don't allow players to log in.

**Comment by MithrandirCraft** [comment]
@Shevchik Good to know that, I already applied adjustments, I hope it stops >_<' It took me weeks to find this one, I only got pointed to your plugin thanks to the memory analysis, even if PowerGamer thinks it's not a leak.

I'll let you know how it goes after the scheduled restarts.

**Comment by MithrandirCraft** [comment]
This plugin alone occupies half a gig of ram just in regular activity, I understand this is pretty normal right?
Can I get pointed to the last 1.12.2 build please?

Hub still crashes, but considering the ammount of memory the plugin consumes, and the low ammount of allocated memory the hub has, It looks kinda logic.

**Comment by krusic22** [comment]
Latest 1.12.2 build on the official Jenkins is 242.
Also there must be an issue with one of your other plugins doing something.
I run my Lobby with 512Mb of ram with PS and I have 0 problems even with multiple users in it at once.
![image](https://user-images.githubusercontent.com/8352435/43370587-df461d36-9381-11e8-8c76-5ea4f9f07baf.png)

**Comment by Speentie8081** [comment]
Allocate more memory to any server running protocolsupport even if it's just a lobby.
It should have a minimum of 1 gigabyte of allocated memory to perform well under load.
