### ISSUE TITLE
1.13 support

### ISSUE THREAD

**Issue by UnNamedAndre** [ProtocolSupport/ProtocolSupport#864]
Version: spigot 1.12.2
Can you add 1.13 support?

**Comment by Shevchik** [comment]
No

**Comment by UnNamedAndre** [comment]
why

**Comment by Speentie8081** [comment]
@UnNamedAndre there is this thing called viaversion that does what you are asking for
viaversion is for forwards compatibility and protocolsupport is for backwards compatibility
