### ISSUE TITLE
chests show as enderchests

### ISSUE THREAD

**Issue by KyonDevelopment** [ProtocolSupport/ProtocolSupport#866]
1.12.2 client, 1.13 server latest build
latest build of ProtocolSupport
double chests appear to be ender chests
http://i.prntscr.com/CDtGHttrSqCa0GvrKhgFrA.png

**Comment by Shevchik** [comment]
Works as intended.

**Comment by Speentie8081** [comment]
@KyonDevelopment if you want a copy of protocolsupport that doesn't have the ender chest issue add me on discord SkorrloreGaming#6124

**Comment by Speentie8081** [comment]
@KyonDevelopment I actually just created a plugin that fixes the issue [https://www.spigotmc.org/resources/protocolsupportchestfix.59314/](https://www.spigotmc.org/resources/protocolsupportchestfix.59314/)
