### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by calvi9** [ProtocolSupport/ProtocolSupport#869]
Receive the following error. None of my players can connect to the server at the moment:

User protocolsupport.protocol.utils.authlib.GameProfile(uuid: null, name: x_BuildingPaws_x, properties: {}) (/86.182.28.0:36467) has disconnected, reason: Disconnected

![image](https://user-images.githubusercontent.com/42122101/43689436-a6855b62-98f2-11e8-87e4-a45f54a72a36.png)

[crash-2018-08-05_19.35.39-server.txt](https://github.com/ProtocolSupport/ProtocolSupport/files/2260654/crash-2018-08-05_19.35.39-server.txt)

**Comment by krusic22** [comment]
> java.lang.OutOfMemoryError

**Comment by Shevchik** [comment]
java.lang.OutOfMemoryError: unable to create new native thread
Not a protocolsupport problem.
