### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by FrankHeijden** [ProtocolSupport/ProtocolSupport#870]
Error:
https://hastebin.com/uvaratusug.sql
Server version: CraftBukkit version git-Spigot-1503de9-53d3ac0 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
ProtocolSupport: b260

**Comment by Shevchik** [comment]
You have a corrupted player .dat file.

**Comment by FrankHeijden** [comment]
Lol, okay, does that happen that fast on 1.13? xD just one day of running it
