### ISSUE TITLE
1.12.2 on 1.13 causes "Timed out" error on login

### ISSUE THREAD

**Issue by 133Seven** [ProtocolSupport/ProtocolSupport#874]
Hi, I am using the latest build of Paper, for MC 1.13, and the latest Jenkins build of ProtocolSupport and ProtocolSupportChestFix, and when I login using a 1.12.2 client I get a timed out error message. Any information you need to diagnose this?

**Comment by Shevchik** [comment]
You can use protocollib to print all packets to find where after which packet it stuck,
