### ISSUE TITLE
Player head is rotated skull head

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#878]
You see player heads as bugged, rotated skeleton skulls.

**Comment by DanielAlves123** [comment]
@Shevchik It only works on 1.13. Other versions see every head as rotated skeleton's skull.

**Comment by MiMic10110** [comment]
Will it be fixed? Tested - Skeleton skulls are visible instead of normal head on version 1.7.10.

**Comment by Xayanix** [comment]
Bump. Same thing.

**Comment by MasterGabeMOD** [comment]
Having the same issue on this. Noticed it after updating from build #305 to #320 that all skulls turn into skeleton heads.

**Comment by Shevchik** [comment]
Fixed.
