### ISSUE TITLE
Build server offline

### ISSUE THREAD

**Issue by BBoyJD10** [ProtocolSupport/ProtocolSupport#879]
Build server offline

**Comment by krusic22** [comment]
It's back already :)

**Comment by 7kasper** [comment]
Somtimes Shevchiks supply runs out so he drinks the vodka out of his pc, then it overheats a bit. Can happen from time to time.

**Comment by AryToNeX** [comment]
Vodka cooled PCs are great tho
But you find them only in Russia sadly
