### ISSUE TITLE
Problem with try login with 1.5, 1.6 and 1.7

### ISSUE THREAD

**Issue by nathampa0909** [ProtocolSupport/ProtocolSupport#88]
Hello, I have this problem: http://prntscr.com/94o8mr when I join to server in versions before 1.8

**Comment by MrPowerGamerBR** [comment]
IIRC ProtocolSupport doesn't work with AutoIn.

**Comment by nathampa0909** [comment]
AutoIn bug the PS. Thanks MrPowerGamerBR <3
