### ISSUE TITLE
Item Frames have incorrect Hitbox (1.13 on 1.13)

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#883]
Some ItemFrames habe an incorrect hitbox (depending on the placement direction, F3+B to see them) when playing 1.13 client on 1.13 server. Because of this they cannot be destroyed and no items can be placed in them.

Without ProtocolSupport on the server that bug does not exist

protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2018.08.29 at 14:32:33 MSK, buildhost: build.true-games.org, buildnumber: 271)
Server: Paper version git-Paper-193 (MC: 1.13.1)

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by Brokkonaut** [comment]
Thanks :)
