### ISSUE TITLE
Incompatibility with LibsDisguises

### ISSUE THREAD

**Issue by FrankHeijden** [ProtocolSupport/ProtocolSupport#885]
Heya,

Players get instantly kicked while trying to join with these 3 plugins enabled: LibsDisguises, ProtocolLib and ProtocolSupport. The error they get while kicked is this one: https://hastebin.com/kakuyeloya.bash

Additional server info:
CraftBukkit version git-Spigot-2440e18-60d7982 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
ProtocolSupport version 4.29-dev (b272)
LibsDisguises version 9.6.0-SNAPSHOT (b224)
ProtocolLib version 4.4.0-SNAPSHOT-b415

**Comment by Shevchik** [comment]
The provided pastebin doesnt exist

**Comment by FrankHeijden** [comment]
https://paste.md-5.net/komusigibo.m

**Comment by Shevchik** [comment]
Something wrong with processing chunk data, will look into it later.

**Comment by Shevchik** [comment]
The lines in the exceptions doesn't match the lines from dev build. Download dev build and paste exception log again.

**Comment by FrankHeijden** [comment]
b277; https://paste.md-5.net/rexufareni.nginx

**Comment by Shevchik** [comment]
The provided chunk data is missing the biome data (while the flag in the packet states that it sohuld be present).

**Comment by FrankHeijden** [comment]
it works perfectly without libsdisguises, what does this have to do with libs?

**Comment by Shevchik** [comment]
Maybe libs sends invalid chunk data. Or something wtih a combination of ps and libs sends invalid chunk data.

**Comment by Shevchik** [comment]
Try reproducing with ps only and libs only (when not having ps installed look closely in the launcher log, invalid chunk packets will throw an exception trace to it).

**Comment by Shevchik** [comment]
See https://github.com/libraryaddict/LibsDisguises/issues/295

**Comment by libraryaddict** [comment]
This should be resolved
