### ISSUE TITLE
Kicks from server and invisible particles

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#886]
1: When you eat enchanted golden apple you don't see any particles
2. When you throw splash potion of regeneration, then splash potion of speed on someone who ate this golden apple and it will get you kicked from the server. It can happen with various types of potions.

Logs with debug from having this situation 2 times:
https://pastebin.com/raw/FLxsirui

**Comment by Shevchik** [comment]
2 should be fixed now. Apple particles are tracked in the separate issue.
