### ISSUE TITLE
Invalid potion throw?

### ISSUE THREAD

**Issue by DanielAlves123** [ProtocolSupport/ProtocolSupport#887]
https://i.imgur.com/XRNgwHK.png
If you have speed 2 and sprint in front, you throw splash potion in front of you, you should be able to break this potion on your head, but it's not possible. Also when you throw potion above yourself, you see 
 potion break and particles not from under you, but next to you.

P.S. Is it really impossible to fix thrown potion texture? Dropped potion are working normally.

**Comment by Shevchik** [comment]
That's exactly how it works even without protocolsupport.

**Comment by MasterDash5** [comment]
Invalid potion textures can be fixed with this plugin. [
https://www.spigotmc.org/resources/protocolsupportpotions.52537/](url)
