### ISSUE TITLE
Everytime a player joins, i get an error.

### ISSUE THREAD

**Issue by MallisOG** [ProtocolSupport/ProtocolSupport#888]
I am using the release 2018.7.0 (latest release iirc) i got this error with the latest version of protocolsupport (build 277 on jenkins) and i got this error:

01:00:27 [INFO] [/192.168.56.1:64097] kicked: read error: net.glowstone.net.pipeline.MessageHandler.getSession()Ljava/util/concurrent/atomic/AtomicReference;

i then tried the latest dev build of both and deleted all the configs for everything as i do not need them since im just setting up the server today. i got this error: https://hastebin.com/bemiqaxoti.bash

after some tinkering around & changing between glowstone + protocolsupport versions, i recieved this error:
01:12:25 [INFO] Still running after shutdown, finding rogue threads...
01:12:26 [INFO] Preparing spawn for world: 44%
01:12:26 [INFO] Rogue threads killed, shutting down.
on every startup, but i think this is a protocolsupport issue, as it never happens when the plugin is not installed.

that is all the info i have, if you need anything more from me lmk.

**Comment by Shevchik** [comment]
Latest protocolsupport is for 1.13.1. Glowstone doesn't support 1.13.1 yet.

**Comment by MallisOG** [comment]
I changed my protocol support version to the latest on spigot & the latest release of glowstone: 11:34:21 [INFO] [/192.168.56.1:55585] kicked: read error: net.glowstone.net.pipeline.MessageHandler.getSession()Ljava/util/concurrent/atomic/AtomicReference;

**Comment by Shevchik** [comment]
You will need to find the latest protocolsupport dev build for 1.12.2. Check the old versions page on protocol.support.

**Comment by MallisOG** [comment]
thank you for this quick reply & info!
