### ISSUE TITLE
Some sounds are not remapped (1.12.2 on 1.13.1)

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#896]
For example when a plugin is playing the BLOCK_NOTE_BLOCK_PLING sound:
`player.playSound(player.getLocation(), Sound.BLOCK_NOTE_BLOCK_PLING, 1, 1);`
You can her it in 1.13.1 but not in 1.12.2

ProtocolSupport: buildtime: 2018.09.10 at 00:31:34 MSK, buildhost: build.true-games.org, buildnumber: 278
Server: git-Paper-249 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by MrMuskle** [comment]
Please do not remap! 😟

**Comment by MrPowerGamerBR** [comment]
While not a "fix", if you are able to provide resource packs to your players, you can add those sounds to a resource pack and players will be able to hear them.

**Comment by Brokkonaut** [comment]
Other sounds are remapped too ( https://github.com/ProtocolSupport/ProtocolSupport/blob/master/src/protocolsupport/protocol/typeremapper/basic/SoundRemapper.java ) Just the changes in 1.13 are currently not added there.

A custom texture pack is no option for us.

**Comment by WesleyVanNeck** [comment]
i think @MrPowerGamerBR got a good point

**Comment by 7kasper** [comment]
If the sound exists in 1.12 it should be remapped.

**Comment by MrPowerGamerBR** [comment]
Wait, is that a new sound in 1.13 or not? I think I mistook that sound with the new noteblock sounds from 1.12.2.

**Comment by zedwick** [comment]
My PR #906 Just got merged which updates the note block sound mappings. Try the latest build @Brokkonaut

**Comment by 7kasper** [comment]
Should be fixed thanks to @zedwick.
