### ISSUE TITLE
[Remapping]: Some blocks get remapped to Stone

### ISSUE THREAD

**Issue by MrMuskle** [ProtocolSupport/ProtocolSupport#898]
**Server Software:**
PaperSpigot - Build #253

 **Installed Plugins:**
(1): ProtocolSupport

**Version of ProtocolSupport:**
Build #278

**Description:**
The following blocks are remapped to `minecraft:stone`:
> minecraft:carved_pumpkin
> minecraft:pumpkin

> minecraft:oak_wood
> minecraft:spruce_wood
> minecraft:birch_wood
> minecraft:jungle_wood
> minecraft:acacia_wood
> minecraft:dark_oak_wood

> minecraft:red_mushroom_block[north=false]
> minecraft:red_mushroom_block[south=false]
> minecraft:red_mushroom_block[east=false]
> minecraft:red_mushroom_block[west=false]
> minecraft:red_mushroom_block[up=false]
> minecraft:red_mushroom_block[down=false]
_There are exceptions._

> minecraft:brick_stairs[shape=inner_left]
> minecraft:brick_stairs[shape=inner_right]
> minecraft:brick_stairs[shape=outer_left]
> minecraft:brick_stairs[shape=outer_right]
> minecraft:brick_stairs[waterlogged=true]

> minecraft:nether_brick_fence[north=true]
> minecraft:nether_brick_fence[south=true]
> minecraft:nether_brick_fence[east=true]
> minecraft:nether_brick_fence[west=true]
> minecraft:nether_brick_fence[waterlogged=true]

**Comment by Brokkonaut** [comment]
Blocks Ii found that are not correctly remapped:
- Connected nether fences
- Edge brick stairs (the red bricks)
- Wood blocks (also known as bark blocks - those logs with bark on all sides) - should be remapped to 17:12-15 and 162:12-13

**Comment by WesleyVanNeck** [comment]
#891

**Comment by 7kasper** [comment]
This was fixed (i think) thanks to @zedwick please reopen if it was not the case!
