### ISSUE TITLE
Tab complete for chat does not work (1.12.2 client on 1.13.1 server)

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#899]
Tab completing chat does not suggest any completes when playing with 1.12.2 on an 1.13.1 server.

For commands (starting with / tab) completing works.

ProtocolSupport: buildtime: 2018.09.10 at 00:31:34 MSK, buildhost: build.true-games.org, buildnumber: 278
Server: git-Paper-253 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by MrPowerGamerBR** [comment]
If you are talking about player names, that's how it works now in 1.13.1, the client that auto completes the names, not the server.

That's something that I will implement soon in ProtocolSupportStuff.

**Comment by Brokkonaut** [comment]
Ok, I did not know that - Would be great if you can add it to your plugin :)

**Comment by Xayanix** [comment]
@MrPowerGamerBR any progress?

**Comment by MrPowerGamerBR** [comment]
@Xayanix not yet, I'm busy with other projects (kinda bored with Minecraft atm so I'm not working on my own server) so I didn't have time to implement that feature.
