### ISSUE TITLE
Maps Bug (BannerBoard)

### ISSUE THREAD

**Issue by EazyFTW** [ProtocolSupport/ProtocolSupport#905]
Is it possible for you to fix maps with BannerBoard. At the moment when you join in a version other than 1.13.x, the maps show nothing (Just an empty item frame, but bigger like a transparent map). I contacted their support and they said it's an issue with ProtocolSupport. 

Thanks,
- EazyFTW.

**Comment by Shevchik** [comment]
Related to item durability not being copied from nbt to legacy data

**Comment by mibby** [comment]
@Shevchik Do you have any estimate when this can be fixed? I also rely heavily on having map data properly sent to older client versions.

**Comment by 7kasper** [comment]
Should be fixed now! 😄

**Comment by TheDumbledodo** [comment]
There is this bug with bannerboard that when there are bungee servers the images from (lobby) pastes on like (Bedwars) if you make 2 maps it won't be bugged but if you reload the server the maps will be again ripped I got Protocolib too
anyone could help? I've had this plugin for a goddamn month
