### ISSUE TITLE
Scoreboard (Featherboard) not parsing correctly

### ISSUE THREAD

**Issue by cloakfox** [ProtocolSupport/ProtocolSupport#907]
Basicly on 1.12.2 or versions below the scoreboard does not parse correctly
This happens: https://imgur.com/a/28SbMEL

Using Protocolsupport build: 280
Using Featherboard: 3.23.0
PaperSpigot: 319

**Comment by Shevchik** [comment]
This is however correct. You reached the limit for 16 symbols for prefix/suffix in old versions.

**Comment by cloakfox** [comment]
> > This is however correct. You reached the limit for 16 symbols for prefix/suffix in old versions.
> 
> I haven't touched the configs prior to updating, bit weird that on lower server versions it parses correctly..

Also notice the word sticfox, wich normally should display skyfox (same lenght)

**Comment by Shevchik** [comment]
In 1.13 prefixes became unlimeted, so most of the scoreaboard plugins switched to using just prefix instead of splitting text between prefix/suffix.
