### ISSUE TITLE
Current status of compatibility with native transport?

### ISSUE THREAD

**Issue by mibby** [ProtocolSupport/ProtocolSupport#912]
Is ProtocolSupport still not compatible with the use of netty's linux native transport? ```use-native-transport``` server.properties setting.

It's been explained that the native transport normally produces ~2x better latency and practically no packet garbage, so being able to actually utilize that optimization would be nice.

**Comment by pkt77** [comment]
Native transport seems to be working fine as of the latest 1.13.1 spigot and ProtocolSupport builds. I haven't tried every client version, but the console hasn't been spammed with errors like it used to.

**Comment by 7kasper** [comment]
Well I think that answers the question. Although I must say it isn't officially supported. I am also pretty sure pspe doesn't like to work with it.

**Comment by mibby** [comment]
@7kasper What could normally go wrong with keeping it enabled? If it is not normally recommended or supported, I'm a bit cautious as to what to look out for.
