### ISSUE TITLE
Unable to ride a boat with an entity.

### ISSUE THREAD

**Issue by mibby** [ProtocolSupport/ProtocolSupport#916]
Paper dev 373 (Spigot 1.13.1)
ProtocolSupport compiled as of commit https://github.com/ProtocolSupport/ProtocolSupport/commit/213c3f8d6c0e4745ca68a9ef3f9ebadc185ee8e8

With ProtocolSupport installed, you are unable to ride with an entity in your boat. i.e. pushing a chicken in your boat, then getting into the boat yourself. Removing ProtocolSupport, riding a boat with mobs is possible again.

**Comment by krusic22** [comment]
This is a feature. It prevents glitches for 1.8 users (and below).
You can use ProtocolSupportStuffs to disable anything below 1.9 to fix this issue.

**Comment by mibby** [comment]
@krusic22 Disabling minecraft 1.8 clients from connecting will allow ProtocolSupport to automatically make entity boat riding work again? As this occurs with 1.13 clients on 1.13 server with ProtocolSupport installed.

**Comment by krusic22** [comment]
Yes. Disabling anything below 1.9 (so 1.4-1.8) will allow boats to work normally again. 
You can use ProtocolSupportStuff to disable unused protocols.

**Comment by mibby** [comment]
Thanks, I'll do that!

**Comment by mibby** [comment]
Is there any way to force riding with entities in boats and _not_ disable the 1.8 protocol? I'd prefer to allow the most amount of players to join and just kick or prevent them from crashing if they don't know how to support that packet. :(

**Comment by mibby** [comment]
@Shevchik Perhaps you know if it is possible to override the disabling to allow entity boat riding to allow it to work without having to disable game version 1.8 from connecting? As 1.8 is a huge version to support for letting the most amount of players to connect. :( Most people either play on either the latest or 1.8.
