### ISSUE TITLE
1.12 and older client bug on 1.13.1 server (villager)

### ISSUE THREAD

**Issue by bilemedimkq** [ProtocolSupport/ProtocolSupport#919]
server version: 1.13.1 (paper)
client version: 1.12.2

Villager trade bug

video:http://ghostmc.com/api/bug.mp4

**Comment by bilemedimkq** [comment]
bump :/

**Comment by Peda1996** [comment]
bump

**Comment by Shevchik** [comment]
Link is dead

**Comment by Peda1996** [comment]
Ah sorry, then I try to create a video of this problem :)

**Comment by Peda1996** [comment]
So I made a new video on this problem:
https://www.youtube.com/watch?v=QcHLwOl_fkY&feature=youtu.be

**Comment by Shevchik** [comment]
Try testing not in creative mode. I may guess that villager trading just doesn't work, because i can't seem to find any implementation of it for < 1.13 in protocolsupport.

**Comment by Shevchik** [comment]
Anyway, try now, should be working if i guessed it right.
