### ISSUE TITLE
Update for 1.13.2

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#922]
I just did this; code style of my commit is too bad for a PR but maybe it might save some time when updating:

https://github.com/Brokkonaut/ProtocolSupport/commit/3d58d517199eef8d6b22dc844d877d6594bb5861

If its not useful just close it.

**Comment by 7kasper** [comment]
Hey are you on our discord too? You can always give us quick suggestions and I'm sure we can get you a contributer role. What I can say is: the code is not too bad, with a bit of tuning I'm sure you can just get it in. I've left some comments already, feel free to PR it though!

**Comment by MrPowerGamerBR** [comment]
And here is the [server invite link](https://discord.gg/x935y8p) (He already uses Discord because he is on Paper's discord server 😛)
