### ISSUE TITLE
Unknown dimension network id

### ISSUE THREAD

**Issue by J0schlZ** [ProtocolSupport/ProtocolSupport#928]
[21:25:36 INFO]: J0schlZ lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown dimension network id 12
[21:25:36 INFO]: [DiscordSRV] Player J0schlZ quit with silent quitting permission, not sending a quit message

Me and my players mostly get those messages if we try to connect with certain Client-Versions.

Installed last version of ProtocolSupport
CraftBukkit version git-Spigot-a1ba5fe-3359cb1 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Installed Plugins:
CoreProtect, dynmap, LuckPerms, WorldEdit, McWiki, TogglePvp, ChunkSpawnerLimiter, WorldBorder, Modifyworld, PandaWire, Votifier, Multiverse-Core, WorldGuard, ProtocolLib, PluginController, iDisguise, PhantomSMP, VisualFixer, Multiverse-SignPortals, EditableSign, Multiverse-Portals, PerWorldPluginsPremium, Vault, MessageFilter, ProtocolSupport, MyCommand, PetMaster, SelectionVisualizer, BKCommonLib, PerWorldInventory, LWC, LiteBans, Citizens, Shopkeepers, DiscordSRV, Plan, CraftBook, Multiverse-NetherPortals, CMI

**Comment by Shevchik** [comment]
Not a protocolsupport issue. Some of your plugins sends invalid dimension id.

**Comment by J0schlZ** [comment]
[21:25:36 INFO]: J0schlZ lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown dimension network id 12
[21:25:36 INFO]: [DiscordSRV] Player J0schlZ quit with silent quitting permission, not sending a quit message

Me and my players mostly get those messages if we try to connect with certain Client-Versions.

Installed last version of ProtocolSupport
CraftBukkit version git-Spigot-a1ba5fe-3359cb1 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Installed Plugins:
CoreProtect, dynmap, LuckPerms, WorldEdit, McWiki, TogglePvp, ChunkSpawnerLimiter, WorldBorder, Modifyworld, PandaWire, Votifier, Multiverse-Core, WorldGuard, ProtocolLib, PluginController, iDisguise, PhantomSMP, VisualFixer, Multiverse-SignPortals, EditableSign, Multiverse-Portals, PerWorldPluginsPremium, Vault, MessageFilter, ProtocolSupport, MyCommand, PetMaster, SelectionVisualizer, BKCommonLib, PerWorldInventory, LWC, LiteBans, Citizens, Shopkeepers, DiscordSRV, Plan, CraftBook, Multiverse-NetherPortals, CMI

Why i only geht this Error with Protocolsupoort installed?
So you have an Idea wich Plugin ist sending wrong id's?

Thankyou

**Comment by Shevchik** [comment]
Because protocolsupport filters invalid data.
As for the plugin - no idea.

**Comment by J0schlZ** [comment]
OK thank you.

**Comment by Artuto** [comment]
I'm getting this and using Multiverse 2.6.0 and only started to appear after the 1.13 update.

**Comment by J0schlZ** [comment]
It seems like cmi is the cause.
I Disabled all other plugins and tracked it down.
Someone sayd as he deleted his CMI Config the issue was fixed vor him.
I've done this step too and still have the problem.

**Comment by J0schlZ** [comment]
Thank you...
