### ISSUE TITLE
[mapping] Banners are black for 1.12.2 (and below?) clients.

### ISSUE THREAD

**Issue by zedwick** [ProtocolSupport/ProtocolSupport#930]
All banners are black banners with 1.12.2 clients, and correctly coloured in 1.13 and above, on a 1.13.2 server. Patterns on banners are correctly coloured in 1.12.2, though.

**Comment by Shevchik** [comment]
They should be correctly seen in the world now, still need to remap items.

**Comment by Shevchik** [comment]
Fixed.
