### ISSUE TITLE
Unsigned writable books are losing their NBT data when dropped or moved through a container.

### ISSUE THREAD

**Issue by mibby** [ProtocolSupport/ProtocolSupport#931]
Paper dev 409 (Spigot 1.13.2)
ProtocolSupport dev 302

With ProtocolSupport enabled, unsigned writable books lose their NBT data when dropping the book or moving it through containers (hopper -> chest). Sometimes it doesn't even save the book data when clicking the done button (not signing) - it just returns blank when re-opening again. 

Removing ProtocolSupport, unsigned written books preserve data perfectly fine again.

Edit: It might just be a visual issue? Removing ProtocolSupport from my test server after testing with an unsigned book with the text "test" being lost when dropped and picked up again, the book got its text back.

**Comment by 7kasper** [comment]
probably a (small) item nbt remapper issue will look into it.

**Comment by mibby** [comment]
Thanks. Hopefully it is a quick and easy fix! Getting lots of complaints with books no longer working due to it. :(
