### ISSUE TITLE
Plugins cannot send plugin channel messages via legacy client connections

### ISSUE THREAD

**Issue by zedwick** [ProtocolSupport/ProtocolSupport#932]
I've not dived into this too deeply, but it seems that plugins which send messages over the BungeeCord channel are unable to do so for clients earlier than 1.13. I'm sure this is because of the change in name format. Most notably, plugins trying to send players to a different server on BungeeCord are unable to do so for 1.12.2 and earlier clients, but can for 1.13 and later clients.

I think this is probably a problem which should be fixed with ProtocolSupport, rather than in other plugins running alongside it.

**Comment by krusic22** [comment]
I don't think PS can fix this (maybe PS Bungee).
Since the message needs to follow the new 1.13 rule to work with both 1.13 and lower clients. 
It's probably easier to just edit the existing plugin to follow the new rules (not that hard to update).

**Comment by zedwick** [comment]
I may have been mistaken, as apparently the "BungeeCord" channel was and is simply "BungeeCord". So not quite sure what's going wrong.

**Comment by 7kasper** [comment]
Should be fixed now.
