### ISSUE TITLE
Sea pickle is mapped to long grass, causing glitches

### ISSUE THREAD

**Issue by Brokkonaut** [ProtocolSupport/ProtocolSupport#933]
In Minecraft 1.12 and older sea pickle is mapped to long grass - But sea pickles have a collision box, so players start glitching there and sometimes cannot move out of them any more.

I would propose to use some block that has a collision box at least as large as the sea pickles box.

**Comment by 7kasper** [comment]
I guess the closest thing by collision box is cake 😄

**Comment by 7kasper** [comment]
Should be fixed now.
