### ISSUE TITLE
[PE] can't connect to the server

### ISSUE THREAD

**Issue by gabe56f** [ProtocolSupport/ProtocolSupport#938]
Can't connect to the server, I just built it a minute ago, and whenever I try to connect to the server, Minecraft just stops the connection.

**Comment by gabe56f** [comment]
[15:52:24 INFO]: [ProtocolSupport] /127.0.0.1:5723 connected with protocol version MINECRAFT_PE

and Minecraft instantly closes the connection

**Comment by krusic22** [comment]
What version of PE are you using?

**Comment by gabe56f** [comment]
Latest, 1.7.0

**Comment by 7kasper** [comment]
Hey @gabe56f come ahead over to our discord channel! https://discord.gg/x935y8p. 
We don't support issues about PE here yet, but we'll help you out at the pe channel.
