### ISSUE TITLE
Version #309 - Can't join at 1.13.2

### ISSUE THREAD

**Issue by xCraftRayX** [ProtocolSupport/ProtocolSupport#943]
All in title ;)
Version from jenkins.

**Comment by krusic22** [comment]
If you have a 1.13.2 server and connect with 1.13.2 ProtocolSupport does noting.
Also you probably should provide more info.

**Comment by Shevchik** [comment]
ProtocolSupport does decode/encode even for latest version tho.
However more info is needed anyway. What exactly happpens when you try to join? Provide kick messages exception log, etc.

**Comment by xCraftRayX** [comment]
I using latest paper for 1.13.2 and when I try join with protocolsupport I had info about bad version MC from spigot.yml
