### ISSUE TITLE
Signs are without content (text) after relog. Tested on version 1.7.10

### ISSUE THREAD

**Issue by MorkaZ** [ProtocolSupport/ProtocolSupport#946]
Signs are without content (text) after relog. Tested on version 1.7.10.
In client logs there are outputs: "Unable to locate sign at x, y, z "
Screen after relog: https://imgur.com/a/K5uv8Uw.

I was using newest spigot 1.13.2 (builded today) & java 8.

**Comment by Shevchik** [comment]
Should be fixed now.

**Comment by MiMic10110** [comment]
It works now. Thank you :)
