### ISSUE TITLE
mcpeinventory - flooded chests and double chests need to be mapped

### ISSUE THREAD

**Issue by k9lego** [ProtocolSupport/ProtocolSupport#947]
So I was testing out the mcpeinventory branch and all double chests and flooded chests didn't appear at all.

**Comment by YasunaMC** [comment]
@k9lego not here issues about pspe aren't supported here

**Comment by YasunaMC** [comment]
https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues
