### ISSUE TITLE
New materials "stripped_xyz_wood" and "xyz_wood" are visible as stone instead of log

### ISSUE THREAD

**Issue by MorkaZ** [ProtocolSupport/ProtocolSupport#948]
New materials "stripped_xyz_wood" and "xyz_wood" are visible as stone instead of xyz_log on lower versions (tested on 1.7.10).
It should be visible as log with color of material's wood type because it has same usages as normal log. Actually it is stone and this misleads players on lower versions.

**Comment by Shevchik** [comment]
Wood blocks did exist before, however wood items did not.
So that's why i didn't notice it from the start.

**Comment by Shevchik** [comment]
Fixed.
