### ISSUE TITLE
[Proposition] Overwrite replaced itemstack's name (if name is not set) with real material name

### ISSUE THREAD

**Issue by MorkaZ** [ProtocolSupport/ProtocolSupport#949]
What do you think about replacing name in itemstacks for replacements if name of item is not set?
It will help a lot players on lower versions get to know what item they are actually holding.
I think it is great idea and names can be easily get from Material's enums.

**Comment by Shevchik** [comment]
Addons exist for that. See ProtocolSupportStuff for example.
