### ISSUE TITLE
[1.5.2] java.net.SocketException: Software caused connection abort: recv failed.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ProtocolSupport/ProtocolSupport#95]
![http://i.imgur.com/bXbvx2T.jpg](http://i.imgur.com/bXbvx2T.jpg)

No errors in the console, however, randomly, my friend would recive this message when he was kicked by my AntiKillAura plugin (not really the plugin fault, sometimes the message would show correctly for the 1.5.2 client).

**Comment by Shevchik** [comment]
Race conditions on connection close in minecraft client. Can't be really fixed on protocolsupport side.

**Comment by MrPowerGamerBR** [comment]
@Shevchik oh, that's what I suspected, because it was randomly happening (instead of happening everytime), also, this is not a major issue for me.
