### ISSUE TITLE
Material "IRON_NUGGET" is crashing client on version 1.7.10 (1.13> versions may be also affected)

### ISSUE THREAD

**Issue by MiMic10110** [ProtocolSupport/ProtocolSupport#950]
Material "IRON_NUGGET" is crashing client lower version client when it is in inventory. Tested with minecraft 1.7.10

**Comment by MrPowerGamerBR** [comment]
Seems to be a regression https://github.com/ProtocolSupport/ProtocolSupport/issues/343

**Comment by MiMic10110** [comment]
IRON_NUGGET is fixed.
More materials found:
https://github.com/ProtocolSupport/ProtocolSupport/issues/951
