### ISSUE TITLE
More materials that are crashing lower minecraft versions

### ISSUE THREAD

**Issue by MorkaZ** [ProtocolSupport/ProtocolSupport#951]
Here are more found Materials objects that are crashing lower versions when they are on the ground or in displayed inventory:
Material.PRISMARINE_BRICKS
Material.DARK_PRISMARINE
If it is in hand of player that uses minecraft 1.13.2, from 1.7.10 point this item is invisible and it is instantly crashing the game if it is being dropped on the ground.

**Comment by Shevchik** [comment]
Should be fixed now.
