### ISSUE TITLE
Scoreboard Team Name Tags

### ISSUE THREAD

**Issue by Sitmobedaf** [ProtocolSupport/ProtocolSupport#953]
Похоже что в 1.13 по сравнению с предыдущими версиями составные части объекта класса Team (prefix, suffix, color) теперь не зависят друг от друга. Я имею ввиду, что если в префиксе например цвет красный, то на ник он не перенесётся, для этого сделали Color. Правда, не понятно, как через Color сделать ник bold.

Есть явная проблема с отображением, которую хорошо видно на скриншоте клиента с версией 1.12.2 (и любая версия ниже)
Заходим с версии 1.13.2 - http://img11.lostpic.net/2018/11/20/42faf70fc692b1fc4e785e5c9480f9c8.png
Заходим с версии 1.12.2 - http://img11.lostpic.net/2018/11/20/99f9351085a8bcfa49a42c5dbb558664.png

**Comment by Sitmobedaf** [comment]
https://translate.google.com/

**Comment by Shevchik** [comment]
You will have to live with that for now. Legacy text converter improvement is tracked at separate issue.
