### ISSUE TITLE
Problem tab complete server 1.13.2 with client 1.12.2 or old

### ISSUE THREAD

**Issue by Guest1131** [ProtocolSupport/ProtocolSupport#969]
I noticed there's a problem:

I use the server 1.13.2, and I have set tab-complete: -1 , if I enter with the client 1.13.2 and disable, but if I enter with client 1.12.2 or earlier, the tab is no longer disabled.

**Comment by Shevchik** [comment]
That means that something is wrong with that option (most likely it doesn't disable server ask tab completes, only disables the command list sending). Ask spigot about this, not us.
