### ISSUE TITLE
[Suggestion] Support for even older versions

### ISSUE THREAD

**Issue by kangarko** [ProtocolSupport/ProtocolSupport#97]
Hello,
first of all, you have done a great job so far and it is highly appreciated by many server owners, including myself ;) I would like to thank you for keeping it up.

The idea I got is to add support for even older versions of Minecraft, for example 1.4.7. The biggest challenge is to deal with that starting with 1.5x, all entities begun to use object type 10, and send the block within seperately. This is done other way in the older versions. Besides, there is no steering vehicle packet (managed differently). It would be amazing to be able to connect with such old version to the latest spigot! I think it is possible to code up support down to 1.2x, since this is the oldest version that supports maps in the current format (256 blocks high).
I can also take a look at the code at my free time and post a pull request, if you are ok with this.

**Comment by Shevchik** [comment]
No point, you can't detect if player pinged with 1.4.7 or 1.5.2 version, so player won't know that you support older version anyway

**Comment by Shevchik** [comment]
P.S. You can actually support all minecraft versions that support multiplayer, but what is the point?
Also there will require many copy paste, currently i'm working on making it less copy paste (First decode packet to some middleware structure that contains all fields that are needed, and that encode it to stream using correct protocol, this will allow you to just implement the writer separately and share them between versions).

**Comment by Tom-III** [comment]
I like this idea alot

**Comment by kangarko** [comment]
Allright thanks for answer. The point would be purely educational, e.g. to shows that something like this is possible, and I like the idea very much since older versions are less biased with unneeded stuff (subjective opinion).

**Comment by Tom-III** [comment]
I really like the idea of adding support for every version, like to prove it can be done :)
I could help in a project like this if you need help

**Comment by Shevchik** [comment]
I'v almost finished rewriting packet decoders/encoders now they are per packet type, so it sohuld be easier to add earlier protocol versions support now. But personally i don't have time to do such things.

**Comment by kangarko** [comment]
What a great news :+1: I don't mind waiting, it's gonna be when it's gonna be, take your time. Love your plugin :smiley:

**Comment by Shevchik** [comment]
Just need to finish 1.4.7 block/item remapping table and it's done. I won't do versions lower that it because i should focus on mcpe branch

**Comment by kangarko** [comment]
Sure thanks :) BTW, It would be amazing to see e.g. some beta version like b1.7.3 able to connect :P But I am aware of the amount of differences so I understand if it's not possible.

**Comment by Shevchik** [comment]
It is possible, but totally not worth it.

**Comment by kangarko** [comment]
I see. Thanks for your time and the effort, really appreciate it.
