### ISSUE TITLE
Acacia and Dark Oak Wood is remaped to Logs

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#979]
Just an incorrect remap with Acacia and Dark Oak wood, nothing much

1.12: http://prntscr.com/lsjq1v
1.13: http://prntscr.com/lsjq4s

**Comment by Shevchik** [comment]
Print the material names and full blockstates for those blocks, we don't have a remap from ACACIA_WOOD and DARK_OAK_WOOD.

**Comment by Shevchik** [comment]
Fixed.
