### ISSUE TITLE
1.7.X Clinet crash The New Dev version

### ISSUE THREAD

**Issue by swan201** [ProtocolSupport/ProtocolSupport#99]
Go to Some Location. 1.7.X User crash this message. 

Internal Exception: io.netty.handler/.codec.DecoderException: Java.ioException: The received string length is longer than maxium allowed (16>15)

**Comment by Shevchik** [comment]
Fuck, forgot that some places have limits of 15, while other 16 symbols...

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by swan201** [comment]
Ok now say 

Internal Exception: io.netty.handler/.codec.DecoderException: Java.ioException: Packet was larger than I expected, found 12 bytes extra whlist reading packet 16

**Comment by Shevchik** [comment]
Should be fixed now

**Comment by swan201** [comment]
http://pastebin.com/cSWvi9kv

Help Me plz ;.; Noting Error in colsole

**Comment by Shevchik** [comment]
Reset your client settings to default
