### ISSUE TITLE
PlayerEditBookEvent not working

### ISSUE THREAD

**Issue by Xayanix** [ProtocolSupport/ProtocolSupport#990]
Newest PaperSpigot & ProtocolSupport.

PlayerEditBookEvent is working only if client's version doing edit is equal to server version.
For example if you edit book on 1.8 version with 1.13.2 then it won't work.

**Comment by Xayanix** [comment]
Also you're able to fake book's author.

**Comment by Shevchik** [comment]
On update to 1.13.2 some item transformers broke. I guess book transforming was one of them.
Which means that book changing just no longer works.

If you see the bokk changing it either a desync, or you are using creative mode.

**Comment by Artuto** [comment]
Any updates on this? Players are freaking out they cant sign books and some cant just change to the server's version because 1.13.2 is the worse at performance :/

**Comment by Shevchik** [comment]
Should be fixed now.
