### ISSUE TITLE
Chunk Queue is shit

### ISSUE THREAD

**Issue by GalaxyGirl59** [ProtocolSupport/ProtocolSupport#991]
https://youtu.be/e3rlTtbD2TQ

Server Version: 1.13.2 (with full 20 tps)
ProtocolSupport Version: Latest on Jenkins

Changing the protocolsupport.chunksend18interval property does NOT fix this.

**Comment by GalaxyGirl59** [comment]
Not caused by a map. The one i showed is in fact, a blank flatland.
This happens when the server has a lot of processes, even with 20 tps

**Comment by Shevchik** [comment]
Then i guess you have a process scheduling problem, so network packet gets sent in batch at lower level. Nothing can be done about it. The queue itself only actually workarounds the client problem, not fixes it. So if you have a better suggestion what to do - you can always leave a suggestion in discord chat.

**Comment by GalaxyGirl59** [comment]
maybe at least make the property actually work.
