### ISSUE TITLE
Reddust particle colors and size

### ISSUE THREAD

**Issue by MasterDash5** [ProtocolSupport/ProtocolSupport#993]
Reddust particle can't be given a custom color nor size.
I set the color to aqua and size to 3 for this example.

1.13.2: http://prntscr.com/lwn6lc
1.12.2 and lower: http://prntscr.com/lwn6ej

**Comment by Shevchik** [comment]
Need a code example on how exactly to spawn that particle for easier reproduction.

**Comment by pkt77** [comment]
` loc.getWorld().spawnParticle(Particle.REDSTONE, loc, 1, new Particle.DustOptions(Color.fromRGB(0, 0, 255), 1));` Is how it's done from Bukkit.
Also if this helps, I made a quick (although bad, as I'm not very familiar with this repo) fix: https://pastebin.com/d4ZFedae
And also removing this line: https://github.com/ProtocolSupport/ProtocolSupport/blob/master/src/protocolsupport/protocol/typeremapper/particle/ParticleRemapper.java#L107
Notice that speed has to be 1 and count has to be 0 for the client to read the offsets as RGB colors instead.

Hope you can make a better and permanent solution.

**Comment by Shevchik** [comment]
Fixed

**Comment by Shevchik** [comment]
I
