### ISSUE TITLE
 Must be within ~3 blocks to see entities

### ISSUE THREAD

**Issue by MWLVegas** [ProtocolSupport/ProtocolSupport#995]
PS build #326, Spigot 1.13.2 (667bdd6, most recent as of this morning)

As stated above, you have to be within approx 3 blocks to see any entities, both living and non-living. Problem happens with client vers 1.13.2, 1.12 and 1.11 - did not check any others.

**Comment by RaidAndFade** [comment]
Can reproduce on 1.13.2 client.

**Comment by Alchemi1963** [comment]
Can confirm 1.13.2. I run the latest ps and spigot.

**Comment by Speentie8081** [comment]
More like 10 blocks roughly, but yeah I'm also able to reproduce the issue on 1.13.2
[https://i.imgur.com/tj0R7Nf.png](https://i.imgur.com/tj0R7Nf.png)
[https://i.imgur.com/WlkjiyF.png](https://i.imgur.com/WlkjiyF.png)

**Comment by MithrandirCraft** [comment]
Hey, same here, looks like when you go over the 11'th block (12th), entities dissappear, and once you go back to the 7th proximity block they come back.

**Comment by SmallSansSerif** [comment]
Yes can confirm this as well.

**Comment by Mgazul** [comment]
Yes can confirm this as well.

**Comment by BBoyJD10** [comment]
Can confirm

**Comment by Shevchik** [comment]
Should be fixed now
